Ultimaker/Cura

- resources/settings/hephestos.json
- resources/settings/hephestos_XL.json
- resources/settings/witbox.json
Profiles have been updated to match the new JSON structure (The actual ones have the structure of the fdmprinter.json of the 15.06 branch).
> Updated BQ printer profiles structure.

- resources/settings/RigidBot.json
- resources/settings/RigidBotBig.json
This adds the RigidBot & RigidBotBig .json and .stl files necessary for
support in Cura 15.06
> Add RigidBot & RigidBotBig Profiles

- resources/machines/bq_hephestos_2.json
- resources/machines/bq_witbox_2.json
Update in the values of temperature, speeds and skirt minimal length.
> Update for BQ printers profiles

- resources/machines/m180.json
This is a translation of the machine that Malyan made for version 15.06. The settings should be the same as what Malyan provided back then.
See also https://github.com/Ultimaker/Cura/pull/582, which was not a pull request but a request for work. I just did the translation.
> Malyan180 support

- CMakeLists.txt
* removes custom target copy-translations
* updating TODO to remove the language list with a nice algorithmus
* renaming file to po_file in foreach-loop
* etc.
Fixes issue #229
> Fixing i18n build and install

- CMakeLists.txt
- cura.desktop
- cura.sharedmimeinfo
> Adding support for additional object files

- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
- resources/qml/Cura.qml
- resources/qml/Sidebar.qml
- resources/qml/SidebarSimple.qml
Rather than reloading the panel every time the mode changes, use a StackView and create static instances of SimpleMode and AdvancedMode.
Requires Ultimaker/Uranium#102
> Fast Simple<->Advanced Switch

- plugins/CuraEngineBackend/ProcessSlicedObjectListJob.py
- plugins/LayerView/LayerView.qml
- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
- plugins/USBPrinting/ControlWindow.qml
- resources/machines/fdmprinter.json
- resources/machines/ultimaker2plus_025.json
- resources/machines/ultimaker2plus_040.json
- resources/machines/ultimaker2plus_060.json
- resources/machines/ultimaker2plus_080.json
- resources/qml/AboutDialog.qml
- resources/qml/Cura.qml
- resources/qml/JobSpecs.qml
- resources/qml/ProfileSetup.qml
- resources/qml/SaveButton.qml
- resources/qml/Sidebar.qml
- resources/qml/SidebarHeader.qml
- resources/qml/SidebarSimple.qml
- resources/qml/SidebarTooltip.qml
- resources/qml/Toolbar.qml
- resources/qml/WizardPages/AddMachine.qml
- resources/qml/WizardPages/Bedleveling.qml
- resources/qml/WizardPages/SelectUpgradedParts.qml
- resources/qml/WizardPages/UltimakerCheckup.qml
- resources/qml/WizardPages/UpgradeFirmware.qml
- resources/themes/cura/styles.qml
This makes the changes necessary for the related performance fixes in Uranium.
Depends on https://github.com/Ultimaker/Uranium/pull/113
Fixes CURA-472
> Performance fixes

- resources/machines/prusa_i3.json
- resources/machines/prusa_i3_xl.json
prusa i3 filament diameter to 1.75
> prusa i3 filament diameter to 1.75

- cura/BuildVolume.py
- cura/ConvexHullNode.py
- cura/CuraActions.py
- cura/CuraApplication.py
- cura/PlatformPhysics.py
- cura/PrintInformation.py
- cura_app.py
- plugins/3MFReader/ThreeMFReader.py
- plugins/LayerView/LayerView.py
- plugins/LegacyProfileReader/LegacyProfileReader.py
- plugins/PerObjectSettingsTool/PerObjectSettingsTool.py
- plugins/RemovableDriveOutputDevice/LinuxRemovableDrivePlugin.py
- plugins/RemovableDriveOutputDevice/OSXRemovableDrivePlugin.py
- plugins/SliceInfoPlugin/SliceInfo.py
- plugins/USBPrinting/PrinterConnection.py
- plugins/USBPrinting/USBPrinterManager.py
As I set up Eclipse+PyDev now to code on Cura I just found these errors.
Probably more will follow...
> Fixing small issues in the code

- resources/machines/ultimaker2plus.json
- resources/machines/ultimaker2plus_025.json
- resources/machines/ultimaker2plus_040.json
- resources/machines/ultimaker2plus_060.json
- resources/machines/ultimaker2plus_080.json
- resources/profiles/materials/abs.cfg
- resources/profiles/materials/cpe.cfg
- resources/profiles/materials/pla.cfg
- resources/profiles/ultimaker2+/abs_0.25_normal.curaprofile
- resources/profiles/ultimaker2+/abs_0.4_fast.curaprofile
- resources/profiles/ultimaker2+/abs_0.4_high.curaprofile
- resources/profiles/ultimaker2+/abs_0.4_normal.curaprofile
- resources/profiles/ultimaker2+/abs_0.6_normal.curaprofile
- resources/profiles/ultimaker2+/abs_0.8_normal.curaprofile
- resources/profiles/ultimaker2+/cpe_0.25_normal.curaprofile
- resources/profiles/ultimaker2+/cpe_0.4_fast.curaprofile
- resources/profiles/ultimaker2+/cpe_0.4_high.curaprofile
- resources/profiles/ultimaker2+/cpe_0.4_normal.curaprofile
- resources/profiles/ultimaker2+/cpe_0.6_normal.curaprofile
- resources/profiles/ultimaker2+/cpe_0.8_normal.curaprofile
- resources/profiles/ultimaker2+/pla_0.25_normal.curaprofile
- resources/profiles/ultimaker2+/pla_0.4_fast.curaprofile
- resources/profiles/ultimaker2+/pla_0.4_high.curaprofile
- resources/profiles/ultimaker2+/pla_0.4_normal.curaprofile
- resources/profiles/ultimaker2+/pla_0.6_normal.curaprofile
- resources/profiles/ultimaker2+/pla_0.8_normal.curaprofile
A few improvements to um2+ machine definitions & profiles.
> UM2+ profile improvements

- cura/CuraApplication.py
As done in #710 I just added a marker with references to github issues.
> [master] Adding marker for the Nvidia workaround

- README.md
> Listing of all paths for every OS

- cura/CuraApplication.py
Had that change locally here, but for a reason I forgot to commit that fix. Oops..
> Fixing a typo

- cura/CrashHandler.py
- cura/MachineManagerModel.py
This fixes an issue where an exception in MachineManager::setActiveMachine would completely prevent the application from starting. In addition, I have improved the uncaught exception handling in Cura so it is a bit more useful and properly aborts on certain kinds of exceptions.
> Minor Exception handling Fixes

- cura/BuildVolume.py
- cura/SettingOverrideDecorator.py
Just take a look at the two commits below.
> [master] code cleanup

- plugins/CuraEngineBackend/CuraEngineBackend.py
close() is already defined in this class. This removes the useless code.
> [master] CuraEngineBackend: Removing duplicate close()

- resources/definitions/bq_hephestos.def.json
- resources/definitions/bq_hephestos_2.def.json
- resources/definitions/bq_hephestos_xl.def.json
- resources/definitions/bq_witbox.def.json
Fixes the reason why the Cura UI freezes when choosing my printer from
the wizard.
> [master] Updating platform_offset for BQ printers

- cura/CuraApplication.py
Just fixes the redefinition of Platform...
> Differencing between Platform from UM.* and UM.Scene.*

- cura/MachineManagerModel.py
- plugins/USBPrinting/USBPrinterOutputDeviceManager.py
- plugins/USBPrinting/__init__.py
This updates the firmware updater to use the new MachineManagerModel
Additionally renamed "machine_type" to "machine_id", which makes it more
selfexplaining, when reading the code.
My printers firmware is not available here and has no heated bed, so
please test this commit!
> [CURA-1615] Updating firmware manager for API 3

- plugins/USBPrinting/USBPrinterOutputDeviceManager.py
> Adding a marker for a correctly unresolved import on Linux and OSX

- cura/CuraSplashScreen.py
> [CURA-1676] SplashScreen: Using system-default fontfamily

- plugins/USBPrinting/USBPrinterOutputDevice.py
Already made that correction in the past. When print monitor was merged it appeared again.
> USBPrinting: Let's "Print via USB"

- plugins/SliceInfoPlugin/SliceInfo.py
Just doesn't remove the "try:" .. "except:" compared to #858
> [CURA-1831] Adding only the basic workaround for OSX

- cura/BuildVolume.py
> CURA-1787 Added message when switching to one_at_a_time.

- cura/BuildVolume.py
Not the prettiest implementation, but it works.
Probably needs some rework when coordinate systems of Cura matches CuraEngine and firmware.
> [CURA-1811] Added prime locations to machine_disallowed_area. 

- plugins/SliceInfoPlugin/SliceInfo.py
I think this is the way YouMagine expects the data to be sent.
Replaces: https://github.com/Ultimaker/Cura/pull/857
> CURA-1445: Using getDurationInISOFormat in SliceInfo

- plugins/LayerView/LayerView.py
- resources/qml/Preferences/GeneralPage.qml
Got really fed up with not being able to look at a single layer. 
Put this in a pull request as we don't have a corresponding ticket for this (and this was therefore built in my own time)
> Added option to only display top layers in layerview

- cura/BuildVolume.py
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
- plugins/PerObjectSettingsTool/__init__.py
- plugins/UltimakerMachineActions/BedLevelMachineAction.py
- plugins/UltimakerMachineActions/BedLevelMachineAction.qml
- plugins/UltimakerMachineActions/UMOCheckupMachineAction.qml
- plugins/UltimakerMachineActions/UMOUpgradeSelectionMachineAction.qml
- resources/definitions/fdmextruder.def.json
- resources/definitions/fdmprinter.def.json
- resources/qml/Actions.qml
- resources/qml/Preferences/GeneralPage.qml
- resources/qml/PrintMonitor.qml
- resources/qml/SidebarSimple.qml
A number of issues were found where the UI uses terms that do not comply to the terms set in the "Ultimaker dictionary". 
CURA-2053
> Update UI texts to be compliant to Ultimaker dictionary

- resources/definitions/innovo_inventor.def.json
Updated JSON file:
- changed machine center is zero to true
- added turn heated bed off to end g code
- changed top/bottom thickness from 0.3 to 1.2mm
- added machine preferences as I did in 2.1 (is this still used?)
Updated STL file.  The last file was 13mb! this one is 810kb!
> Update def.json and STL file

- resources/definitions/innovo_inventor.def.json
Added M140 to turn off heated bed
Changed default extruder temp to 205
Changed print speed defaults
Removed infill overlap override
Removed machine preferences
> Updated innovo_inventor.def.json settings

- plugins/LayerView/LayerView.py
This is a much simpler implementation of https://github.com/Ultimaker/Cura/pull/906, and this one works. The only disadvantage of this approach over an approach based on renderpasses is the look of the ghost over the buildplate checkerboard.
CURA-1601
> Show "ghosts" for all objects on the buildplate in layerview

- plugins/SliceInfoPlugin/SliceInfo.py
... for every model placed on the build plate.
> [CURA-1445] Adding hashes

- resources/definitions/fdmprinter.def.json
Added setting outer_inset_first to experimental category in fdmprinter.def.json.
This is for the Pull Request https://github.com/Ultimaker/CuraEngine/pull/177
> Added setting outer_inset_first.

- resources/definitions/bfb.def.json
- resources/definitions/julia.def.json
- resources/definitions/kupido.def.json
- resources/definitions/makerbotreplicator.def.json
- resources/definitions/ord.def.json
- resources/definitions/punchtec_connect_xl.def.json
- resources/definitions/rigid3d.def.json
- resources/definitions/rigid3d_3rdgen.def.json
- resources/definitions/rigid3d_hobby.def.json
- resources/definitions/rigid3d_zero.def.json
- resources/definitions/robo_3d_r1.def.json
- resources/extruders/punchtec_connect_xl_extruder_left.def.json
- resources/extruders/punchtec_connect_xl_extruder_right.def.json
* Fix extruders for Punchtec printer
* Fixes some manufacturers
* Makes capitalization consistent
> All legacy machines fixes

- cura/Settings/MachineManager.py
- plugins/CuraEngineBackend/StartSliceJob.py
- resources/qml/Actions.qml
- resources/qml/Preferences/ProfilesPage.qml
Goal: User cannot create a profile that is invalid.
> Changed MachineManager.isActiveStackValid to areStacksValid. CURA-2730

- cura/Settings/ContainerManager.py
- resources/qml/Cura.qml
- resources/qml/Preferences/ProfilesPage.qml
added importProfile(s), exportProfile to ContainerManager. CURA-787
> Drag profile into Cura; CURA-787

- resources/qml/Cura.qml
- resources/qml/Settings/SettingExtruder.qml
This PR fixes two (unrelated) qml errors, neither of which affect functionality.
> Fix qml errors

- resources/i18n/de/cura.po
> Correcting German translation

- README.md
Reference to an example machine profile contained invalid link. Link updated.
Signed-off-by: CeDeROM <CeDeROM@tlen.pl>
> Updated reference to an example machine profile.

- resources/qml/Sidebar.qml
This PR fixes two minor issues introduced in the feature_find_settings merge:
* When starting Cura in simple mode, the filter toggle is incorrectly showing up on the "advanced" tab
* A qml error about anchoring
> Fix issues introduced in the feature_find_settings merge

- resources/definitions/printrbot_simple_extended.def.json
@Ghostkeeper 
a simple fix please review
> Minor starting code new line fix

- resources/definitions/101Hero.def.json
This is a definition file for the 101Hero. A Kickstarter/Indiegogo campain product. It is based on Marlin 1.0.0 firmware.
> Add definition file for 101Hero

- cura/CuraActions.py
- cura/CuraApplication.py
- cura/MachineActionManager.py
- cura/PrintInformation.py
- cura/Settings/ContainerManager.py
- cura/Settings/ExtruderManager.py
- cura/Settings/MachineManager.py
- cura/Settings/SettingInheritanceManager.py
- plugins/3MFReader/WorkspaceDialog.py
- plugins/ImageReader/ImageReaderUI.py
- plugins/LayerView/LayerViewProxy.py
- plugins/MachineSettingsAction/MachineSettingsAction.py
- plugins/UltimakerMachineActions/BedLevelMachineAction.py
See the matching PR in Uranium: https://github.com/Ultimaker/Uranium/pull/206
> Support for the Big Flame Graph profiler

- cura/BuildVolume.py
- cura/ConvexHullNode.py
- cura/CuraApplication.py
- cura/LayerPolygon.py
- plugins/LayerView/LayerView.py
- plugins/SolidView/SolidView.py
- plugins/XRayView/XRayView.py
- plugins/XRayView/xray_composite.shader
- resources/qml/Cura.qml
- resources/qml/Legend.qml
- resources/themes/cura/theme.json
Now that the code is there to have the colors in the layerview based on the theme, it is fairly trivial to add a legend of the layer "polygon" types to the viewport. This PR does just that.
The PR builds on the themeable viewport branches:
https://github.com/Ultimaker/Cura/pull/1370 (included in this PR)
https://github.com/Ultimaker/Uranium/pull/215 (required by this PR)
CURA-1037 (?)
> Layerview Legend

- cura/BuildVolume.py
- cura/ConvexHullNode.py
- cura/LayerPolygon.py
- plugins/LayerView/LayerView.py
- plugins/SolidView/SolidView.py
- plugins/XRayView/XRayView.py
- plugins/XRayView/xray_composite.shader
- resources/themes/cura/theme.json
This PR makes the Solid, Xray & Layerview use themeable colors, paving the way for a true dark theme. It relies on its Uranium counterpart: https://github.com/Ultimaker/Uranium/pull/215
When testing this PR (together with the Uranium PR) everything should look the same as it did before. See the new colors in theme.json to make changes in the looks.
Fixes https://github.com/Ultimaker/Cura/issues/1364
> Feature theme viewport

- resources/i18n/ptbr/cura.po
- resources/i18n/ptbr/fdmextruder.def.json.po
- resources/i18n/ptbr/fdmprinter.def.json.po
As per directions given on PR #676, I created the translation files for brazilian portuguese. All strings are translated and have been subjected to the latest version of template file using msgmerge from gettext.
> Added translation files for Brazilian Portuguese

- resources/i18n/ptbr/cura.po
- resources/i18n/ptbr/fdmprinter.def.json.po
Fixed  two typos, removed quotes from jerk, changed 'anti-suporte' to 'anti-pendências' so that it does not conflict with future changes.
> Fixed little things according to advice from Ghostkeeper

- cura/CuraApplication.py
- plugins/CuraEngineBackend/ProcessSlicedLayersJob.py
- plugins/LayerView/LayerPass.py
- plugins/LayerView/LayerView.py
- plugins/LayerView/LayerView.qml
- plugins/LayerView/layers.shader
- plugins/LayerView/layers3d.shader
- plugins/LayerView/layerview_composite.shader
- plugins/XRayView/xray.shader
- plugins/XRayView/xray_composite.shader
- resources/qml/Preferences/GeneralPage.qml
- Added 4.1 core shaders.
- Layer view compatibility mode uses OpenGLContext.isLegacyOpenGL and preference force_layer_view_compatibility_mode
> Opengl41core - on top of layer_view3_cleanup

- resources/definitions/renkforce_rf100.def.json
Add [this printer](https://www.conrad.de/de/renkforce-rf100-3d-drucker-starter-kit-inkl-filament-single-extruder-1507428.html). This file is based on the `.ini` file that came with it, as per https://github.com/Ultimaker/Cura/issues/1316
> Add Renkforce RF100

- cura/Settings/ExtrudersModel.py
- cura/Settings/MachineManager.py
These are the changes needed in the Cura code related to https://github.com/Ultimaker/Uranium/pull/221 . The most imporant change here is to postpone the containersChanged signal of the active container stacks.
> Improve performance of switching variant/material/quality

- cura/PrinterOutputDevice.py
- cura/Settings/ExtruderManager.py
- plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
- plugins/USBPrinting/USBPrinterOutputDevice.py
- resources/qml/PrintMonitor.qml
- resources/qml/Sidebar.qml
This adds a feature to pre-heat the print bed in order to have it be warm by the time you're done slicing and such. It also basically redesigns the side bar of the print monitor.
Implements issue CURA-3161.
> Pre-heat Bed and Redesign Print Monitor

- cura/CuraApplication.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/LayerView/LayerView.py
- plugins/LayerView/LayerView.qml
- plugins/LayerView/LayerViewProxy.py
- resources/qml/JobSpecs.qml
- resources/qml/MonitorButton.qml
- resources/qml/SaveButton.qml
This PR shows the legend in layerview compatibility mode.
The PR includes https://github.com/Ultimaker/Cura/pull/1436 because getLayerViewType() was not working.
> Fix compatibility mode legend

- resources/qml/AboutDialog.qml
- resources/qml/Preferences/GeneralPage.qml
On some OSes/configurations/screens, the options on the General pane and the list of credits on the About window don't fit until the window is resized. Adding a scrollview helps in these cases.
This PR also adds libSavitar to the list of open source projects on the About window, which is totally unrelated to the PR other than that I had the file open and I did not want to bog down the PR queue any further.
> Fix window overflow

- cura/CuraApplication.py
- cura/Settings/MachineManager.py
- cura/Settings/UserChangesModel.py
- resources/qml/Cura.qml
- resources/qml/DiscardOrKeepProfileChangesDialog.qml
This replaces the switch profile dialog with a more explict dialog.
CURA-3221
> Feature override profile

- plugins/3MFReader/ThreeMFReader.py
- plugins/3MFWriter/ThreeMFWriter.py
This should significantly speed up working with 3mf files. Loading should be ~10 times as fast and saving should be ~3 times as fast.
> 3mf speedup (CURA-3215)

- cura/Settings/ContainerManager.py
- resources/qml/Cura.qml
`file_urls` should be a list of strings, thus `QVariantList`.
> CURA-3471 Crash on drag and drop STL

- resources/qml/DiscardOrKeepProfileChangesDialog.qml
- Remove the star image
- Use "default" font for the description text
- Adjust dialog window and table view sizes
- Use "system" font for texts in the table view so they fit in their rows
> CURA-3221 improve override profile dialog

- resources/definitions/renkforce_rf100.def.json
Update as per discussion in https://github.com/Ultimaker/Cura/pull/1350
> Update Renkforce RF100 profile

- cura/CuraApplication.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/ImageReader/ImageReader.py
- resources/qml/Actions.qml
- resources/qml/Cura.qml
**MERGE THIS ONE FIRST**: https://github.com/Ultimaker/Uranium/pull/230
Put open project/models into a single menu item. When multiple files are selected, it will check for Cura project file(s), and show an dialog asking for action (opening the project file or other models file(s)) if this is the case.
How to trigger:
1. Start Cura.
2. Go to menu and select "Open Project/Models".
3. Select multiple files with at least one Cura project file and one model file.
4. It will show the following dialog, asking whether you want to import all models.
> CURA-3495 Open project/models menu item

- cura/CuraApplication.py
- resources/qml/DiscardOrKeepProfileChangesDialog.qml
- resources/qml/Preferences/GeneralPage.qml
> CURA-3561 Save with code names for profile override preference

- resources/qml/Preferences/GeneralPage.qml
In the same way as https://github.com/Ultimaker/Cura/pull/1554
> Add more spacing between the label and combobox for override profile option

- resources/qml/Cura.qml
Have to make a function for handling multiple files because QML just executes everything altogether. So, if we put all those code in a single block and multiple files are selected (with Gcodes), we will get all kinds of dialogs poping up at the same time.
> CURA-3495: Add message dialog for ignoring gcode in multiple file selection

- plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
@nallath Made a mistake in batched compression. The last batch could be ignored. This is a fix for that.
> CURA-3604 Fix batched gcode compression for "print over network"

- plugins/3MFReader/WorkspaceDialog.qml
- resources/qml/DiscardOrKeepProfileChangesDialog.qml
- resources/qml/WorkspaceSummaryDialog.qml
Some recently added dialogs don't work nicely with Hi DPI screens, and don't use the system theme properly. This PR fixes some of those issues.
Fixes https://github.com/Ultimaker/Cura/issues/1634
> Fix issues with Workspace and Profile Changes dialogs

- plugins/LayerView/LayerView.py
Use layer_id to determine total layer count
> CURA-3615 Fix total layer count when raft is enabled

- cura/Arrange.py
- cura/CuraApplication.py
- cura/ShapeArray.py
- resources/qml/Actions.qml
- resources/qml/Cura.qml
- tests/TestArrange.py
This PR adds some arrange functions which are used to find "good" locations for objects.
There are 3 parts that benefit from this functionality:
- When loading a model, the new object(s) are placed on "good" locations
- The right mouse button has an "Arrange All Models"
- When multiplying models, the new models are placed on a "good" location as well
> Feature arrange CURA-3239

- plugins/3MFReader/WorkspaceDialog.qml
Fixes https://github.com/Ultimaker/Cura/pull/1636#issuecomment-291801102
> Fix typo in WorkspaceDialog.qml

- cura/CuraApplication.py
In combination with https://github.com/Ultimaker/Uranium/pull/242
> CURA-3529: Set dir names in config to allow UM detect old cura dir

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
In combination with https://github.com/Ultimaker/Uranium/pull/243
> CURA-3540 update profiles when deserializing them

- plugins/LayerView/LayerView.qml
Don't show "Top/Bottom" and "Inner Wall" legends in "Material Color" in Layer View.
> CURA-3730: Hide Top/Bottom and Inner Wall legends in "Material Color"

- cura/CuraApplication.py
Fixes this issue: https://github.com/Ultimaker/Cura/issues/1703
> CURA-3711: Set job name when opening a file from CLI

- resources/qml/Sidebar.qml
Background of toggle button gets same color as toolbar surrounding the button.
> Make background color of toggle button themeable

- cura/Settings/ExtruderManager.py
- cura/Settings/MachineManager.py
- plugins/MachineSettingsAction/MachineSettingsAction.py
This PR fixes some issues with the Multiextruder Machine Settings, and is a followup to #1521
> Fix multiextruder machinesettings

- resources/definitions/alya3dp.def.json
See https://github.com/Ultimaker/Cura/issues/1759
> Add definition for Alya 3d printer

- plugins/3MFReader/ThreeMFWorkspaceReader.py
~**NEEDS** https://github.com/Ultimaker/Uranium/pull/248~
It works with both old and new project files, but the code is not very nice. Let's have some discussion about it.
> CURA-3756 Fix project loading

- plugins/3MFWriter/ThreeMFWorkspaceWriter.py
> Save Cura version to project files

- resources/i18n/ptbr/cura.po
- resources/i18n/ptbr/fdmextruder.def.json.po
- resources/i18n/ptbr/fdmprinter.def.json.po
Updated brazilian portuguese strings for Cura 2.6
> updated strings for cura 2.6

- cura/LayerDataBuilder.py
- plugins/LayerView/LayerPass.py
This PR fixes https://github.com/Ultimaker/Cura/issues/1931
> Fix displaying layers with python3.6

- resources/definitions/peopoly_moai.def.json
This PR adds common values for infill overlap and adhesion type to the Moai definition by request of Peopoly.
> Update Peopoly Moai definition

- resources/definitions/fdmprinter.def.json
See https://github.com/Ultimaker/CuraEngine/pull/536.
> Added z_seam_relative setting to determine whether z seam origin is relative to part or not.

- resources/qml/Preferences/GeneralPage.qml
https://github.com/Ultimaker/Cura/issues/1572
See also; https://github.com/Ultimaker/Uranium/pull/264
> Added zoom to mouse preference

- resources/definitions/cartesio.def.json
- resources/extruders/cartesio_extruder_0.def.json
- resources/extruders/cartesio_extruder_1.def.json
- resources/extruders/cartesio_extruder_2.def.json
- resources/extruders/cartesio_extruder_3.def.json
Cartesio extruders start and end positions added
> Cartesio extruders start positions

- resources/qml/JobSpecs.qml
- resources/qml/MonitorButton.qml
- resources/qml/SaveButton.qml
- resources/qml/Sidebar.qml
The printing time is moved to a new location, in the sidebar rather than the print job statistics bit.
> Move printing time

- plugins/PluginBrowser/PluginBrowser.py
Orientated a bit on the way how browsers are sending their strings.
No idea, whether there is a standard on this or not.
Needs to be discussed I guess..
> PluginBrowser: Send also OS and architecture

- cura/Settings/ExtruderStack.py
- cura/Settings/GlobalStack.py
- cura/Settings/PerObjectContainerStack.py
- cura/Settings/SettingOverrideDecorator.py
- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
- resources/qml/Settings/SettingItem.qml
> CURA-4186 Add stack context for function evaluation

- resources/definitions/fdmprinter.def.json
UI addition that goes with https://github.com/Ultimaker/CuraEngine/pull/579.
> Add relative_extrusion setting to special modes category.

- resources/definitions/vertex_delta_k8800.def.json
We've added the config for the K8800 machine
> Added vertex delta k8800

- cura/QualityManager.py
- cura/Settings/ProfilesModel.py
- resources/qml/Menus/ProfileMenu.qml
- resources/qml/Settings/SettingView.qml
- resources/qml/Sidebar.qml
- resources/qml/SidebarSimple.qml
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
> CURA-4182 Slider for quality profile

- resources/definitions/fdmprinter.def.json
Cross infill for super flex
Replaces https://github.com/Ultimaker/Cura/pull/2166
CuraEngine PR: https://github.com/Ultimaker/CuraEngine/pull/595
CURA-4095
> Fractal 3d infill alternate

- plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
- plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
Jira [CL-118](https://jira.ultimaker.com:8443/browse/CL-118)
> CL-118 Add support and text for disabled printers and print jobs which require config changes.

- plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
- plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
Jira https://jira.ultimaker.com:8443/browse/CL-455
These changes fell between the cracks during the merge/move action for the plugin yesterday.
> CL-455 Implement the print job pause, resume and abort for Cura Connect

- resources/definitions/fdmprinter.def.json
Engine stuff is https://github.com/Ultimaker/CuraEngine/pull/609.
Provides solution for #2412
> Added infill_offset_x and infill_offset_y settings.

- plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
> Revert "CL-523: Made sure printers are present before printjobs to avoid referring to…"

- plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
> CL-511 fix abort crash

- plugins/LayerView/LayerView.qml
This PR changes the width of the layerview layer number indicator.
Fixes #2396
> Fix width of the layerview layer box

- plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py
.. Logger has been imported twice..
> Sorting imports and removing superfluous import

- plugins/UM3NetworkPrinting/ClusterMonitorItem.qml
- plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
Make the blue color on the monitor tab consistent
CL-554
> CL-554 Make the blue color on the monitor tab consistent

- plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
- plugins/UM3NetworkPrinting/NetworkPrinterOutputDevicePlugin.py
> CL-555 Don't blow up at plugin start up due to the plugin path not being ready yet

- resources/qml/ExtruderButton.qml
- resources/qml/JobSpecs.qml
- resources/qml/Preferences/MaterialView.qml
- resources/qml/Preferences/MaterialsPage.qml
- resources/qml/PrintMonitor.qml
- resources/qml/Settings/SettingView.qml
- resources/qml/Sidebar.qml
- resources/qml/SidebarHeader.qml
- resources/qml/SidebarSimple.qml
Together with Uranium PR: https://github.com/Ultimaker/Uranium/pull/293
CURA-4437
> Change Text to Label and cast all sizes to int

- plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
> CL-584 no selecting disabled printers in the Cura Connect monitor tab

- plugins/UM3NetworkPrinting/NetworkPrinterOutputDevicePlugin.py
See Randall's big comment in CL-555. This PR correctly updates the printer output device objects with the correct number of detected printers in the Cura Connect group. This fixes the Cura Connect messages in the printer selection dialog which were incorrect for manually added printers.
> CL-555 fix incorrect msg in discovery

- plugins/MachineSettingsAction/MachineSettingsAction.py
> Fix crash when exiting Machine Settings

- cura/CuraApplication.py
- cura/Settings/MachineManager.py
- cura/Settings/SimpleModeSettingsManager.py
- resources/qml/SidebarSimple.qml
> Cura 4333 notification icon for recommended mode

- resources/definitions/fdmprinter.def.json
Why don't I have push access to Cura any more?
This PR accompanies https://github.com/Ultimaker/CuraEngine/pull/620
> slicing mode

- plugins/LayerView/LayerSliderLabel.qml
- plugins/UM3NetworkPrinting/ClusterControlItem.qml
- plugins/UM3NetworkPrinting/DiscoverUM3Action.qml
- plugins/UM3NetworkPrinting/MonitorItem.qml
- plugins/UM3NetworkPrinting/PrintCoreConfiguration.qml
- plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
- plugins/UM3NetworkPrinting/PrinterVideoStream.qml
- resources/qml/AskOpenAsProjectOrModelsDialog.qml
- resources/qml/JobSpecs.qml
I replaced `| 0` by `Math.floor(...)` so the code is more consistent.
> Cleaner open project dialog & redering on partial pixels fixes

- plugins/UM3NetworkPrinting/DiscoverUM3Action.qml
Fix for https://github.com/Ultimaker/Cura/issues/2745
Not sure if 'undefined' is different from 'null' in qml
> Also check if base.selectedPrinter is null

- resources/definitions/fdmprinter.def.json
See also CuraEngine PR https://github.com/Ultimaker/CuraEngine/pull/658
> CURA-4104 added settings for flow rate compensated extrusion

- resources/definitions/dagoma_discoeasy200.def.json
Hi,
Here is the list of changes:
- Icon name change (even if it doesn't exist)
- Plateform offset adjustment.
- Machine head adjustements.
- Gantry height adjustment.
- Gcode flavor removal as the default value of this setting in the fdmprinter json is ok.
- Gcode start modification as it uses 'print_temperature' setting which is an invalid Cura 2.x/3.x setting. I decided to use 'material_initial_print_temperature' as its description matches the needed purpose (minimal temperature to start the print).
- Overrides the material diameter as this printer uses 1.75 mm PLA filament.
Regards,
Orel from Dagoma
> Improve discoeasy200 profile

- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/SimulationView.qml
- plugins/SimulationView/__init__.py
Increase simulation speed.
Hide Layer Thickness option in color scheme.
Hide nozzle when switching layers.
Set the handles in front of the view.
Name changed back to "Layer View"
> CURA-4609 Minor improvements in Simulation View

- plugins/CuraEngineBackend/StartSliceJob.py
Some minor performance optimisations, and refactoring to pull some of the common code out to a separate function.
> Optimise sending slice job

- plugins/MachineSettingsAction/MachineSettingsAction.py
This PR fixes updating material container for extruder when changing gcode flavor between Ultigcode and Marlin for the UM2(extended). Since single extrusion printers have a single extruder stack now, material container needs to be set on the extruder stack instead of the global stack.
This fixes the following scenario:
* Add a new UM2
* In Machine Settings, switch gcode flavor to Marlin
* The UM2 should now gain material selection, but Cura shows that the printer has no material set (red material selection dropdown).
Furthermore:
* Select a material
* Switch flavor back to Ultigcode (Ultimaker 2). Material selection is now removed
* Slice something
* Note that Cura still thinks the printer has a material (cost estimation in the lower right of the sidebar, which should not be available, …
> [regression] Fix material container for extruder when changing gcode flavor

- plugins/USBPrinting/USBPrinterOutputDevice.py
This PR enhances the USB Printing plugin to show target temperatures (from M105 responses), shows the total and estimated remaining time, and the jobname while printing. This was previously left unimplemented.
This PR fixes #2760
> Show USB target temperatures, (estimated) time and jobname

- plugins/CuraEngineBackend/ProcessSlicedLayersJob.py
Hi @diegopradogesto, I think this PR fixes the black cat problem. Does it make sense to you?
> Fix simulation view render race (aka black cat issue!)

- cura_app.py
Have currently the issue here, that when running Cura as a COM service, that the Cura.exe is popping up for (feels like) 1s or less and crashes.
> Getting logs earlier!

- resources/definitions/builder_premium_large.def.json
- resources/definitions/builder_premium_medium.def.json
- resources/definitions/builder_premium_small.def.json
- resources/definitions/deltacomb.def.json
Finishing the cleaning up like #2867 did.
Contributes to issue CURA-4243.
> Remove ID from definition files

- plugins/PluginBrowser/PluginBrowser.py
- plugins/PluginBrowser/PluginBrowser.qml
- plugins/PluginBrowser/PluginEntry.qml
Re-styled plugin browser. Some small tweaks are needed but it is fully functioning.
> Plugin browser

- plugins/SimulationView/SimulationView.qml
- plugins/UltimakerMachineActions/UMOCheckupMachineAction.qml
- resources/qml/Cura.qml
- resources/qml/ExtruderButton.qml
- resources/qml/MonitorButton.qml
- resources/qml/SaveButton.qml
- resources/qml/Settings/SettingCategory.qml
- resources/qml/Settings/SettingCheckBox.qml
- resources/qml/Settings/SettingComboBox.qml
- resources/qml/Settings/SettingExtruder.qml
- resources/qml/Settings/SettingItem.qml
- resources/qml/Settings/SettingOptionalExtruder.qml
- resources/qml/SidebarHeader.qml
- resources/qml/SidebarSimple.qml
- resources/qml/SidebarTooltip.qml
- resources/qml/Toolbar.qml
- resources/themes/cura-light/styles.qml
I went through all divisions in the qml files. Hope I didn't miss anything.
CURA-4941
> Fix rounding errors for garbled text

- plugins/MachineSettingsAction/MachineSettingsAction.qml
- plugins/SimulationView/SimulationView.qml
- resources/qml/Cura.qml
- resources/qml/JobSpecs.qml
- resources/qml/Preferences/MaterialView.qml
- resources/qml/Preferences/MaterialsPage.qml
- resources/qml/SaveButton.qml
- resources/qml/Settings/SettingCategory.qml
- resources/qml/Settings/SettingExtruder.qml
- resources/qml/Settings/SettingItem.qml
- resources/qml/Settings/SettingView.qml
- resources/qml/Sidebar.qml
- resources/qml/SidebarHeader.qml
- resources/qml/SidebarSimple.qml
- resources/qml/Topbar.qml
- resources/themes/cura-light/styles.qml
This is a PR for 3.2 and also has a Uranium PR ( https://github.com/Ultimaker/Uranium/pull/327 )
CURA-4941
> Checked all divisions (again..) and multiplications on rounding errors

- resources/definitions/fdmprinter.def.json
- resources/themes/cura-light/theme.json
This PR makes possible to enable and disable the setting that allows connecting the infill through the walls, for the grid and triangular infill.
This goes together with https://github.com/Ultimaker/CuraEngine/pull/706
> Feature zigzag all infill for triangular and grid

- cura/Settings/MachineManager.py
- resources/qml/Settings/SettingView.qml
Context menu option when right clicking in a value.
So the user has both 'copy value to all extruders' and 'copy all values to all extruders'.
> add Copy all values to all extruders

- plugins/GCodeReader/RepRapFlavorParser.py
See https://duet3d.dozuki.com/Wiki/Gcode#Section_G90_Set_to_Absolute_Positioning
> No! G90 does not command absolute extrusion, M82 does that.

- resources/i18n/zh_TW/cura.po
- resources/i18n/zh_TW/fdmextruder.def.json.po
- resources/i18n/zh_TW/fdmprinter.def.json.po
Traditional Chinese translation for cura 3.3
> [3.3] Update zh_tw translation for cura 3.3

- resources/definitions/fdmprinter.def.json
- resources/quality/ultimaker3/um3_aa0.25_CPE_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_CPE_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_CPE_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_CPE_High_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_CPE_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_CPE_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_CPE_Superdraft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_CPE_Verydraft_Print.inst.cfg
- resources/variants/ultimaker3_bb0.8.inst.cfg
- resources/variants/ultimaker3_bb04.inst.cfg
- resources/variants/ultimaker3_extended_bb0.8.inst.cfg
- resources/variants/ultimaker3_extended_bb04.inst.cfg
These settings should increase the reliability of PVA prime towers, especially in combination with CPE.
> Prime tower updates

- resources/quality/ultimaker3/um3_aa0.4_PC_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PC_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PC_High_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PC_Normal_Quality.inst.cfg
PC top bottom speed for the 0.4 printcore adjusted to work based on formula
> PC profile adjustment

- cura/MultiplyObjectsJob.py
- cura/Scene/CuraSceneNode.py
- plugins/SupportEraser/SupportEraser.py
> [3.3] Fix support eraser 

- resources/definitions/fdmprinter.def.json
This is a setting to control the maximum travel resolution feature in this Pull Request: https://github.com/Ultimaker/CuraEngine/pull/755
Implements CURA-5171.
> Add setting for maximum travel resolution

- resources/quality/ultimaker3/um3_aa0.25_PP_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PP_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PP_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PP_Normal_Quality.inst.cfg
Fixed the temperatures so they are calculated from the material file. No more exclamation marks.
> PP formula based temperatures fix

- plugins/Toolbox/resources/qml/Toolbox.qml
- plugins/Toolbox/resources/qml/ToolboxAuthorPage.qml
- plugins/Toolbox/resources/qml/ToolboxCompatibilityChart.qml
- plugins/Toolbox/resources/qml/ToolboxDetailPage.qml
- plugins/Toolbox/resources/qml/ToolboxDetailTile.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsGridTile.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsShowcaseTile.qml
- plugins/Toolbox/resources/qml/ToolboxFooter.qml
- plugins/Toolbox/resources/qml/ToolboxInstalledTile.qml
- plugins/Toolbox/resources/qml/ToolboxLicenseDialog.qml
- plugins/Toolbox/resources/qml/ToolboxTabButton.qml
- resources/themes/cura-light/styles.qml
- resources/themes/cura-light/theme.json
This PR fixes a number of minor issues in the new Toolbox:
* improves thumbnail rendering
* fixes text rendering (OSX and on dark themes)
* fixes binding loop and other warnings
> Fix toolbox appearance

- plugins/ChangeLogPlugin/ChangeLog.txt
Added more details about the work I did. Additionally, I think your effort in designing the final icon should be also mentioned!
I'm left-handed with UI designing as you know..
> Updating changelog about engine icon

- resources/definitions/fdmprinter.def.json
frotnend setting to https://github.com/Ultimaker/CuraEngine/pull/710
> support_wall_count setting

- cura/CuraPackageManager.py
- resources/qml/Cura.qml
Simplified hack other than https://github.com/Ultimaker/Cura/pull/3832 and https://github.com/Ultimaker/Uranium/pull/351
@ianpaschal
> CURA-5357 Drag-n-drop for curapackages

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
- Solve https://github.com/Ultimaker/Cura/issues/3608.
- Now account for raft layers when choosing "Pause at layer no".
- Now positions the nozzle at (X, Y) of the next layer when resuming.
- Cleaning code
> Bug fixes and improvements for PauseAtHeight plugin

- plugins/VersionUpgrade/VersionUpgrade33to34/VersionUpgrade33to34.py
- resources/definitions/fdmprinter.def.json
frontend settings for CuraEngine PR: https://github.com/Ultimaker/CuraEngine/pull/711
> settings for infill support

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
- plugins/XmlMaterialProfile/product_to_id.json
This PR includes some needed changes for being able to use PVA to 3rd party printers and mark Ultimaker printers as incompatible.
> PVA compatible with 3rd party printers.

- cura.appdata.xml
> Fixed incorrect appstream data XML.

- resources/definitions/uni_print_3d.def.json
- resources/meshes/uni_print_3d_platform.stl
This PR adds support for the UNI-PRINT-3D printer from TheCoolTool:
* [Machinekit Config on GitHub](https://github.com/thecooltool/machinekit-configs/tree/v2/UNI-PRINT-3D)
* [Offical Product Page](http://www.thecooltool.com/en/products/uni-print-3d/)
> adding the UNI-PRINT-3D config from TheCoolTool

- cura/CuraPackageManager.py
Make sure that the package file is there before we remove the existing installed files.
> Check the package file before installing it

- plugins/GCodeReader/FlavorParser.py
- plugins/Toolbox/src/Toolbox.py
- plugins/UM3NetworkPrinting/ClusterUM3OutputDevice.py
- plugins/UM3NetworkPrinting/DiscoverUM3Action.py
- plugins/UM3NetworkPrinting/SendMaterialJob.py
- plugins/X3DReader/X3DReader.py
I made some fixes so the code-style test will pass.
> Fix code style

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
There was a bit more involved than I thought, so now making a PR and a branch for it.
- For UM3 / Griffin it only does M10 ; pause
- For UM2 / UltiGCode it skips the temperature settings and replaces the retracts with M10 and M11 if the retract_amount > 0
Tested both and it seems to work fine.
> CURA-5491 pause at height

- resources/i18n/zh_CN/cura.po
- resources/i18n/zh_CN/fdmprinter.def.json.po
> Update Chinese translation

- plugins/Toolbox/resources/images/installed_check.svg
- plugins/Toolbox/resources/qml/ToolboxDownloadsGridTile.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsShowcaseTile.qml
- plugins/Toolbox/src/AuthorsModel.py
- plugins/Toolbox/src/Toolbox.py
In case of the authors view, it will show up in different color if not all the packages of this author are installed.
> CURA-5536 Use an icon indicating when a package is installed

- cura/CuraApplication.py
- plugins/CuraEngineBackend/CuraEngineBackend.py
This fixes a bug that we introduced in 07e92ead0b6100a4fd518fd4008536f0774ebb0a. This was a
bad translation from the previous code.
> CURA-5572 Update the scene when a Gcode is loaded.

- plugins/Toolbox/resources/qml/ToolboxDownloadsGrid.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsGridTile.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsPage.qml
- plugins/Toolbox/src/PackagesModel.py
- plugins/Toolbox/src/Toolbox.py
- resources/bundled_packages.json
> Add generic material packages to materials page

- resources/quality/ultimaker3/um3_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Verydraft_Print.inst.cfg
Removed an unneccesary line and changed first layer print temperature formula to use the set temperature, and not the default temperature.
> TPU 08 profiles cleanup

- resources/definitions/fdmprinter.def.json
frontend setting changes for https://github.com/Ultimaker/CuraEngine/pull/774
> Connect Infill Polygons AND Multiply Infill

- resources/qml/SaveButton.qml
> Indicate when "Prepare" button has already been clicked

- resources/definitions/fdmprinter.def.json
Frontend PR for:
https://github.com/Ultimaker/CuraEngine/pull/775
> Infill outline count

- plugins/Toolbox/resources/qml/ToolboxCompatibilityChart.qml
Contributes to CURA-5598
> *Please do **not** delete this branch after merging. Save it for future Toolbox related changes and PRs.*
> Continue scrolling over compatibility charts

- plugins/3MFWriter/ThreeMFWriter.py
- plugins/GCodeGzWriter/GCodeGzWriter.py
- plugins/GCodeWriter/GCodeWriter.py
- plugins/UFPWriter/UFPWriter.py
That will give some more information to the user when a message is shown in the frontend, like this:
This PR depends on https://github.com/Ultimaker/Uranium/pull/374
> Add some extra information when the FileWriters can't write the files.

- resources/definitions/fdmprinter.def.json
- resources/quality/ultimaker3/um3_aa0.25_ABS_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.25_CPE_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_ABS_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_CPE_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Verydraft_Print.inst.cfg
- resources/variants/ultimaker3_bb0.8.inst.cfg
- resources/variants/ultimaker3_bb04.inst.cfg
- resources/variants/ultimaker3_extended_bb0.8.inst.cfg
- resources/variants/ultimaker3_extended_bb04.inst.cfg
- resources/variants/ultimaker_s5_bb0.8.inst.cfg
- resources/variants/ultimaker_s5_bb04.inst.cfg
New settings for the prime towers for all profiles expect PP0.8 printcore
The desired outcome: 
prime tower diameter: 20 mm 
prime tower minimal volume: 6 mm3
> Cura-5457 prime tower settings

- cura/OneAtATimeIterator.py
- cura/Scene/ConvexHullDecorator.py
- cura/Settings/GlobalStack.py
Companion PR: https://github.com/Ultimaker/Uranium/pull/375
> CURA-5538 Fix print order for one-at-a-time mode

- plugins/CuraEngineBackend/StartSliceJob.py
> Fix the gcode start/end formatter

- cura/CuraApplication.py
- cura/Settings/SidebarCustomMenuItemsModel.py
- resources/qml/Settings/SettingView.qml
> Code style fixes

- cura/OneAtATimeIterator.py
- cura/Scene/ConvexHullDecorator.py
- cura/Settings/GlobalStack.py
Fix the collision detection in OneAtATimeIterator
Together with: https://github.com/Ultimaker/Uranium/pull/375
> CURA-5538 Fix one at a time

- resources/variants/ultimaker3_extended_aa0.25.inst.cfg
Set ultimaker3_extended_aa0.25.inst.cfg to be the same as the ultimaker3_aa0.25.inst.cfg.
> Fix UM3extended 0.25 variant file

- plugins/UM3NetworkPrinting/ClusterUM3OutputDevice.py
[CL-980](https://jira.ultimaker.com:8443/browse/CL-980)
> Send UFP to Ultimakers provided the firmware version is sufficient.

- cura/CuraApplication.py
- cura/Settings/GlobalStack.py
- plugins/GCodeGzWriter/__init__.py
- resources/qml/Cura.qml
- resources/qml/SaveButton.qml
Together with https://github.com/Ultimaker/Uranium/pull/389
> CURA-5649 Do not show gcode.gz as an option in save file dialog

- cura/Machines/QualityManager.py
The last fallback is the global qualities, either machine-specific or
generic, but not using both. Because if a machine defines its own global
qualities, it is intended to override the existing ones, so do not
fallback again in this case.
> CURA-5668 Fix quality lookup fallback mechanism

- plugins/UFPWriter/UFPWriter.py
> Add materil xml file to UFP file

- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFReader/__init__.py
- plugins/3MFWriter/__init__.py
- resources/qml/Cura.qml
> change .curaproject.3mf to just use .3mf

- plugins/Toolbox/resources/qml/ToolboxDownloadsGridTile.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsPage.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsShowcaseTile.qml
- plugins/Toolbox/src/Toolbox.py
Contributes to CURA-5670
Note: When testing this, you won't see any plugins in the plugins showcase because no plugins are currently tagged as "showcase". This has to be fixed in packages repository, not Cura.
> Build models using reserved tags

- resources/bundled_packages.json
Also rename the version upgrade bundled package.
> Update bundled packages to SDK version 5

- plugins/SimulationView/SimulationView.qml
> Set simulation path to 0 after updating layer

- plugins/SimulationView/SimulationView.qml
This reverts commit 3da6e3c4535db85a921bf5770903bd1a729946e1.
(Which was based on a misunderstanding between Andreea and Aleksei.)
> [CURA-5725] Revert "Set simulation path to 0 after updating layer"

- plugins/SimulationView/LayerSlider.qml
- plugins/SimulationView/PathSlider.qml
> Stop simulation after pressing Up or Down in simulation layer textfield

- plugins/UM3NetworkPrinting/resources/qml/CameraButton.qml
- plugins/UM3NetworkPrinting/resources/qml/ClusterControlItem.qml
- plugins/UM3NetworkPrinting/resources/qml/ClusterMonitorItem.qml
- plugins/UM3NetworkPrinting/resources/qml/DotButton.qml
- plugins/UM3NetworkPrinting/resources/qml/PrintCoreConfiguration.qml
- plugins/UM3NetworkPrinting/resources/qml/PrintJobInfoBlock.qml
- plugins/UM3NetworkPrinting/resources/qml/PrinterVideoStream.qml
- plugins/UM3NetworkPrinting/resources/svg/camera-icon.svg
- resources/themes/cura-light/theme.json
This PR is #4366 but without the later additions of the warnings/notifications. It branches of the original 'cura_connect_improvements' branch.
> Cura connect improvements 3.5

- cura/ObjectsModel.py
- plugins/CuraEngineBackend/Cura.proto
- plugins/CuraEngineBackend/StartSliceJob.py
This pull requests includes the name of each mesh in the message passed to CuraEngine. This will allow including comments in slicing to delineate which blocks of gcode are associated with specific meshes.
> Add mesh names to slicing message

- resources/definitions/ultimaker_s5.def.json
Removing the prime blob, equalizing flows and avoiding supports.
> S5 profile optimizations

- resources/definitions/fdmprinter.def.json
As discussed in https://github.com/Ultimaker/Cura/issues/4004.
See https://github.com/Ultimaker/CuraEngine/pull/850.
> Add gyroid infill pattern.

- resources/definitions/fdmextruder.def.json
As discussed in https://github.com/Ultimaker/Cura/issues/4259.
> Add machine_extruder_cooling_fan_number setting to specify print cooling fan for each extruder.

- plugins/MachineSettingsAction/MachineSettingsAction.qml
Provide easy way of setting the per-extruder print cooling fan number (see #4267).
> Added extruder setting field for cooling fan number.

- plugins/CuraEngineBackend/ProcessSlicedLayersJob.py
> Don't skip empty first layers in the layer view

- resources/qml/AboutDialog.qml
This PR adds some recent additions to the included python modules credited in the About dialog. It also fixes the appearance of the About dialog with the Ultimaker Dark theme.
> Add Charon, Shapely, Trimesh and NetworkX to credits

- resources/definitions/ultimaker_s5.def.json
Changed the wrong prime_blob setting, now it should be visible but disabled.
> Fixed prim blob visibility

- cura/CuraApplication.py
- cura/PrinterOutput/CameraView.py
- cura/PrinterOutput/NetworkCamera.py
- plugins/UM3NetworkPrinting/resources/qml/MonitorItem.qml
- plugins/UM3NetworkPrinting/resources/qml/PrinterVideoStream.qml
Temporary fix for 3.6-BETA, we'll probalby have a variant of https://github.com/Ultimaker/Cura/pull/4656 later, either for full release or subsequently.
> Cura 5821 fix camera memory leak

- resources/quality/ultimaker3/um3_aa0.4_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_TPU_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_TPU_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_TPU_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_TPU_Verydraft_Print.inst.cfg
Removal of all final and initial print temperature offsets, and huge increase in first layer print temperature. These changes should greatly improve first layer extrusion.
> TPU temperatures update

- plugins/UM3NetworkPrinting/resources/qml/PrinterCard.qml
- plugins/UM3NetworkPrinting/resources/qml/PrinterCardDetails.qml
> CL-1063 Always show camera icon in monitor tab

- plugins/UM3NetworkPrinting/resources/qml/PrinterCard.qml
Fixing CL-1063 (adding camera button at all times) introduced a few small spacing issues. This PR fixes them.
> Monitor tab spacing improvements

- plugins/ChangeLogPlugin/ChangeLog.txt
- plugins/Toolbox/resources/qml/Toolbox.qml
- plugins/Toolbox/resources/qml/ToolboxDownloadsShowcaseTile.qml
- plugins/Toolbox/src/PackagesModel.py
- plugins/Toolbox/src/Toolbox.py
- resources/qml/Actions.qml
- resources/qml/Cura.qml
> Rename user visible entries of ToolBox to Marketplace

- resources/qml/AddMachineDialog.qml
This PR is a followup to https://github.com/Ultimaker/Cura/pull/4498 and fixes codestyle and readability of those changes. 
Tag: CURA-5847
> Add Printer dialog codestyle and readability

- CMakeLists.txt
- cura/CuraApplication.py
- cura/CuraVersion.py.in
Needs https://github.com/Ultimaker/Uranium/pull/413
> CURA-5842 Set CuraApplication display name

- cura/PrintInformation.py
- cura/Scene/ConvexHullDecorator.py
> [3.6] [CURA-5896] Fix naming bugs and object shadow

- plugins/ChangeLogPlugin/ChangeLog.txt
- resources/bundled_packages/cura.json
- resources/quality/ultimaker_s5/um_s5_cc0.6_CFFCPE_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_CFFPA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_GFFCPE_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_GFFPA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_PLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_PLA_Fast_Print.inst.cfg
- resources/variants/ultimaker_s5_cc06.inst.cfg
> [3.6] [CURA-5900] Rename "CC Red 0.6" to "CC 0.6"

- plugins/UM3NetworkPrinting/resources/qml/PrintJobInfoBlock.qml
> CL-1140 Show print time in monitor tab

- plugins/VersionUpgrade/VersionUpgrade33to34/__init__.py
- plugins/VersionUpgrade/VersionUpgrade34to35/__init__.py
Add the quality folder to the version upgrade in order to update quality profiles.
Contributes to CURA-5915.
> Add version upgrade for quality profiles

- plugins/Toolbox/resources/qml/ToolboxCompatibilityChart.qml
Special version for master, so we don't break the string-freeze for 3.6 but still not forget to translate.
> (master) CURA-5922 add safety data sheet links

- resources/bundled_packages/cura.json
Apparently this is the new author_id.
Contributes to CURA-5926.
> Change the Ultimaker author_id to UltimakerPackages

- resources/qml/ActionPanel/ActionPanelWidget.qml
- resources/qml/Cura.qml
- resources/qml/ExtruderButton.qml
- resources/qml/Toolbar.qml
- resources/themes/cura-light/styles.qml
- resources/themes/cura-light/theme.json
Restyling of the Toolbar following the indications of the designers.
CURA-5928
> Toolbar 4.0

- resources/definitions/fdmprinter.def.json
See PR: #4486 
Fix English grammar and remove 'enabled for TreeSupport' without first merging to branch of fork (and then back).
CURA-5903
> Desktop metal feature minimum support area

- resources/qml/Account/GeneralOperations.qml
Previously this button just took you to the log-in page. Now it links you to the page to create a new account.
Fixes issue CURA-5921.
> Correct the link to create a new account

- resources/qml/ExtruderButton.qml
- resources/qml/Toolbar.qml
- resources/themes/cura-light/styles.qml
- resources/themes/cura-light/theme.json
... by modifying the rectangles and the behavior to get a rounded rectangle on the right-top and right-bottom. The hover and active colors also changed.
Contributes to CURA-5962.
> Improve the toolbar style

- cura.desktop.in
- cura.sharedmimeinfo
Together with https://github.com/Ultimaker/cura-build/pull/202
> CURA-5878 Update desktop and mimeinfo to add gcode mime type

- resources/definitions/bibo2_dual.def.json
- resources/definitions/bibo2_single_extruder_0.def.json
- resources/definitions/bibo2_single_extruder_1.def.json
- resources/extruders/bibo2_dual_extruder_0.def.json
- resources/extruders/bibo2_dual_extruder_1.def.json
- resources/extruders/bibo2_single_extruder_0_0.def.json
- resources/extruders/bibo2_single_extruder_0_1.def.json
- resources/extruders/bibo2_single_extruder_1_0.def.json
- resources/extruders/bibo2_single_extruder_1_1.def.json
Please, add BIBO2 3D printer definition and extruders settings to supported resources.
> Add BIBO2 printer (dual and single extruder settings)

- resources/qml/BorderGroup.qml
- resources/qml/RoundedRectangle.qml
It's designed so that it works in exactly the same way as Rectangle.
> Add border to rounded rectangle.

- resources/definitions/cocoon_create_modelmaker.def.json
- resources/extruders/cocoon_create_modelmaker_extruder_0.def.json
Add a preset for the Cocoon Create ModelMaker (Mini 3D printer sold by Aldi in Australian stores) to model list
> Add Cocoon Create ModelMaker

- cura/PrinterOutput/PrintJobOutputModel.py
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobPreview.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobProgressBar.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
This brings the progress bar and printer state in line with the Cura 4.0 redesign
> CL-1153 printer states in monitor

- resources/themes/cura-light/theme.json
CURA-6018. Together with https://github.com/Ultimaker/Uranium/pull/429
> Fix styling of messages

- plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
This was fixed in 4.0 and accidentally got reverted when merging another branch in.
Contributes to CL-1160
> CL-1160 Replace fix for 'None' materials

- cura/BuildVolume.py
- cura/Machines/MachineErrorChecker.py
- cura/Machines/Models/BaseMaterialsModel.py
- cura/Machines/Models/FavoriteMaterialsModel.py
- cura/Machines/Models/GenericMaterialsModel.py
- cura/Machines/Models/MaterialBrandsModel.py
- cura/Settings/ExtruderManager.py
- cura/Settings/ExtrudersModel.py
- cura/Settings/GlobalStack.py
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/CuraEngineBackend/StartSliceJob.py
- resources/qml/Dialogs/WorkspaceSummaryDialog.qml
- resources/qml/Menus/SettingsMenu.qml
> Cura 6016 improve ui speed

- plugins/PreviewStage/PreviewMenu.qml
- plugins/SimulationView/SimulationViewMenuComponent.qml
- resources/qml/ViewsSelector.qml
- resources/themes/cura-light/theme.json
> Fix preview stage menu

- cura/CuraApplication.py
- cura/Machines/Models/NozzleModel.py
- cura/Settings/ExtrudersModel.py
- cura/Settings/MachineManager.py
- plugins/MachineSettingsAction/MachineSettingsAction.qml
- plugins/SimulationView/SimulationViewMenuComponent.qml
- plugins/SolidView/SolidView.py
- plugins/UM3NetworkPrinting/resources/qml/UM3InfoComponents.qml
- resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
- resources/qml/Menus/ContextMenu.qml
- resources/qml/Preferences/ProfilesPage.qml
- resources/qml/PrintMonitor.qml
- resources/qml/PrintSetupSelector/Custom/CustomPrintSetup.qml
- resources/qml/PrintSetupSelector/PrintSetupSelector.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedSupportSelector.qml
- resources/qml/Settings/SettingExtruder.qml
- resources/qml/Settings/SettingOptionalExtruder.qml
- resources/qml/Toolbar.qml
Together with https://github.com/Ultimaker/Uranium/pull/434
- Use a single `ExtrudersModel` instead of creating one in every QML that uses it.
- Some cleanup
- Fix some warnings and errors in QML
> [4.0] CURA-6015 Fix osx crash

- plugins/UM3NetworkPrinting/resources/qml/UM3InfoComponents.qml
Also improve readability of super-duper-ultra-long-lines
> Fix UM3InfoComponents warnings

- plugins/MachineSettingsAction/MachineSettingsAction.qml
> [4.0] CURA-6036 Fix machine settings dialog

- plugins/UM3NetworkPrinting/resources/qml/MonitorCarousel.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorStage.qml
> Add keyboard navigation for printer carousel

- plugins/PostProcessingPlugin/scripts/ChangeAtZ.py
Fixed a spelling mistake in one of the tooltips.
> Fixed typo in ChangeAtZ.py

- plugins/Toolbox/resources/qml/ToolboxInstalledTile.qml
- resources/themes/cura-light/theme.json
Needs https://github.com/Ultimaker/Uranium/pull/459
> CURA-6085 Fix font sizes

- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterBuildPlate.py
- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrintCoreConfiguration.py
- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrintJobConfigurationChange.py
- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrintJobImpediment.py
- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrintJobStatus.py
- plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrinterStatus.py
These are the changes that should be made to the models for cloud printing after cura connect is updated to send the extra fields to the cloud
> Star-347: Update Cura Connect models

- resources/definitions/alfawise_u20.def.json
small tweak to fix start gcode in order to avoid default position of bed clamps
> fix start gcode on alfawise u20

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> CL-1222 Cloud flow pop-up (Finalize copy)

- resources/quality/ultimaker_s5/um_s5_cc0.6_PLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_PLA_Fast_Print.inst.cfg
> Add cc06 pla profile

- resources/definitions/anycubic_i3_mega.def.json
"has_materials": true for Anycubic i3 Mega
Fixes #4867
> Fix Anycubic i3 Mega has_materials

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> CL-1222 Ensure pop-up is not shown if cloud connection is already configured

- plugins/Toolbox/resources/qml/ToolboxDetailTile.qml
- plugins/Toolbox/resources/qml/ToolboxDetailTileActions.qml
> Add a where to buy link underneath the install button for material

- cura/Arranging/ArrangeObjectsJob.py
- cura/Arranging/ShapeArray.py
See also https://github.com/Ultimaker/Uranium/pull/467
> Arrange child-nodes (like blocker) with parents. [CURA-6120]

- resources/definitions/fdmprinter.def.json
Haven't actually tried printing gyroid support but at least now it can be evaluated.
As discussed in https://github.com/Ultimaker/CuraEngine/issues/991.
> Support gyroid support.

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> Improve "don't ask me again" checkbox

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
This may fix the images appearing in the messages for Cura Connect when running on Windows.
> Fix the path to the pop up images in the monitor tab.

- resources/definitions/flsun_qq.def.json
- resources/extruders/flsun_qq_extruder.def.json
This is my first attempt to add a new printer to Cura. I think I've followed all the instructions, but Cura tells me that the profile is corrupt. Perhaps someone could help me.
> Adds a printer definition for the FLSUN QQ

- plugins/UM3NetworkPrinting/resources/qml/MonitorQueue.qml
[CL-1247](https://jira.ultimaker.com:8443/browse/CL-1247)
> CL-1247 Hide the "View print history" button when connecting via cloud

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
- plugins/UM3NetworkPrinting/src/LegacyUM3OutputDevice.py
- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
^What it says on the box.
I also sorted the Uranium imports alphabetically... just some minor Boy Scouts of America type stuff.
> CL-1274 Don't use __file__ in the monitor tab

- cura/Machines/MaterialManager.py
Together with https://github.com/Ultimaker/Uranium/pull/468
> CURA-6237 Fix material container removal

- plugins/USBPrinting/USBPrinterOutputDevice.py
bed_temperature_matches : error in temperature search expression
> monitor does not show "Build Plate"

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> Prevent multiple cloud-flow pop-ups

- plugins/UM3NetworkPrinting/resources/qml/MonitorStage.qml
> CL-1281 Make sure to show printers even if queue is empty

- cura/Settings/MachineManager.py
> CL-1282 Handle "" and None as hot-end and material IDs

- resources/quality/ultimaker2_plus/um2p_nylon_0.25_high.inst.cfg
- resources/quality/ultimaker2_plus/um2p_nylon_0.4_fast.inst.cfg
- resources/quality/ultimaker2_plus/um2p_tpu_0.25_high.inst.cfg
Some more wrong values were found, these should be fixed with this pull request
> Update the speed values for the um2+

- resources/definitions/alfawise_u30.def.json
I can see a lot of complains about the print time being really different from what Cura says from the reality so here is a PR for the U30.  
I don't own an Alfawise **U20** printer but as they are almost the same, it may be duplicated to its definition too, (i won't do it)
> Fix Alfawise U30 to get more realistic print times

- plugins/UM3NetworkPrinting/src/Cloud/CloudProgressMessage.py
Less repetitive and don't use the word "cluster"
> CL-1287 Improved Cloud pop-up

- resources/definitions/ultimaker2.def.json
- resources/definitions/ultimaker2_plus.def.json
- resources/definitions/ultimaker3.def.json
- resources/definitions/ultimaker_original.def.json
- resources/definitions/ultimaker_original_dual.def.json
... except UMS5
Contributes to CURA-6089.
> Exclude gff and cff materials for all ultimaker printers

- plugins/Toolbox/resources/qml/ToolboxDetailTileActions.qml
- plugins/Toolbox/resources/qml/ToolboxHeader.qml
- plugins/Toolbox/resources/qml/ToolboxInstalledTileActions.qml
- plugins/Toolbox/resources/qml/ToolboxTabButton.qml
- plugins/Toolbox/src/Toolbox.py
- resources/qml/MainWindow/MainWindowHeader.qml
- resources/qml/Widgets/NotificationIcon.qml
- resources/qml/qmldir
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
This adds a notification icon to the top of the marketplace if there are packages that have a newer version on the marketplace.
This is paired with https://github.com/Ultimaker/Uranium/pull/476
CURA-6151
> Notify updates from marketplace

- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> CL-1325 Pass output device (or not) to cloud check method

- resources/themes/cura-light/theme.json
> Make pop up more visible

- cura/Settings/GlobalStack.py
- cura/Settings/MachineManager.py
Note: You need the ['handle_log_once' branch](https://github.com/Ultimaker/Uranium/pull/480) in Uranium to prevent spamming the logs!
part of CURA-6457
(Just a few ones, enough to check if this approach will get us anywhere.)
> Deprecate some MachineManager functions.

- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml
- plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
> CL-1055 show sliced for pills on print jobs

- cura/CuraApplication.py
- cura/Machines/Models/DiscoveredPrintersModel.py
- plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
- resources/qml/WelcomePages/AddPrinterByIpContent.qml
- tests/Machines/Models/TestDiscoveredPrintersModel.py
Together with https://github.com/Ultimaker/Uranium/pull/484
> CURA-6483 Move add by ip device discovery into DiscoveredPrintersModel

- plugins/UM3NetworkPrinting/resources/qml/MonitorBuildplateConfiguration.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorConfigOverrideDialog.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorContextMenuButton.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorExtruderConfiguration.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorIconExtruder.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorInfoBlurb.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobProgressBar.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterPill.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorQueue.qml
- plugins/UM3NetworkPrinting/resources/qml/PrintJobContextMenuItem.qml
- plugins/UM3NetworkPrinting/resources/qml/PrintWindow.qml
I saw this many times before in macOS when connecting to a secondary screen. I added some missed renderType properties in the Labels in QML.
**Before**:
**After**:
> Fix rendering issues in Monitor Page

- plugins/Toolbox/resources/qml/ToolboxDetailTileActions.qml
- resources/qml/Preferences/MachinesPage.qml
- resources/qml/PrintSetupSelector/PrintSetupSelectorContents.qml
- resources/qml/PrinterSelector/MachineSelector.qml
To be used in features that handle the following functionality: 
Marketplace, printer pref, add/manage printer from main mnu, print settings
> Added several ids to be used in integration tests

- resources/qml/Preferences/Materials/MaterialsBrandSection.qml
- resources/qml/Preferences/Materials/MaterialsList.qml
- resources/qml/Preferences/Materials/MaterialsPage.qml
-Added a text property to MaterialsBrandSection
-Added ids to materials menu buttons
> Added ids to materials for squish tests

- plugins/UM3NetworkPrinting/resources/qml/MonitorConfigOverrideDialog.qml
> CL-1259 Hide the Override button if it is not an option

- plugins/UM3NetworkPrinting/resources/qml/MonitorConfigOverrideDialog.qml
- plugins/UM3NetworkPrinting/src/ConfigurationChangeModel.py
This should maybe be cherry picked into 4.1, no?
> CL-1259 hide useless override button

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Brazilian portuguese strings updated for the release of Cura 4.1.
> Updated pt_BR strings

- resources/definitions/fdmprinter.def.json
> Fix visibility of Connect Support Lines.

- resources/definitions/hms434.def.json
- resources/extruders/hms434_tool_1.def.json
- resources/extruders/hms434_tool_2.def.json
- resources/extruders/hms434_tool_3.def.json
- resources/extruders/hms434_tool_4.def.json
- resources/extruders/hms434_tool_5.def.json
- resources/extruders/hms434_tool_6.def.json
- resources/extruders/hms434_tool_7.def.json
- resources/extruders/hms434_tool_8.def.json
start gcode changed
exruder gcode changed
> HMS434 update

- resources/definitions/erzay3d.def.json
Hello,
Before it gets into release, I want to fix value.
My previous pull request: https://github.com/Ultimaker/Cura/pull/5583
Robokinetics.
> Fix "retraction_amount" value for Erzay3D

- resources/shaders/striped.shader
> Fix striped (off-buildplate) shader for ortho-view.

- resources/definitions/creality_base.def.json
- resources/definitions/easyarts_ares.def.json
- resources/definitions/kossel_mini.def.json
- resources/definitions/kossel_pro.def.json
- resources/definitions/prusa_i3.def.json
- resources/definitions/prusa_i3_mk2.def.json
- resources/definitions/prusa_i3_xl.def.json
- resources/definitions/stereotech_start.def.json
- resources/definitions/vertex_delta_k8800.def.json
- resources/definitions/vertex_k8400.def.json
- resources/definitions/vertex_k8400_dual.def.json
- resources/qml/WelcomePages/AddLocalPrinterScrollView.qml
This should make it easier to find your printer among the long list of printers that we have now.
Implements CURA-6635.
> Categorise printers by manufacturer in Add Printer wizard

- plugins/3MFReader/ThreeMFWorkspaceReader.py
> CURA-6654 Fix creality project files

- plugins/CuraProfileReader/CuraProfileReader.py
> CURA-6659 Use VersionUpgradeManager to update the imported quality

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
- resources/definitions/fdmprinter.def.json
Change to align with the name in the XML material files.
Contributes to CURA-6662.
> Change the name of the original depriming settings

- plugins/SliceInfoPlugin/SliceInfo.py
> Add camera_view as stats

- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PETG_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PETG_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PETG_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PLA_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PLA_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PLA_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-M_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-M_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-M_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-OKS_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-OKS_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-OKS_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-S_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-S_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_PVA-S_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_TPU98A_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_TPU98A_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_TPU98A_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_PETG_B.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_PETG_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_PETG_D.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_PLA_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_PLA_D.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_TPU98A_B.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_TPU98A_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_TPU98A_D.inst.cfg
Just some minor changes to flow and temp for some profiles...
> eMotiontech_S3D_Flow_&_Temp_tuning

- plugins/PostProcessingPlugin/scripts/Stretch.py
The post stretch script currently treats extruder-only moves (retraction and priming) as normal extrusion moves. As the script stretches x-y coordinates around, this can result in slight x-y motions while retracting and priming.  Although seemingly benign, these slight x-y motions confuse certain printer firmwares to the point of ruining the print job.
This change detects extruder-only moves during gcode parsing and preserves the extruder-only motion in the output.
> Preserve extruder-only moves in post stretch script

- cura/PlatformPhysics.py
> Drop down to buildplate after resize (fix).

- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
> CS-251 Add manage printer link

- plugins/MachineSettingsAction/MachineSettingsPrinterTab.qml
- resources/definitions/fdmprinter.def.json
- resources/definitions/ultimaker_s5.def.json
See also the engine: https://github.com/Ultimaker/CuraEngine/pull/1106
part of CURA-6717
> Add machine_heated_build_volume.

- cura/PrinterOutput/Models/PrinterOutputModel.py
- cura/PrinterOutput/PrinterOutputDevice.py
- tests/PrinterOutput/Models/TestPrinterOutputModel.py
- tests/PrinterOutput/TestPrinterOutputDevice.py
> Cura 6732 available configurations

- plugins/UM3NetworkPrinting/src/SendMaterialJob.py
- plugins/UM3NetworkPrinting/tests/TestSendMaterialJob.py
> Fix materials API call

- plugins/CuraEngineBackend/CuraEngineBackend.py
Similar fix to those in https://github.com/Ultimaker/Cura/commit/23f4aa6e4f6d02b0342fb727cbed2991f3ea16d1
> Avoid crash due to race in CuraEngineBackend.

- cura/PrinterOutput/FirmwareUpdater.py
- plugins/FirmwareUpdater/FirmwareUpdaterMachineAction.qml
- plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py
- plugins/USBPrinting/AvrFirmwareUpdater.py
- plugins/USBPrinting/avr_isp/intelHex.py
- resources/definitions/ultimaker3.def.json
- resources/definitions/ultimaker3_extended.def.json
- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
Reverts Ultimaker/Cura#6313.
This merged master into our release branch. Instead we'll cherry-pick the two commits about R2 support to 4.3.
> Revert "CS-171 Add R2 support"

- cura/CuraActions.py
- plugins/SolidView/SolidView.py
- resources/shaders/overhang.shader
- resources/themes/cura-light/icons/rotate_face_layflat.svg
- resources/themes/cura-light/styles.qml
Wraps up development for the 'lay flat by face' feature, at least concerning the 4.3-BETA (we'll probably revisit it in the near future).
Added icon thanks to @Yian-Lai 
(See also the PR in Uranium, https://github.com/Ultimaker/Uranium/pull/521)
> CURA-6754 / CURA-6761 Fix Select Face

- resources/definitions/fdmprinter.def.json
Sorry, didn't notice this untll today.
> Fix spelling mistakes in blurb for small feature settings.

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Update brazilian portuguese strings for Cura 4.3.
> Updated pt_BR strings for Cura 4.3

- plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py
Follow up for https://github.com/Ultimaker/Cura/pull/6432. This time a better solution.
> CS-328 improvements

- cura/CuraApplication.py
Just preventing some long lines.
> CuraApplication: Some formatting around messageBox functions

- cura/CuraApplication.py
- cura/SingleInstance.py
- resources/qml/Dialogs/AskOpenAsProjectOrModelsDialog.qml
- resources/qml/Dialogs/OpenFilesIncludingProjectsDialog.qml
- resources/qml/Menus/RecentFilesMenu.qml
The logic using just a "skip_project_file_check" boolean was too obscure
imho, so used a string value with more explicit values to improve readability
CURA-6824
> Consider user preference when opening project files from cli.

- resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml
- resources/qml/Menus/MaterialMenu.qml
- resources/qml/Menus/NozzleMenu.qml
It is disabled, so changing it's material / variant doesn't make that much sense...
CURA-6872
> Prevent changing material / variant of disabled extruder

- resources/qml/IconWithText.qml
- resources/qml/Preferences/Materials/MaterialsDetailsPanel.qml
- resources/qml/PrintSetupSelector/Custom/CustomPrintSetup.qml
- resources/qml/PrintSetupSelector/PrintSetupSelectorHeader.qml
Fix some long texts extending their bounds
> CURA-6862_truncate_profile_names

- resources/intent/um_s5_aa0.4_ABS_Draft_Print_Quick.inst.cfg
- resources/intent/um_s5_aa0.4_ABS_Fast_Print_Accurate.inst.cfg
- resources/intent/um_s5_aa0.4_ABS_Normal_Quality_Accurate.inst.cfg
- resources/intent/um_s5_aa0.4_PLA_Draft_Print_Quick.inst.cfg
- resources/intent/um_s5_aa0.4_PLA_Fast_Print_Accurate.inst.cfg
- resources/intent/um_s5_aa0.4_PLA_Normal_Quality_Accurate.inst.cfg
- resources/intent/um_s5_aa0.4_TPLA_Draft_Print_Quick.inst.cfg
- resources/intent/um_s5_aa0.4_TPLA_Fast_Print_Accurate.inst.cfg
- resources/intent/um_s5_aa0.4_TPLA_Normal_Quality_Accurate.inst.cfg
No clear release date is scheduled yet, so we need to wait with adding these profiles until they're ready.
Contributes to issue CURA-6864.
> Add UMS5 intent profiles

- resources/definitions/fdmprinter.def.json
frontend setting for https://github.com/Ultimaker/CuraEngine/pull/872
> feat: option to leave the very bottom of the print open

- cura/CuraApplication.py
- cura/Machines/Models/FirstStartMachineActionsModel.py
- cura/Machines/Models/IntentCategoryModel.py
- cura/Settings/MachineManager.py
- cura/Settings/SettingInheritanceManager.py
- resources/i18n/nl_NL/cura.po
- resources/qml/PrintSetupSelector/Recommended/RecommendedPrintSetup.qml
- resources/qml/Settings/SettingItem.qml
- resources/qml/Settings/SettingView.qml
I dusted off the good 'ol qml profiler to make things a bit faster. 
Linked with https://github.com/Ultimaker/Uranium/pull/537
> Qml speed improvements

- plugins/PreviewStage/PreviewMain.qml
- plugins/SimulationView/PathSlider.qml
- plugins/SimulationView/SimulationViewMainComponent.qml
- resources/qml/Cura.qml
Dynamically resize the simulation path slider width based on 
the window width and the preferred width from the theme.
Same approach as used for the layer slider
> CURA-6874_path_slider_layout

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
- resources/definitions/fdmprinter.def.json
part of CURA-6971
See also PPA pull 38.
> Add missing 'material break preparation temperature'.

- resources/qml/Cura.qml
Added the project name in Window Title.
> CURA-6978/Added the project name in Window Title

- plugins/PostProcessingPlugin/scripts/DisplayRemainingTimeOnLCD.py
Only correcting in master; may want to consider correcting in other branches depending your opinion
> Fixed typo

- resources/i18n/es_ES/cura.po
"Anchura" means width not weight. Weight is translated as "peso"
> Spanish i18n fix fillament weight

- cura/Machines/VariantNode.py
Previous implementtion would default to first material in base file.
Fixed and added some checks and logs
CURA-7023
> Fix selecting a new material for a base file on container deletion

- cura/CuraApplication.py
- cura/UI/CuraSplashScreen.py
Add some intermediate loading messages and make sure the messages are shown at the right moment
> CURA-6823_improve_splash_screen_responsiveness

- run_mypy.py
Checking Cura takes up most of the time, but during that time we could check for the plugins.
See also: https://github.com/Ultimaker/Uranium/pull/558
> Speed up mypy checking

- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/SimulationView.py
Since python is bad at looping, only re-calculate the start/end index when it's changed (instead of doing this for each render)
> Speed up layerview

- plugins/USBPrinting/USBPrinterOutputDevice.py
- plugins/XmlMaterialProfile/PluginInfo.py
- plugins/XmlMaterialProfile/XmlMaterialProfile.py
- plugins/XmlMaterialProfile/__init__.py
I'm undecided as to whether the creating of a new class is really worth it. Please advise, reviewer.
> CURA-6255_incorrect_usage_of__file__

- cura/Machines/Models/MaterialBrandsModel.py
- cura/Machines/VariantNode.py
Creating this on behalf of Kostas Karmas
> Cura 7087 machine specific materials not loaded correctly

- plugins/Toolbox/src/Toolbox.py
- resources/qml/Actions.qml
- resources/qml/MainWindow/ApplicationMenu.qml
- resources/qml/Menus/MaterialMenu.qml
Button was fixed to open the in-Cura marketplace.
> Cura 7027 add more materials from marketplace button

- cmake/CuraTests.cmake
- docker/build.sh
- scripts/check_invalid_imports.py
Added a grep for import plugins.*. Wondering what the best place is to put this code
> ci_invalid_import_checker

- plugins/Toolbox/resources/qml/dialogs/ToolboxLicenseDialog.qml
- plugins/Toolbox/src/CloudSync/DownloadPresenter.py
- plugins/Toolbox/src/CloudSync/LicenseModel.py
- plugins/Toolbox/src/CloudSync/LicensePresenter.py
- plugins/Toolbox/src/CloudSync/SyncOrchestrator.py
- plugins/Toolbox/src/Toolbox.py
Depends on a Uranium PR with the same name
> CURA-7129_license_window_design

- plugins/SliceInfoPlugin/MoreInfoWindow.qml
- plugins/Toolbox/resources/qml/dialogs/ToolboxLicenseDialog.qml
- resources/qml/Widgets/ScrollableTextArea.qml
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
> Fix some dark theme styling (MoreInfoWindow, ToolboxLicenseDialog

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
As discussed in https://github.com/Ultimaker/Cura/issues/2550.
> Add fuzzy skin outside only option.

- cura/CuraApplication.py
- plugins/Toolbox/src/CloudSync/CloudPackageManager.py
- plugins/Toolbox/src/CloudSync/SyncOrchestrator.py
- plugins/Toolbox/src/Toolbox.py
- resources/qml/Cura.qml
> Cura 7099 sync sideloaded plugins

- plugins/RemovableDriveOutputDevice/WindowsRemovableDrivePlugin.py
> Fix the "save to removable drive" not appearing

- plugins/Toolbox/src/CloudSync/LicensePresenter.py
- plugins/Toolbox/src/CloudSync/SyncOrchestrator.py
> Fix LicensePresenter: reset state when presenting licenses

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
Provide simple solution for https://github.com/Ultimaker/Cura/issues/2158.
> Added Hole Horizontal Expansion setting.

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmextruder.def.json.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Also changed a couple old strings because the translation was not very good.
> Updated pt_BR strings for Cura 4.5

- cura/CrashHandler.py
- cura_app.py
- plugins/SentryLogger/SentryLogger.py
> Prune all sensitive data before sending it to Sentry

- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
> Hide the Cloud Sync message when the user logs out

- plugins/PostProcessingPlugin/scripts/ColorMix.py
- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
Updated changes to https://github.com/Ultimaker/Cura/pull/6810
> Update to ColorMix.py script

- resources/definitions/skriware_2.def.json
Added `resolveOrValue('layer_height')` `support_infill_sparse_thickness` and `infill_sparse_thickness`
> fixed support layer height

- plugins/AMFReader/AMFReader.py
- plugins/TrimeshReader/TrimeshReader.py
This PR fixes the AMF and TriMesh readers to support watching the filesystem for modified files.
Fixes #7192
> Fix watching for changes in AMF and trimesh-loaded files

- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
Note that per object settings can not be enabled due to a bug introduced in CURA-7211
> CURA-7255_infill_only_dropdown

- plugins/3MFReader/ThreeMFReader.py
This PR fixes the 3MF reader to support watching the filesystem for modified files.
This PR is a followup to #7205
> Fix watching for changes in 3mf files

- resources/intent/ultimaker_s3/um_s3_aa0.4_ABS_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_ABS_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_CPEP_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_CPEP_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_CPE_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_CPE_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_Nylon_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_Nylon_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_PC_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_PC_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_PLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_PLA_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_TPLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_TPLA_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_ABS_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_ABS_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPEP_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPEP_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPE_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPE_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_Nylon_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_Nylon_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PC_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PC_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PLA_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_TPLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_TPLA_Normal_Quality_Accurate.inst.cfg
These are new intent profiles to improve dimensional accuracy for those materials.
Implements CURA-7313.
> Add engineering profiles for engineering materials for UMS3 and UMS5

- resources/qml/Account/GeneralOperations.qml
- resources/qml/WelcomePages/CloudContent.qml
Updated Cloud sign in strings CURA-7314
> Updated Cloud sign in strings CURA-7314

- resources/qml/Preferences/GeneralPage.qml
Sorry for doing this, but my previous PR had an extraneous preference in it due to pressing Ctrl-Z one time too many. att @BagelOrb
> Remove extraneous preference

- cura/PrinterOutput/FirmwareUpdater.py
- plugins/ImageReader/ImageReaderUI.py
- resources/definitions/anet3d.def.json
- resources/qml/WelcomePages/AddLocalPrinterScrollView.qml
- resources/qml/WelcomePages/AddNetworkPrinterScrollView.qml
It would be great to have flow settings that are specific for every filament you have in your list, so that you don't have to write the flow value on every spool you have, in order to remember it.
Thanks
> FIlament specific flow settings.

- resources/texts/change_log.txt
> Updated "What's New?"change log for 4.6

- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
Might help prevent the sync message to show multiple times
CURA-7364
> Add None-checks to CloudPackageChecker

- plugins/CuraEngineBackend/StartSliceJob.py
On behalf of @nallath 
CURA-7329
> Only check changed settings (and whatever it affects) for errors in POS

- plugins/SolidView/SolidView.py
- plugins/XRayView/XRayView.py
- resources/shaders/xray_composite.shader
X-ray errors showed as green and translucent instead of read and solid.
CURA-7407
> CURA-7407 Fix x-ray error colour

- plugins/PostProcessingPlugin/PostProcessingPlugin.py
- resources/texts/change_log.txt
- resources/variants/creality_ender3pro_0.2.inst.cfg
- resources/variants/creality_ender3pro_0.3.inst.cfg
- resources/variants/creality_ender3pro_0.4.inst.cfg
- resources/variants/creality_ender3pro_0.5.inst.cfg
- resources/variants/creality_ender3pro_0.6.inst.cfg
- resources/variants/creality_ender3pro_0.8.inst.cfg
- resources/variants/creality_ender3pro_1.0.inst.cfg
~~Will add ticket number later.~~  CURA-7404
See also: https://github.com/Ultimaker/Uranium/pull/605
> Clean pycache in non-bundled folders.

- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/SimulationView.py
- plugins/SimulationView/layers.shader
- plugins/SimulationView/layers3d.shader
- plugins/SimulationView/layers3d_shadow.shader
- plugins/SimulationView/layers_shadow.shader
You'll need
https://github.com/Ultimaker/Uranium/pull/606
to make the per-layer simulator not crash :-)
> CURA-7426 Layerview can now deal with visibility extruder nrs. > 4

- resources/definitions/leapfrog_creatr_hs.def.json
- resources/definitions/leapfrog_creatr_hs_xl.def.json
- resources/extruders/leapfrog_creatr_hs_extruder_left.def.json
- resources/extruders/leapfrog_creatr_hs_extruder_right.def.json
- resources/extruders/leapfrog_creatr_hs_xl_extruder_left.def.json
- resources/extruders/leapfrog_creatr_hs_xl_extruder_right.def.json
Add support for Leapfrog Creatr HS and Creatr HS XL printers
> Leapfrog Creatr HS / XL Integration

- resources/definitions/hms434.def.json
- resources/extruders/hms434_tool_1.def.json
- resources/extruders/hms434_tool_2.def.json
Added host control of chamber fans
Added host info for toolchange
> HMS434 upgrade

- resources/definitions/tevo_tarantula.def.json
- resources/definitions/tevo_tarantula_pro.def.json
- resources/extruders/tevo_tarantula_extruder_1.def.json
- resources/extruders/tevo_tarantula_pro_extruder_1.def.json
> add 2nd extruder to Tevo Tarantula printers

- cura/Machines/Models/DiscoveredPrintersModel.py
This suggested change fixes #7739.
Tested on `master` with a second network plugin (WIP) enabled. Both plugins attempted to communicate with the printer at the specified IP address:
```
cura.Machines.Models.DiscoveredPrintersModel._attemptToAddManualDevice [171]: Network plugin UM3NetworkPrinting: attempting to add manual device with address 192.168.0.136.
UM3NetworkPrinting.src.Network.LocalClusterOutputDeviceManager.<lambda> [71]: Error transferring http://192.168.0.136/api/v1/system - server replied: Not Found
cura.Machines.Models.DiscoveredPrintersModel._onManualRequestTimeout [191]: Manual printer [192.168.0.136] request timed out. Cancel the current request.
cura.Machines.Models.DiscoveredPrintersModel._attemptToAddManualDevice [171]: Network plugin MPSM2NetworkPrinting: attempting …
```
> Add printer by IP: support more than one network plugin at the time

- resources/definitions/I3MetalMotion.def.json
- resources/extruders/I3MetalMotion_extruder_0.def.json
I added the definition for the eMotionTech printer and its extruder.
This is dully tested.
> Addition of the I3 Metal Motion printer by eMotionTech and the afferent extruder

- resources/i18n/fr_FR/fdmprinter.def.json.po
terme primaire pour prime pas équivalent en français   -> d'amorçage
> changement primaire _> d'amorçage

- resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
I have no idea why I thought a listview was needed for this when this was made. The data shouldn't be flickable, so it makes way more sense to use a row layout.
CURA-7480
> Converted the listview into a RowLayout

- cura/OAuth2/AuthorizationRequestServer.py
- cura/OAuth2/LocalAuthorizationServer.py
> Fix Authorization server not properly stopping after flow completes.

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
This PR requires https://github.com/Ultimaker/Cura/pull/7873 to be merged first.
CURA-7455
> Cura 7455 Add "Keep printer configurations" button in the removed printers message

- resources/definitions/fdmprinter.def.json
See also https://github.com/Ultimaker/CuraEngine/pull/1271
> CURA-6989 / CURA-6747 Add setting: Minimum slope steepness for stair-stepping.

- cura/CuraApplication.py
- docker/build.sh
Should make the tests a bit faster.
> [WIP] Run CTest in parallel

- plugins/3MFReader/ThreeMFWorkspaceReader.py
> Fix crash while reading 3mf files if the project's extruder list is empty

- plugins/UFPWriter/UFPWriter.py
Add a list of object names to the ufp file metadata
CURA-6915
> Write a list of object names to the global metadata objects to UFP file 

- resources/definitions/fdmprinter.def.json
- resources/definitions/skriware_2.def.json
> Value of skin_outline_count reverts to 0 when concentric top/bottom used

- cura/CuraApplication.py
- cura/UI/PrintInformation.py
- resources/qml/Preferences/GeneralPage.qml
- resources/texts/change_log.txt
- tests/TestPrintInformation.py
Technical implementation done.
Todo: add more variables
CURA-5479
> Add a print job name setting to general preferences

- resources/qml/Dialogs/AboutDialog.qml
> Update list of dependencies in "About" dialog

- .gitignore
- plugins/VersionUpgrade/VersionUpgrade462to47/VersionUpgrade462to47.py
- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
Removed spaghetti infill.
see also https://github.com/Ultimaker/CuraEngine/pull/1280
> Cura 7199 remove spaghetti infill

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
> Fix printer counts for the auto-added printer message

- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS-X_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS-X_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS-X_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_ABS_C.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_BVOH_A.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_BVOH_B.inst.cfg
- resources/quality/strateo3d/Standard_0.4/s3d_std0.4_BVOH_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS-X_B.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS-X_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS-X_D.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS_B.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_ABS_D.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_BVOH_B.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_BVOH_C.inst.cfg
- resources/quality/strateo3d/Standard_0.6/s3d_std0.6_BVOH_D.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS-X_C.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS-X_D.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS-X_E.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS_C.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS_D.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_ABS_E.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_BVOH_C.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_BVOH_D.inst.cfg
- resources/quality/strateo3d/Standard_0.8/s3d_std0.8_BVOH_E.inst.cfg
i fixed the problem of whitespace modification, sorry about that!
> New_fixed_Strateo3D_pull_request

- cura/CuraApplication.py
- cura/UI/PrintInformation.py
- plugins/VersionUpgrade/VersionUpgrade462to47/VersionUpgrade462to47.py
- resources/qml/Preferences/GeneralPage.qml
- resources/texts/change_log.txt
- tests/TestPrintInformation.py
It was decided that functionality present in existing plugins is
sufficient. No need to replicate it in our own codebase and
take on the burden of maintenance
CURA-5479
> Revert changes for CURA-5479

- resources/qml/Menus/FileMenu.qml
Quick qml string change. People sometimes send the wrong 3mf on the forum/issue tracker and then there's wasted time asking for it again. Idea from @fieldOfView
> Change "Save..." to "Save Project..." in file menu

- plugins/3MFWriter/ThreeMFWorkspaceWriter.py
- plugins/VersionUpgrade/VersionUpgrade462to47/VersionUpgrade462to47.py
> CURA-7608 Ignore machine network information when handling project files

- plugins/3MFReader/ThreeMFWorkspaceReader.py
> CURA-7608: Ignore machine network metadata when reading a project file

- resources/definitions/cubicon_style_neo_a22.def.json
- resources/extruders/cubicon_style_neo_a22_extruder_0.def.json
> [CUBICON] Add printer device (Style NEO-A22)

- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFReader/UpdatableMachinesModel.py
- plugins/3MFReader/WorkspaceDialog.py
- plugins/3MFReader/WorkspaceDialog.qml
Similar to PR: https://github.com/Ultimaker/Cura/pull/8142 with the difference that the drop down menus are merged into one. 
CURA-7609
> CURA-7609: Pick any printer when opening a project file (single dropdown)

- plugins/SimulationView/SimulationPass.py
- resources/shaders/striped.shader
> Show models outside of BP clearly in layerview.

- cura/Machines/Models/QualityManagementModel.py
I have no idea why it wasn't being created, but it has been wrong for a very long time.
Fixes #8245
> Ensure that quality_changes profile is correctly created on profile duplication

- resources/i18n/ko_KR/fdmprinter.def.json.po
-Corrected a grammar mistake
-Corrected the wrong translation
> Correct Korean translation

- cura/Settings/MachineManager.py
- resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml
- tests/TestMachineManager.py
> Speed up disable extruder

- resources/definitions/fdmprinter.def.json
See the backend PR https://github.com/Ultimaker/CuraEngine/pull/1324 for more information.
> CURA-7676 re-enable outer- and inner-wall widths

- resources/definitions/creality_base.def.json
- resources/definitions/creality_cr6se.def.json
- resources/variants/creality_cr6se_0.2.inst.cfg
- resources/variants/creality_cr6se_0.3.inst.cfg
- resources/variants/creality_cr6se_0.4.inst.cfg
- resources/variants/creality_cr6se_0.5.inst.cfg
- resources/variants/creality_cr6se_0.6.inst.cfg
- resources/variants/creality_cr6se_0.8.inst.cfg
- resources/variants/creality_cr6se_1.0.inst.cfg
Based on the profile that was shared within the Creality CR-6 SE community I wanted to merge this with the main branch in order to have it available by default in upcomming releases.
> Add support for Creality CR-6 SE

- plugins/USBPrinting/AutoDetectBaudJob.py
While working on a patch to make Cura work with my printer I noticed this variable is unnecessary.
> Remove redundant variable

- cura/CuraApplication.py
Merge along with https://github.com/Ultimaker/Uranium/pull/642
CURA-7735
> CURA-7735: Make symlink following optional when checking the plugin signatures

- cura/Arranging/Arrange.py
- cura/Arranging/ArrangeObjectsJob.py
- cura/Arranging/Nest2DArrange.py
- cura/BuildVolume.py
- cura/CuraApplication.py
- cura/MultiplyObjectsJob.py
- cura_app.py
CURA-7440
Also needs:
https://github.com/Ultimaker/Uranium/pull/643
> Swap out arrange for PyNest2d

- resources/definitions/fdmprinter.def.json
> disable material shrinkage percentage

- cura/OneAtATimeIterator.py
- plugins/CuraEngineBackend/StartSliceJob.py
> CURA-7776: Slicing not possible in one-at-a-time if objects outside buildplate overlap

- plugins/MonitorStage/MonitorMain.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorBuildplateConfiguration.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorCarousel.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorContextMenuButton.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorExtruderConfiguration.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorIconExtruder.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobProgressBar.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterPill.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorQueue.qml
- plugins/UM3NetworkPrinting/resources/qml/PrintJobContextMenuItem.qml
- plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterStatus.py
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
It only fixes a few of em, but hey, it's progress!
Cura-7745
> Fix some montior page hacks

- cura/Settings/MachineManager.py
> Force an re-evaluation of a setting when extruder has been disabled

- plugins/UM3NetworkPrinting/src/UltimakerNetworkedPrinterOutputDevice.py
> Fix not a group host message

- cura/Settings/MachineManager.py
> Revert "Prevent duplicate adding of extruders"

- cura/CuraApplication.py
This fixes the issue when the packing algorithm rotated an object
CURA-7796
> Reset the entire transformation when merging

- plugins/UM3NetworkPrinting/resources/qml/MonitorStage.qml
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/Models/Http/CloudClusterResponse.py
> Hide queue in Monitor page if printer does not support it

- resources/definitions/fdmprinter.def.json
See Engine-PR: https://github.com/Ultimaker/CuraEngine/pull/1350
> CURA-7557 / CURA-7677 Rename Optimize Wall Printing Order to Order Inner Walls By Inset.

- plugins/SliceInfoPlugin/SliceInfo.py
5 min fix. Helping the data team out a bit. Should we merge this in 4.8?
> Send None instead of empty string.

- cura/CuraApplication.py
> Gracefully handle exceptions in arrange

- resources/definitions/fdmprinter.def.json
Contributes to CURA-7115
Coupled with PR ultimaker/curaengine#1353
> Disable infill multiplier if gradual infill and connected lines enabled

- plugins/PerObjectSettingsTool/PerObjectSettingsTool.py
> Also add wall_line_count when adding a infill mesh

- resources/i18n/de_DE/cura.po
- resources/i18n/de_DE/fdmprinter.def.json.po
- resources/i18n/es_ES/cura.po
- resources/i18n/es_ES/fdmprinter.def.json.po
- resources/i18n/fr_FR/cura.po
- resources/i18n/fr_FR/fdmprinter.def.json.po
- resources/i18n/it_IT/cura.po
- resources/i18n/it_IT/fdmprinter.def.json.po
- resources/i18n/ja_JP/cura.po
- resources/i18n/ja_JP/fdmprinter.def.json.po
- resources/i18n/ko_KR/cura.po
- resources/i18n/ko_KR/fdmprinter.def.json.po
- resources/i18n/nl_NL/cura.po
- resources/i18n/nl_NL/fdmprinter.def.json.po
- resources/i18n/pt_PT/cura.po
- resources/i18n/pt_PT/fdmprinter.def.json.po
- resources/i18n/ru_RU/cura.po
- resources/i18n/ru_RU/fdmprinter.def.json.po
- resources/i18n/tr_TR/cura.po
- resources/i18n/tr_TR/fdmprinter.def.json.po
- resources/i18n/zh_CN/cura.po
- resources/i18n/zh_CN/fdmprinter.def.json.po
- resources/i18n/zh_TW/cura.po
- resources/i18n/zh_TW/fdmprinter.def.json.po
- resources/qml/Preferences/GeneralPage.qml
> CURA-7782 Add translations for 4.8

- tests/TestMachineManager.py
> CURA-7833: Add tests for correctPrintSequence

- resources/quality/ultimaker2_plus_connect/um2pc_cpe_0.4_fast.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_cpe_0.4_high.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_cpe_0.4_normal.inst.cfg
Combing settings for 0.4nozzle
> Update CPE settings for UM2C

- cura/BuildVolume.py
- tests/TestBuildVolume.py
This fixes CURA-7835 and Fixes #8716
> Ensure that the skirt_brim_line_width is selected from right extruder

- cura/Machines/MaterialNode.py
This was taking up 40% of the time to create the material nodes.
> Simplify and speed up the extending of the qualities list

- cura/CuraApplication.py
Otherwise they could be floating very high above the buildplate.
CURA-7855
> Drop objects to buildplate that have been scaled

- plugins/UFPWriter/UFPWriter.py
- resources/qml/Menus/FileMenu.qml
- resources/qml/Menus/SaveProjectMenu.qml
- resources/qml/Widgets/ComboBox.qml
> CURA-7865 Save file in existing project mvp

- resources/definitions/cubicon_style_neo_a31.def.json
- resources/definitions/cubicon_style_plus_a15.def.json
- resources/extruders/cubicon_style_neo_a31_extruder_0.def.json
Add Cubicon device. (Style NEO-A31)
> [CUBICON] Add device(Style NEO-A31) & Update start gcode.

- plugins/PostProcessingPlugin/scripts/CreateThumbnail.py
Added the ability to have thumbnails embedded into gcode similar to other slicers.
> Create Thumbnails in gcode via PostProcessingPlugin

- .github/ISSUE_TEMPLATE/bugreport.yaml
- .github/ISSUE_TEMPLATE/featurerequest.yaml
Fixed typo in featurerequest.yaml
Clarified message in bugreport.yaml about uploading project file
> Fixed typo and clarified message

- cura/CuraApplication.py
- resources/qml/Menus/FileMenu.qml
- resources/qml/Menus/SaveProjectMenu.qml
CURA-8034
https://github.com/Ultimaker/Uranium/pull/673
> Set & use enabled property for saving projects when ufp/gcode is loaded

- resources/definitions/geeetech_A10.def.json
Removed overwriting temperature gcode in the definition
Removed repeated gcode
Added comments for the gcode
> Update Geeetech A10 definition

- resources/qml/TableView.qml
> CURA- 8066: Change TableView row color and text color when the row is selected

- resources/qml/WelcomePages/AddNetworkOrLocalPrinterContent.qml
> CURA-8152: Go to the next page when adding a networked machine in oboarding wizard

- resources/qml/Preferences/GeneralPage.qml
Upgrade to newer QtQuickControls.
> CURA-8127 preference-screen OSX fix

- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
Fixed by using the qt quick controls 2
CURA-8127
> CURA-8127: Post processing script add script fix

- cura/OAuth2/KeyringAttribute.py
This should hopefully shut mypy up.
Contributes to CURA-7180
> Added typing of KeyringAttributes

- resources/definitions/flsun_q5.def.json
- resources/extruders/flsun_q5_extruder.def.json
Add FLSUN Q5 printer profile with working startup and end gcodes. Tested it and it works fine.
> FLSUN Q5 Printer profile

- cura/API/Account.py
- plugins/VersionUpgrade/VersionUpgrade48to49/VersionUpgrade48to49.py
> CURA-8093: Check client scope when upgrading from 4.8

- resources/qml/WelcomePages/WhatsNewContent.qml
Let's hope they don't go too crazy with the file size of these. But animated GIFs are now supported here.
Fixes CURA-8145.
> Support animated images in what's new pages

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmextruder.def.json.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Fixed some boolean entries description, fixed some verb declinations and added new translations.
> Updated pt_BR translation

- .github/ISSUE_TEMPLATE/bugreport.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/featurerequest.yaml
Removed issue-body in bugreport.yaml and featurerequest.yaml
Added config file: can't create a blank issue and added contact link to ultimaker community.
> Update issue forms

- resources/definitions/skriware_2.def.json
- resources/quality/skriware_2/sk2_advanced.inst.cfg
- resources/quality/skriware_2/sk2_fast.inst.cfg
- resources/quality/skriware_2/sk2_precise.inst.cfg
quality profiles for Skriware 2 added.
def.json updated with new settings resolve problems fixed for raft parameters.
> skriware 2 print settings update

- resources/definitions/syndaveraxi2.def.json
- resources/extruders/syndaveraxi2_extruder_0.def.json
This machine is slightly different from the Syndaver AXI Original. We would like it added into the Cura Ultimaker Supported Printers option.
> Add AXI2 machine profile

- resources/definitions/ultimaker.def.json
- resources/definitions/ultimaker2.def.json
- resources/definitions/ultimaker2_plus.def.json
- resources/definitions/ultimaker3.def.json
- resources/definitions/ultimaker_original.def.json
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.25_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_draft.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_fast.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.6_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.8_normal.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.25_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Verydraft_Print.inst.cfg
> Add PETG quality profiles

- resources/definitions/syndaveraxi.def.json
- resources/definitions/syndaveraxi2.def.json
correction to the SynDaver Axi machines gantry height value
> correction

- plugins/DigitalLibrary/src/DFFileExportAndUploadManager.py
- plugins/DigitalLibrary/src/DigitalFactoryController.py
- plugins/DigitalLibrary/src/DigitalFactoryFileModel.py
- plugins/DigitalLibrary/src/DigitalFactoryProjectModel.py
- plugins/DigitalLibrary/tests/TestDFFileExportAndUploadManager.py
- plugins/DigitalLibrary/tests/TestDigitalFactoryFileModel.py
- plugins/DigitalLibrary/tests/TestDigitalFactoryProjectModel.py
- plugins/DigitalLibrary/tests/TestDigitalLibraryApiClient.py
- plugins/DigitalLibrary/tests/conftest.py
> Cura 7959 add unit tests

- resources/definitions/inat_base.def.json
- resources/definitions/inat_proton_x_rail.def.json
- resources/definitions/inat_proton_x_rod.def.json
+ Changed the default machine height
+ Added one line to the start g-code
The start gcode change is important, the height change not so much.
> Small fixes for INAT printers

- plugins/DigitalLibrary/src/DigitalFactoryController.py
> Filter images from DF open screen

- README.md
This would resolve #9914.
I think @Ghostkeeper documented the channels a few years ago, likely a good choice for a review.
> Update Readme regarding irc network

- cura/CuraApplication.py
Requires https://github.com/Ultimaker/Uranium/pull/704.
CURA-8291
> CURA-8291: Set enterprise edition on initialization

- cura/CuraActions.py
> Set object bottom to be on buildplate with center model action

- resources/qml/WelcomePages/WhatsNewContent.qml
- resources/themes/cura-light/theme.json
Discussed with UX what the best approach would be.
Both came to the conclusion that this is the simplest
and more aesthetic approach.
The extra white space at the bottom and height of the
first screen is still acceptable according to UX.
Contributes to CURA-8290_whats_new_text
> Increased the height of the welcome wizard screen.

- cura/Backups/Backup.py
- cura/Backups/BackupsManager.py
CURA-8313 
https://github.com/Ultimaker/Uranium/pull/707
> Re-enable backing up of plugins

- resources/definitions/longer_base.def.json
- resources/definitions/longer_cube2.def.json
- resources/definitions/longer_lk1.def.json
- resources/definitions/longer_lk1plus.def.json
- resources/definitions/longer_lk4.def.json
- resources/definitions/longer_lk5.def.json
- change travel_speed to 65mm/s for LKx printers;
- set default adhesion type to raft
Please merge this into all forthcoming release version.
> Update LONGER printer profiles

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/Messages/PrintJobUploadSuccessMessage.py
The button redirects the user to the cloud page
CURA-8018
> Add monitor print button for cloud print

- plugins/SimulationView/SimulationViewMenuComponent.qml
> Change icon in simulation view to rectangle

- resources/qml/Widgets/ScrollableTextArea.qml
> CURA-8437: Wrap the text in the license window

- resources/definitions/seckit_skgo.def.json
- resources/definitions/seckit_sktank.def.json
- resources/extruders/seckit_skgo_extruder_0.def.json
- resources/extruders/seckit_sktank_extruder_0.def.json
Please help add SecKit printer definitions into Cura printer list. Thank you!
> Add SecKit SK-Tank and SK-Go printer definitions.

- resources/qml/ActionPanel/SliceProcessWidget.qml
- resources/qml/Menus/ConfigurationMenu/ConfigurationListView.qml
Requires: https://github.com/Ultimaker/Uranium/pull/718
**Before:**
**After:**
CURA-8439
> CURA-8439: Replace coloured warning icons

- plugins/UM3NetworkPrinting/resources/qml/CameraButton.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorInfoBlurb.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
> Inform user that the webcam is disabled for cloud printers

- com.ultimaker.cura.appdata.xml
- cura/CuraActions.py
- cura/CuraApplication.py
- cura/OAuth2/AuthorizationService.py
- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
- plugins/DigitalLibrary/src/DFFileExportAndUploadManager.py
- plugins/Toolbox/resources/qml/components/ToolboxDownloadsShowcase.qml
- plugins/Toolbox/resources/qml/components/ToolboxHeader.qml
- plugins/UM3NetworkPrinting/resources/qml/DiscoverUM3Action.qml
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
- resources/qml/Account/GeneralOperations.qml
- resources/qml/Account/UserOperations.qml
- resources/qml/Actions.qml
- resources/qml/WelcomePages/AddCloudPrintersView.qml
- resources/qml/WelcomePages/AddNetworkPrinterScrollView.qml
- resources/qml/WelcomePages/CloudContent.qml
- tests/TestOAuth2.py
> Add campaign links

- resources/definitions/fdmprinter.def.json
CURA-8458
Needs to be combined with https://github.com/Ultimaker/CuraEngine/pull/1477
> Expose distribution radius

- plugins/DigitalLibrary/src/BackwardsCompatibleMessage.py
- plugins/DigitalLibrary/src/DFFileExportAndUploadManager.py
- plugins/DigitalLibrary/src/DigitalFactoryController.py
Message-types are a new parameter to Messages, so they can't be used in SDK/API versions smaller than 7.7.0.
CURA-8473
> Digital Library plugin needs to be backwards compatible.

- cura/CuraApplication.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/VersionUpgrade/VersionUpgrade49to50/VersionUpgrade49to50.py
- plugins/VersionUpgrade/VersionUpgrade49to50/__init__.py
> Fix project loading Arachne

- plugins/DigitalLibrary/resources/qml/SaveProjectFilesPage.qml
> Disable df save if name is invalid

- plugins/VersionUpgrade/VersionUpgrade49to410/VersionUpgrade49to410.py
- plugins/VersionUpgrade/VersionUpgrade49to410/__init__.py
This could break backups in certain cases
CURA-8521
Fixes #10311
> Add the missing preference upgrade for 4.9 to 4.10

- resources/qml/Settings/SettingView.qml
This way we don't have to use the html in the setting item and we dont have to re-do the whole hover logic in the search text field.
This also makes the search magnifier themed, so it looks a lot better in the dark theme (which is the actual issue we're trying to solve here)
CURA-8498
> Replace the textfield with cura.Textfield

- cura/CuraApplication.py
This should remove the Unable to upgrade file of type extruder of version 2 messages
CURA-8509
> Add extruder to current version for version upgrade script

- cura/OAuth2/AuthorizationHelpers.py
Since we're no longer stuck on python 3.5, we can use secrets instead of random which provides better randomness.
CURA-8401
SEC-207
> Use secrets instead of random

- resources/i18n/zh_TW/cura.po
- resources/i18n/zh_TW/fdmprinter.def.json.po
> Traditional Chinese

- cura/ApplicationMetadata.py
- cura/UI/PrintInformation.py
- plugins/DigitalLibrary/src/DigitalFactoryOutputDevice.py
- plugins/UFPReader/plugin.json
- resources/bundled_packages/cura.json
This PR brings back the changes that were made as part of CURA-8358 in https://github.com/Ultimaker/Cura/pull/10328.
CURA-8566
> CURA-8566: Update filename after saving

- resources/definitions/creality_ender6.def.json
- resources/variants/creality_ender6_0.2.inst.cfg
- resources/variants/creality_ender6_0.3.inst.cfg
- resources/variants/creality_ender6_0.4.inst.cfg
- resources/variants/creality_ender6_0.5.inst.cfg
- resources/variants/creality_ender6_0.6.inst.cfg
- resources/variants/creality_ender6_0.8.inst.cfg
- resources/variants/creality_ender6_1.0.inst.cfg
Is there a reason this printer isn't yet added to Cura?
> Add Profile for Creality Ender 6

- resources/bundled_packages/cura.json
- resources/qml/ApplicationSwitcher/ApplicationButton.qml
- resources/qml/ApplicationSwitcher/ApplicationSwitcherPopup.qml
- resources/texts/change_log.txt
Switch from system styled tooltips to custom styled ones.
> CURA-8422 style tooltips

- resources/definitions/hellbot_magna_2_230_dual.def.json
- resources/definitions/hellbot_magna_2_300_dual.def.json
- resources/extruders/hellbot_magna_2_230_dual_extruder_0.def.json
- resources/extruders/hellbot_magna_2_230_dual_extruder_1.def.json
- resources/extruders/hellbot_magna_2_300_dual_extruder_0.def.json
- resources/extruders/hellbot_magna_2_300_dual_extruder_1.def.json
Change start gcodes of the Definitions of Magna 2 230 and 300 Dual. 
Add start and End gcodes for the extruders 1 and 2 of the Magna 2 230 and 300 Dual.
> Update Definitions and Extruders of Magna 2 230/300 dual

- cura/Arranging/Nest2DArrange.py
- cura/MultiplyObjectsJob.py
> Fix duplicating / multiplicating support blockers

- cura/Settings/SettingInheritanceManager.py
- resources/qml/Settings/SettingItem.qml
- resources/qml/Settings/SettingView.qml
A few unneeded conversions were done. Also moved one check to python from JS
According to my profiler, this should make it about 2x as fast.
> Improve speed of the inherit button

- plugins/PostProcessingPlugin/scripts/ChangeAtZ.py
Polish some changes made in https://github.com/Ultimaker/Cura/pull/10554 before potential merge.
> [Cura-8655] merge ChangeAtZ build-volume from contrib

- plugins/PostProcessingPlugin/scripts/ChangeAtZ.py
hello, I'm unsure of the requirements for creating pull requests, sorry in advanced.
I've fixed a couple typos and added the "enclosure temp" function to be adjusted.
> change at z update

- cura/CuraApplication.py
See also: https://github.com/Ultimaker/Uranium/pull/747
> [CURA-8647] Fix URL's for the update checker for Beta's.

- plugins/SupportEraser/SupportEraser.py
The translate wasn't done via an operation, so it wouldn't go back to the same
state after an undo / redo
Since I also ran into this, I decided to fix this in my own time :) 
Fixes #10648
> Fix undo and redo for support blocker

- plugins/Marketplace/PackageModel.py
- plugins/Marketplace/resources/images/placeholder.svg
- plugins/Marketplace/resources/qml/PackageCard.qml
- plugins/Marketplace/resources/qml/Packages.qml
- resources/qml/ToolTip.qml
- resources/themes/cura-light/icons/default/Download.svg
- resources/themes/cura-light/theme.json
Draft request so I don't forget to set the receiving branch to marketplace_redesign.
Very much W.I.P.!
> [CURA-8561] Introduce Plugin Card

- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
- plugins/Marketplace/RemotePackageList.py
- plugins/Marketplace/resources/qml/ManagePackagesButton.qml
- plugins/Marketplace/resources/qml/Marketplace.qml
- resources/qml/SearchBar.qml
- resources/qml/Settings/SettingView.qml
Add a search-bar for the (new) Marketplace.
Works for both Plugins and Materials. Inactive (hidden) when dealing with the Manage Packages tab (the already installed ones).
> [CURA-8559] Add new-marketplace search

- resources/definitions/ultimaker.def.json
The skin orientation is optimized for the cross (3d) pattern to reduce the bridge distance. For more information see PP-55.
> PP-55 reduce cross3d top layer bridge distance arachne

- resources/texts/change_log.txt
Updated the change log with two bug fixes
> Update change log

- plugins/Marketplace/resources/qml/Marketplace.qml
- plugins/Marketplace/resources/qml/Packages.qml
- White boxes
- Height of bar
- New message if no results (instead of end-of-results message)
> [CURA-8559] (New-)Marketplace Search-Bar UX Fixes

- cura/CuraApplication.py
- plugins/Marketplace/resources/qml/ManagedPackages.qml
- plugins/Marketplace/resources/qml/Marketplace.qml
- plugins/Marketplace/resources/qml/Materials.qml
- plugins/Marketplace/resources/qml/OnboardBanner.qml
- plugins/Marketplace/resources/qml/Packages.qml
- plugins/Marketplace/resources/qml/Plugins.qml
Add onboarding banners to the market place.
Fixes  [CURA-8541]
> Cura 8564 add onboarding banners with link to explain cura mp

- plugins/Marketplace/resources/qml/ManagedPackages.qml
- plugins/Marketplace/resources/qml/Marketplace.qml
- plugins/Marketplace/resources/qml/Materials.qml
- plugins/Marketplace/resources/qml/Packages.qml
- plugins/Marketplace/resources/qml/Plugins.qml
> [Cura 8563] - Easy navigation to cloud marketplace

- resources/i18n/cs_CZ/cura.po
- resources/i18n/cs_CZ/fdmprinter.def.json.po
Sorry, this time I did not manage to add the translations before the release.
> Add Czech translations for v4.12.1

- cura/UI/WelcomePagesModel.py
- cura/UI/WhatsNewPagesModel.py
Although this PR isn't technically required to implement the functionality, it does clean up some things in code that has to do with the functionality. The "real" fix is in the uranium counterpart (https://github.com/Ultimaker/Uranium/pull/754)
CURA-8696
> CURA-8696 Show whats new after beta

- resources/intent/ultimaker_s3/um_s3_aa0.4_PLA_VeryDraft_Print_Quick.inst.cfg
- resources/intent/ultimaker_s3/um_s3_aa0.4_TPLA_VeryDraft_Print_Quick.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PLA_VeryDraft_Print_Quick.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_TPLA_VeryDraft_Print_Quick.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_BAM_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_BAM_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_Verydraft_Print.inst.cfg
This pull request creates an experimental 0.3mm layer height print mode with a default and draft intent for PLA, T-PLA and the support materials PVA and BAM.
> Pp 50 0.3mm layer height print profiles

- resources/definitions/ultimaker.def.json
Overextrusion needs to be avoided to main high quality. More info: PP-86
> reduce flow for 100% density parts

- cura/BuildVolume.py
- resources/definitions/fdmprinter.def.json
- tests/TestBuildVolume.py
Also have temporary proposal for UX solution.
See backend PR: https://github.com/Ultimaker/CuraEngine/pull/1543
> [CURA-8083] Separate Vertical and Horizontal Shrinkage Compensation.

- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
Changed link how to load material profiles via usb
> Update material sync link

- resources/definitions/creality_sermoond1.def.json
- resources/variants/creality_sermoond1_0.2.inst.cfg
- resources/variants/creality_sermoond1_0.3.inst.cfg
- resources/variants/creality_sermoond1_0.4.inst.cfg
- resources/variants/creality_sermoond1_0.5.inst.cfg
- resources/variants/creality_sermoond1_0.6.inst.cfg
- resources/variants/creality_sermoond1_0.8.inst.cfg
- resources/variants/creality_sermoond1_1.0.inst.cfg
Hi there,
we work with several Sermoon D1 printers. And we would like to ask you to integrate this into Ultimaker Cura. (Original printer settings from Creality Slicer)
Thanks
Felix
> Add Creality Sermoon D1 Profile to Ultimaker Cura

- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_VeryDraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPLA_VeryDraft_Print.inst.cfg
0.3 profiles benefit from larger line width. PP-99
> increase linewidth to machine nozzle size

- cura/CrashHandler.py
- cura/CuraApplication.py
- plugins/SentryLogger/SentryLogger.py
Although this doesn't solve the issue, it does allow us to actually get data on what is going wrong!
https://github.com/Ultimaker/Uranium/pull/766
CURA-8760
> Ensure that stored log lines are sent to sentry if they haven't already been logged

- resources/i18n/de_DE/fdmprinter.def.json.po
Fix some German translations. 
Translated some empty msgstr
> Fixed some German translations

- cura_app.py
We don't need it ourselves, and it's a potentially serious attack vector.
CURA-8475
> Refuse to listen to QT_PLUGIN_PATH.

- resources/quality/ultimaker3/um3_aa0.4_TPLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPLA_Draft_Print.inst.cfg
The fdmprinters definitions contains the right default of one line. It is not set anywhere in the ultimaker profiles, appart from here. PP-98
> remove skin outline count overwrite

- resources/definitions/tevo_tarantula.def.json
- resources/definitions/tevo_tarantula_pro.def.json
Fixes https://github.com/Ultimaker/Cura/issues/11365
> Set default z hop speed to maximum allowed value for tevo tarantula pro

- plugins/FirmwareUpdateChecker/FirmwareUpdateCheckerJob.py
- plugins/GCodeReader/FlavorParser.py
- plugins/PostProcessingPlugin/PostProcessingPlugin.py
Doing this in a branch since my local mypy isn't failing.
> Fix typing

- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
- plugins/PerObjectSettingsTool/SettingPickDialog.qml
- resources/qml/Settings/SettingCheckBox.qml
Fix incorrect checkbox radius on all SettingCheckBox
Fix misalignment of show all checkbox in per model setting visibility dialog
Fix bad padding overwrite in DF search bar causing logo to overlap text
> [CURA-8378] improve checkbox visibility

- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
> [CURA-8939] Fix issues in the material sync dialog

- resources/qml/Menus/ContextMenu.qml
- resources/qml/Menus/EditMenu.qml
- resources/qml/Menus/FileMenu.qml
- resources/qml/Menus/HelpMenu.qml
- resources/qml/Menus/MaterialMenu.qml
- resources/qml/Menus/PreferencesMenu.qml
- resources/qml/Menus/SettingsMenu.qml
- resources/qml/Widgets/Menu.qml
- resources/qml/Widgets/MenuItem.qml
- resources/qml/Widgets/MenuSeparator.qml
- resources/themes/cura-light/theme.json
CURA-8928 
https://github.com/Ultimaker/Uranium/pull/784
> Menu visual fixes

- resources/qml/MonitorButton.qml
- resources/qml/PrinterOutput/ManualPrinterControl.qml
> [CURA-8980] Fix monitor page buttons

- resources/qml/Preferences/SettingVisibilityPage.qml
CURA-8978
https://github.com/Ultimaker/Uranium/pull/786
> Fix hide / show all in setting visibility page

- resources/qml/ColorDialog.qml
- resources/qml/Preferences/Materials/MaterialsView.qml
> Color dialog

- resources/qml/PrinterOutput/ExtruderBox.qml
- resources/qml/PrinterOutput/HeatedBedBox.qml
- resources/qml/PrinterOutput/ManualPrinterControl.qml
- resources/qml/PrinterOutput/OutputDeviceHeader.qml
Some imports were incorrect/missing.
CURA-9000
> Fix launching the usb printing menu

- resources/qml/MachineSettings/GcodeTextArea.qml
- resources/qml/MachineSettings/NumericTextFieldWithUnit.qml
- resources/qml/PrintSetupHeaderButton.qml
- resources/qml/PrintSetupSelector/Custom/CustomPrintSetup.qml
- resources/qml/Settings/SettingCheckBox.qml
- resources/qml/Settings/SettingExtruder.qml
- resources/qml/Settings/SettingOptionalExtruder.qml
- resources/qml/Settings/SettingTextField.qml
- resources/qml/Widgets/ComboBox.qml
- resources/qml/Widgets/RadioButton.qml
- resources/qml/Widgets/TextField.qml
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
Update checkboxes, radio and textinput to align with new designs.
CURA-8991
> [CURA-8991] Align input component styling

- resources/qml/Actions.qml
- resources/qml/PrintSetupSelector/Custom/MenuButton.qml
- resources/qml/PrintSetupSelector/Custom/QualitiesWithIntentMenu.qml
- resources/qml/ToolTip.qml
CURA-8928 
We forgot to update the qualities with intent menu. Since it uses tooltips, we can't re-use the menu items.
> Leftover menu fixes 

- resources/qml/Preferences/ProfilesPage.qml
CURA-8982
https://github.com/Ultimaker/Uranium/pull/790
> Profile tab fixes (preferences)

- resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml
Make material and print core menus appear at bottom of button like drop downs.
CURA-9004
> [CURA-9004] materials selection dropdown improvements

- resources/themes/cura-light/theme.json
Reduce width of profiles list and printers list.
Reduce width of buttons for selecting pages in preferences dialog
CURA-9008
https://github.com/Ultimaker/Uranium/pull/795
> [CURA-9008] Reduce width of preferences dialog page selection buttons.

- resources/qml/Preferences/ProfilesPage.qml
> Profile page fixes

- resources/qml/Actions.qml
- resources/qml/MainWindow/ApplicationMenu.qml
- resources/qml/Widgets/MenuSeparator.qml
> Application menu fixes

- resources/qml/Dialogs/DiscardOrKeepProfileChangesDialog.qml
- resources/qml/Preferences/GeneralPage.qml
- resources/themes/cura-light/theme.json
Swap comobox_wide sizes for combobox. Added an actually wide comobox_wide to be used in the general page.
CURA-8990
> [CURA-8890] combobox width

- resources/definitions/snapmaker2.def.json
Reference issue https://github.com/Ultimaker/Cura/issues/11666 for more details
> - fixed snapmaker2 End-Gcode definition for Z return variable

- cura/CuraApplication.py
- resources/definitions/fdmprinter.def.json
> Add resolve values for raft & interface extruders

- resources/qml/Preferences/GeneralPage.qml
- resources/qml/Settings/SettingView.qml
Added OnPositionChanged to General Page
CURA-8979
> [CURA-9039] fix combobox scrolling out of view

- resources/definitions/fdmprinter.def.json
The description was wholly wrong. Check out the new description to understand the setting for what it actually does!
> Fix Transitioning angle description with what it's actually for

- resources/definitions/fdmprinter.def.json
> disable 100% infill bottom layers trick for spiralize

- resources/definitions/fdmprinter.def.json
Relates to PP-143
Relates to CURA-9069
> Disable the variable line strategy option in the UI CURA-9069

- resources/definitions/fdmprinter.def.json
Frontend changes for https://github.com/Ultimaker/CuraEngine/pull/1622
For internal reference: PP-148
> Remove Center Last option from Wall Ordering

- resources/definitions/fdmprinter.def.json
Frontend settings for https://github.com/Ultimaker/CuraEngine/pull/1627
Contributes to CURA-9080
> Feat/Fix: transition filter limit

- cura/CuraApplication.py
May be a bit crude, but simple and readable, and we're supposed to have handled everything anyway at the point the event comes in.
Hopefully also solves the crashes reported on (some?) Linux/Mac by colleagues in the WIP branches.
> [CURA-9155] Fix Cura not closing properly on Windows.

- plugins/Marketplace/CloudApiModel.py
- plugins/Marketplace/CloudSync/CloudApiClient.py
- plugins/Marketplace/CloudSync/CloudPackageChecker.py
- plugins/Marketplace/CloudSync/DiscrepanciesPresenter.py
- plugins/Marketplace/CloudSync/DownloadPresenter.py
- plugins/Marketplace/CloudSync/LicenseModel.py
- plugins/Marketplace/CloudSync/LicensePresenter.py
- plugins/Marketplace/CloudSync/RestartApplicationPresenter.py
- plugins/Marketplace/CloudSync/SubscribedPackagesModel.py
- plugins/Marketplace/CloudSync/SyncOrchestrator.py
- plugins/Marketplace/__init__.py
- plugins/Marketplace/resources/qml/CompatibilityDialog.qml
- plugins/Marketplace/resources/qml/MarketplaceLicenseDialog.qml
- plugins/Marketplace/resources/qml/MultipleLicenseDialog.qml
- plugins/Marketplace/resources/qml/OnboardBanner.qml
- resources/qml/Account/SyncState.qml
- resources/qml/Account/UserOperations.qml
- resources/qml/Menus/PrinterTypeMenu.qml
That was a big oversight on our end! We removed the old plugin, but outright forgot to port the syncing logic.
This does introduce a bit of duplication, as we have a "LicenceDialog" and a "MultipleLicenceDialog". But seeing as we're so close to a release, I've opted to not take the more dangerous route of making sure that only one is used. We could consider fixing this in the future, but it's not too bad as far as I'm concerned (since it's also contained in a single plugin)
CURA-9146
> Account sync was broken

- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
- plugins/Marketplace/resources/qml/Packages.qml
Fix scrollbar filling space by replacing custom implementation with generic UM.ScrollBar
CURA-9144
> CURA-9144 Scrollbar in Marketplace and Digital Library are acting up

- plugins/Marketplace/resources/qml/CompatibilityDialog.qml
- plugins/Marketplace/resources/qml/MultipleLicenseDialog.qml
Path for placeholder images was one to many folder up the hierarchy
> CURA-9146 missing placeholder images for Marketplace

- plugins/Marketplace/resources/qml/PackageCardHeader.qml
> [CURA-9194] Tiny marketplace icon

- resources/i18n/cs_CZ/cura.po
- resources/i18n/cs_CZ/fdmprinter.def.json.po
I am finishing the translation. I have last few settings to translate. Then I will read all the new translations again and check for spelling errors and mistakes. But now I need to sleep on it.
It was really a big update this time. There are many new settings and some of them were quite hard to understand to me. I could not simply translate the texts without understanding what the settings really do. That's why it is taking so long.
Hopefully, I will finish it on 2nd of May.
> Czech translations v5.0

- resources/definitions/creality_ender3pro.def.json
The Ender 3 Pro's power supply can handle heating both at once.
> Heat bed and extruder together (Ender 3 Pro)

- resources/definitions/ultimaker2_plus_connect.def.json
Supersedes https://github.com/Ultimaker/Cura/pull/12113
> [PP-168] [CURA-9293] Fix UM2+C buffer underruns

- cura/CuraApplication.py
See backend PR: https://github.com/Ultimaker/Uranium/pull/822
> [SEC-255] [CURA-8966] In secure version: disable loading themes from unbundled folders.

- cura/CuraApplication.py
See backend PR: https://github.com/Ultimaker/Uranium/pull/823
> In secure version: disable loading themes from unbundled folders.

- com.ultimaker.cura.appdata.xml
screenshot.png does not exist anymore on master use cura-logo.png instead
Add content_rating tags according to https://hughsie.github.io/oars/index.html
> Add content_rating tags and fixes wrong url

- plugins/CuraEngineBackend/CuraEngineBackend.py
> Prevent run of out-of-install executable in secure context.

- resources/definitions/ultimaker.def.json
> reduce top/bottom flow by enabling top surface skin layers

- resources/definitions/ultimaker.def.json
PP-37 is not needed anymore because of PP-27. This solves the problem of PP-46 as well. For more details see PP-46
> revert PP-37

- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
While CURA-9337 is not implemented this a mitigation to avoid unnecessary combing. PP-172
> PP-172 disable travel_avoid_supports

- resources/variants/ultimaker_s3_dd04.inst.cfg
- resources/variants/ultimaker_s5_dd04.inst.cfg
DD core variant files for S3 & S5 printers
Relates to: PP-166
Needs to be pulled together with the following pull request in the Cura repository: https://github.com/Ultimaker/fdm_materials/pull/205
> PP-166 DD core variant files

- cura/CuraPackageManager.py
- plugins/3MFWriter/ThreeMFWriter.py
Fix some bad uses of paths causing issues when searching files on different OS
> [CURA-8610] save required packages metadata

- plugins/3MFWriter/ThreeMFWriter.py
> Don't show scary error message when saving custom file

- cura/CuraPackageManager.py
Ensure that we can also update intents (and variants) via packages.
CURA-7667
> Intents in packages

- plugins/3MFReader/WorkspaceDialog.qml
- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- resources/qml/Dialogs/AboutDialog.qml
- resources/qml/Dialogs/AskOpenAsProjectOrModelsDialog.qml
CURA-9402 
https://github.com/Ultimaker/Uranium/pull/836
> Fix background dark theme

- plugins/PostProcessingPlugin/scripts/Stretch.py
Use enumerate instead of range(len
> PostProcessingPlugin/.../Stretch.py Use enumerate

- .run_templates/pycharm_cura_run.run.xml.jinja
- .run_templates/pycharm_cura_test.run.xml.jinja
- conandata.yml
- conanfile.py
Add extra test run configuration.
> [CURA-8792] Move run configuration templates out of conan-config into this repo.

- resources/definitions/fdmprinter.def.json
It'll just confuse users. It confused _us_ (both developers and materials experts) a lot of the time :-D
See backend PR: https://github.com/Ultimaker/CuraEngine/pull/1689
> [CURA-9357] Remove some very difficult to explain (even to experts) settings.

- cura/Settings/CuraContainerStack.py
Cleaner and more idiomatic way to reverse a dictionary
> CuraContainerStack.py: improve TypeIndexMap

- cura/PrinterOutput/Peripheral.py
Since Peripheral is a data class use dataclasses
> Use dataclasses for Peripheral

- cura/TaskManagement/OnExitCallbackManager.py
- Fix typos
- Improve grammar
- Improve clarity
- Improve layout and shorten line lengths
> OnExitCallbackManager.py: improve documentation

- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
While CURA-9337 is not implemented this a mitigation to avoid unnecessary combing. PP-172
> disable travel_avoid_supports

- cura/Machines/Models/MachineListModel.py
- resources/qml/PrinterSelector/MachineListButton.qml
- resources/qml/PrinterSelector/MachineSelectorList.qml
> Add button to hide/show connected printers

- cura/MachineAction.py
Use f-string and error method with Logger instead of "Old Style" string
formatting.
> MachineAction.py: Use error method with Logger

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
> Always check if an abstract machine needs to be added

- plugins/VersionUpgrade/VersionUpgrade22to24/VersionUpgrade.py
Use enumerate instead of range(len
> VersionUpgrade.py: Use enumerate

- plugins/X3DReader/X3DReader.py
No need for range(len.. and later use of index...
> X3DReader.py: Iterate directly over list in readIndex()

- cura/Settings/MachineManager.py
> Fix extruders enabled button not updating

- cura/Settings/CuraContainerStack.py
There is no need for range(len
> CuraContainerStack.py: iterate directly over IndexTypeMap

- cura/Arranging/ArrangeObjectsJob.py
arrange from Nest2DArrange will return a boolean so we can simplify
> ArrangeObjectsJob.py: Refactor run method

- cura/Machines/Models/GlobalStacksModel.py
- cura/Machines/Models/MachineListModel.py
- cura/Settings/GlobalStack.py
- plugins/UM3NetworkPrinting/src/Messages/RemovedPrintersMessage.py
- resources/qml/Preferences/MachinesPage.qml
Various fixes regarding the cloud printer type feature that came out of the QA-process.
Cura 9277
> Various fixes for the cloud printer types feature

- cura/UI/PrintInformation.py
Use f-string and warning method with Logger instead of "Old Style string
formatting
> PrintInformation.py Use warning method with Logger

- resources/definitions/fdmprinter.def.json
CURA-9433
https://github.com/Ultimaker/CuraEngine/pull/1733
> Add initial layer flow settings

- cura/Machines/Models/CompatibleMachineModel.py
- resources/qml/Dialogs/ChoosePrinterDialog.qml
- resources/qml/PrinterSelector/PrintSelectorCard.qml
A few things weren't quite working / looking as they should.
CURA-9278
> UI / UX fixes for printer selection card

- plugins/UFPWriter/UFPWriter.py
> Add intent and quality fields to slice metadata

- .github/workflows/notify_on_print_profile_change.yml
To avoid print profile changes for ultimaker printers going unnoticed a github action is set up. PP-260
> Notify PP&M on Print Profile Change

- packaging/AppImage/AppRun
First unset QT_STYLE_OVERRIDE, then start Cura
Should fix https://github.com/Ultimaker/Cura/issues/12343
> Fix startup on Zorin OS

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
- Change M18 to M84 when disarming
- Add option to keep steppers engaged for 1 hour (when changing filament for example)
- Add beep option
- Allow newlines in "Additional GCODE" fields
> PauseAtHeight.py postprocessing script improvments

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
> minor fixes + layer_no instead of height

- resources/definitions/fdmprinter.def.json
See https://github.com/Ultimaker/CuraEngine/pull/1575
> Settings for Interlocking Structure Generation

- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFReader/WorkspaceDialog.qml
- plugins/3MFReader/WorkspaceSection.qml
- resources/qml/RoundedRectangle.qml
- resources/qml/Widgets/ComboBox.qml
Fix minor styling issues.
Fix opening the same project file with a new pinter multiple times causing a failure to load. 
CURA-9424
> [CURA-9424] Workspace dialog fixes

- resources/i18n/fr_FR/cura.po
Hi,
Several errors are present in the latest release (5.2.1).
Some Italian translations were present in the fr_FR version
Have a nice day. Thanks
> Translating Cura - Update fr_FR language

- cura/Settings/ActiveQuality.py
- cura/Settings/MachineManager.py
- plugins/UFPWriter/UFPWriter.py
- resources/qml/Dialogs/DiscardOrKeepProfileChangesDialog.qml
- resources/qml/PrintSetupSelector/Custom/CustomPrintSetup.qml
- resources/qml/PrintSetupSelector/PrintSetupSelectorHeader.qml
> Add quality type to ufp files

- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.4_PVA_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.8_PVA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.8_PVA_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_bb0.8_PVA_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.4_PVA_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.8_PVA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.8_PVA_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_bb0.8_PVA_Verydraft_Print.inst.cfg
> Remove the use of support towers when using PVA

- resources/definitions/ultimaker.def.json
> Revert "[CURA-9548] The engine now operates on the area _before_ the offset."

- resources/definitions/ultimaker.def.json
This makes adhesion more robust for inaccuracies in the first layer thickness. PP-288
> PP-288-increase-initial-layer-skin-flow

- resources/definitions/fdmprinter.def.json
backend PR: https://github.com/Ultimaker/CuraEngine/pull/1772
CURA-9901
[CURA-9901]: https://ultimaker.atlassian.net/browse/CURA-9901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CURA-9901-introduce-small-layer-temperature

- .github/workflows/cura-installer.yml
See the workflow: https://github.com/Ultimaker/Cura/actions/runs/3854096872
> CURA-8607_sign_windows_installer_workflow

- docs/PULL_REQUEST_TEMPLATE.md
This pull requests adds a pull request template so that we can better understand the community pull requests
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Add PR template

- resources/definitions/ultimaker.def.json
While waiting on further improving seam location, None gives currently the best results. PP-282
> PP-282_update-seam-corner-preference

- resources/definitions/anycubic_kobra_go.def.json
- resources/extruders/anycubic_kobra_go_extruder_0.def.json
- resources/quality/anycubic_kobra_go/anycubic_kobra_go_abs.inst.cfg
- resources/quality/anycubic_kobra_go/anycubic_kobra_go_pla.inst.cfg
- resources/quality/anycubic_kobra_go/anycubic_kobra_go_tpu.inst.cfg
Hey,
this is the first time I'm doing this, so this will need more work.
This is heavily based on https://github.com/Ultimaker/Cura/pull/11518/files @ANYCUBIC-3D 
Some questions:
1. How do I test this?
2. The quality files were a lot of guess work, there's no way to export them for cura in the correct format is there? I always get `quality_changes` files, which I guess is then based of a referencing definition.
> Add anycubic kobra go

- plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Apply Sovengers suggested fix so more Macusers can print over USB as mentioned in https://community.ultimaker.com/topic/42417-fix-for-connecting-creality-ender-3-neo-to-mac-via-usb/
> [CURA-10118] Change Only_List_USB

- plugins/PostProcessingPlugin/scripts/RetractContinue.py
See #14100 for a description of the problem. Note that the mention of needing to compensate was indeed the main issue, but (unmentioned in that issue) the series of 'continued' retractions was _also_ wrong in relative mode.
Relative mode was just never implemented with regard to this script it seems.
In the end, a (partial) rewrite turned out to be easier.
> [CURA-10092] fix/rewrite retract-continue relative mode

- resources/definitions/fdmprinter.def.json
Relates to PP-283. This needs to be merged to the 5.3 branch as well.
> optimize interlocking settings

- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/SliceInfoPlugin/SliceInfo.py
- plugins/SliceInfoPlugin/example_data.html
Will give us an insight if slicing time goes up per version, which we can then hopefully pinpoint and fix in further versions.
> [CURA-10299] Put slice-time in slice-data-sharing.

- cura/Settings/ExtruderManager.py
- resources/qml/Widgets/SingleSettingComboBox.qml
- resources/qml/Widgets/SingleSettingSlider.qml
- resources/qml/Widgets/SingleSettingTextField.qml
> Wrong extruder recommended settings

- resources/qml/PrintSetupSelector/PrintSetupSelectorContents.qml
This PR add the "resize handle" to the recommended settings panel.
> Add resize handle to recommended window

- resources/i18n/fr_FR/cura.po
- resources/i18n/pt_PT/cura.po
- resources/i18n/ru_RU/cura.po
- resources/i18n/tr_TR/cura.po
> Cura 10208 ii

- resources/i18n/cs_CZ/cura.po
- resources/i18n/cs_CZ/fdmprinter.def.json.po
Added Czech translations for empty strings, fixed fuzzy translations (they were pretty bad) and fixed some existing strings in order to be more consistent.
> Czech translations for v5.3

- cura/CuraApplication.py
- plugins/Marketplace/resources/qml/Marketplace.qml
- resources/i18n/cs_CZ/cura.po
- resources/i18n/de_DE/cura.po
- resources/i18n/es_ES/cura.po
- resources/i18n/fr_FR/cura.po
- resources/i18n/it_IT/cura.po
- resources/i18n/ja_JP/cura.po
- resources/i18n/ko_KR/cura.po
- resources/i18n/nl_NL/cura.po
- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_PT/cura.po
- resources/i18n/ru_RU/cura.po
- resources/i18n/tr_TR/cura.po
- resources/i18n/zh_CN/cura.po
- resources/i18n/zh_TW/cura.po
Adds sign in wall for the marketplace for enterprise versions
> (MERGE TRANSLATIONS FIRST!!!) [CURA-10182] Add sign in wall enterprise

- resources/qml/MachineSettings/ComboBoxWithOptions.qml
fixes https://github.com/Ultimaker/Cura/issues/14795
CURA-10374
> Cura 10374 fix combobobobobox

- resources/qml/PrinterSelector/PrintSelectorCard.qml
The compatible was broken. This PR fixes that
Previously
With fix
CURA-10507
> Fix compatible printers window UI issues

- resources/intent/ultimaker_s3/um_s3_cc0.4_petcf_0.15mm_annealing.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.4_petcf_0.15mm_engineering.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.4_petcf_0.2mm_annealing.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.4_petcf_0.2mm_engineering.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.6_petcf_0.15mm_annealing.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.6_petcf_0.15mm_engineering.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.6_petcf_0.2mm_annealing.inst.cfg
- resources/intent/ultimaker_s3/um_s3_cc0.6_petcf_0.2mm_engineering.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.4_petcf_0.15mm_annealing.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.4_petcf_0.15mm_engineering.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.4_petcf_0.2mm_annealing.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.4_petcf_0.2mm_engineering.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.6_petcf_0.15mm_annealing.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.6_petcf_0.15mm_engineering.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.6_petcf_0.2mm_annealing.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.6_petcf_0.2mm_engineering.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.4_petcf_0.15mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.4_petcf_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.6_petcf_0.15mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.6_petcf_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.6_petcf_0.3mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.4_petcf_0.15mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.4_petcf_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_petcf_0.15mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_petcf_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.6_petcf_0.3mm.inst.cfg
> Profiles for filled material

- resources/texts/change_log.txt
New Release notes for the upcoming 5.4 Release
> Updated Changelog for Cura 5.4

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Updated Brazilian Portuguese strings for Cura
* Operating System: Arch Linux
> Updated Brazilian Portuguese strings for Cura 5.4

- resources/texts/change_log.txt
Updated changelog for Cura 5.4 Stable
> Update Changelog for Cura 5.4 Stable

- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
> Cura 8754 refresh button material sync list doesn't provide any feedback

- .github/ISSUE_TEMPLATE/bugreport.yaml
- .github/workflows/update-translation.yml
- cura/BackendPlugin.py
- cura/CuraApplication.py
- plugins/CuraEngineBackend/Cura.proto
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/CuraEngineBackend/StartSliceJob.py
First rough draft of how the frontend will handle the backend_plugins. 
Originally i added the concept of backend_plugins to uranium, but the extra abstraction made it clumsy quite fast. So i moved all of it over to Cura. The accompanying Uranium PR now essentially only contains boyscouting changes. Since they are still good to do, i've left them in.
https://github.com/Ultimaker/Uranium/pull/886
CURA-10717
> Frontend plugin orchestration

- plugins/USBPrinting/AutoDetectBaudJob.py
Add some extra debug logging for the autobaudrate job
This is needed in order to figure out what is causing https://github.com/Ultimaker/Cura/issues/15263
> Usb printing debug improvements

- resources/definitions/fdmprinter.def.json
Clarify relation with Hole Horizontal Expansion and ole Horizontal Expansion Max Diameter
Resolves CURA-10771 and helps with https://github.com/Ultimaker/Cura/issues/15877
> Update description for Hole Horizontal expansion

- plugins/Marketplace/RemotePackageList.py
Added a class attribute "last_updated" for sort_by Added an instance attribute for search_sort
Added if statement to add the sort_by string, currently by default.
CURA-10850
The results users get when searching for material or plugins in marketplace within cura
Run from source, search and validate results in materials & plugins
> Update to add sort_by option

- .gitignore
- AboutDialogVersionsList.qml.jinja
- conanfile.py
- resources/qml/Dialogs/AboutDialog.qml
> Cura about dialog when shaked gives extra info

- resources/qml/MachineSettings/NumericTextFieldWithUnit.qml
> Force left to right reading direction for numeric textfield

- resources/definitions/kingroon_kp3s_pro.def.json
> fix: kp3s pro author

- plugins/3MFReader/WorkspaceDialog.py
- plugins/3MFReader/WorkspaceDialog.qml
- plugins/3MFWriter/ThreeMFWriter.py
- plugins/3MFWriter/tests/TestMFWriter.py
- plugins/Marketplace/MissingPackageList.py
- plugins/Marketplace/PackageModel.py
- plugins/Marketplace/resources/qml/InstallMissingPackagesDialog.qml
- plugins/Marketplace/resources/qml/MissingPackages.qml
> Show install missing packages button in open workspace dialog for plugins

- conanfile.py
> from deploy field.

- resources/definitions/fdmprinter.def.json
A new feature request needed to make this work.
CURA-10503
> Brim distance is not "settable_per_mesh"

- conanfile.py
> testing for build

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
> Add fluid motion related settings

- resources/definitions/matterhackers_pulsexe_e444m.def.json
- resources/extruders/matterhackers_extruder.def.json
This PR submits the bare minimum of settings needed for the Matterhackers Pulse XE E444M. This supersedes #12730, which seems to be abandoned.
* Operating System: Windows 11 and direct from memory card on machine
> Definition: Pulse XE E444M

- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
CURA-8728
Using tab in the per model settings
https://github.com/Ultimaker/Cura/issues/10967
> tab button in per model setting

- conanfile.py
- cura/BackendPlugin.py
> Log backend plugin std out

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
backend-pr: https://github.com/Ultimaker/CuraEngine/pull/1963
CURA-11110
> Top surface inner outer wall config

- cura/Machines/Models/IntentCategoryModel.py
- cura/Machines/Models/IntentTranslations.py
- cura/Machines/Models/QualityManagementModel.py
> Rename "Default" intent to "Balanced"

- resources/texts/change_log.txt
> Updates for the Cura 5.5 Beta 

- plugins/3MFReader/ThreeMFReader.py
CURA-9755
fix for https://github.com/Ultimaker/Cura/issues/13523
> Cura 9755 meshes in correct location

- plugins/CuraEngineBackend/StartSliceJob.py
With the proposed changes users are able to write expressions within the start/end gcode template's. Example of what is now possible can be seen below
```
G0 X{prime_tower_position_x - prime_tower_size/2} Y{prime_tower_position_y-prime_tower_size/2} F6000
M109 S{material_final_print_temperature}
G4 S5
```
Should be merged along with corresponding Uranium PR: https://github.com/Ultimaker/Uranium/pull/914
🏃🏼‍♀️🏃 Run from source 
CURA-11155
> Formulas in start/end code

- plugins/VersionUpgrade/VersionUpgrade54to55/VersionUpgrade54to55.py
Removed update of materials other than:
abs
pla
petg and
tough-pla
CURA-11151
> Updated upgrade script. 

- resources/qml/Dialogs/ColorDialog.qml
> Add deprecation warning for ColorDialog

- packaging/AppImage-builder/AppImageBuilder.yml.jinja
Ensure that glibc is present and that it is on the `LD_LIBRARY_PATH` should fix the issue with Debian 12.
See [UltiMaker-Cura-5.6.0-alpha+cura_11145_888c9e-linux-X64-AppImage](https://github.com/Ultimaker/Cura/suites/17565007372/artifacts/1003554319) for a build
* Operating System: various Linux systems
> Cura 11145

- resources/texts/change_log.txt
Updated changelog for 5.5 Stable
> Update changelog for 5.5 Stable

- resources/definitions/fdmprinter.def.json
Improved names and descriptions of the new prime tower settings related to the base
> [CURA-11259] Improve prime tower settings description

- resources/texts/change_log.txt
New and improved, short and sweet.
> Updated Changelog for 5.6

- resources/definitions/ultimaker_method_base.def.json
- resources/definitions/ultimaker_methodx.def.json
- resources/definitions/ultimaker_methodxl.def.json
- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
- resources/definitions/ultimaker_s7.def.json
This is in line with the updated brand guide for UltiMaker
> CURA-11267 Update the Naming of the Method printers

- CuraVersion.py.jinja
- conanfile.py
- resources/qml/Dialogs/AboutDialog.qml
>  about dialog blemishes

- resources/definitions/fdmprinter.def.json
CURA-11075
description added to setting
> expected behavior added text in description of setting

- cura/ApplicationMetadata.py
- resources/bundled_packages/cura.json
Upgrade CURA SDK version to 8.6.0, and plugins.
Same PR should be existing for Uranium but I (again) accidentally pushed on 5.6 so you can still review the commit:
https://github.com/Ultimaker/Uranium/commit/2c9fdcd38a0247083afe624cca48aad196dee000
> SDK version upgrade

- resources/intent/ultimaker_methodx/um_methodx_1c_um-absr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_1c_um-absr-175_0.2mm_solid.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_1c_um-absr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_1c_um-absr-175_0.2mm.inst.cfg
PP-400 ABS-R profiles for the 1C extruder
> - ABS-R print profiles for ABS-R with the 1C extruder

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Also add Brazilian Portuguese.
> PT_BR translations 5.6.x

- resources/i18n/fr_FR/cura.po
- resources/i18n/fr_FR/fdmprinter.def.json.po
Fixed some very bad French translations... Thanks ChatGPT
> Fixed wrong French translations

- resources/texts/change_log.txt
Update the changelog to reflect changes made during the Beta
> Updated changelog to Stable

- resources/definitions/multicomp_mcpi200.def.json
- resources/definitions/renkforce_pro10plus.def.json
- resources/variants/multicomp/multicomp_mcpi200_0.2.inst.cfg
- resources/variants/multicomp/multicomp_mcpi200_0.4.inst.cfg
- resources/variants/multicomp/multicomp_mcpi200_0.6.inst.cfg
- resources/variants/multicomp/multicomp_mcpi200_0.8.inst.cfg
- resources/variants/multicomp/multicomp_mcpi200_1.0.inst.cfg
- resources/variants/renkforce/renkforce_pro10plus_0.2.inst.cfg
- resources/variants/renkforce/renkforce_pro10plus_0.4.inst.cfg
- resources/variants/renkforce/renkforce_pro10plus_0.6.inst.cfg
- resources/variants/renkforce/renkforce_pro10plus_0.8.inst.cfg
- resources/variants/renkforce/renkforce_pro10plus_1.0.inst.cfg
> add Renkforce 10+ and Multicomp MCPI 200 profiles 

- cura/Arranging/GridArrange.py
- cura/Arranging/Nest2DArrange.py
I didn't get to the very root cause of the issue, but using absolute coordinates when doing a grid placement fixes it.
> [CURA-11279] Fix arrange in grid

- resources/definitions/fdmprinter.def.json
[CURA-11392](https://ultimaker.atlassian.net/browse/CURA-11392)
[CURA-11392]: https://ultimaker.atlassian.net/browse/CURA-11392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CURA-11392_threshold

- conandata.yml
- plugins/CuraEngineBackend/Cura.proto
- plugins/CuraEngineBackend/StartSliceJob.py
Part of https://github.com/Ultimaker/CuraEngine/pull/1999
* Operating System: Windows & Linux
> CURA-11482 additional sentry info

- cura/CuraApplication.py
for error loading of the wrong URL.
Better message handling
> CURA-11289

- resources/qml/Preferences/SettingVisibilityPage.qml
CURA-11480
Preferences > setting visibility > Check all button status doesn't update correctly
> ppr setting was added when it should be excluded

- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/SimulationView.py
CURA-7647
extension of simulation speed time dependent. Special case of multiple extruders
> Case of simulation with multiple extruders

- conanfile.py
- cura_app.py
- packaging/AppImage-builder/AppImageBuilder.yml.jinja
- packaging/AppImage/AppRun
> Revert "qt6.6 scroll issues"

- cura/Machines/Models/ExtrudersModel.py
> change "label" to "name" to align with items in global_container_stack check

- .github/workflows/installers.yml
- .github/workflows/windows.yml
- conanfile.py
> Big changes are coming for code signing certificates in 2023. New and reissued publicly trusted organisation validation (OV) and individual validation (IV) code signing certificates will have to be issued or stored on preconfigured secure hardware by the issuing Certificate Authority (CA) and the device must meet FIPS 140 Level 2, Common Criteria EAL 4+ or equivalent security standards.
This is already the case for EV (Extended Validation) certificates, and it presents some problems in an automated build environment. In this post we'll take a look at the issues with hardware-based certificates and how to work around them.
> https://www.finalbuilder.com/resources/blogs/code-signing-with-usb-tokens
See also: https://github.com/Ultimaker/cura-workflows/compare/bc4a5fa0c31c07f6f191889a76f123 …
> Cura 11544 self hosted windows runner

- resources/quality/ultimaker_s3/um_s3_aa0.25_abs_0.1mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.25_um-abs_0.1mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_abs_0.1mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_um-abs_0.1mm.inst.cfg
Set initial fan speed for AA0.25 ABS 0.1mm print mode from 40% to 0% to increase adhesion robustness.
PP-422
> PP-422 Lower initial fan speed AA0.25 ABS to improve adhesion robustness 

- resources/qml/Actions.qml
Fixes #7499
It hasn't been tested - because I was previously unable to create a run-from-source environment.
> Stop Esc key from exiting full screen mode

- resources/quality/ultimaker_s3/um_s3_aa0.25_um-abs_0.1mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.25_um-tough-pla_0.1mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_um-abs_0.1mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_um-tough-pla_0.1mm.inst.cfg
Add cool fan speed = 0 to the initial layer of Ultimaker ABS.
Fix high speed profile T-PLA (was still generic profile). Mistake in PP-391, but taken along in this PR.
PP-422
> PP-422 Fix fan speed ABS AA0.25

- cura/CuraApplication.py
- resources/qml/Preferences/MachinesPage.qml
It happened because of creating MachineActionManager as a singleton. Code is refractored to make it work.
CURA-11558
> crash while opening printer setting

- resources/quality/ultimaker_s3/um_s3_aa0.4_um-abs_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_um-petg_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_um-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_um-tough-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_um-abs_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_um-petg_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_um-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_um-tough-pla_0.2mm.inst.cfg
Increase part strength of high speed modes by compensating for the slip at high flow rates.
PP-386
> PP-386 Increase part strength of high speed modes

- cura/CuraApplication.py
- cura/PlatformPhysics.py
- plugins/3MFReader/WorkspaceDialog.py
- plugins/3MFReader/WorkspaceDialog.qml
- resources/qml/Preferences/GeneralPage.qml
- resources/qml/Toolbar.qml
Drop to buildplate preference setting shown while opening a project, a user can select if they want to drop or not. By default it is set to the user preference
> Cura 10542 drop to buildplate

- tests/TestOAuth2.py
related to internal ticket CURA-11406
> Fix unit-tests.

- resources/extruders/geeetech_A20_1.def.json
> restore extruder definition

- plugins/3MFWriter/ThreeMFWriter.py
exported_model_settings were supposed to be None instead of {} for 3mf saving
CURA-11403
> saving extruder settings on model

- plugins/CuraEngineBackend/CuraEngineBackend.py
I changed a message, woohoo !! :partying_face: 
CURA-11445
> Change slicing crash error message

- resources/quality/ultimaker_s3/um_s3_aa0.4_tpu_0.15mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_tpu_0.1mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_tpu_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_tpu_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_tpu_0.3mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_tpu_0.4mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_tpu_0.15mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_tpu_0.1mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_tpu_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_tpu_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_tpu_0.3mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_tpu_0.4mm.inst.cfg
**Re-committed changes from Paul's improvements to resolve some conflicts and exclude unrelated stuff.**
**Original PR: #18321**
Improve TPU top surface quality by adding a bridge layer as first skin layer and increase the number of top layers to 6.
[PP-428](https://ultimaker.atlassian.net/browse/PP-428)
[PP-428]: https://ultimaker.atlassian.net/browse/PP-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PP-428 - Improve top layer quality of TPU

- cura/PrinterOutput/Models/MaterialOutputModel.py
> Add missing nylon material to material map

- cura/PrinterOutput/Models/MaterialOutputModel.py
Changed names of materials as per materials list
Removed materials with GUID not found in materials
CURA-11710
> Changed names of materials as per materials list

- plugins/3MFWriter/UCPDialog.py
- plugins/3MFWriter/__init__.py
CURA-11715
Reintroduce mimetype for ucp
> Mimetype introduction for ucp

- plugins/3MFReader/WorkspaceDialog.qml
placing "Setting loaded from ucp" on top before "Suggested Profile setting"
CURA-11721
> placing Setting loaded from ucp on top before Suggested Profile setting

- plugins/3MFWriter/__init__.py
- resources/qml/Menus/FileMenu.qml
- resources/qml/Menus/SaveProjectMenu.qml
added limit mimetype for 3mf project and removed saving ucp as mesh writer
> Cura 11715 save as type for 3mf

- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/SimulationView.py
fix bug in simulation view
CURA-11758
yes
* Operating System: macos13.3
> Fix crash in similation view

- resources/i18n/ru_RU/cura.po
Hello. Here is update for translation ru_RU
> update ru_RU translation

- plugins/UM3NetworkPrinting/src/Cloud/CloudApiClient.py
- plugins/UM3NetworkPrinting/src/Cloud/machine_id_to_name.json
See #18606 for details. Was made before the 5.7.x branch, but we want it in there, so cherry-picked.
> [CURA-11786] [PP-452] Clean up the CloudAPIClient

- plugins/3MFReader/WorkspaceDialog.qml
learn more button alligned in UCP
CURA-11781
> learn more button alligned in UCP

- resources/definitions/creality_ender3v3se.def.json
Move nozzle clean movements to designated area of the heatbed.
This fixes #17165 
Host system: Windows 10
> Move nozzle clean to designated area

- resources/texts/change_log.txt
Contributes to CURA-11797 and updates the changelog for stable release.
> Update Changelog for Stable Release

- resources/qml/Dialogs/AskOpenAsProjectOrModelsDialog.qml
As it doesn't open the file as Cura project anymore
CURA-11738
> Corrected string

- resources/texts/change_log.txt
Updated Changelog for the 5.7.1 Release
Contributes to Cura-11840
> CURA-11840 update changelog 571

- cura/Machines/Models/ActiveIntentQualitiesModel.py
> Fix intent selection

- cura/Machines/Models/ActiveIntentQualitiesModel.py
- cura/Settings/IntentManager.py
> Improve currentIntentCategory logic

- .printer-linter
- printer-linter/src/printerlinter/linters/profile.py
new linter for long profile names
CURA-11153
> Add new linter for long profile names

- conandata.yml
> fix wrong channel

- resources/definitions/fdmprinter.def.json
adding resolve function for 'raft_remove_inside_corners'
> Added resolve function to take the values from material profiles

- .github/workflows/printer-linter-pr-post.yml
Following PR https://github.com/Ultimaker/Cura/pull/19141
Script doesn't work because of wrong indentation...
> Fix indentation

- .github/workflows/printer-linter-pr-post.yml
Following PR https://github.com/Ultimaker/Cura/pull/19151
Script doesn't work because of wrong file path (forgot to change the folder name after copy-paste)
> Fix printer linter injection

- resources/texts/change_log.txt
> Updated Changelog for Cura 5.7.2

- printer-linter/src/printerlinter/linters/formulas.py
We also need to consider the extruder settings when looking into formulas for existing values.
> Fix false warnings on setting formulas

- cura/Machines/Models/IntentTranslations.py
Add the translation to IntentTranslation.py
CURA-11976
> Add missing "annealing" intent translation

- resources/texts/change_log.txt
Updated Changelog for the Cura 5.8 Beta Release
> CURA-12030 Update Changelog 5.8 Beta

- resources/definitions/creality_crm4.def.json
This is to add the Creality CR-M4 printer definition.
> Add CR-M4 printer definition

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
Updated pt_BR strings for Cura 5.8
* Operating System: Arch Linux
> Updated pt_BR strings for Cura 5.8.

- resources/i18n/ja_JP/cura.po
- resources/i18n/ja_JP/fdmextruder.def.json.po
- resources/i18n/ja_JP/fdmprinter.def.json.po
Improving Japanese localization for 5.9
Resolves: #19438
* Operating System: Windows 11
> improve Japanese translation for 5.9

- resources/i18n/fr_FR/fdmprinter.def.json.po
This fixes the French translation for the scarf seam descriptions, which was really meaningless
> Provide better French translation for scarf seam

- resources/definitions/fdmprinter.def.json
> Display corner preference only with sharpest corner

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/advanced.cfg
- resources/setting_visibility/basic.cfg
- resources/setting_visibility/expert.cfg
Interlocking seems to be stable enough and quite important for multi-material, so we can now move it out of experimental.
CURA-12247
> CURA-12247 Move interlocking settings out of experimental

- cura/PrinterOutput/Models/PrinterConfigurationModel.py
- resources/qml/Menus/ConfigurationMenu/ConfigurationItem.qml
Similar to the warning we already had for missing materials.
> [CURA-12368] Warn for mismatched cores on multi-config printers.

- cura/PrinterOutput/FormatMaps.py
- plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterConfigurationMaterial.py
Adds the proper name mapping for the extruders of the Sketch* printers
CURA-12401
> CURA-12401 Fix makerbot compatibility warning

- resources/qml/Menus/ConfigurationMenu/ConfigurationItem.qml
> CURA-12393 Set support page to be opened on core incompatibility

- resources/definitions/ultimaker_s8.def.json
> Adjust settings ultimaker_s8.def.json

- resources/definitions/ultimaker_sketch_sprint.def.json
> Remove redundant overrides

- resources/qml/Preferences/SettingVisibilityItem.qml
- resources/qml/Preferences/SettingVisibilityPage.qml
> Cura 12466 experimental setting visibility

- cura/OAuth2/AuthorizationRequestHandler.py
- printer-linter/src/terminal.py
Implements 2 fixes that have been reported as security issues. Although they are both not technically required, they are part of security good practices and will silent warnings for automatic reporting tools.
CURA-12458
> CURA-12458 security fixes that came in via the inbox

- resources/qml/TableView.qml
Rewrite the interaction to allow resizing the columns relative to each other, which is much more natural
CURA-12439
> CURA-12439 Improve TableView manual column resizing

- resources/qml/WelcomePages/ChangelogContent.qml
- resources/qml/WelcomePages/WhatsNewContent.qml
- resources/texts/change_log.txt
Contributes to CURA-12481, and prepares the changelog for the stable release
> CURA-12481 changelog update

- .github/ISSUE_TEMPLATE/SlicingCrash.yaml
Contributes to CURA-12465, this should help with getting more focus in the input we are receiving from the slicing crashes. The old one was a bit outdated.
> Updated Slicing Crash issue

- .github/workflows/find-packages.yml
Add workflow to start a build using a ticket number
> Jira ticket installers workflow

- resources/texts/change_log.txt
Updated changelog for service patch, contributes to CURA-12640
> Updated changelog for service patch

- resources/setting_visibility/advanced.cfg
- resources/setting_visibility/basic.cfg
Make "Use Towers" setting visible in all visibilities
CURA-12688
> CURA-12688 Make "Use Towers" setting visible in all visibilities

- plugins/PaintTool/PaintTool.qml
Second part of the PR, on main, not to break string freeze on 5.11
CURA-12761
> CURA-12761 Note that an ungrouped object should be selected for painting
