Ultimaker/Cura

- cura/OAuth2/LocalAuthorizationServer.py
We got a crash report where a PermissionError was raised when http.server is imported. This PermissionError seems to be specific to the user's system. It's crashing somewhere internally in that library when it's trying to read the MIME types supported. Perhaps this user has elevated their computer's security in some way.
Instead of crashing, we don't start the web server. This means that instead of crashing Cura, you get an error in the browser after logging in that it can't reach the localhost page. In Cura you'll remain logged out, as it keeps waiting on the response from the log-in.
Fixes Sentry crash CURA-3Q.
> Prevent crashing on PermissionError when importing http.server

- resources/definitions/mp_mini_delta.def.json
This was pointed out to me by new users during Cura 4.5 Beta testing. I would greatly appreciate it if this could be included with the final release of Cura 4.5, but I understand if it needs to wait.
The stock Monoprice Mini Delta 3D printer has trouble reaching 60 C. Setting the bed temperature to 40 C so that it doesn't confuse newcomers to the hobby when the printer sits forever waiting for the bed to reach a temperature that it cannot attain.
> Fixing default bed temperature for MP Mini Delta

- cura_app.py
Purpose
=====
The purpose of this bug report is to allow running the source code using `pythonw`. `pythonw` will be used at the makerspace I work for to allow running modified source code without having to compile Cura. We don't want to have a command prompt window with a lot of debug information visible since it may confuse lab users.
Description
========
When running a Python script using `pythonw` instead of `python`, standard input, output, and error are not defined. The `faulthandler` module is used by Cura and is initialized with either `sys.stderr` if it is defined or `sys.stdout`. The problem is if `sys.stdout` is `None`, which will result in `faulthandler` being unable to initialize since the output is undefined. This results in a crash when starting using `pythonw`.
Changes …
> Add Check for stdout Being Defined for faulthandler

- CMakeLists.txt
According to what I found in the docs[1], there is no "DIRECTORY" available as <type>.
Therefore, correcting it to "PATH", which is according to the docs correct.
At the moment I'm getting the following error[2]:
```
CMake Warning (dev) at CMakeLists.txt:8 (set):
implicitly converting 'DIRECTORY' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at CMakeLists.txt:9 (set):
implicitly converting 'DIRECTORY' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
[1] https://cmake.org/cmake/help/v3.6/command/set.html
[2] https://launchpadlibrarian.net/464670600/buildlog_ubuntu-focal-amd64.cura_1%3A4.5~202002121434~rev4433~pkg330~ubuntu20.04.1_BUILDING.txt.gz
> CMake: Fixing warning about path conversion

- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- resources/qml/ActionButton.qml
This PR adds a "notification" count to the button that indicates there are postprocessing scripts active. It also adds a descriptive tooltip text, showing the name(s) of the active scripts without having to open the PostProcessing plugin dialog to inspect.
While fixing this, I also fixed some missing tooltips for ActionButtons.
Fixes #7159
> Show active postprocessing scripts count

- cura_app.py
This prevents accidentally loading packages from the working directory that are not in Cura's build.
Contributes to issue CURA-7081.
> Remove working directory from sys.path

- resources/qml/PrinterOutput/ExtruderBox.qml
- resources/qml/PrinterOutput/HeatedBedBox.qml
This PR fixes the values shown in the preheat temperature fields on the Print Monitor (USB or OctoPrint). As reported in #7172, this functionality was broken in https://github.com/Ultimaker/Uranium/commit/2d4dab687afff47df33c6237910bb373fc99ebaa, but since that is a performance optimization this PR works around those changes instead of reverting them.
Fixes #7172
> Fix values in print monitor preheat fields

- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
- plugins/PerObjectSettingsTool/PerObjectSettingsTool.py
The problem: When infill mesh is set, wall_thickness and top_bottom_thickness are added to the settings.
Then these settings are set to visible on the visibility_handler.
It appears however, that the visibility_handler considers all added settings to be visible. It thus concludes that no UI update is necessary because the settings are already added.
> CURA-7211_pos_infill_defaults_0

- resources/qml/WelcomePages/AddPrinterByIpContent.qml
If the connection to your printer fails (or takes a long time), we show a link to a help page on Ultimaker's website. This only explains about Ultimaker's printers so the link is worded to only apply to Ultimaker's printers.
Implements CURA-7017.
> Show link to help pages if connection fails

- resources/variants/ultimaker3_bb0.8.inst.cfg
- resources/variants/ultimaker3_bb04.inst.cfg
- resources/variants/ultimaker3_extended_bb0.8.inst.cfg
- resources/variants/ultimaker3_extended_bb04.inst.cfg
- resources/variants/ultimaker_s3_bb0.8.inst.cfg
- resources/variants/ultimaker_s3_bb04.inst.cfg
- resources/variants/ultimaker_s5_bb0.8.inst.cfg
- resources/variants/ultimaker_s5_bb04.inst.cfg
Given that:
* stair stepping is intended to be used to reduce the adhesion between support and the model, where the support rests on the model, and to reduce scarring, and
* PVA doesn't suffer from scarring or adhesion issues due to its water-solubility, and
* our current stair stepping algorithm has some bugs, causing support to disappear sometimes
we've decided to set stair stepping to 0 for all PVA profiles for UM3, UMS5 and UMS3.
Contributes to issue CURA-7311.
> Reduce stair step height to 0 for PVA

- plugins/3MFReader/ThreeMFWorkspaceReader.py
This PR fixes loading of comments in start and end gcode snippets when loading in a project, by setting the appropriate option for the ConfigParser to not regard comments in the ini structure as comments but to read them as text instead.
This PR fixes #7304
> Fix loading comments in gcode snippets from 3mf projects

- resources/qml/MainWindow/ApplicationMenu.qml
This PR allows extensions to add separators between menuitems in their Extensions submenu like this:
`        self.addMenuItem("", lambda: None)`
The method of reusing the existing `addMenuItem` instead of eg an `addMenuSeparator` means that (1) the method is fully backward compatible in the sense that this menuItem just renders as an empty menuitem and (2) confines the changes to Cura instead of requiring a change in both Cura and Uranium.
> Add method to add separators to extension menus

- resources/definitions/deltabot.def.json
This PR hides the Deltabot definition from the Add Printer dialog. The Deltabot is used as a generic stub for delta-style printers. We want users to use the "Custom FFF Printer" instead, which is more fully featured (supports multiple extruders) and has the appropriate options to set an elliptical build plate and origin at center.
With this PR, user that have already configured a Deltabot can keep using their configuration, but users wanting to add a new delta-style printer for which there is no premade configuration will only be able to pick the Custom FFF Printer.
Contributes to #6688
> Hide deltabot from Add Printer dialog

- plugins/SolidView/SolidView.py
- plugins/XRayView/XRayView.py
- resources/shaders/xray_composite.shader
This PR fixes the xray_in_solid_view branch to work on legacy opengl renderers. textureSize() is not available in opengl 2.1, so we calculate the xray error image scale outside the shader (which is also a theoretical performance improvement because now the scale does not get computed over and over for each pixel)
This PR builds on top of https://github.com/Ultimaker/Cura/pull/6569 and has that branch as target.
> Fix xray composite shader for opengl 2.1

- plugins/3MFReader/ThreeMFReader.py
- plugins/3MFWriter/ThreeMFWriter.py
This PR stores and retreives the SceneNode name as attributes of the `<object.` node in 3mf files, in accordance with the spec:
https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#attributes-3
It requires https://github.com/Ultimaker/libSavitar/pull/23 and CI will (should) fail until that PR is merged.
This PR solves the problem that after saving a project and loading it back in to Cura, all model names are changed to `Object n` (where n is a number referring to the order objects are stored in the 3mf file). This makes it hard to find models back in the model list, and makes eg the postprocessing script to display model names useless for projects. Additionally, the PR follows the 3MF spec more closely by supporting a known metadata entry that was …
> Store/retreive SceneNode name in/from <object> attribute

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Small change in _PauseAtHeight_ script for *Post-Processing Plugin*, which adds `M18 S{VALUE}` command with a specified in a new _Pause Duration_ field number of seconds.
This overrides the default disarm timeout in firmware by user-defined value, which helps to prevent situation, when firmware disarms steppers and Z-axis falls down bcuz of weight which leads to loosing the Z-position and making it impossible to continue printing.
> PP-plugin -> PauseAtHeight: steppers disarm timeout

- plugins/SolidView/SolidView.py
- resources/qml/Preferences/GeneralPage.qml
- resources/shaders/xray.shader
- resources/shaders/xray_composite.shader
This PR contains some fixes for the xray_in_solid_view branch (#6569)
*  Disables the option in the message should hide the message only
*  Adds the patches from @smartavionics so it works on Raspberry PI 4s and, more importantly, legacy opengl renderers (openGL 2.1).
It also fixes resetting the preference, and factors out an unnecessary import.
> Fix xray in solid view

- resources/qml/PrinterOutput/ManualPrinterControl.qml
This PR fixes the Layout of the buttons used to jog the head for output devices that support it (eg USB, OctoPrint) with newer Qt versions than what is currently used in official releases (eg people running from source or unofficial distributions on Linux).
The GridLayout was using incorrect row and column indexes. The Qt versions used in official releases sofar would accept the incorrect indexes, but newer Qt versions apparently truncate the GridLayout, as seen in the screenshot below:
Please do not git blame to find out who thought the indices within a GridLayout start at 1.
This PR fixes https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/149
> Fix the layout of the head jogging controls with newer Qt versions

- resources/qml/ActionButton.qml
- resources/qml/ActionPanel/ActionPanelWidget.qml
Fixed: ActionPanelWidget's width was removed, 
which prevented a safe area from being layed out.
This in turn caused misalignment of the simulation slider
> CURA-7340_fix_simulation_slider_layout

- cura/CuraApplication.py
- plugins/3MFReader/ThreeMFReader.py
There was an issue where when reloading muliple objects from a 3mf file, object 1 was being replicated everywhere. 
This PR only fixes that issue to make sure that object 1 is not replicated, when the number of objects has not been changed. There is still undefined behavior when the number of objects or their positional indexes inside the file change.
Requires 
- https://github.com/Ultimaker/libSavitar/pull/24
- https://github.com/Ultimaker/Uranium/pull/596
> Cura 7333 fix reloading 3mf files with many objects

- resources/definitions/creality_ender3pro.def.json
In this discussion: https://github.com/Ultimaker/Cura/issues/7252
Some were pointing out the Ender-3 Pro comes with a magnetic bed without clips making the entire surface of the bed printable. The disallowed areas in the standard Ender-3 are not easily removed. @Ghostkeeper seemed to indicate a new "Pro" profile is an acceptable solution. So, here it is.
P.S. I'm still very new to GitHub. I made this change in the 4.6 branch instead of master this time. Is this correct? (preferred by you?)
> Add Ender-3 Pro without clip boundaries for magnetic bed

- cura/Machines/MachineNode.py
When the MachineNode is updated through _loadAll, it was not updating
its VariantNodes when they already existed. This caused an issue to
UM2+Olsson block printers, where changing the G-Code flavor to Marlin
was not updating the VariantNodes to search for materials (since the
variants already existed).
This commit fixes that by forcing an update to the existing Variant
nodes.
Related GitHub issue: https://github.com/Ultimaker/Cura/issues/7347
CURA-7354
> Force reloading the VariantNode if it exists

- resources/definitions/creality_cr10spro.def.json
Changed M420 to G29 to stop the machine from auto-homing and inadvertantly drawing a triangle
> Fix for Creality CR-10S Pro ABL Command

- cura/Settings/SettingOverrideDecorator.py
- cura/UI/ObjectsModel.py
- resources/qml/ObjectItemButton.qml
- resources/qml/ObjectSelector.qml
- tests/TestObjectsModel.py
This PR adds some information to the object list:
* indicates the extruder(-color) used for the model (for multi-extrusion printers only)
* shows the meshtype if the model is not a normal mesh
* shows the number of per model setting overrides
* indicates models that are outside the build volume
Clicking the mesh-type or per-model-settings-count will open the Per Model Settings tool panel.
The PR also adds a small fix to ensure that support_mesh models are rendered using the color of the support_extruder.
> Objectlist additions

- cura/API/Account.py
- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
Manual sync for Cloud printers
(this is also available in branch CURA-7290_manual_account_sync
This PR also adds
manual + auto sync for marketplace packages every 30 seconds
... which was not explicitly requested in 7290. If it is undesirable, 
the other branch can be merged instead
> CURA-7290_auto_sync_packages

- tests/Machines/TestPlatformMeshes.py
As a result of Cura and Cookies discussion, we decided to limit the
sizes of platform meshes to less than 1MB. This test checks that
during the CI/CD process and displays an assertion error when a
mesh excludes this limit.
> Limit platform meshes to 1MB

- cura/API/Account.py
- cura/OAuth2/AuthorizationService.py
- resources/qml/WelcomePages/AddCloudPrintersView.qml
- resources/qml/WelcomePages/AddNetworkOrLocalPrinterContent.qml
- tests/API/TestAccount.py
- tests/TestOAuth2.py
Adds a button in the "Waiting for cloud response" page, which will allow the user to force logout from Cura and from mycloud.ultimaker.com in the browser, in order to login again and sync the accounts between Cura and the browser.
> Cura 7427 add option to sign in with different account while waiting for printers

- resources/definitions/fdmprinter.def.json
Engine can now rotate this infill pattern so let the user specify an angle.
Only the first angle in the array is used.
> Make Infill Line Directions visible for cubicsubdiv infill pattern.

- plugins/VersionUpgrade/VersionUpgrade462to47/VersionUpgrade462to47.py
- resources/definitions/fdmprinter.def.json
- resources/definitions/hms434.def.json
- resources/definitions/skriware_2.def.json
Previously, the ironing_inset was changed in the profiles to reflect
the changes made in the CuraEngine. This inset though was not taking
into account the ironing_pattern (in the CuraEngine, the inset is
compensated differently depending on the pattern).
This PR fixes that in the version upgrader and the printer
definitions in order to maintain the same behavior for the old
profiles.
Merge along with Ultimaker/CuraEngine#1254
CURA-7318
> Upgrade the ironing inset based on the selected ironing pattern

- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
Cherry-pick the commits that fix the persistent bundled packages notification.
Merge along with https://github.com/Ultimaker/Uranium/pull/613
CURA-7459
CURA-7245
> Cherry-pick changes from CURA-7245_fix_bundled_package_sync

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
This PR corrects the current cloud printer discovering process to also add printers that are offline.
The fix was much simpler than we expected.
CURA-7458
> Add the offline cloud printers in Cura when they are discovered

- cura/CuraApplication.py
- resources/qml/Preferences/GeneralPage.qml
This PR adds a preference to use a single instance for loading files which has the same functionality as the --single_instance command line argument. ~It adds a very minimal preference parser that specifically looks for this particular preference instead of spinning up the full preference singleton, so the early boot is not delayed by much for this feature.~ Edit: the preferences are already available at that point, so I can use them as is.
The "single instance" feature is commonly used by users of CAD applications that launch Cura from their CAD application, and who may prefer to sequentially load objects into a single instance of Cura instead of starting up a new Cura for each iteration of the design.
This PR fixes #7664
> Add a preference to use a single instance for loading files

- plugins/USBPrinting/AutoDetectBaudJob.py
- plugins/USBPrinting/USBPrinterOutputDevice.py
Some printers are using 76800baud, and cura is not able to detect them.
Why?
Running a 16Mhz ATmega2560 at the more common _115200 baud_ is not recommended as the error rate of 3% would be above what the spec tolerates, because of the clock mismatch 16Mhz is not divisible by 300.
So the next more appropriate rate is `76800 baud` with a much cleaner transmission with an error rate of about 0.2%.
76800 is also referred as 38400 double rate, and some ESP-12 also use 76.8K baud.
Sources:
https://www.robotroom.com/Asynchronous-Serial-Communication-2.html
https://trolsoft.ru/en/uart-calc
> Support serial connections with 76800 baud rate 

- resources/qml/PrinterSelector/MachineSelector.qml
Display a different message in the popup tooltip when the internet
is reachable but the printer is offline.
CURA-7460
> Display appropriate tooltip message when cloud printer is offline

- plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrintJobStatus.py
time_total, time_elapsed and owner were updated twice for the ClusterPrintJobStatus Model. 
(Also 1000th fork)
> UM3NetworkPrinting: remove duplicate updates for model properties

- plugins/UM3NetworkPrinting/src/Cloud/ToolPathUploader.py
Previously the print job was sent with multiple PUT requests. This was necessary since the request was made with the Python Requests library, which freezes the interface while it's running. By breaking the upload up in chunks, it would at least periodically keep updating the interface (4 times per second or so, depending on your internet speed and Ultimaker's). Later on, this was replaced by a `QNetworkRequest` which doesn't freeze the interface in a refactor, but it was still broken up in chunks.
Recently that was again refactored to use Uranium's `HttpRequestManager`, which under the covers also uses `QNetworkRequest`. This also doesn't freeze while uploading, which is good. However for some reason the second chunk would always give a `QNetworkReply::ProtocolUnknownError`, which is a …
> Upload to cloud printer in a single chunk

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
Since the first device might be activated in case there is no active printer yet,
it would be nice to prioritize online devices
CURA-7493
> Sort new_devices on online status first, name second

- cura/CuraApplication.py
- cura/Machines/Models/BaseMaterialsModel.py
- cura/Settings/MachineManager.py
- cura/UI/AddPrinterPagesModel.py
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
- resources/qml/Cura.qml
- resources/qml/Dialogs/WorkspaceSummaryDialog.qml
- resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
- resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedSupportSelector.qml
- resources/qml/PrinterSelector/MachineSelectorList.qml
This PR adds an additional button in the "removed printers from account" message that allows the user to completely remove these printers from Cura. 
For that to happen, the user is asked through a question box to confirm the action.
To achieve the requirements of this ticket, the following had to be done in Cura:
- Add another "AddPrintersPagesModel" that is exactly the same as the other one with the exception that it does not display a "Cancel" button
- Allow Cura to set an empty active machine, if all machines are removed (when pressing the "Remove printers" button)
- Gracefully handle in the front-end the case where the last active machine is removed 
- Popup the "Add printers" wizard without the option to be cancelled when the last printer is removed
**Note 1**: Tests are failing …
> CURA-7454: Add "remove printers" button in removed printers from account message

- resources/qml/Toolbar.qml
This makes the panel grow upwards into clear space rather than downwards which is a problem
when the Cura window height is restricted as the bottom of the panel become inaccessible.
As discussed in https://community.ultimaker.com/topic/32840-a-problem-in-the-fitting-on-the-screen/.
The panel anchor point for the top toolbar buttons (Move, Scale, Rotate) is not changed.
> Change the panelBorder rectangle anchor to the bottom for lower toolbar buttons.

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
As per #7339, FlyingBear Ghost 4S uses command M25, instead of marlin M0 to pause printing.
I tried to use the new script for all printers, but the condition on the pause method was wrong.
> Adjusted correct pause_method for FlyingBear Ghost 4S

- resources/qml/WelcomePages/AddLocalPrinterScrollView.qml
- resources/qml/WelcomePages/AddNetworkOrLocalPrinterContent.qml
- resources/qml/Widgets/ScrollView.qml
- resources/qml/qmldir
This PR improves the UX of adding a local printer:
* Makes the scrollbar while selecting local printer visible so it doesn't look like only Ultimaker printers are supported
* Makes it more obvious there may be more items in the list by showing at least one more item (Custom)
* Makes the name field look less like a search field by placing it - along with some metadata of the selected printer - to the right of the list
* Makes the list respond to resizing the window
Showing the scrollbar is the most important change, and partly based on work by @diegopradogesto here: https://github.com/Ultimaker/Cura/pull/6325
This PR also in part reimplements https://github.com/Ultimaker/Cura/pull/4498
The "Add a networked printer" section remains untouched
> Add local printer improvements

- resources/qml/MachineSettings/NumericTextFieldWithUnit.qml
This problem has been seen before but I don't think it was ever fixed and one of the users of my builds reported it again so here's a fix for the bad valign issue that you can get in the machine settings dialog (at least on Linux).
Before...
After...
FYI I'm using Qt 5.13.2.
> Set padding to 0 to remove vertical shift on Linux builds.

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Fixed bug #7918
Excluded lines that start with M205, command used for setting Jerk and not to move.
https://marlinfw.org/docs/gcode/M205.html
> Fixed next XY return position after pause

- cura/Settings/MachineManager.py
When printers share the same group_id, they are removed, regardless if they are hidden or not. This was resulting in sometimes removing multiple printers when removing a printer that was created by a project file.
This PR fixes that by actually checking whether the printer-to-be-removed is hidden.
CURA-7522
> CURA-7522: Removing printer created by project file also removes the original printer

- plugins/PostProcessingPlugin/Script.py
Refactored the code to use a join so that it doesn't need to check for adding spaces everytime.
We use a join at the end so that every element is separated by a space.
It also fixes the bug where it would grab the comment including ";" and then add another ";" when reinserting the comment
> Fixed double ";" when using putValue on a line with a comment

- resources/intent/ultimaker_s5/um_s5_aa0.4_ABS_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_ABS_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPEP_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPEP_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPE_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_CPE_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_Nylon_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_Nylon_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PC_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PC_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_PLA_Normal_Quality_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_TPLA_Fast_Print_Accurate.inst.cfg
- resources/intent/ultimaker_s5/um_s5_aa0.4_TPLA_Normal_Quality_Accurate.inst.cfg
- resources/variants/ultimaker3_aa0.25.inst.cfg
- resources/variants/ultimaker3_aa04.inst.cfg
- resources/variants/ultimaker3_extended_aa0.25.inst.cfg
- resources/variants/ultimaker3_extended_aa04.inst.cfg
- resources/variants/ultimaker_s5_aa0.25.inst.cfg
To compensate elephant foot -> initial layer horizontal expansion setting is modeified for engineering and AA0.25 core profile for UMS5 and for UM3  for AA0.4 and AA0.25 cores.
> Initial layer Horizontal Expansion for AA0.4 and AA0.25 print core

- cura/PrinterOutput/Models/ExtruderConfigurationModel.py
Fixes an issue where 2 configurations
(empty, empty) and (pla, empty) were considered
equal
CURA-7248
> Fix ExtruderConfigurationModel.__eq__

- plugins/3MFReader/ThreeMFWorkspaceReader.py
By using "pass" when the IndexError occured while reading the quality changes, empty quality
changes containers were added to the registry. These empty quality changes were then used as
"global" quality_changes, since the container registry was simply picking the first quality
changes instance container that had an empty extruder stack. The correct global
quality changes (that actually had the global settings that were changed, like the support)
was just ignored in the whole process.
CURA-7549
> Fix losing global quality changes when reading a 3MF with a CFFF

- plugins/ImageReader/ImageReaderUI.py
This fix selects transparency model according to the UI. There index 0 is Linear mode and index 1 is Translucency mode. In the python code it was interpreted the other way round.
> Correctly select the color mode from GUI - this fixes bug #8040

- resources/definitions/dagoma_disco.def.json
Values taken from [Dagoma Marlin source code](https://github.com/dagoma3d/Marlin-By-Dagoma/blob/Dagoma-Development/LinuxAddons/Dagoma/conf/serie/E200/Base). Same values are in Marlin for DiscoUltimate.
> Include additional machine defaults for Dagoma DiscoEasy / DiscoUltimate

- resources/definitions/fdmprinter.def.json
When the  Bottom Pattern Initial Layer and Top/Bottom Pattern are set to concentric
AND the Top Surface Skin Layers are 0, hide the Extra Skin Wall Count, as it has not
effect.
Merge along with https://github.com/Ultimaker/CuraEngine/pull/1287.
CURA-6684
> CURA-6684: Hide Extra Skin Wall Count in concentric

- plugins/VersionUpgrade/VersionUpgrade34to35/__init__.py
Since the metadata/setting_version field was not written in project files from the 3MF writer,
the preferences were never really updated, because their preferences version was marked as 6000000
(basically omitting the setting_version). Now, if any project file is found without a metadata
setting_version tag, it will default to preference version 6000000 and thus it will start calling
the updatedPreferences() functions starting from VersionUpgrade34to35, properly updating the
preferences and adding the metadata/setting_version field in the preferences.cfg of the project
file.
CURA-6711
> CURA-6711: Fix preferences.cfg not being updated in project files

- plugins/PostProcessingPlugin/plugin.json
- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
- plugins/PostProcessingPlugin/scripts/PauseAtHeightforRepetier.py
I've opened a Feature Request, but made this change.
So, I've tested with my Cura 4.6 on Windows and it worked like a charm. 
Example:
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current layer: 87
M83 ; switch to relative E values for any needed retraction
G1 F2400 E-30
G1 F300 Z18.64 ; move up a millimeter to get out of the way
G1 F9000 X30 Y30
M104 S240 ; standby temperature
M18 S900 ; Set the disarm timeout
**M300 S440 P200;
M300 S660 P250;
M300 S880 P300;**
M0 ; Do the actual pause
**M300 S440 P200;
M300 S660 P250;
M300 S880 P300;**
M109 S240 ; resume temperature
G1 F2400 E30
G1 F2400 E-30
I've putted some beep code to alert me when it's time to change the filament.
> Included 2 fields on PauseAtHeight script for user to put custom GCODE's before and after the actual pause

- resources/qml/PrintSetupTooltip.qml
This is something that will by default probably not make any difference for Cura, unless there are settings with extremely long descriptions and people try to read them on very small screens. I'm implementing this because the Settings Guide has an option to put the articles in the setting tooltips. That option is sometimes useless because the articles are just way too long to display on the screen.
I've made a change that allows the user to interact with the setting tooltips and scroll through the text, if it is too long to display on the screen. To allow this, I've also implemented that hovering over the tooltip makes the tooltip stay visible. You can hover over the tooltip while it is still visible (opacity > 0), so you've got the 0.1s duration of the fade animation to move the cursor …
> Allow scrolling through setting tooltips

- resources/i18n/ko_KR/fdmprinter.def.json.po
en:i changed ironing_flow translation to "다림질 압출량". "과정" means process. so i changed it "압출량"-every flow word has been translated to this. 
kr:기존의 다림질 과정에서 flow를 "과정"이 아닌 "압출량"으로 바꾸었습니다.
> Retranslate ko_kr "ironing_flow"

- cura/Settings/CuraStackBuilder.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
The non-global settings of only the first extruder are applied, while the rest of the extruders are ignored. This happens because of the fact that the machine_extruder_count is not taken into consideration when creating a machine, which leads to the extruderList thinking that there is only 1 extruder (since machine_extruder_count == 1 by default). The problem is observed in project files with printers that have a settable number of extruders (through their machine settings).
This PR fixes that by accounting for the amount of extruders specified in the definition_changes of the printer when creating the machine.
In addition, this PR fixes the issue of displaying the materials of multiple extruders in the open project dialog, even if the printer has only 1 extruder.
> CURA-7646: Settings not applied when creating new CFFF from project file

- cura/Settings/CuraContainerStack.py
- cura/Settings/ExtruderStack.py
- cura/Settings/GlobalStack.py
- tests/Settings/TestGlobalStack.py
I was doing some research on finding a way to create a fundamentally different way to handle properties. But during that time I again found some things that were being rather inefficient about it.
This PR should improve the speed of setting loading & value changes.
The one that is easiest to measure it the speed by which the slice message sending is handled. 
Before: 0.65s
After: 0.36s
> Get property speed improvements

- cura/Settings/CuraContainerRegistry.py
- resources/qml/Preferences/ProfilesPage.qml
Warn when importing quality profiles that don't match the current configuration
When importing a profile that doesn't much the current nozzle combination (e.g. importing a 'high'
quality when we have AA0.8 and AA0.4 nozzles), the profile was being accepted and a success message
was shown to the user, but the quality did not show up in the profile list.
This commit fixes that by accepting the quality profile and informing the user that the profile is
not visible due to the current configuration.
CURA-7691
> CURA-7691: Unclear why imported profile is not immediately visible

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
This alias shouldn't be written any more since the firmware misinterprets the setting value and errors when it's more than 100%.
Contributes to issue CURA-7724.
> Remove shrinkage percentage setting alias

- cura/Settings/MachineManager.py
So that the dialog ensures actually knows that there are no changed settings and will not show up.
CURA-7728
> CURA-7728: Recalculate the number of user settings after setting the quality group

- cura/Arranging/Nest2DArrange.py
I've added a feature to libnest2d to be able to mark items as disallowed areas. Other items won't collate with disallowed areas to minimise the used surface area of the group together. But they will still avoid the position of the disallowed areas and pack inside them.
Also improve the filtering a bit so that it's no longer dependent on the order. Doesn't really matter in this case but it should be more robust.
Contributes to issue CURA-7754.
This change depends on a change to pynest2d: https://github.com/Ultimaker/pynest2d/pull/2 which in turn depends on a change to libnest2d: https://github.com/Ultimaker/libnest2d/pull/1
> Mark disallowed areas as disallowed areas

- cura/Arranging/ArrangeObjectsJob.py
- cura/Arranging/Nest2DArrange.py
- plugins/3MFReader/ThreeMFReader.py
This PR fixes three things:
- The "Finding Location" message would remain open without an option to be closed, if for any reason arrange would crash. This is fixed by surrounding arrange with try-except.
- If for some reason an objects has no convex hull, then it will be skipped from being arranged.
- Previously, objects loaded from 3mf and are outside of the buildplate would have no ConvexHullDecorator. This is now fixed by adding it on 3mf loading.
CURA-7780
> CURA-7780: Fix arrange message not closing when arrange crashes

- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
To make sure that the printer status reflected in Cura is the same as the one in the Digital Factory when the printer is preparing for the print.
Contributes to CURA-7745
> Add "preparing" printer status in the monitor page

- cura/BuildVolume.py
CURA-7643 
There could still be some cases where the prime tower brim was overlapping with the brim of the object.
needs: https://github.com/Ultimaker/Uranium/pull/649
> Fix prime tower overlap

- plugins/PostProcessingPlugin/scripts/DisplayProgressOnLCD.py
This updates post-process plugin to export remaining time in M73 R in addition to M117 status line.
Update remaining time with M117 can be updated periodically in addition to every layer.
Discussed in #8331
> M73 R and update interval in Display Progress On LCD PP plugin

- cura/Settings/MachineManager.py
The addMachineExtruders function assumes that this is a new printer (first time the printer is activated since a restart of Cura) and it needs to add the extruder stacks to it. However most of the time when we're switching, it's not to a new printer. If it's not a new printer, this function would get called anyway and we'd be adding the extruders multiple times. This then does a lot of unnecessary work and eventually fails a couple of calls deep when it sees the extruders are already there.
This change prevents it from adding the extruders if there are already extruders associated with the printer, thus preventing this unnecessary work (switch is faster) and preventing the error from happening.
Discovered during work on CURA-7501.
> Prevent duplicate adding of extruders

- tests/TestArrange.py
So that the output of the CI/CD testing step is not cluttered with deprecation warnings.
Done during TTT
> Skip running the tests for the old arrange algorithm

- resources/quality/ultimaker_s3/um_s3_aa0.25_Nylon_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_ABS_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_ABS_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_ABS_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_ABS_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_Nylon_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_Nylon_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_Nylon_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_Nylon_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PLA_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_ABS_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_Nylon_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_Nylon_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_Nylon_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_Nylon_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PLA_Normal_Quality.inst.cfg
These settings are optimized by Coen who was doing his internship project on raft release strategy for PLA, Nylon and ABS for AA0.4 print core for UMS3 and UMS5 printers.
> Modified raft settings: raft air gap, raft surface speed, speed layer 0

- resources/qml/ToolTip.qml
This PR fixes tooltips on ActionButtons such as the buttons that constitute the toolbar and buttons in the ActionPanel etc. The tooltips were broken in 5f574d4b64ab0114b19b843acbc70e006bbe69d1, and this PR applies a fix on top of that. I am not entirely sure what the original commit was meant to fix, so there may be a more direct way to fix the tooltips than this roundabout fix.
> Fix tooltips on actionbuttons

- cura/CuraApplication.py
This way it gets loaded only once on start-up, which prevents errors that the plug-in was already loaded.
This PR depends on https://github.com/Ultimaker/Uranium/pull/648 . Please merge at the same time.
Contributes to issue CURA-7501.
> Add ConsoleLogger as pre-loaded plug-in

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
Adds a new setting called "Maximum Extrusion Area Deviation", which tells the simplification algorithm what is the maximum allowed extrusion area error when removing intermediate junctions from a straight ExtrusionLine.
A few bench(y)marks and statistics of the simplification of colinear segments:
|    | Benchy |
| ------------- | ------------- |
| Total candidate points checked  | 445834 |
| Area deviation Error == 0μm²  | 382422  |
| Area deviation Error in range (0mm², 500μm²]  | 41977 |
| Area deviation Error in range (500mm², 1000μm²]  | 11910 |
| Area deviation Error in range (1000μm², 2000μm²] | 5657 |
| Area deviation Error in range (2000μm², 3000μm²] | 1390 |
| Area deviation Error in range (3000μm², 4000μm²] | 1017 |
| Area deviation Error in range (4000μm², 5000μm²] | 624 |
| …
> CURA-7751: Simplify arachne toolpaths

- plugins/PostProcessingPlugin/scripts/TimeLapse.py
This adds a z-hop and filament retraction for timelapse post processing.
On my Ender 3 Pro that reduces to zero the stringing ocurring when parking the head.
With the original script:
With the modified script:
The test settings was:
Tested on Cura 4.8
> Add Z-Hop and filament retraction to Timelapse

- resources/definitions/fdmprinter.def.json
This change adds a number of settings for things that were initially hard-coded in the variable line width code. In some cases the value is still hard-coded but updated to a more sensible value.
These are the variables that have been considered for this change:
* Wall Transition Length: This is a new setting that determines how much space is used to transition from one bead count to another. Instead of the previously suggested % of nozzle size, the default and warning values are now % of line width. The maximum is chosen based on what could theoretically result in loops within one transition. Experimentally though this doesn't seem to be a problem. What is a problem is that we get all sorts of assertion failures at extreme values of this setting. This causes some lines to be missing. …
> Add new specialised settings for variable line width

- resources/definitions/fdmprinter.def.json
Since the insets are going to be removed from CuraEngine, some settings will no longer work until they are adapted to use the libArachne toolpaths. At the moment the following settings are disabled:
- Fuzzy Skin
- Fuzzy Skin Outside Only
- Fuzzy Skin Thickness
- Fuzzy Skin Density
- Fuzzy Skin Point Distance
Merge along with https://github.com/Ultimaker/CuraEngine/pull/1364.
CURA-7678
> CURA-7678: Remove inset usage

- docs/How_to_use_the_flame_graph_profiler.md
There is a small typo in docs/How_to_use_the_flame_graph_profiler.md.
Should read `their` rather than `thier`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, thier -> their

- plugins/XmlMaterialProfile/XmlMaterialProfile.py
While attempting to save a project on my machine using Python 3.9 I ran into the following traceback.
```
File "/usr/lib/python3.9/site-packages/cura/CuraApplication.py", line 1063, in event
return super().event(event)
File "/usr/lib/python3.9/site-packages/UM/Qt/QtApplication.py", line 464, in event
event._function_event.call()
File "/usr/lib/python3.9/site-packages/UM/Event.py", line 218, in call
self._function(*self._args, **self._kwargs)
File "/usr/lib/python3.9/site-packages/cura/Utils/Threading.py", line 34, in _handle_call
ico.result = func(*args, **kwargs)
File "/usr/lib/cura/plugins/3MFWriter/ThreeMFWorkspaceWriter.py", line 57, in write
self._writeContainerToArchive(container, archive)
File …
```
> Adapt to Python 3.9 API changes

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
This PR fixes the json definition of the PauseAtHeight script, which contained a double declaration of the default value for the machine_gcode_flavor setting.
> Fix definition of machine_gcode_flavor setting in PauseAtHeight

- resources/definitions/snapmaker2.def.json
- resources/definitions/snapmaker2_A150.def.json
- resources/definitions/snapmaker2_A250.def.json
- resources/definitions/snapmaker2_A350.def.json
- resources/extruders/snapmaker_extruder_0.def.json
- resources/quality/snapmaker2/snapmaker2_fast.inst.cfg
- resources/quality/snapmaker2/snapmaker2_high.inst.cfg
- resources/quality/snapmaker2/snapmaker2_normal.inst.cfg
This PR adds Snapmaker 2.0 definitions as an available printer within Cura.
The intention is to generally mimic the Luban settings (i.e. the default Snapmaker Profiles).  These settings are generally found in: https://github.com/Snapmaker/Luban/tree/master/resources/CuraEngine/Config.
I have tested these with the A350 for about a month now without issue.
The A250 and A150 profiles were added for completeness but, lacking those models, I cannot test them myself.
> feat: add snapmaker 2.0 definitions

- plugins/MachineSettingsAction/MachineSettingsExtruderTab.qml
- resources/qml/MachineSettings/NumericTextFieldWithUnit.qml
This PR fixes the issue that users of some system locales have to enter nozzle and material diameters with a comma instead of a decimal dot.
The DoubleValidator depends on the system locale, requiring users with certain locales to enter floats with a comma instead of a dot (though confusingly floats are always represented with a decimal a dot). Instead of configuring the DoubleValidator with a locale that only accepts decimal dots, this commit uses a RegExpValidator, like other numeric fields in Cura does.
Fixes #6546
> Fix validator for floats in Machine Settings dialog

- plugins/CuraEngineBackend/CuraEngineBackend.py
When autoslicing is enabled, it was trying to create a snapshot before the main window is present.
You'll need the Uranium branch of the same (fix_is_visible) name if you don't want this to crash on slicing!
> Don't take snapshot if no main window present.

- plugins/3MFReader/ThreeMFReader.py
Otherwise the user could infer valid, but empty workspace is corrupt.
You'l need https://github.com/Ultimaker/Uranium/pull/669 to make this work properly.
> [CURA-7996] Possible to distinguish between empty and corrupt 3MF.

- plugins/MachineSettingsAction/MachineSettingsPrinterTab.qml
- resources/definitions/fdmprinter.def.json
This was done as a solution to this issue:  #9167. The original issue can be read for more information, but I'll go over the basics of the change here. 
This change Add a checkbox on the 'Printer' tab of machine settings that allows users to enable/disable the application of extruder offsets to generated gcode. By default this setting is ENABLED for every printer, unless setup in the printer's .def.json file, which is not really accessible unless the user knows what they are doing and want to mess with program files. 
The reason for this change was that my chimera style printer had the offsets defined in firmware. I also defined them in Cura so that I could see the printable area for each nozzle. When it actually went to print, the plastic was off by the distance of the offset. 
This …
> Add checkbox to enable/disable Extruder Offsets during Gcode generation

- plugins/PostProcessingPlugin/PostProcessingPlugin.py
This PR fixes the PostProcessing plugin to load scripts from all registered resource paths instead of only the main resource folder. With this change, a plugin can include its own `scripts` folder and register it with the following snippet (from its `__init__` implementation):
`Resources.addSearchPath(os.path.dirname(os.path.abspath(__file__)))`
/sa https://github.com/5axes/Calibration-Shapes/issues/1
> Fix loading scripts from all registered resource paths

- plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrintJobConstraints.py
- plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrintJobStatus.py
During Digital Factory implementation of the UM2+C this bug was discovered. For now we'll also make sure that printers always send at least an empty object, but this bug should be fixed here nonetheless. Also fixed the typing for the constraints (was typed a list, but is actually just a single object with known key `require_printer_name`, which is already optional).
The original stack trace:
```
File "/build/4.8/build/inst/lib/python3.5/site-packages/UM/TaskManagement/TaskManager.py", line 143, in event
File "/build/4.8/build/inst/lib/python3.5/site-packages/UM/TaskManagement/TaskManager.py", line 33, in callFunction
File "/tmp/.mount_UltimaPsBReR/usr/bin/plugins/plugins/UM3NetworkPrinting/src/Cloud/CloudApiClient.py", line 245, in parse …
```
> Fix cluster print job constraints typing and optionality

- plugins/UM3NetworkPrinting/src/Network/ZeroConfClient.py
The code is clearly written to take into account that 'addresses' may be null. But not that the whole 'addresses' attribute may not exist. And then instead of printing one warning (Could not get information about XX) it instead printed a stacktrace and retried and printed a stacktrace and retried and printed a stacktrace and.... It ended up driving me a bit nuts when looking at the logs for unrelated reasons. So Ifinallay fixed it. Could end up as a speedup in some cases as well I suppose?
> Fix error log spam.

- plugins/SolidView/SolidView.py
UX found that users where confused by the word non-manifold. Reword the message and add an explanatory link.
(There's still something off there, as the message doesn't always seem to show. I often have to load the clearly broken testmodel multiple times in order to see it.)
> [CURA-7820] Reword the non-manifold message, add link.

- plugins/SimulationView/SimulationPass.py
This fixes a very old bug in Cura where sometimes after re-slicing it would display the layer as if you've been going horizontal through the path slider, even if you never touched the horizontal path slider.
This was caused by a tracking flag in the `SimulationPass`, `_switching_layers`. This bit of state in the `SimulationPass` was tracking whether the user is going through the vertical layer slider (`True`) or the horizontal path slider (`False`). If `False`, the nozzle mesh is drawn and lower layers get drawn in a shadowy shader. The state of this flag was being updated on every render by looking at whether the previous render has the same current layer number but a different path index. If so, it changed to `False`, meaning that it assumes you're going through the paths on a layer and …
> Fix layer view being greyed out after reslicing gives same current layer

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Bug:
The Post Processing Plugin "Pause at height" has a bug with the Repetier Method where the Z-height is 1mm to high after continue.
Discuss: https://github.com/Ultimaker/Cura/issues/8575
The wrong line starts here:
458: prepend_gcode += self.putValue(G = 1, Z = current_z + 1, F = 300) + "\n"
The correct line:
458: prepend_gcode += self.putValue(G = 1, Z = current_z, F = 300) + "\n"
> Post Processing Plugin | Pause at height | Repetier (@pause) 1mm to high

- plugins/Toolbox/resources/qml/components/ToolboxHeader.qml
We generally disabled the clicks in the mouseArea of the tooltips.
In this case though it should still accept the left click since it acts as a button.
CURA-8125
> CURA-8125: Fix marketplace button not directing to the web marketplace

- plugins/Toolbox/resources/qml/components/ToolboxFooter.qml
After installing a package and hitting the "Close Ultimaker Cura" button, the Toolbox window was remaining open for a few seconds, even though the Cura window was instantly closing.
This is not fixed by explicitly hiding the Toolbox dialog once that button is pressed.
CURA-8126
> CURA-8126: Fix Toolbox window not closing instantly after pressing "Quit Cura"

- plugins/SimulationView/layers3d.shader
All of our current layer view colour schemes are properties of a line, not of a vertex. The line has a single feedrate, a single line type, a single layer thickness, a single material colour and a single width. This is even limited by the g-code specification itself, which is unable to represent lines with varying line width. However, we store this information in the vertices, the vertex data being the only data sent to layer view since layer view is sent as polylines to the shader.
This change makes the entire line take on the colour scheme of the vertex where its representative data is stored. This data is intended for the line, not just for that vertex, so it makes sense that the entire line listens to the data of the correct vertex, not just the nearest vertex of the line's endpoint. …
> Draw simulation view lines with a constant colour for the entire line

- cura/OAuth2/KeyringAttribute.py
Write an empty string as value to the keyring if None is parsed and
return a None value if an empty string was parsed from the keyring.
CURA-7180_keyring_none_value
> Handle storing None values in keyring

- resources/qml/Menus/ConfigurationMenu/CustomConfiguration.qml
Menu's didn't always close, and on newer Macs users wouldn't be able to even close the menu, making this a blocker. Will fix this properly before the final, but at least the beta should be usable now.
> CURA-8142 Custom-menu OSX workaround

- resources/qml/Preferences/SettingVisibilityPage.qml
This will make this Qt5.15 control work on mac again. (Since the older controls are deprecated.)
CURA-8127
> Also convert visibility-preset dropdown.

- resources/qml/Settings/SettingView.qml
The signal `setActiveFocusToNextSetting` has an argument which wasn't being passed in the `onSetActiveFocusToNextSetting()` function, causing the broken behavior.
Fixes https://github.com/Ultimaker/Cura/issues/9529.
CURA-8166
> CURA-8166: Fix tab button not switching to the next print setting field

- resources/qml/Preferences/GeneralPage.qml
- Language and Theme selections where empty and 'Colorblind' no matter what. This was an UX issue, since selecting and changeing them still worked, it just didn't show the active ones.
- Remove donkey: We where showing our donkey due to an unfortunate abbreviation/truncation of 'Colorblind Assist'. Now that should already not show in for a default install (see previous point) but also just give the box some more space.
- Revert most of the rest of the preferences/general page back to the old controls (except for the combo-boxes, which needed to be upgraded in order to work on MacOS 11), pending a _proper_ redesign to the newer style of this page.
> [CURA-8161] Remove donkey and other UX adventures

- cura/Arranging/Nest2DArrange.py
So libnest2d is giving a segfault when it's being triggered without any disallowed areas. This is because we then give a single disallowed area for the border around the build plate, and give this disallowed area 0 vertices. Because libnest2d doesn't do defensive coding here, it's going to crash, taking Cura along with it. The crash is in libnest2d's function `libnest2d::_Item<ClipperLib::Polygon>::rightmostTopVertex()`.
This segfault started happening recently in Cura. However it only happens when there are no disallowed areas. Steps to reproduce the error are:
- Use Custom FFF Printer.
- Set the Adhesion Type setting to 'None'.
- Load any two models.
I tracked the segfault down to this commit: https://github.com/Ultimaker/Uranium/pull/684/commits/74ddbaab4bb4737367ad2f82698ee7422305a047 …
> Fix segfault when arranging without any disallowed areas

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/Messages/PrintJobUploadErrorMessage.py
Fix 'uploaded print-job cache' set before the mesh upload.
Since we use that to detect when the mesh is already uploaded, and thus can be reprinted, this could cause problems, since, while we do properly set it to None when an error is returned, if the request never returns to us, or if a reprint is started while the mesh is still uploading, the print-job cache could be set while the mesh wasn't actually there yet. Which could in theory have maybe caused the problems we see.
> [CURA-8004] Fix wrong 'uploaded print job' cache.

- cura/OAuth2/KeyringAttribute.py
When Cura is starting up, it reads the authentication data from the preferences (cura.cfg). If the auth tokens have previously been stored in the keyring, it means that their values will be null in the cura.cfg file. Therefore, on startup, Cura reads the tokens as none from the preferences and then sets the empty values in the keyring as tokens. This leads to the user being signed off every time Cura restarts on Mac.
On Windows, the access token was still stored in the preferences, so on startup it was safe. The refresh token, on the other hand, had the same issue as on Mac, which means that on startup it was read as None from the cura.cfg and was stored in the keyring as an empty string. This meant that, even though on startup (on windows) the user was kept signed in, the next time Cura …
> CURA-8178: Fix auth tokens being set to none on startup

- tests/TestOAuth2.py
This test was failing with Python 3.9 while packaging `cura` for Fedora 34.
`authorization_service._onAuthStateChanged()` marks the user as logged-in if `success` is `True` (default value) in `AuthenticationResponse`. (I thikn) setting `success` to `False` produces the expected behavior for the test.
> Fix test_wrongServerResponses

- plugins/SimulationView/layers3d.shader
Not sure I understand why this works - size_x/y are for the end of the line not the start
> Fix for crashes on Mac 10.13 in 2010 era hardware Bug #9631

- resources/themes/cura-light/styles.qml
This PR prevents hundreds of QML warning messages logged per second in some user reports of Cura being slow.
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/24#issue-872046698 includes a log that has 700 of these warnings in the span of 2 seconds.
https://github.com/Ultimaker/Cura/issues/9628#issuecomment-823952208 also has hundreds of these warnings.
These warnings seem to be more prevalent in combination with the SidebarGUI plugin, but I see them too with "vanilla" Cura, especially when closing the application.
styles.qml currently uses `UM.Theme` and `Theme` interchangeably. This PR changes that to consistently use `UM.Theme` like the rest of Cura. For me that makes all the warnings go away.
I have made this PR against the 4.9 branch, because I think it is imperative that …
> Fix floods of QML errors in styles.qml

- plugins/SimulationView/SimulationView.py
This pull request has a tiny bugfix.
In the `setMinimumPath` function, it was limiting the minimum path index to the number of layers:
```
if self._minimum_path_num > self._max_layers:
self._minimum_path_num = self._max_layers
```
This should've been limiting it to the number of paths. I discovered this while working on automating the creation of screenshots for the Settings Guide.
When fixing that, I decided that these functions should also be simplified, so I changed them to use `min()` and `max()` calls instead of those if statements. And I added documentation for them.
The minimum path index can't be changed from the Cura interface at the moment, since the horizontal path slider only allows changing the upper limit of the range, not the lower limit. But it's good to fix it anyway I …
> Fix path minimum limit

- plugins/UM3NetworkPrinting/src/Network/SendMaterialJob.py
Some ultimakers tend to choke if you try and send a lot of materials in one go.
Previously we would also always send the materials on the main thread, which would also make
the interface freeze a bit. That should no longer happen.
The implementation of this is not really great, but since this is a hotfix i've opted to change
as little as possible.
CURA-8224
> Rate limit the sending of materials to networked ultimakers

- cura_app.py
- plugins/PostProcessingPlugin/__init__.py
- plugins/UM3NetworkPrinting/src/__init__.py
Previously, Arcus, Savitar, and pynest2d were being build with a missing sip flag. This led to Cura
getting `ValueError: PyCapsule_GetPointer called with incorrect name`, if those libraries were not
imported (even if they were unused).
This flag was added in the following commits:
* https://github.com/Ultimaker/libSavitar/commit/83393f989c0a8eb0b4ddc00560f028bf4eb4ac6b
* https://github.com/Ultimaker/libArcus/commit/e9e530d96383c18a739e7ad181907c33b30157ec
* https://github.com/Ultimaker/pynest2d/commit/bd440b50ad6fe969063ecafe8ad99a7b7a25ccc2
Since the issue seems to be gone now, the unused imports should be removed from Cura.
All credits go to Rex Dieter for figuring that this missing flag was the issue.
https://src.fedoraproject.org/rpms/libarcus/pull-request/1#request_diff
CURA-8146
> CURA-8146: Fix getting PyCapsule error on import

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Should fix #9752 -- This makes the repetier case completely analogous to the other 'not-griffin' flavours (at least what concerns retraction amounts), and also neatly dove-tails with the first point things start to go wrong in the bug-report.
> [CURA-8246] Pause-at-height/repetier: Extrusion should be retraction.

- cura/CuraApplication.py
- cura/Scene/CuraSceneNode.py
- plugins/SliceInfoPlugin/SliceInfo.py
- plugins/SliceInfoPlugin/example_data.html
We'd like to see which file type people are opening in our anonymous usage statistics.
This PR requires https://github.com/Ultimaker/Uranium/pull/696 .
It is currently marked as a draft because the statistics database is not yet ready to accept this data.
Contributes to issue CURA-8232.
> Add source file type to anonymous usage statistics

- cura/OAuth2/AuthorizationService.py
This PR fixes a crash when starting Cura without a network connection if the user was previously logged in to an Ultimaker account.
*Steps to reproduce*
* Start Cura 4.9.1
* Log in to Ultimaker account
* Close Cura
* Disconnect from all networks
* Restart Cura
Result:
Infinite loop of `AuthorizationService._parseJWT -> AuthorizationService._storeAuthData -> AuthorizationService.getUserProfile -> AuthorizationService._parseJWT -> etc`
This PR fixes https://github.com/Ultimaker/Cura/issues/9847
> Fix an crash when starting Cura without a network connection

- resources/qml/Menus/SettingVisibilityPresetsMenu.qml
- resources/qml/Settings/SettingView.qml
- resources/qml/Widgets/Menu.qml
- resources/qml/Widgets/MenuItem.qml
- resources/qml/Widgets/MenuSeparator.qml
- resources/qml/qmldir
This PR changes the Setting Visibility presets menu ("hamburger" in setting view) to use Cura-themed Menu, MenuItem and MenuSeparator controls so the menu looks less out of place.
> Fix setting visibility presets menu style

- cura/Backups/Backup.py
- cura/Backups/BackupsManager.py
Backups are synced with your account anyway. Backing up the plugins means that you
quickly reach the limit of the max size (250mb) that the backups allow.
CURA-8269
> Exclude plugins from backup

- plugins/SimulationView/SimulationView.py
The max value was being calculated as the product of the max line width, max layer thickness
and max feedrate but it should be calculated as the maximum of the products of the width,
thickness and feedrate for each individual line. i.e. calculate the flow for each line
and use the max values of the flows. The min value calculation is similarly changed.
> Rework calculation of min/max flow rates for simulation view colour scheme

- cura/CuraApplication.py
- cura/Scene/CuraSceneNode.py
The other transformations, in particular rotation, were also influencing the merge. The transformations were not removed when calculating the center position, causing the center position of a mesh to be calculating differently. When the meshes were actually transformed/moved, all of the transformations were removed but this gave the model a different center position. The different center position wasn't properly being compensated for using the previously calculated center position.
This caused a bug to appear where merged meshes were wildly repositioned. This bug started becoming more prominent in Cura 4.8 because newly loaded models there are rotated to fit better, using the new arrange algorithm.
Fixes CURA-7873 and fixes #8765.
> Fix positioning of merged transformed meshes

- cura/Machines/Models/MaterialManagementModel.py
- cura/Settings/GlobalStack.py
- resources/definitions/ultimaker2_plus_connect.def.json
- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
- resources/qml/Preferences/Materials/MaterialsPage.qml
This is a feature to export all materials to a .umm archive from Cura.
Requirements, as from the ticket, are:
> requirements:
> 
> * ONE save all button
> * button to export all material profiles to a zip to specific location on disk
> * File-format should work with the firmware of both the s-line and UM2+c (just a .ZIP with the .xml files)
> * Default to removable drive if it is available
> * Only visible on UM-printers
The name of the button is taken from the GUI design by @lorenzoromagnoli . The rest of that design is explicitly considered out of scope.
Implements CURA-8055.
> Export all materials to archive

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
The extrusion mode is read from the primary extruder (`extruders[0]`). I am not familiar with multi-extruder setups, but I assume that the relative mode, if enabled, would be active for all extruders anyway (thus validating the use of `extruders[0]`).
> Added "Relative Extrusion" mode support for PauseAtHeight.py script

- plugins/USBPrinting/AutoDetectBaudJob.py
If the baudrate was anything else than 115200, detection of baudrate could fail
because readline() with a wrong baudrate would never return, even if timeouts
were set.
Update: Sometimes detection would succeed anyway if restarting Cura enough times, or pulling the USB cable out and in enough times. The problem may be that readline() would read an infinite stream of random data that usually, but not always, would happen to have an EOF character by coincidence.
The fix in the PR still applies
> Fix connecting to printer via USB

- resources/qml/ToolTip.qml
In some buttons (specifically, the "Manage printers" button), the tooltip arrow is being drawn even though the tooltip text is empty. This commit fixes that by making sure that the background rectangle (PointingRectangle) of the tooltip is not be visible if the height of the tooltip is 0.
CURA-8334
> CURA-8334: Don't draw tooltip background if height is 0

- cura/OAuth2/KeyringAttribute.py
Denying access to the keyring was causing Cura to crash on MacOS.
Contributes to issue CURA-8332 and sentry issue CURA-2EW
> CURA-8332: Don't crash if keyring access is denied on Mac

- cura/Backups/Backup.py
- plugins/CuraDrive/src/DriveApiService.py
- plugins/CuraDrive/src/DrivePluginExtension.py
- plugins/CuraDrive/src/qml/components/BackupListItem.qml
A few issues were happening while restoring the backup:
1. The preferences that were read from the backup were being overridden by the cached preferences when the `illuminate()` function was called, leading to the wrong `cura.cfg` after the backup was restored. This is now fixed by ensuring that the preferences are read _from the restored cura.cfg_ before illuminating the secrets.
2. There was no indication in the interface that a backup restore was in progress after the "Restore" button was pressed. This was giving the impression that Cura stopped working during the backup restore (especially if it took long). This is now fixed by showing a busy wheel in the "restore" button that was pressed
3. The extraction of the backup could take quite some time, during which, the interface was …
> CURA-8313: Restore backup messes configurations

- cura/OAuth2/KeyringAttribute.py
It turns out that when the `KeychainDenied` error is raised, it is being caught by the macOS keyring API and the non-macOS-specific `KeyringLocked` error is raised instead, so we need to catch this one.
In addition, it is now being caught also when _setting_ the token in the keyring.
CURA-8332
> CURA-8332: Cura crashes when access to keyring is denied

- cura/Backups/Backup.py
Sometimes, while a backup is being restored, one of the files in the current config folder may still be in use. This means that once the backup tries to replace this file with the one in the backup, the entire backup restoration fails (on Windows, due to a permission error) and half of the configuration folder may end up being missing.
To prevent that, we decided to ignore files that are currently in use while restoring a backup (i.e. keep the current version of those files and not replace them with the ones in the backup). This _may_ lead to a slightly wrong configuration (e.g. a plugin may not be restored properly), but it is an acceptable result, as the rest of the configuration folder is restored properly.
CURA-8313
> CURA-8313: Ignore files-in-use while restoring a backup

- resources/definitions/flyingbear_base.def.json
- resources/definitions/flyingbear_ghost_4s.def.json
- resources/definitions/flyingbear_ghost_5.def.json
Remove start G-code from Flying Bear Ghost 5 because it was causing positioning problems during Power-loss Recovery
Update machine_start_gcode and machine_end_gcode for Flying Bear Base
Update machine_height for Flying Bear Ghost 4S / 5 to a safe value
> Fix Power-loss Recovery and update G-codes for Flying Bear Base

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Otherwise it is superfluous.
Also, don't add it twice for the Repetier flavour.
This way the code is separated better into if-else cases to make it easier to read, even though it has this line in there 3 times.
Fixes issue CURA-8331.
> Only add G92 for Griffin if redoing layer in Pause At Height

- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.25_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_draft.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_fast.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.4_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.6_normal.inst.cfg
- resources/quality/ultimaker2_plus_connect/um2pc_petg_0.8_normal.inst.cfg
- resources/quality/ultimaker3/um3_aa0.25_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PETG_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_PETG_Superdraft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.8_PETG_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.25_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_High_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_PETG_Verydraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.25_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_High_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_PETG_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Superdraft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_PETG_Verydraft_Print.inst.cfg
Changed max combing distance for UMS3, UMS5, UM2C and UM3 to reduce stringing for PETG.
Fixed distance of 8mm.
> Petg updates 410

- plugins/PrepareStage/PrepareMenu.qml
- resources/qml/ExpandableComponent.qml
- resources/qml/ExpandablePopup.qml
If there are multiple sources from which you can open files, the open file button turns into a drop-down menu.
The drop-down menu then allows you to select the source from which to open files.
If there is only one option, it shows the old button.
Implements CURA-8008.
> Add a drop-down to the open-file button if multiple options are available

- plugins/DigitalLibrary/src/DigitalFactoryApiClient.py
- plugins/DigitalLibrary/src/DigitalFactoryController.py
- plugins/DigitalLibrary/src/DigitalFactoryFeatureBudgetResponse.py
- plugins/DigitalLibrary/src/DigitalFactoryFileProvider.py
- plugins/DigitalLibrary/src/DigitalFactoryOutputDevice.py
Users with an account and an UM printer should have some basic access to the Digital Library. To this end, and to remain future proof, the online team has made an extension to its API so now feature budgets can be gauge. At the moment it's only checked whether the user has any access to personal projects at all. If so, the interface shows Digital Library functionality.
Known issue: Removing the last printer from DF while still logged in leaves the DL access in the Cura interface until logged out or Cura restarted.
> [CURA-8138] Digital Library: Allow 'personal users' to Digital Library

- plugins/PrepareStage/PrepareMenu.qml
Instead of translating "open file" and "from Disk" separately, which could make the some translation results making less sense, it's better to just keep the dropdown entries only.
CURA-8411
> Remove the "Open file" label from the open file dropdown menu

- resources/qml/Actions.qml
- resources/qml/MainWindow/ApplicationMenu.qml
If you're using Cura in a different language, it was crashing on MacOS due to being moved to the special "Ultimaker Cura" menu that MacOS creates. These were the reproduction steps:
* Change Cura's language in its preferences menu.
* Restart Cura to complete the language change.
* Exit Cura. MacOS gives an error message then.
To fix this, certain menu entries should not be translated. Translating them causes Cura to update the menu entry's name upon closing down Cura, but the menu entry can't be found in its original place any more. The Qt documentation warns us that signals on the moved Menu elements won't work well any more.
The items changed below are the items that are moved by MacOS. Only those should not be translated any more. The rest should still be translated. MacOS itself …
> Fix crash on exit on MacOS if using Cura's translations

- resources/definitions/mp_mini_delta.def.json
- resources/definitions/mp_mini_delta_v2.def.json
- resources/extruders/mp_mini_delta_v2_extruder_0.def.json
Adding the MP Mini Delta V2. While this printer has the same form factor as the original MP Mini Delta, it is actually made by a different manufacturer (WEEBO instead of Malyan). The different mainboard, firmware, and other minor changes calls for different Start Gcode, as well as some other settings tweaks. 
I also made some minor changes to the original MP Mini Delta def. 
I am behind on the process for adding printers to Cura manually (via file copy), so I have not tested this def outside of making sure the Start/End gcode makes the old V1 def work for the V2. I can dig into this more if the build test cases report errors.
> MP Mini Delta V2 Printer Definition

- cura/PreviewPass.py
- cura/Snapshot.py
See also [this more substantial PR](https://github.com/Ultimaker/Uranium/pull/719) in UM.
If the context menu is opened over the slice button, then it _may_ on some cases (on Windows) fail on the creation of the snapshot. Within this fix, the snapshot is then still not created, but at least it doesn't crash any more. (Also the snapshot _will_ be there if a reslice is done.)
> [CURA-8412] Part of fix for crash on context menu open + click on slice.

- resources/definitions/fdmprinter.def.json
This adds a number of settings that allow the skin, top surface and ironing to be printed in a monotonic order.
For a more thorough explanation, see the CuraEngine sister-PR. Please contain the discussion in that PR as well.
https://github.com/Ultimaker/CuraEngine/pull/1476
Contributes to CURA-7928. Implements https://github.com/Ultimaker/Cura/issues/8909.
> Monotonic ordering of skin, top surface and ironing

- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
The following things were incompatible with 4.9/4.10:
- `Cura.TextField` doesn't have a `leftIcon` property in these versions. This is the property intented to add the "search" icon. To fix that, I did not use the property and instead I added a `UM.RecolorImage` manually inside the `TextField` to hold the "search" icon.
- `Cura.SecondaryButton` doesn't have a `tooltipWidth` property in earlier versions. This property was added to make sure that the tooltip has a smaller width than the DigitalLibrary window, or else it doesn't get drawn at all, which is confusing. Since it was not available in 4.9 and 4.10, I had to make the tooltip text smaller to make sure that it will fit.
- Previous text: "You have reached the maximum number of projects allowed by your subscription. Please upgrade to …
> CURA-8444: The Digital Library does not work on earlier Cura versions

- resources/definitions/fdmprinter.def.json
This replaces the single and confusingly named 'Line Compactness' with a set of 2 settings that give both more detailed control and will hopefully a bit easier to understand.
See back-end PR: https://github.com/Ultimaker/CuraEngine/pull/1481
> [CURA-8459] Differentiate even vs. uneven nr. of walls for add/split middle wall transitions.

- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
This PR makes parking the head optional (for all methods, except Griffin which handles the parking in the firmware so it is never added to the gcode). Not adding parking gcode makes the repetier `@pause` method suitable for use with OctoPrint (which similarly handles the parking in most cases). Not adding parking gcode can also be beneficial in modern Marlin flavors, since those too can handle the parking by themselves.
Contributes to #7842
> Make parking optional in all "methods" of Pause at Height

- resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
Both the `preferredWidth` AND the `width` need to be set for the labels to be properly elided if there is no more room  in the `ColumnLayout`. In addition, the `ColumnLayout` that contains the variants and material names needs to be visible only if `width>0` otherwise when the width is negative, for some reason, the `materialTypeLabel` appears again.
Before
After
CURA-8496
> CURA-8496: Fix long material names overlapping with icon

- resources/themes/cura-light/icons/deprecated_icons.json
This PR adds an alias for the previously existing "star" icon that was used in the header for the profile dropdown to show a profile had changed settings.
The PR is against version 4.11, because if the alias is not there in Cura 4.11 then it makes little sense to add it back to the next version of Cura.
> Fix missing "star" icon in Cura 4.11

- resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
When the labels were getting truncated and invisible after reducing the width of Cura's window, their visibility wasn't being restored back and, as a result, the `materialTypeLabel` was the only one that was remaining visible, even if there was enough space for the full `materialBrandColorTypeLabel`.
Changing the ColumnLayout to a Column, where the width is inherited from the parent, fixes that issue.
**Before:** After resizing from a small Cura window to a very wide one, the material color is not restored even though there is enough space
**After:** The material colors are restored as expected when there is enough space
CURA-8496
> CURA-8496: Fix showing only the material type after resizing Cura's window

- plugins/Toolbox/resources/qml/components/ToolboxDownloadsShowcase.qml
- plugins/Toolbox/resources/qml/pages/ToolboxInstalledPage.qml
- resources/qml/WelcomePages/WhatsNewContent.qml
- resources/themes/cura-dark/theme.json
- resources/themes/cura-light/theme.json
The following things are fixed by this PR:
1. The links in the What's new pages were using the OS-style links and they were inconsistent between OS. In addition to the inconsistency, the OS-styled link in Windows was hard to see in the dark theme. This is now fixed by making the links in that text area use a specific style. 
**Note: ** The style is applied by prepending the CSS style, since the text in the What's new pages is retrieved from html files.
2. The background color of premium plugins and materials was making the "Search materials" link very hard to see in the dark theme. This is now changed to a darked shade of grey
3. The "No plugins/materials installed" text in the Installed tab in the Marketplace was invisible in the dark theme. This is now changed so that the text color …
> CURA-8380: Align link style among os in whats new

- plugins/UM3NetworkPrinting/resources/qml/PrintWindow.qml
- resources/qml/Dialogs/DiscardOrKeepProfileChangesDialog.qml
The PrintWindow still used an old style combobox.
This resulted in a Mac user not being able to specify
which clustered printer he wanted to send a slice to.
Using the new QtQuick.Controls and specifically setting
the currentIndex fixed it for Mac.
Contributes to CURA-8214
> Fix greyed out cluster printers

- cura/UI/PrintInformation.py
- plugins/DigitalLibrary/src/DigitalFactoryController.py
- plugins/DigitalLibrary/src/DigitalFactoryOutputDevice.py
Cura was not retaining the last saved filename selected by the user after they were saving their file. This PR fixes that by making sure that the filename selected by the user in the save file dialog will update the name of the workspace (project) all around Cura.
**Note:** The stored filename is forgotten when the user loads another project file, creates a new project (Ctrl+N) or clears the buildplate (Ctrl+D).
Requires https://github.com/Ultimaker/Uranium/pull/728
CURA-8358
> Retain the last saved filename after saving a file

- cura/Settings/CuraContainerRegistry.py
- cura/Settings/DatabaseHandlers/IntentDatabaseHandler.py
- cura/Settings/DatabaseHandlers/QualityDatabaseHandler.py
- cura/Settings/DatabaseHandlers/VariantDatabaseHandler.py
Instead of re-reading the metadata from the files on every boot, which is pretty slow on windows (10+ seconds, even on machines with a fast SSD), we store the profiles in a database. By using the modified time of the files, we can check if the database needs updating.
Creating the database is about as fast as what it used to do, but every subsequent run, it knocked my boot time from 10s on windows to 0.6s. It also increases the booting time on Linux, but there it's only 300ms faster.
CURA-6096
Needs to be combined with https://github.com/Ultimaker/Uranium/pull/729
> Store metadata in database

- cura/SingleInstance.py
- resources/qml/Preferences/GeneralPage.qml
This PR adds a preference to the General pane of the preferences to clear the buildplate before loading a model via the "single instance" method. This way a user can choose to iterate on a single model (the current behavior, and still the default option) or to load multiple models into the single instance.
See https://community.ultimaker.com/topic/35858-command-line-to-open-an-stl-model-while-keeping-existing-ones/?tab=comments#comment-282714 and https://www.reddit.com/r/Cura/comments/mbkw2j/cant_open_multiple_models_at_the_same_time/
> Add preference to enable loading multiple objects into a single instance

- plugins/CuraEngineBackend/StartSliceJob.py
- resources/definitions/fdmprinter.def.json
This PR adds two new replacement patterns that users can add to their start gcode snippets: `{material_type}` and `{material_name}`. They map directly to metadata of the XmlMaterialProfile objects.
Contributes to https://github.com/Ultimaker/Cura/issues/10223 and https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/244
> Add {material_type} and {material_name} as replacement patterns

- resources/definitions/creality_ender5plus.def.json
If the Ender 5 Plus is turned off without moving the extruder after a print, upon turning it back on, the BLTouch will hit the frame of the printer and enter an error state. This prevents that by changing the end gcode for the Ender 5 Plus to move the extruder to X{machine_width} Y{machine_depth} instead of X0 Y{machine_depth}, where the BLTouch is not positioned to hit the frame when extended.
> Change Ender 5 Plus end gcode to prevent BLTouch collision

- resources/definitions/anycubic_mega_zero.def.json
- resources/definitions/atmat_signal_pro_base.def.json
- resources/definitions/creatable_d3.def.json
- resources/definitions/deltacomb_base.def.json
- resources/definitions/fdmprinter.def.json
- resources/definitions/inat_base.def.json
- resources/definitions/julia.def.json
- resources/definitions/leapfrog_bolt_pro.def.json
- resources/definitions/liquid.def.json
- resources/definitions/maker_made_300x.def.json
- resources/definitions/malyan_m200.def.json
- resources/definitions/monoprice_select_mini_v2.def.json
- resources/definitions/renkforce_rf100.def.json
- resources/definitions/renkforce_rf100_v2.def.json
- resources/definitions/renkforce_rf100_xl.def.json
- resources/definitions/robo_3d_r1.def.json
- resources/definitions/seemecnc_artemis.def.json
- resources/definitions/seemecnc_v32.def.json
- resources/definitions/skriware_2.def.json
- resources/definitions/strateo3d.def.json
- resources/definitions/tizyx_evy.def.json
- resources/definitions/tizyx_evy_dual.def.json
- resources/definitions/tizyx_k25.def.json
- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
- resources/definitions/voron2_base.def.json
New combing mode "Not in Outer Surfaces" to avoid going through the skin, only on the bottom-most and too-most outer surfaces. Compared to the "Not in Skin" option, which avoids combing through all the skin surfaces regardless if they are visible, the "Not in Outer Surfaces" avoids only the skin surfaces that are actually exposed and will be visible in the printed model. This has the added benefit that it saves time while preserving visual quality.
The "Not in Outer Surfaces" option will be enabled by default in the following cases:
1. Monotonic Top/Bottom Order is enabled (in any extruder)
2. Ironing is enabled (in any extruder)
3. Top Surface Skin Layers > 0 and Monotonic Top Surface Order is enabled (in any extruder)
Requires https://github.com/Ultimaker/CuraEngine/pull/1505.
CURA-7976
> CURA-7976: Combing strategy to avoid top and bottom most surface skins

- resources/qml/WelcomePages/CloudContent.qml
* Skip button
- Moved to the left, such that a user won't click on it mindlessly
- Made it a Tertiary button, so it will have predictable margins
* Sign-in button
- Moved to the right bottom, making it the logical next option
* Create an account
- Moved to be in line with skip and sign-in
- Made it a secondary button as requested by UX
Fixes CURA-8602
> Reorient layout of skip, sign-in and create

- cura/Machines/Models/MaterialManagementModel.py
This PR adds a message on startup which will appear if the user has just installed or updated material packages. The message will only show if the user has printers which support material export.
Requires https://github.com/Ultimaker/Uranium/pull/743.
CURA-8254
> CURA-8254: Trigger material profile sync with printer

- plugins/Marketplace/resources/qml/ManagePackagesButton.qml
- plugins/Marketplace/resources/qml/Marketplace.qml
I updated the styling of the hover state for the manage plugins button to match the styling of the buttons in the toolbar. and adjusted some sizes and paddings of the tabs button.
> adjusted style of hover and button sizes

- plugins/GCodeReader/FlavorParser.py
- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
We do retracts/unretracts on different heights sometimes, for instance after a pause. This would get seen as a new layer. It's quite safe to say that purely retracts and unretracts on a different height do not constitute a layer in a normal g-code file. There would be nothing to draw anyway.
There was also an unnecessary unretract/retract introduced by the Pause At Height script sometimes. The unretract/retract is only necessary if it's priming some extra material. Fixing that up should reduce ooze for those who don't need to prime.
Fixes #10282. Fixes CURA-8522.
> Fix visualisation of layer view with pause at height enabled

- resources/definitions/ultimaker.def.json
The skin orientation is optimized for the cross (3d) infill pattern to reduce the bridge distance. For more information see PP-55.
> optimized skin orientation for cross infill pattern

- resources/definitions/fdmprinter.def.json
- resources/definitions/ultimaker2.def.json
- resources/definitions/ultimaker3.def.json
- resources/definitions/ultimaker_s3.def.json
- resources/definitions/ultimaker_s5.def.json
This variable makes more sense to as a Ratio.
This was discussed during the eCCB 12/11/21
and implemented as a 5 min fix.
Note: The current default values were 0.5 there
is a new PR which change these 1.0. These values
should be multiplied with a 100
See also PR Ultimaker/CuraEngine#1529
> Flow equalization width factor as percentage

- plugins/Marketplace/resources/qml/ManagePackagesButton.qml
- plugins/Marketplace/resources/qml/Marketplace.qml
- plugins/Marketplace/resources/qml/PackageTypeTab.qml
In the current implementation of the marketplace navigation, clicking the manage plugins icon would not disable the previously active tab. Moreover the styles of the active, inactive and hover buttons where not aligned which might have led to confusion. 
I moved the manage packages buttons inside the tabview and style all the buttons to look similar when active, inactive and hovered. I also addressed some other comments I got from @Ghostkeeper in the previous PR
> Marketplace navigation improvements

- plugins/SimulationView/layers3d.shader
This PR fixes a compilation error of the shader used to render the simulation view. Some GPUs (rightly) complain about the difference between a float and an int. 
Fixes #10837
> Fix shader compilation on some GPUs

- resources/definitions/snapmaker2.def.json
Fixing the initial print temperature for print head and bed for the Snapmaker profile so that users can set the "Printing Temperature Initial Layer" and "Build Plate Temperature Initial Layer" properties and they actually do something.
> Fix initial layer bed and print head temperature for Snapmaker profile

- cura/API/Account.py
- cura/OAuth2/AuthorizationHelpers.py
- cura/OAuth2/AuthorizationRequestHandler.py
- cura/OAuth2/AuthorizationService.py
- plugins/Toolbox/src/CloudSync/CloudPackageChecker.py
- tests/API/TestAccount.py
- tests/TestOAuth2.py
The OAuth log-in flow was using the `requests` library. This was a problem for us for three reasons:
* The `requests` library doesn't properly use the desktop integrations of network requests, like the OS-provided local SSL certificate roots.
* The `requests` library is blocking, including blocking the main thread at start-up.
* The `requests` library is another attack vector for security issues. While there are no known issues with the current version, using a single library for all network requests reduces the attack surface.
This is a series of refactors to change that to use the HttpRequestManager, which uses the QNetworkManager under water. This does properly use local certificate roots and is not blocking. With this, we are no longer impacted by security issues in `requests` if any …
> OAuth via HttpRequestManager

- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobProgressBar.qml
The `printJob` now also contains a status for detecting aborted prints that were awaiting cleanup, preventing the need for the additional checks in the `await_cleanup` status.
Fixes CURA-8541
> [CURA-8541] Add handling of missing printJob status cases

- cura/Backups/Backup.py
Restoring plugins will cause a headache when (they are large and) the central storage was removed in the mean time. Since it's current policy to ignore plugins _anyway_ when backing up, the simple solution is to also just don't restore them, even if they where present to begin with. Of course this is also applied to other to-be-ignored files and folder types.
> [CURA-8666] Don't restore files ignored with current backup policy.

- plugins/3MFWriter/ThreeMFWorkspaceWriter.py
- plugins/3MFWriter/ThreeMFWriter.py
This PR adds a thumbnail to project files (edit: and exported files), like they are added to UFP files.
This PR fixes #10913
> Add a thumbnail to 3mf files (projects & exports)

- cura/Machines/Models/GlobalStacksModel.py
- cura/PrinterOutput/UploadMaterialsJob.py
- cura/UltimakerCloud/UltimakerCloudConstants.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFWriter/ThreeMFWorkspaceWriter.py
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py
- plugins/UM3NetworkPrinting/src/Models/Http/CloudClusterResponse.py
- resources/definitions/ultimaker2_plus_connect.def.json
- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
Old versions of the Ultimaker firmware can't receive them.
This causes the list of printers in the material sync window to be limited only to the printers that report that they can import materials via the cloud API.
> [CURA-8671] Don't send materials to printers that can't receive them

- cura/UltimakerCloud/CloudMaterialSync.py
This fxes the issue where it would still show an error message if you
first have a sync fail and then have one that succeeds
CURA-8670
> Fix error message after a failed sync

- cura/Layer.py
- cura/LayerDataBuilder.py
- cura/LayerPolygon.py
- plugins/SimulationView/SimulationPass.py
- plugins/SimulationView/layers.shader
- plugins/SimulationView/layers3d.shader
- plugins/SimulationView/layers3d_shadow.shader
- plugins/SimulationView/layers_shadow.shader
This reverts a change made to the rendering system in https://github.com/Ultimaker/Cura/pull/10259 .
The change there was to send the rendered mesh to the GPU only once, instead of every frame it is rendered. This provided a significant performance boost. However on AMD graphics drivers this also resulted in extra lines being rendered in random directions. The current theory is that these extra lines are rendered out of uninitialised VRAM, which is zeroed out on Intel and Nvidia but not on AMD.
This was the back-up solution. A number of other solutions have been tried as well:
* Changing the precision of the `u_drawRange` parameter. This had no effect.
* Breaking the vertex buffer objects into several pieces. This turned out to be prohibitively expensive because the index buffer may …
> Revert graphics buffer update

- resources/i18n/ru_RU/fdmprinter.def.json.po
Update strings having 'nozzle' translated as 'head' and make them more consistent with others where translation is correct.
> Fix translation for 'nozzle'.

- plugins/SimulationView/plugin.json
This PR adds a more descriptive text to the Simulation View plugin explaining what it does. Twice now I have had to help people who complain that they no longer have a PREVIEW tab after having disabled the "Simulation View". In the UI, the term "Simulation View" is never mentioned, and apparently (rightfully) don't associate the "Simulation View" plugin with the Preview functionality in Cura.
The description of a plugin named "Simulation View" being "Provides the Simulation View" is not really all that descriptive. In the PR, I have changed it to "Provides the preview of sliced layerdata", which at least has the word "preview" in it.
> Clarify the Simulation View plugin description

- resources/definitions/creality_ender5.def.json
Using G28 to fix the orientation of homing & the speed after the print.
> Ender5 Fixed Extruder hitting frame after print

- resources/quality/ultimaker3/um3_aa0.4_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_TPU_Fast_Print.inst.cfg
- resources/quality/ultimaker3/um3_aa0.4_TPU_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPU_Fast_Print.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.4_TPU_Normal_Quality.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Draft_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Fast_Print.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.4_TPU_Normal_Quality.inst.cfg
The top/bottom speed is reduced by 80% to allow for better cooling of the top layers. This reduces pillowing. The line width is increased by 80% to maintain the flow equalization. PP-95
> reduce top/bottom speed by 80%

- cura/CrashHandler.py
This breaks builds without the Sentry SDK. The check below handles the missing library fine, but this line introduced in https://github.com/Ultimaker/Cura/commit/3bfea5b97094615753fccdb7d03be335417f3228 broke it.
> Remove unused import of sentry_sdk

- cura/BuildVolume.py
- cura/Settings/ExtruderManager.py
- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
- tests/TestBuildVolume.py
See https://github.com/Ultimaker/CuraEngine/pull/1555 for a more detailed description of what this change is for and why we want to make it.
This pull request contains:
* New settings to change the individual layers of the raft (base, interface and surface, or their user-visible names: Base, Middle and Top).
* Updates of the build volume calculations to get the adhesion settings from the correct extruders.
* Updates of the used extruder calculation with the new raft extruders.
* Updates of the initial extruder calculation with the new raft extruders.
Contributes to issue CURA-8868.
> Raft Extruders

- cura/Arranging/Nest2DArrange.py
- cura/PlatformPhysics.py
- resources/qml/Dialogs/AboutDialog.qml
To upgrade to Python 3.10, we had to remove Shapely. It got replaced with Pyclipper.
The tests are failing because Pyclipper is not in the build environment yet. It will be added by this PR: https://github.com/Ultimaker/cura-build-environment/pull/119
Contributes to issue CURA-8592.
> Upgrade to Python 3.10

- resources/definitions/fdmprinter.def.json
The maximum extrusion area deviation is updated to 50000um2 by default and the warning levels are removed. Relates to PP-45
> update Maximum Extrusion Area Deviation

- resources/qml/Settings/SettingView.qml
In the Cura UI shows if there are hidding settings changed in the settings menu by showing an `i`-icon. Previously clicking this icon would show the hidden setting in the menu, this functionality broke over time. This PR re-enables that functionality.
> Fix show hidden settings

- cura/BuildVolume.py
- cura/Settings/ExtruderManager.py
- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
- tests/TestBuildVolume.py
This feature adds a setting by which the user can change the number of middle layers to print in the raft.
See https://github.com/Ultimaker/CuraEngine/pull/1572 for a more complete description.
> Raft Middle Layers

- resources/themes/cura-light/theme.json
Just a very small PR to look of the build plate grid. 
I reduced the line contrast while keeping the grid still very visible. 
old
new
> adjusted buildplate grid color

- plugins/CuraEngineBackend/StartSliceJob.py
Modifier meshes were not being included in object groups in one at a time mode. 
This change adds all modifier meshes to each object group in one at a time mode
.
> [CURA-8031] Modifier meshes in one at a time mode

- plugins/UM3NetworkPrinting/resources/qml/DiscoverUM3Action.qml
In component discover um 3 dialog. After a "complete" action the dialog will immediately close. This was undesired behaviour as we want to keep the dialog active if an IP address is wrongly added.
Additionally, it is no longer necessary to close/hide the dialog after a reject/accept as this is done by default.
CURA-8955
> [CURA-8955] Ip adress dialog

- resources/qml/Preferences/Materials/MaterialsPage.qml
Proposed solution takes a different approach compared to the previous solution. Previously there was one message dialog that was hidden by default. When the import/export material confirm dialog was triggered the text and body of this message dialog would change.
I did deviate from this pattern as this might introduce hard to debug issues when a property would be set on this dialog. As this dialog is used for various instances every instance should update the same properties. If one property is missed then the popup might show unwanted information.
I propose a different solution instead. Here a popup is created dynamically. This way the properties used for each instance is clear. This might add a delay when showing the popup as the whole component needs to be created when called. …
> [CURA-8959] Add "Ok" button in export/import materials popup dialog

- plugins/Marketplace/RemotePackageList.py
- plugins/Marketplace/resources/qml/ManagedPackages.qml
- plugins/Marketplace/resources/qml/Materials.qml
- plugins/Marketplace/resources/qml/PackageCard.qml
- plugins/Marketplace/resources/qml/PackageCardHeader.qml
- plugins/Marketplace/resources/qml/PackagePage.qml
- plugins/Marketplace/resources/qml/Packages.qml
- plugins/Marketplace/resources/qml/Plugins.qml
This splits up the single show controls property into three separate ones and no longer hides installed packages from the plugin & materials list
CURA-8834
> Show install, uninstall & disable buttons in packages list

- resources/qml/ProfileOverview.qml
It's not a great solution, but I just can't figure out why it wouldn't update.
The binding is correctly in place, so it should work. Might be a bug with QT?
CURA-8931
> Add workaround for TableModel not updating when rows are set directly

- plugins/GCodeReader/FlavorParser.py
Currently the filament diameter of extruder `0` is used but if one wants to display a gcode which was sliced with different filament diameters the lines of one will be too thick/thin.
This fixes the problem for up to 4 extruders (otherwise a index out of range error gets thrown),
> use current filament diameter

- resources/definitions/fdmprinter.def.json
Front-end counterpart of https://github.com/Ultimaker/CuraEngine/pull/1599
Re-implementing this feature for Arachne, so it should be (possible to) enable(d) again.
> [CURA-7887] Manually revert fuzzy skin disable.

- resources/qml/JobSpecs.qml
Swap TextField for Cura.TextField so it has the same styling as the rest of text fields.
CURA-9010
> [CURA-9010] adjust text highlight color of textfield when changing project name

- resources/qml/SpinBox.qml
This fixes the issue where the value that was in the textfield before typing would be incremented instead, if the textField had active focus.
CURA-8945
> [CURA-8945] odd spinbox behaviour when typing

- resources/definitions/fdmprinter.def.json
This PR introduces Minimum Wall Line Width settings which control the Middle Line Thresholds in a more intuitive fashion.
Moreover, this PR includes the formulae which properly relate the Minimum Lien Width settings to the Threshold settings.
These formulae can be used to verify the current behavior of the threshold settings more easily.
> More intuitive line thresholds

- resources/qml/Preferences/ProfilesPage.qml
Add isActiveModelFunction that can be overwritten in inheriting components
Override isActiveModelFunction in Profiles page, this is done because quality models do not have a unique id that can be assigned to activeId
CURA-9044
https://github.com/Ultimaker/Uranium/pull/798/
> Remove reference to Cura in UM component

- resources/qml/Dialogs/WorkspaceSummaryDialog.qml
- resources/qml/Menus/ConfigurationMenu/ConfigurationListView.qml
- resources/qml/Preferences/GeneralPage.qml
- resources/qml/Preferences/Materials/MaterialsPage.qml
- resources/qml/Preferences/Materials/MaterialsView.qml
- resources/qml/PrintMonitor.qml
This PR fixes what looks like a vestigial "double" scrollbar in some places. The mechanism seems to be that even though a custom scrollbar is provided, the "default" scrollbar is not hidden because it has a parent outside the scrollview (and the custom scrollbar is inside the scrollview). The resulting "default" scrollbar is non-functional, but its hitarea overlaps the custom scrollview so that one has a very small hit-area.
Both scrollbars showing in the materials pane are affected:
The profile selector is also affected:
For (some) details: https://doc.qt.io/qt-5/qml-qtquick-controls2-scrollbar.html#attaching-scrollbar-to-a-flickable
> Fix "double"/non-functional scrollbars on ScrollViews

- resources/definitions/fdmprinter.def.json
Revert "Set the default value of the Maximum Extrusion Area Deviation to 50.000um2 and remove the warning levels."
This reverts commit 3c4c91947e4eed82babe58550316789ffcde2444.
See also backend PR: https://github.com/Ultimaker/CuraEngine/pull/1621
> [CURA-9036] Revert to normal deviation error value.

- cura/Machines/MachineErrorChecker.py
It seems that in Qt5, the update loop was triggered a lot more often than in qt6.
Since we used that to handle the error checking, this made it so that you sometimes had to wait
for quite some time untill the slicing would start (as that is blocked by the error checker)
> Check multiple settings per update of event loop

- plugins/DigitalLibrary/src/DigitalFactoryController.py
Wrapping Retrieval in DFRetrieval does not seem to work in QT6, the object in QML returns undefined for all enum values.
Fixed by creating and registering the enum inside DigitalFactoryController.py
CURA-9126
> CURA-9126 Window not closing on creating new library project

- plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml
Center remove button in row by giving it the same height as the input.
Adjust width of rows when scrollbar is present so they don't overlap.
CURA-9149
> CURA-9149 Fix PerObjectSettings remove button layout

- resources/qml/Settings/SettingView.qml
When scrolling the setting list, it was clearing the focus in order to close the pop-ups in the setting list. If pop-ups like for the infill pattern or extruder selection settings are not closed, the pop-up part is still rendered even if the user scrolls those settings out of view, causing the pop-up to appear somewhere on top of completely unrelated interface elements. It scrolls all the way to the top of the screen, effectively.
I couldn't find a way to cause pop-ups to be clipped with the rest of the contents of the ListView. They are always rendered on top due to the nature of the pop-up. I could find a way to trigger pop-ups to close upon changing the scrolled position without changing the focus, but that method was fairly complex with a bunch of `Connection`s and an extra signal. …
> Fix search field losing focus when scrolling the setting list

- resources/qml/PrinterSelector/MachineSelectorButton.qml
Subtract previously unused rightMargin from MachineSelectorButton width.
CURA-9134
> CURA-9134 Misaligned machine label

- plugins/CuraDrive/src/qml/pages/WelcomePage.qml
- plugins/DigitalLibrary/resources/qml/LoadMoreProjectsCard.qml
- plugins/DigitalLibrary/resources/qml/SelectProjectPage.qml
- plugins/ModelChecker/ModelChecker.qml
- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorIconExtruder.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobPreview.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- resources/qml/Settings/SettingView.qml
This PR fixes some missing icons in the Cura 5.0 UI. In Qt6, the source of an image needs to be a resolved URL, whereas in Qt5 it could be a relative path string. This PR also fixes a "deprecated theme icon" warning.
After fixing this for the missing camera icon in the monitor page, I found the rest via a search in the source.
Fixes #11884, CURA-9117, CURA-9195
> [5.0b1] Fix missing icons since move to PyQt6

- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- resources/qml/Menus/ContextMenu.qml
- resources/qml/Menus/ExtensionMenu.qml
- resources/qml/Menus/MaterialMenu.qml
- resources/qml/Menus/NozzleMenu.qml
- resources/qml/Menus/OpenFilesMenu.qml
- resources/qml/Menus/PrinterMenu.qml
- resources/qml/Menus/PrinterTypeMenu.qml
- resources/qml/Menus/SaveProjectMenu.qml
- resources/qml/Menus/SettingVisibilityPresetsMenu.qml
- resources/qml/Menus/SettingsMenu.qml
It turns out that the order of these functions matters. So when we created a function with only one param, it would actually give it the index. Removing with the index didn't work, so the object would still be there. The Qt objects would already be deleted which caused segfaults
CURA-9222
> Use the correct function parameters when removing objects in menu

- resources/qml/Menus/ContextMenu.qml
This PR fixes the Multiply selected models when the number of copies is left to 1. The `value` of the spinbox does not get initialised to 1, so even though the label says 1, the value is 0. The command was making 0 copies.
Fixes #11897
> [5.0b1] Fix creating a single copy of a model

- resources/qml/Preferences/Materials/MaterialsPage.qml
- resources/qml/Preferences/ProfilesPage.qml
selectedNameFilter is now an object instead of a string. The nameFilter has to be manually pulled out using the index in selectedNameFilter.
If only one filter is supplied to nameFilters, the index will always be -1. I assume this is because we are not selecting the file type in the Dialog, it just defaults to the only item. The workaround I've written will work even if this behaviour changes. 
FileDialog now uses currentFolder instead of folder.
CURA-9214
> [CURA-9214] Can't export profiles, also fixes exporting materials

- resources/qml/PrintSetupTooltip.qml
The PrintSetupTooltip was catching events while invisible on the top left of the screen. This was causing the menubar not to be clickable.
I've disabled PrintSetupTooltip when not visible so that it does not catch events.
CURA-9232
> [CURA-9232] Fix menubar not catching events

- resources/qml/Menus/FileMenu.qml
This PR removes a "phantom menu" that is only accessible when navigating the File menu with the keyboard, by moving "between" the `Open Files...` and `Open Recent` options and pressing the right cursor key. In the screenshot below, note how there is no parent menuitem visible for the submenu that opened, and the submenu that opened is not the submenu for the `Open Recent` menu.
This PR solves a cosmetic issue, but the fix is fairly trivial.
> [5.0b1] Remove "phantom menu" when there is only a single FileProvider

- resources/qml/Menus/MaterialBrandMenu.qml
This fixes materials menu popups pushing down off the screen when many materials are installed. 
The popups will now push up when in the bottom half of the screen.
> [CURA-9185] Material menu cut off in menu

- plugins/PrepareStage/PrepareMenu.qml
- resources/qml/Account/UserOperations.qml
The drop-down to select where to open files from had a problem where the items inside had the necessary width to fit their text, but that left space if there were other items next to it.
This is now fixed. All items have their width adjusted to fit the width of the pop-up. The pop-up takes on the width of the widest item inside. The code is taken from UM.Menu and works similarly, but with a different width property.
Another issue was fixed where the buttons in the account profile menu weren't as wide as the parent, and the text was wider than the buttons. This made the hover area a bit weird. That's fixed by simply making the buttons as wide as their parent.
> Fix width of some drop-downs

- resources/qml/MachineSettings/NumericTextFieldWithUnit.qml
- resources/qml/Preferences/Materials/MaterialsView.qml
This PR fixes setting values on the Print Settings tab of the Materials pane of the preferences. Without this PR, changes will not be saved at all. This PR also disables the input fields on the Print Settings tab for "read-only" materials.
Fixes https://github.com/Ultimaker/Cura/issues/12155
> [5.0b1] Fix material "Print Settings" tab

- cura/CuraApplication.py
This was recently added. However it appears that we have the same path multiple times in the resources, leading to the resources being found twice. This would normally get removed by virtue of being a set, but not this time since it's a different way of writing the same path.
For the themes, it finds the following paths (in my unpacked directory): `{'/home/trin/tempy/cura5/UM/../share/uranium/resources/themes', '/home/trin/tempy/cura5/cura/../share/cura/resources/themes', '/home/trin/tempy/cura5/share/cura/resources/themes', '/home/trin/.local/share/cura/5.0/themes', '/home/trin/tempy/cura5/share/uranium/resources/themes'}` For both Cura and Uranium, this points to /home/trin/tempy/cura5/curanium/resources/themes twice. So let's remove this one.
Contributes to issue CURA-9147.
> Remove extra resource path from Python file

- resources/qml/TableView.qml
Problem was that the mouse events were not properly propagated to the underlying mouse area. Fixed by placing the MouseArea on top of the content (instead of under) and allowing the mouse events to propagate through the mouse area. This way we don't have to propagate the mouse event for each individual component that could be located within the ToolTipArea.
Also removed some logic where the properties of the Mouse area were exposed. However this was only used in one instance (as far as I could find) and in my opinion this was abusing the intended use of the ToolTipArea component. This last issue is simply fixed by adding an additional mouse area.
CURA-9219
> Fix for tooltip

- resources/qml/Cura.qml
This PR fixes the z-order of toolpanels and the placement of the toolbar when the toolbar becomes longer than the window permits (eg through multiple additional tool-plugins and/or many extruders).
Fixes #11990
> Fix toolbar positioning when the toolbar is taller than its parent

- resources/definitions/fdmprinter.def.json
Enabling this adds more control, possibly improving the productivity of the printer by allowing higher acceleration and jerk rates during travel moves where they have less of an impact.
Disabling this reduces the size of the g-code and the CPU requirements of the printer.
If these settings are disabled, travel moves will be printed using the acceleration and/or jerk of the first extruded move _after_ the string of travel moves. This is considered better than using the acceleration/jerk _before_ the travel, because if a travel move ends at a sensitive structure like the outer wall, it's good if the printer doesn't shake any more as it arrives there so that it doesn't shake when extruding. If it starts at a sensitive part the shaking of the fast travel move doesn't happen until after that …
> Add setting to no longer use different jerk/acc for travels

- cura/CuraApplication.py
This fix will stop enterprise versions from searching user config folder for non storage type resources.
Refer to SEC-253 for more information
SEC-253
> [SEC-253] [CURA-8964] resource preference injection 5.0.0

- cura/CuraPackageManager.py
- plugins/3MFWriter/ThreeMFWriter.py
- plugins/UFPWriter/UFPWriter.py
- plugins/XmlMaterialProfile/XmlMaterialProfile.py
I've added functionality for exporting information about packages used in enabled extruder stacks. This metadata is stored inside Metadata/packages.json inside .3mf files. 
Finding the package that owns a material from only the material container is a bit difficult since we only store the material source file name.  I've added getMaterialFilePackageId inside CuraPackageManager to solve this issue, please suggest some extra comments if it is not clear.
> [CURA-8610] Save package metadata

- cura/Machines/Models/IntentCategoryModel.py
- cura/Machines/Models/QualityManagementModel.py
- cura/Settings/MachineManager.py
Previously we would only accept intents that had a translation. If we could not find one, we would use "unknown" as the intent category. However, we didn't really do this consistently. In some places it would show unknown and in others we'd show the intent type.
This should make the behavior the same across the board. It will try to get a translation for the intent category and show that. If it's unable to find that it will use the category instead. Note that it will use the python title function to ensure it has nice capitalization
CURA-9297
> Use intent category if no translation is available

- resources/definitions/ultimaker.def.json
The reasoning of PP-86 also holds for the support interface layers, however we forgot about support when we implemented PP-86. When doing PP-108 we found this improvement.
> PP-86 reduce support interface flow

- cura/CuraPackageManager.py
- plugins/3MFWriter/ThreeMFWriter.py
Before this change packages were only being checked if they were bundled after loading the package_id. However only installed packages were being loaded so this would always be false.
The solution here is to check first if a material file is inside "secure_paths" (these are install directory resource paths). If it is, it must be a bundled material.
CURA-8610
> [CURA-8610] Fix warning when saving bundled packages

- resources/definitions/voron2_base.def.json
VORON V2.4 is an fast machine. There is no reason to limit
the user to 300mm/s. Unlock these speeds by removing maximum_value
which makes cura fallback to machine_max_feedrate_x/y which are
set to the C (299,792,458).
Also set the warning to 301 (As requested by Fulg) as
anything above 300 means beyond the "standarts".
> voron2_base.def.json: Do not limit travel speeds to 300mm/s

- plugins/3MFWriter/ThreeMFWriter.py
Add check for empty material instance containers before trying to fetch material metadata. This fixes failing to save a project on a printer with no materials (UM2 for example).
CURA-9412
> [CURA-9412] Project file saving fails on printers without materials

- cura/BuildVolume.py
We were previously both scaling down the buildplate and scaling up the disallowed areas of the models with shrinkage compensation. Doing both reduces the max usable area when scaling.
The solution is to do only one of these options.
Removing the disallowed area works fine when scaling models from their centre. However we scale 2 or more models from the buildplate centre rather than the model centre. This means that the models can go outside the buildplate without it being obvious from the visualisation.
The better solution is to remove the buildplate x/y scaling and keep the disallowed areas. This mean our preview can go above the max z shown in prepare, but this is the good solution without implementing 3d disallowed areas.
Removed shrinkage factor build volume scaling on x and y. This …
> [CURA-9271] Build plate shrinks when using horizontal scaling shrinkage compensation

- resources/qml/IconWithText.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedAdhesionSelector.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedInfillDensitySelector.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedPrintSetup.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedResolutionSelector.qml
- resources/qml/PrintSetupSelector/Recommended/RecommendedSupportSelector.qml
- resources/qml/Settings/SettingItem.qml
- resources/qml/Widgets/ComboBox.qml
The changes to the recommended settings menu are as follows
- Replaced resolution combobox yellow warning with two blue flashes of the combobox lining 
- Hovering over the text/icon or the checkbox will now show the tooltip
- Made the print settings reset button blue to match the recommended settings reset button
- Fixed the left alignment of the Resolution icon in recommended settings
> [CURA-8849] more intent fixes

- resources/qml/Dialogs/DiscardOrKeepProfileChangesDialog.qml
It's the same hack that we already use for the other instances where we use the tableModel.
For some reason it wasn't done here, so we also had the not updating bug
CURA-9270
> Add the "clear" hack to the tableModel for discardOrkeepchanges

- plugins/DigitalLibrary/src/DigitalFactoryProjectResponse.py
If the user that created a project has been deleted, the response from the API doesn't include a username. This crashes Cura because it had no default for the username.
The organization_shared field was also optional.
Done as a small fry to fix a bug found by a colleague.
> Fix crash if a Digital Library project is made by deleted user

- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
We had some issues when dragging dialogs between screens with different scale issues.
This issue was fixed by introducing `UM.Window` a python class that inherits from `QQuickWindow`, thereby exposing all available python methods. By intercepting the window's `moveEvent` and triggering an `update` the rendering issues seemed to be resolved on my machine.
Currently the fix is only applied to the preference dialogs and sync dialog windows. If the fix works for other devices as well we might want to update [the `Window` element in the default dialog object](https://github.com/Ultimaker/Uranium/blob/6bd71a153ffe8dbf397ace17874f62f96ad3e901/UM/Qt/qml/UM/Dialog.qml#L11) to an `UM.Window` as well. I decided not to do that in this PR as
1. it was a bit invasive; it didn't feel right to put …
> Fix rendering issues when moving dialogs between screen with different scale settings

- cura/ApplicationMetadata.py
- cura/CuraApplication.py
Add the information about the Conan managed dependencies to the log output
```
2022-07-15 17:40:41,437 - DEBUG - [MainThread] cura.CuraApplication.run [824]: Using Conan managed dependencies: arcus/5.1.0-beta+13@ultimaker/stable#e51ba5f9a7ad05441c0bfb4b12cd381bc85e2eff, protobuf/3.17.1#d4970b86fb1d8cbce961e2624834a0bc, zlib/1.2.12#3b9e037ae1c615d045a06c67d88491ae, cpython/3.10.4#4adc4633d487e404c356abf3933fd19d, openssl/1.1.1l#de73a8aad9d5a14da8ed43b40592195a, expat/2.4.1#a36c94ae11100f2e3259a9edd4f77055, libffi/3.2.1#33b3eff20f1be5d569235ae100266729, mpdecimal/2.5.0#d8aaabf46cfa93efaadfe66733885102, libuuid/1.0.3#42d244923e46f0a22bdafd1978cc4109, libxcrypt/4.4.25#a6ab0080853010bf96ed0b9539412e7b, bzip2/1.0.8#b056f852bd2d5af96fc7171aadfd6c0b, gdbm/1.19#c420bc00f3cc629aef665fdc3100f926, …
```
> CURA 9365 add conan info to log

- resources/definitions/creality_ender3s1.def.json
- resources/variants/creality_ender3s1_0.2.inst.cfg
- resources/variants/creality_ender3s1_0.3.inst.cfg
- resources/variants/creality_ender3s1_0.4.inst.cfg
- resources/variants/creality_ender3s1_0.5.inst.cfg
- resources/variants/creality_ender3s1_0.6.inst.cfg
- resources/variants/creality_ender3s1_0.8.inst.cfg
- resources/variants/creality_ender3s1_1.0.inst.cfg
This adds a machine profile for the Ender 3 S1 as requested in #11512. I ported the settings from Creality Cura and made up-to-date Cura printer profiles.
> Add Creality Ender 3 S1 profile - fixes #11512

- resources/definitions/creality_ender3.def.json
Since the Ender 3 v2 is the same hardware profile as the Ender 3, make it clear in the profile name.
> Rename Ender-3 profile to include v2

- resources/definitions/ultimaker.def.json
Fixed issue with tree support having an infill density set to 15%. Now it is set to 0%.
Relates to CURA-9520
> CURA-9520_Fix_support_infill_tree_support

- cura/UI/PrintInformation.py
- plugins/CuraEngineBackend/Cura.proto
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/SliceInfoPlugin/SliceInfo.py
- plugins/SliceInfoPlugin/example_data.html
Add an UUID to the slice info data. This UUID is generated by CuraEngine and send via Arcus to the front-end
See also the PR on the CuraEngine side
> Cura 9031 add slice id to griffin gcode header

- resources/definitions/ultimaker.def.json
Lower the value of the warning color for the children of support_infill_rate when selecting tree support
See comment made by @Vandrasc in ticket CURA-9520 PPM: Tree support has infill density 15%, but should have 0%
> Don't show warning color for children of support_infill_rate when using tree support

- cura/API/Account.py
- cura/PrinterOutput/Models/PrintJobOutputModel.py
- plugins/DigitalLibrary/src/DigitalFactoryApiClient.py
- plugins/UM3NetworkPrinting/resources/qml/MonitorContextMenu.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorQueue.qml
- plugins/UM3NetworkPrinting/resources/qml/MonitorStage.qml
- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDevice.py
- plugins/UM3NetworkPrinting/src/UltimakerNetworkedPrinterOutputDevice.py
- resources/qml/ApplicationSwitcher/ApplicationSwitcherPopup.qml
- resources/qml/Preferences/Materials/MaterialsSyncDialog.qml
- tests/API/TestAccount.py
Like Animal Farm taught us, some accounts have more access than others. For instance, they may be able to change print jobs only for their own jobs, not for others. Or they may be unable to read the print queue at all. This pull request is intended to hide buttons that would do things that the user doesn't have permission to do anyway.
It adds a request to the sync that requests the user's permissions. This list of permissions gets stored in the account and can be accessed via the Cura API, even from within QML.
Using this new property, the following changes are made:
* The print queue is hidden in the monitor page if the user can't read the print jobs.
* The "move to top" function is hidden if the user can't change other people's print jobs.
* The "pause" function is hidden if the user …
> Hide cloud interaction buttons if the user has no permissions to them

- cura/Arranging/ShapeArray.py
- plugins/X3DReader/X3DReader.py
This is advocated by both PEP8 and the Google Python Style Guide
> Use is not operator rather than not ... is

- docs/repositories.md
Reformatting of documentation file: repositories.md
- the name of each repo is now at the beginning of the section that describes what it does.
- the text that describes what each repo does is broken up into lists. This is easier to read and understand.
- a few grammatical improvements.
> repositories.md: reformat to aid reading

- resources/qml/PrintSetupSelector/Recommended/RecommendedInfillDensitySelector.qml
When changing to an intent with infillDensity > 100 in recommended settings the RecommendedInfillDensitySelector would set infillDensity=100.
This is because the onValueChanged function checks if the slider has a different value from the settings and updates the settings if it does. The slider has a max value of 100, so when setting the sliders value to 1000 the slider would update to have a value of 100. This would then update the setting to value to 100.
The fix is as follows. When updating the slider value > 100 just ignore the first onValueChanged. Following onValueChanged, which are triggered by the user sliding the slider, will still trigger.
CURA-9488
> [CURA-9488] Fix infill density being set incorrectly when changing intent

- cura/Machines/MachineErrorChecker.py
This simplifies understanding the class `__init__` function
> MachineErrorChecker.py: Move _error_check_timer initialization to a separate function

- docs/profiles/setting_properties.md
- Reformat the text to make it easier to read and understand by breaking up the descriptions into separate lines.
- Use italics to emphasize "not used by Cura"
- A few grammatical corrections
> setting_properties.md: Reformat text and corrections

- cura/Scene/CuraSceneController.py
- Correct log message (we want to log the "select**ed**" build plate)
- Use f-string and debug method for Logger instead of "Old Style" string formatting.
> CuraSceneController.py : Fix problem with log message and use f-string

- cura/Settings/MachineManager.py
- plugins/MonitorStage/MonitorMain.qml
If an abstract, but cloud connected printer is chosen to monitor, send the user to digital factory instead. (Since we don't know which printer they want, since all we have is a type.)
> [CURA-9422] 'Monitor page' for abstract printer types

- resources/definitions/fdmprinter.def.json
This PR automatically enables Remove All Holes when Spiralize Outer Contour is enabled.
Vase mode is meant for models which are solid, but many people don't know and model their things hollow.
With this automatic setting change these people won't notice that they have modeled it wrong.
Which means there are less times I need to explain stuff to users.
Profit.
> automatically remove all holes when spiralizing

- resources/definitions/fdmprinter.def.json
New setting to limit the width of the base of tree support.
I was trying to optimize the hell out of one print and I figured that this setting might help.
> setting for support_tree_max_diameter

- resources/definitions/kingroon_base.def.json
Kingroon's KP3/KP3S print range is 180x180x180, but the current End G-Code contains a code that moves to Y 200 or Y 300.
As a result, after printing, an error occurs due to a move outside the range.
I have created a small fix code.
Please merge if it is OK.
Thank you.
_Before Fix_
_After Fix_
.
> Prevents the head from moving outside the print area

- cura/LayerPolygon.py
- Shortened excessively long lines: some lines in the file were excessively long, even in the context of the Cura project which seems to prefer a long line length.
These lines could not be read easily even on github .... 
- Removed some unnecessary whitespaces
- Added some extra spaces so that inline comments are separated by at least two spaces from the statement
> LayerPolygon.py: Shorten excessively long lines

- cura/Machines/MachineErrorChecker.py
We want the Logger in line 215 to give the execution time in seconds
so we don't want the start time to be the epoch.
Currently the logger will output something like
time = 1659518458.5s
not like
time = 3.0s
> Fix Bug in timing MachineErrorChecker execution

- cura/Machines/MachineErrorChecker.py
Use one line conditional assignement instead of if else block.
The intent is now clearer and the code is easier to read.
> MachineErrorChecker.py: Use one line conditional assignment

- cura/LayerPolygon.py
First commit improved the iteration using enumerate.
Second commit uses np.where() instead to improve clarity of intent.
> LayerPolygon.py: Refactor check for unknown line types

- resources/definitions/fdmprinter.def.json
- resources/definitions/ultimaker.def.json
Enable monotonic roofing only when roofing_layer_count is > 0 otherwise enable monotonic ordering for all skin layers (skin_monotonic).
Relates to PP-232
> Only enable monotonic ordering for the roof layer

- plugins/USBPrinting/USBPrinterOutputDevice.py
PrintJobOutputModel.py requires timeElapsed be an int.  USBPrinterOutputDevice.py sets it to a float instead, which causes PILES of exception windows to open up, though Cura does not crash and the print continues fine (albeit displaying some nonsense values for percentage done, etc).  Simple fix.
> USBPrinterOutputDevice.py: Convert estimated time to int

- cura/Settings/CuraStackBuilder.py
- plugins/GCodeWriter/GCodeWriter.py
- plugins/UFPWriter/UFPWriter.py
Add settings to ufp files so that changes in settings can be reviewed on Digital Factory.
> [CURA-9224] Approver settings json

- requirements.txt
Seems networkx itself is low on dependencies itself. It does require some optional ones for e.g. it's linalg sub-package, but those are numpy and scipy, which we already have.
> [CURA-9535] Some trimesh operations require networkx

- resources/definitions/fdmprinter.def.json
- resources/definitions/ultimaker.def.json
Enable bridging settings for all Ultimaker machines.
Set bridge wall speed to equal to the skin speed such that all speeds around a bridge are approx. the same.
The minimum bridge wall length was changed to a length long enough to prevent switching of settings over small unsupported areas (e.g. X/Y distance). This was changed in fdmprinters.def.json
Relates to PP-195
> PP-195_Improve_bridging

- resources/definitions/fdmprinter.def.json
- resources/definitions/ultimaker.def.json
Move conical support out of experimental and under the support category.
Enabled conical support by default for ultimaker profiles and increased min. width to 10mm.
Relates to PP-230 and CURA-6710
> Pp 230 enable conical support

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
Duplicate print jobs were being sent when printing via cloud from abstract printers.
This was due to the connect function not being called on the CloudOutputDevice used to print on the cloud. This function is only called when it becomes an active printer (AbstractCloudOutputDevice is the active printer instead now).
The fix is to always listen for signals to reset the print job even when not the active printer.
I've chosen different signals now so there is not too much spam on the reset function.
The BackendStateDone signal catches new slices. The SceneChanged signal catches ufp files being loaded (These do not trigger BackendState changes)
CURA-9678
> [CURA-9678] Duplicate print jobs sent to cloud

- .github/workflows/conan-package.yml
- .github/workflows/unit-test.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- cura/MachineAction.py
- resources/qml/Preferences/MachinesPage.qml
[Added machine action buttons dynamic visibility](https://github.com/Ultimaker/Cura/commit/ed14e3bd44890ff15406f7f53c7199f3fa6018e6)
Based on this change, users now will be able to manage the visibility of their machine action plugin implementations. For example, a machine action only visible when loggedIn.
[Added machine action dialog optional](https://github.com/Ultimaker/Cura/commit/75840426d735ddc421b594e6fa2378ed03ad2364)
Based on this change, users will be able to run their machine action plugins code just by clicking the action button, so without having to open a modal.
> Machine Actions improvement

- plugins/UFPWriter/UFPWriter.py
PR #13209 adds the modified settings to the UFP exports. The settings are serialized as JSON but doesn't handles the SettingFunctions. This was also reported by users in emtrax-ltd/Cura2MoonrakerPlugin#55.
**Reproduction steps:**: Modify a setting with a computed default, then click the ![image](https://user-images.githubusercontent.com/3748582/193446731-ef31b235-14be-4d9a-a46b-27fb8fa76196.png) icon. Slice and save the result as a .ufp file. Cura will crash with:
```
File "Cura/cura/CuraApplication.py", line 1127, in event
return super().event(event)
File "Uranium/UM/Qt/QtApplication.py", line 502, in event
event._function_event.call()
File "Uranium/UM/Event.py", line 218, in call
self._function(*self._args, **self._kwargs)
File …
```
> UFPWriter: fix serialization of SettingFunctions

- plugins/3MFReader/ThreeMFWorkspaceReader.py
3mf project files saved with an abstract printer would crash on loading when selecting a non abstract printer to load the project with.
This was because the metadata "is_abstract_machine" was being loaded into the non abstract machine. This caused a crash in MachineListModel.py by trying to delete this non abstract machine from a list where it didn't exist.
The solution is to ignore the "is_abstract_machine" metadata when loading settings from saved machines in 3mf files.
CURA-9714
> [CURA-9714] Crash loading abstract machine 3mf

- packaging/NSIS/Ultimaker-Cura.nsi.jinja
So that uninstall is properly linked in the 'programs and features' again.
If you have a deja-vu: The line went from HKCU -> HKCR -> HKLM. The previous assumption that HKCR would take care of both HKCU _and_ HKLM behaviour is not correct. And anyway, we want installs to work for the whole local machine; the user (can) log(s) in afterwards in Cura itself.
Uninstaller works, we'll just have to deal with the users who'd expect the registry keys to the same place one more time, and then we're (hopefully) done.
> [CURA-9696] Fix windows uninstall.

- cura/Settings/MachineManager.py
…uders while the current global stack also has no extruders.
This was caused by trying to compare "extruders_enabled_count" which was None with an integer.
CURA-9714
> [CURA-9714] Crash double 3mf that contains printer with no extruders

- packaging/NSIS/Ultimaker-Cura.nsi.jinja
This should ensure that updating a patch doesn't override the uninstaller in the settings->Installed apps
Fixes: #13337
CURA-9670 Correct the version number in the uninstaller
> Fix correct version number in uninstaller for patch releases

- resources/qml/Preferences/Materials/MaterialsSlot.qml
It can take the space of the favourite button then. Also made the margin on the left a little smaller.
Currently the list of materials is quite hard to read:
With this change, it's a little better:
If a material is favourited (or hovered to show the favourite button) then it does become shorter again to make space for that button:
> Allow text to be wider if favourite button is not shown

- conanfile.py
The conan package from the internal package wasn't deployed, added the logic for the second list item
> Fix internal data plugins deployment

- CITATION.cff
Hey there!
This is just a simple update to the `CITATION.cff` file, to update it to the latest version of Cura and clean up formatting and keywords.
- As you can verify by browsing to the PR branch, all changes are correctly reflected in the sidebar of the repo.
- All changes have been successfully validated with [cffconvert](https://pypi.org/project/cffconvert/). See output below:
In the future, I will keep this updated with new releases of both Cura and `.cff` since it's fairly easy for me to test and deploy.
Going forward, we might consider a simple [GitHub action for validation](https://github.com/citation-file-format/cffconvert-github-action) and a pre-release hook that bumps the version in CITATION.cff, but it's not really urgent atm since it takes all of 10 minutes for me to set up …
> Update CITATION.cff to 5.2.1

- resources/definitions/fdmprinter.def.json
Frontend PR exposing the ability to set some more of the settings (retract) on a per object (or per model) basis.
Backend PR: https://github.com/Ultimaker/CuraEngine/pull/1769
> [CURA-9876] Expose per-model retraction settings.

- resources/definitions/ultimaker.def.json
For large prints the initial layer skin flow turns out to be too low. PP-275
> PP-275-increase-initial-layer-skin-flow

- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFReader/WorkspaceDialog.qml
Fix loading files with unknown printers. The default is now to select another printer of the same type first (Abstract printer if possible). If there are no printers of the same type it will default to creating a new printer. 
CURA-9424
> [CURA-9424] Fix loading files

- resources/definitions/ultimaker.def.json
The frontend should compensate for that: Do _not_ apply the formula, as this now happens implicitly.
See also backend: https://github.com/Ultimaker/CuraEngine/pull/1765
> [CURA-9548] The engine now operates on the area _before_ the offset.

- resources/definitions/ultimaker.def.json
The zigzag pattern gives a nicer model surface compared to the concentric pattern. With CURA-9350 merged it will also automatically put a wall around the zigzag support interface.
Relates to PP-183 and CURA-9945
> PP-183 Enable zigzag support interface

- printer-linter/README.md
Updated the README to clarify that Cura defintion files should be their relative paths from the root of the project; I just realized by doing #13967 that running it with an invalid file path yields an empty result instead of an error (although that is a separate issue from this PR):
```shell
XXX@pop-os:~/DEV/Cura$ python3 printer-linter/src/terminal.py "path/to/nowhere" --format --fix
Diagnostics: []
```
> Clarify linter steps for running locally

- printer-linter/src/terminal.py
This PR prevents silent failure with empty diagnostics if an invalid file path was provided. Fixes behavior described in #13968
> printer-linter: exit on invalid definition file paths

- resources/definitions/creality_cr10spro.def.json
Hello,
This is one of the first things I was being told from the community in regards to using cura with the CR-10S Pro. The current start gcode snippet actually does not save and use the mesh after creating it. I hope this change will improve a lot of users' experiences.
> Actually make CR-10S Pro use the mesh it just measured

- resources/qml/Menus/MaterialBrandMenu.qml
- resources/qml/Menus/MaterialBrandSubMenu.qml
This PR fixes two issues. 
1.  The material popups were not overlapping the brand popup. The lining of both were visible. This overlaps them slighly so we only see a single lining width.
2.  The materials list being too wide by one scrollbar width when opened for the first time. When opening the materials list the size of the popup is adjusted, this causes the scrollbar to disappear. For some reason this does not update the width/implicitWidth of the popup even though it is defined based using the scrollbar width. The fix here is to force the width adjustments in the onOpened function.
> [CURA-9522] Material list styled oddly 

- packaging/AppImage/AppRun
I wanted to run `CuraEngine` from within the AppImage. Since `AppRun` only executes `Ultimaker-Cura`, I modified it to use AppImage's `ARGV0` environment variable to allow users to select the executable to run.
The use, download the AppImage as usual and create a symlink:
```
ln -s Ultimaker-Cura-5.0.0-Linux.AppImage CuraEngine.AppImage
```
Now, running `CuraEngine.AppImage` will launch `CuraEngine` instead of `Ultimaker-Cura`
If the name of the AppImage does not match a file inside the AppImage, `Ultimaker-Cura` will run by default.
> Use ARGV0 to select the executable to execute from AppRun. Intended to run CuraEngine

- resources/definitions/fdmprinter.def.json
CURA-10047
Disable fuzzy skin when using interlocking. Using these settings together causes the interlocking structure walls to be fuzzy (These are inside model)
> [CURA-10047] Disable fuzzy skin when using interlocking.

- resources/setting_visibility/advanced.cfg
- resources/setting_visibility/expert.cfg
Have Interlocking visible in Advanced, but the sub-settings in Expert Setting Visibility
> [CURA-10168] Add Interlocking to settings visibility

- .gitignore
- plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
In the script ```PauseAtHeight.py``` there are two places where the user can add gcode that will be executed either before or after the actual pause command is executed.
I simply added a regex search and replace to those variables in the script so that the user can optionally add more than one gcode command in those text boxes by separating them with a comma. The script will replace the comma with a linefeed ```\n``` wherever a comma exists in the text box. It will also remove any white space around the comma, which will yield cleaner code in the final output.
I have tested this change and it works perfectly.
> Added ability to have multiple gcode commands before and after paused print job

- resources/i18n/ja_JP/cura.po
Fixes Typo with extensions mentioned here: https://github.com/Ultimaker/Cura/issues/14290
Bug fix (non-breaking change which fixes an issue)
I checked the translation files of mentions of 拡張子 and changed them
Windows 11
Changed with Github Desktop and Notepad++
> [CURA-10167] - Fix Typo in Japanese mention of Extensions

- resources/qml/ExtruderButton.qml
Switching support extruder while a model is selected also changes the models extruder. This is a fix for that issue. 
> [CURA-10233] switching support extruder switches model extruder

- plugins/GCodeReader/FlavorParser.py
CURA-10183
Loading gcode from machine with more extruders than the current machine would cause a crash.
Catch error when loading gcode with more extruders than the current machine
> [CURA-10183] Catch error when loading gcode with more extruders than the current machine

- requirements.txt
Fixes compilation in MacOS by adding a hash of `PyQt6-NetworkAuth-Qt6==6.2.4` to `requirements.txt`.
Fixes issue https://github.com/Ultimaker/Cura/issues/14504.
Successfully built and ran Cura.
* Operating System: MacOS Monterrey
> Add hash for PyQt6-NetworkAuth-Qt6

- .github/workflows/cura-installer.yml
Packages conflict. The same commit worked fine the previous day, so it's likely not our fault. We should probably inform maintainers, but until then, try to work around the problem without a blanket ignore of all 'overwrite' type errors. The only clear thing is that this all has to do with 'odbc', which is database related. We use that to cache certain things on start-up, so likely we actually need it.
> [CURA-10290] workaround for conflicting packages on 'linux-modern'

- .github/workflows/printer-linter-format.yml
- .github/workflows/printer-linter-pr-diagnose.yml
The clean-up step for setting up Python and pip assumes that you do at least something with those programs -- and so that cache folders have been made, that need to be cleaned up. If nothing happens, the clean-up step then crashes on the non-existent cache folder.
> Prevent execution of spurious clean-up step, which then crashes.

- plugins/GCodeReader/FlavorParser.py
Add a try catch around fetching material diameter. This stops crashes when G-Code with more extruders than the active machine is loaded. 
> [CURA-10183] Fix G-Code reader crash

- resources/i18n/pt_BR/cura.po
- resources/i18n/pt_BR/fdmprinter.def.json.po
This updates the strings for Brazilian Portuguese internationalization.
Replaced the strings file locally with my installation of cura
* Operating System: Linux
> Updated strings for pt_BR

- resources/definitions/vzbot_base.def.json
The correct value should be -03 not 0.3 Should actually still in the 5.3. Maybe it works out.
Fix
> [5.3] Fix VzBot Base definition file

- resources/qml/PrinterOutput/HeatedBedBox.qml
The fix rounds heated bed temperature values when printer sends them with decimal digits.  Same roundings already exist on the extruder temperatures (see ExtruderBox.qml line 50 and 85)
Very stupid fix.
* Operating System: indows 10 22H2
> Fix decimals on heated bed temperature monitor (HeatedBedBox.qml)

- resources/definitions/creality_ender3s1.def.json
- resources/definitions/creality_ender3s1plus.def.json
- resources/definitions/creality_ender3s1pro.def.json
- resources/variants/creality/creality_ender3s1pro_0.2.inst.cfg
- resources/variants/creality/creality_ender3s1pro_0.3.inst.cfg
- resources/variants/creality/creality_ender3s1pro_0.5.inst.cfg
- resources/variants/creality/creality_ender3s1pro_0.6.inst.cfg
- resources/variants/creality/creality_ender3s1pro_0.8.inst.cfg
- resources/variants/creality/creality_ender3s1pro_1.0.inst.cfg
Make the 3 Ender 3 S1 profiles more consistent with each other as well as defining the missing variants for the pro model.
Tested configuration on my Ender 3 S1 pro by printing multiple items.
> Make Creality Ender 3 S1 consistent

- resources/definitions/fdmprinter.def.json
Done because there where situations (when support interface was set to 'off' and there is a small spike hanging downwards for example), that the support could go around the model rather than actually supporting it. -- The old (now '1.0'/'classic') tree support had horizontal expansion disabled as well. Since you can set both the tip-diameter, the expansion-rate and several other related settings for tree support 2.0, its disablement shouldn't be a great loss even so.
> [CURA-10472] Disable horizontal expansion when using tree-support.

- resources/definitions/kingroon_kp3s_pro.def.json
This adds the KP3S Pro using the KP3S base definition. It is slightly larger than the KP3S, with a 200x200x200 build area.
* Operating System: Windows 10
> Add Kingroon KP3S Pro Printer

- resources/definitions/fdmprinter.def.json
We're not sure why this introduces a boatload of small segments into the infill, and we're out of time to try and fix this before the beta. Re-introducing after the beta seems like a bad idea, so this'll have to wait until 5.5 unfortunately.
Done as part of fixing for CURA-10500, but for the original Small Skin Area feature, see CURA-10201. For the ticket to (fix? and) reintroduce the feature, see CURA-10670.
> [CURA-10500] Disable Small Skin Area feature for now :-/

- cura/CuraApplication.py
- cura/Settings/CuraFormulaFunctions.py
- docs/profiles/getting_a_setting_value.md
- resources/definitions/fdmprinter.def.json
Add settings-function to get an extruder based on a property.
We wanted to select an extruder based on whether or not it has support-material, so that the user doesn't have to think about selecting a support extruder any more and in most cases, can't forget anymore either. The formula present in fdmprinter to do that was not only an unreadable nightmare, but also very slow. We decided to pull most of that functionality into the settings-function machinery instead (but just a bit more generic so other properties can be selected, not just 'material_is_support_material').
__update__: We're not going to actually _use_ this in 5.4 yet, due to it not being optimized yet and slowing down the UI too much.
> [CURA-10643] filter extruder by material prop

- resources/qml/ActionPanel/PrintJobInformation.qml
@Diegovd addressed in https://github.com/Ultimaker/Cura/issues/12270 that the currency in the Material Estimation Box is too small to reflect all the currencies. This is the proposed improvement. 
Tested a number of currencies to see if they fit
Operating System:
Windows 11
Cura 5.4
> Increase Boxes for Printjob Information

- resources/setting_visibility/basic.cfg
We show this setting in the recommended mode, but users could not find it in custom because they had basic visibility. 
Windows 11
Cura 5.4
> Add Support Structure to Basic

- plugins/PostProcessingPlugin/PostProcessingPlugin.py
- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- plugins/PostProcessingPlugin/Script.py
- plugins/PostProcessingPlugin/scripts/ChangeAtZ.py
- plugins/PostProcessingPlugin/scripts/ColorMix.py
- plugins/PostProcessingPlugin/scripts/FilamentChange.py
- plugins/PostProcessingPlugin/scripts/RetractContinue.py
- plugins/PostProcessingPlugin/scripts/SearchAndReplace.py
- plugins/PostProcessingPlugin/scripts/Stretch.py
These seem to be wrong by accident. Let's update them to reflect the rest of Cura which falls under the LGPLv3 or higher.
This resolves CURA-10814 and https://github.com/Ultimaker/Cura/issues/15731
> Fix wrong licenses

- cura/Machines/Models/IntentSelectionModel.py
- cura/Settings/CuraContainerStack.py
The issue was that sometimes intents are also shared. This would only cause issues for material profiles from the marketplace that have intents. 
CURA-10788
> Let intent selection use the quality_definition instead of direct def

- resources/qml/Cura.qml
Previously we used the qdialog enum, which isn't the one you should use for the qml dialog.
CURA-10741
> Use correct value for multiple file open enum

- resources/README.md
- resources/definitions/entina_tina2.def.json
- resources/definitions/entina_tina2s.def.json
- resources/definitions/weedo_base.def.json
- resources/definitions/weedo_tina2.def.json
- resources/definitions/weedo_tina2s.def.json
- resources/definitions/weefun_tina2s.def.json
- resources/extruders/weedo_base_extruder_0.def.json
This PR adds configs for the following printers.
- Weedo Tina2
- Weedo Tina2s
- Entina Tina2
- Entina Tina2s
The configurations came from Entina's prepackaged Cura installer.
Additional printer support.
This has been tested on version 5.3.1 with benchy using PLA+. I've also been printing custom parts with this config over the past week with no issues related to the config.
* Operating System: Windows 11 Pro Version 22H2, build 22521.1848
> add tina2 support

- cura/BackendPlugin.py
- cura/CuraApplication.py
This will make very little sense without taking a look at: https://github.com/Ultimaker/Uranium/pull/890
> [CURA-10722] backend plugins are always (potential) additional setting definition providers

- cura/CuraApplication.py
Cuz ya know. If you don't set the data before checking, you will have a baaaad time.
See also: https://github.com/Ultimaker/Uranium/pull/891
Remove a plugin that is marked as required, check the logs. 
> Move the required plugins list to before it's actually checked

- resources/definitions/elegoo_base.def.json
Change `minimum support area` to be 0 when tree supports are used. This should prevent confusion like https://www.reddit.com/r/Cura/comments/15ggbuj/cura_54_not_generating_tree_supports/
- Printer definition file(s)
> Change minimum support area to be 0 when tree supports are used (Elegoo profile)

- plugins/PostProcessingPlugin/PostProcessingPlugin.py
- plugins/PostProcessingPlugin/PostProcessingPlugin.qml
- plugins/PostProcessingPlugin/Script.py
- plugins/PostProcessingPlugin/scripts/ChangeAtZ.py
- plugins/PostProcessingPlugin/scripts/ColorMix.py
- plugins/PostProcessingPlugin/scripts/FilamentChange.py
- plugins/PostProcessingPlugin/scripts/RetractContinue.py
- plugins/PostProcessingPlugin/scripts/SearchAndReplace.py
- plugins/PostProcessingPlugin/scripts/Stretch.py
As discussed in https://github.com/Ultimaker/Cura/issues/15731, we should align these licenses under the LGPLv3 because they fall under the Cura umbrella.
This is part of CURA-10814
> Align Licenses to LGPLv3

- plugins/RemovableDriveOutputDevice/RemovableDriveOutputDevice.py
The file exported on USB storage is now removed after the export in case an error occured.
I couldn't resist to clean the _onFinished method because it had a duplicate error handling, including one for which I'm failing to see how it could be reached (and could even possibly lead to a dirty situation). If this was necessary somehow, advise me and I will make the according revert.
> CURA-10180-warning_out_of_space

- cura/Scene/ConvexHullDecorator.py
- resources/definitions/tizyx_evy.def.json
- resources/definitions/tizyx_evy_dual.def.json
- resources/definitions/tizyx_k25.def.json
Call to _add2DAdhesionMargin is moved to a lower method so that it is always called when appropriate.
This should not cause side-effects, or at least only for one-at-a-time mode which is tagged as experimental.
> CURA-10307_expand-one-at-a-time-shadow

- plugins/USBPrinting/AutoDetectBaudJob.py
I Removed the ISP leaving part from serial communication, which is **probably** unnecessary 99.99% of the times but may cause a hang when some USB devices are connected.
However, this may have side-effects in situations that I'm not aware of. IMHO, it may be useful after a failed firmware update, so that we can still detect the printer and retry the firmware update. But that may be workarounded by forcing the firmware update ? Maybe these cases would need testing.
Tested with UM S2 and Creality Ender 3 : detection still works as expected.
> Fix possible hang at startup/add printer

- cura/BackendPlugin.py
- plugins/CuraEngineBackend/CuraEngineBackend.py
> Find available port when starting backend plugin

- cura/BackendPlugin.py
Add backend specific logging, should help with debugging. It will create a log file for each services started in which it pipes the output to a unique file.
[CuraEngineGradualFlow.log](https://github.com/Ultimaker/Cura/files/12673168/CuraEngineGradualFlow.log)
> Cura 11064 plugin specific log files

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/advanced.cfg
- resources/setting_visibility/expert.cfg
This pr add a setting to the front end to group walls.
Backend-PR: https://github.com/Ultimaker/CuraEngine/pull/1958
Ran from source
MacOS
CURA-11082
> Add setting to group outer walls

- resources/qml/PrintSetupSelector/Recommended/RecommendedPrintSetup.qml
CURA-11051
This is most likely a bug in QT, however since it hard to debug/fix QT I propose this PR as a workaround instead. When changing printer/material/nozzle configuration sometimes the content of the recommended mode would change. As the content height of the recommended mode element would change the scroll bar would sometimes appear/disappear. When a scrollbar is visible the width of the recommended mode would change due to the additional space needed for the scrollbar. Some QT items in this page didn't like this and as a result cura would crash (most likely a crash in QT). As a work-around I propose to always leave space for the scroll bar whether is is visible or not. In my opinion it doesn't look bad, and it doesn't crash cura.
Running from source, crash doesn't happen anymore. …
> Fix cura recommended mode crashing

- cura/Settings/cura_empty_instance_containers.py
CURA-11089
Within some conditions, Cura crashes when adding some specific printers, because they use an "empty" material which has no brand reference, and we try to access it.
> Fix crash when adding some printers

- .github/workflows/installers.yml
- .github/workflows/linux.yml
- packaging/AppImage-builder/create_appimage.py
The asc was created for the AppImage, but never uploaded as an artifact. **Merge to `5.5` and then merge `5.5` to `main`**. Since we will use the GH action from main to build the 5.5.0-beta.1 release
Fixes CURA-11087
* Operating System: Linux
> Fix missing asc file in Linux build artifacts

- plugins/PostProcessingPlugin/scripts/CreateThumbnail.py
All slicers I have tried uses an "x" instead of space in between width and height.
Also DWC (Duet web control) can't view thumbnails without the "x" character.
> Fix thumbnail format

- tests/Settings/TestCuraContainerRegistry.py
We're changing the validation function of metadata for containers to require the type and name parameters. That needs to be reflected in the tests.
Contributes to issue CURA-3Z4.
While this PR could be merged on its own without damage, it's only necessary when https://github.com/Ultimaker/Uranium/pull/830 is merged.
> Update tests with new required metadata fields

- cura/UI/ObjectsModel.py
This is a minor change that fixes a `DeprecationWarning: invalid escape sequence '\('` by compiling the regex pattern as a raw `str` (i.e., preceded by an `r`)
Extensive testing not performed&mdash;should not be necessary.
> Fix non-raw RegEx pattern string

- cura/Settings/CuraFormulaFunctions.py
CURA-11048
This code is an additional check if the enums are named starting with a Capital alphabet in the intent file.
Only check for support type and adhesion type
> Cura 11048 unclear support type

- cura/PrinterOutput/NetworkMJPGImage.py
- plugins/UM3NetworkPrinting/resources/qml/PrinterVideoStream.qml
Fix memory leak issues in monitor page. Issue was that QT (incorrectly?) asserted that there was a binding loop between width and height in the `NetworkMJPGImage` component. This caused the height to evalualte to `infinity`, making QT create a buffer with an infinite amount of memory. Solved by calculating a serpeate `img_scale_factor` which both the width and height uses.
CURA-11180
Yes
* macos arm64
> Fix memory leak issues in monitor page

- packaging/AppImage-builder/AppImageBuilder.yml.jinja
Make sure that all relevant icons and pix-buf libs are packaged. Tested in on Manjaro, Mint 20.4, Debian and  Ubuntu
By running this build on various systems: [UltiMaker-Cura-5.6.0-alpha+cura_11132_dd2a80-linux-X64-AppImage](https://github.com/Ultimaker/Cura/suites/17531272304/artifacts/1001529737)
* Operating System: Linux see above
> CURA 11132 fix missing icon crash

- cura/Settings/MachineManager.py
- plugins/3MFReader/ThreeMFWorkspaceReader.py
- plugins/3MFReader/WorkspaceDialog.py
This PR solves the bug where the intent does not correctly change when loading a project file that was saved using the "default" ("balanced") profile.
Yes
mac os arm64
> Fix bug loading intents

- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
Simply add a setting to allow for a different line spacing for the raft of the prime tower's first layer, because in some situations we want extra adhesion for it as it has a low footprint but can get very tall.
This goes along with https://github.com/Ultimaker/CuraEngine/pull/1974
CURA-11233
> Add setting for specific prime tower raft line spacing

- packaging/MacOS/build_macos.py
Mac's `altool` is being deprecated. New signing tool provided by apple is `notarytool`. This PR replaces `altool` for `notarytool`.
see: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3
Ran github action and checked if the builds were correctly signed
mac os arm
CURA-9929
> Replace altool for notary tool

- resources/qml/Menus/MaterialMenu.qml
Grey-out generic menu if no options are available
CURA-11266
yes
* Operating System: macOS
> Grey out menu if no items are present

- cura/PreviewPass.py
- cura/Snapshot.py
This PR makes it possible to take snapshots of single scene nodes.
_Written as a non breaking api change, as only a node is added_
Ran from source
> Add `node` as an optional argument to `isometricSnapshot`

- resources/definitions/fdmprinter.def.json
- resources/quality/ultimaker_s3/um_s3_aa0.8_um-petg_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_um-petg_0.2mm.inst.cfg
Increase flow during bridging to prevent stretching and breaking the thread.  
At 0.2 layer height with an AA 0.8 core, the top surface had a lot of pillowing with PETG, caused by bad bridging on top of the infill. By setting the flow multiplier to 200% during bridging, the thread is laid down with without stretching it.
> Set bridging flow to 200 for PETG AA08 02

- resources/quality/ultimaker_s3/um_s3_aa0.8_um-abs_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_um-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s3/um_s3_aa0.8_um-tough-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_um-abs_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_um-pla_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_aa0.8_um-tough-pla_0.2mm.inst.cfg
Apply the same fix from PETG to PLA, TPLA, ABS to solve prints having a rough surface in certain circumstances.
All profiles have been validated to fix the issue, and still have good bridging in traditional bridge structures.
> Increase bridging flowrate on AA 0.8 at 0.2 layers

- plugins/MachineSettingsAction/MachineSettingsExtruderTab.qml
- resources/definitions/fdmextruder.def.json
This PR adds the following settings
- Extruder start gcode duration
- Extruder end gcode duration
By entering a duration (expressed in seconds) for this setting the amount of time is added to the time estimation for a nozzle switch. This makes it possible to more accurately tune print time estimations, especially for printers that have longer nozzle switching sequences. Both these settings default to 0; if no value is entered no amount of time is added to the print time estimations.
Also see CuraEngine PR: https://github.com/Ultimaker/CuraEngine/pull/1981
CURA-11099
Yas
* Operating System: MacOS 13
> Add extruder start/end gcode duration settings

- plugins/MakerbotWriter/MakerbotWriter.py
Only fields in miracle_config get sent to analytics by method firmware.  I don't know if anything else in our codebase expects to also see these fields at the top level, so I put one copy at the top level and one copy down in miracle_config.
> Copy version info to miracle_config

- plugins/CuraEngineBackend/StartSliceJob.py
With the previous implementation of the formula's in start/end gcode templates we made some oversights. With that implementation the following template (valid) would _not_ be accepted
```
; {filament_cost}, {print_time}, {filament_amount}, {filament_weight}, {jobname} <- post slice variables are not availabe in templates
; {3.14} decimal would be interpreted as object attribute retrieval, `14` is not an attribute of the number `3`
; {any([True])}  function calls would be parsed, and each function-part would be retrieved and resolved individually, instead we would like to interpret them as a whole
```
There is one asterix attached to the current implementation; that is that post slice variables won't work with formula's. This is because the templates are resolved in a two step process. …
> Cura 11347

- resources/definitions/ultimaker_method_base.def.json
When self-support is enabled do not use support material layers in the raft. 
Note: Switching support settings takes longer in the UI due to the recalculations.
PP-402
> No support material in raft when self support is used

- plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py
- plugins/UM3NetworkPrinting/src/ExportFileJob.py
- plugins/UM3NetworkPrinting/src/MeshFormatHandler.py
- plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDevice.py
We were uploading `.makerbot` files to the digital factory for s-line and legacy um printers. 
yes
* Operating System: macOS 13.3
> Fix sending over .makerbot files to digital factory for s-line and legacy um printers

- README.md
Fixed **Test** and **Conan** badges because they become broken after [Change to GitHub workflow badge routes](https://github.com/badges/shields/issues/8671) . Changes have been made according to the guide from the ticket.
Updated the **Downloads** badge to lead to the *latest release page*.  Because when I clicked on it, the link went to the picture. It's a bad UX that I decided to fix it.
Before
After
</br>
Documentation: ReadMe update
* Click to the  **Downloads** badge
* Assert that user redirected to the latest published release
* Open ReadMe file in Preview mode or Navigate to the repository main link
* Assert that **Test** and **Conan** badges now shows correct statuses
* Not needed
> Documentation: update readme

- resources/definitions/flyingbear_ghost_6.def.json
- resources/variants/flyingbear/flyingbear_ghost_6_0.25.inst.cfg
- resources/variants/flyingbear/flyingbear_ghost_6_0.30.inst.cfg
- resources/variants/flyingbear/flyingbear_ghost_6_0.40.inst.cfg
- resources/variants/flyingbear/flyingbear_ghost_6_0.50.inst.cfg
- resources/variants/flyingbear/flyingbear_ghost_6_0.60.inst.cfg
- resources/variants/flyingbear/flyingbear_ghost_6_0.80.inst.cfg
I'm using for a couple of month a Flying Bear Ghost 6 with Ultimaker Cura as Slicer. Sadly, there aren't any profiles ready for this printer. I made a new definition for the printer using as base the definition of the previus printer (Ghost 4S) and I have changed the bed size and the retraction settings (the ghost 6 is a direct drive machine). 
For the "Machine Settings" definitions, I used the value returned by the firmware of the printer. This is my first time contributing to Cura, please tell me if I have did something wrong.
> Add printer definition for Flying Bear Ghost 6

- resources/definitions/creality_ender3v3se.def.json
This updates the dimensions of the gantry & print head (used for one-at-a-time mode) from default values to their actual size on an Ender 3 V3 SE
> Print head & gantry dimensions for Ender 3 V3 SE

- cura/BuildVolume.py
Cura lowers the available build volume height when more than 1 model is loaded. This count should include grouped nodes as one (since they will be slice as one and thus not affect the gantry), and should not include modifier meshes or support meshes (since support-meshes are always printed with the first model anyway).
Fixes https://github.com/Ultimaker/Cura/issues/16566
* Windows 10
- [x ] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
> Fix available height when adding modifier mesh in One at a Time printing

- resources/definitions/ultimaker_method_base.def.json
Fix a bug in which Cura sets fanspeed in the 0..255 range instead of the 0..1 range for Method machines.
CURA-11441
> CURA-11441 Fix fan speed Method machines

- resources/qml/PrinterSelector/MachineSelector.qml
CURA-11459
Due to pyqt update to 6.6. The active machine was shown blank in the UI. 
Provides a fix for that
> Property of machinemanager redefined

- plugins/PostProcessingPlugin/scripts/AddCoolingProfile.py
See discussions in #15853 (which was closed, for which this is a replacement) and (internally) tracking-ticket CURA-11520.
> Add 'Advanced Cooling Fan Control' post-processing script.

- conanfile.py
- cura_app.py
- packaging/AppImage-builder/AppImageBuilder.yml.jinja
- packaging/AppImage/AppRun
CURA-11468
qt6.6 changelog: 06540cdb02 Flickable: Proportional wheel scrolling if deceleration is
large
When using a plain "clicky" mouse wheel, Flickable has historically
applied acceleration: the faster you rotate the wheel, the faster it
flicked. The default value of flickDeceleration was 5000, which felt
hard to control, but changing it in QML affected touch-flicking and
wheel behavior simultaneously. So now we decouple those:
flickDeceleration only affects touchscreen flicking, and Flickable
rather uses a new default value of 15000, which is defined to mean that
scroll distance becomes directly proportional to
QWheelEvent::angleDelta() * QStyleHints::wheelScrollLines() (where a
"line" is 24 logical pixels, because Flickable does not have direct
understanding of its contents). You can …
> qt6.6 scroll issues

- plugins/CuraEngineBackend/StartSliceJob.py
When using templated string variables in start/end machine/extruder gcode users may enter an optional extruder nr `{expr[, extruder_nr]}`. When providing an `extruder_nr` the expression is evaluated using the extruder stack with the provided extruder_nr. However, this workflow was broken when providing a variable that would evaluate to an extruder nr. E.g. the start code ` M140 S{material_bed_temperature, 0}` will produce the expected result but `M140 S{material_bed_temperature, initial_extruder_nr}` wouldn't.
This was an oversight when implementing https://github.com/Ultimaker/Cura/pull/16962, before merging this PR we did already support this behavior.
fixes #17501 
CURA-11536
YEs
* Operating System: MacOS 13.3
> Allow for expressions in start/end machine/extruder code extruder_nr field

- resources/definitions/ultimaker_method_base.def.json
- resources/extruders/ultimaker_methodx_extruder_left.def.json
- resources/extruders/ultimaker_methodx_extruder_right.def.json
- resources/extruders/ultimaker_methodxl_extruder_left.def.json
- resources/extruders/ultimaker_methodxl_extruder_right.def.json
Improve the time estimates for the Method machines be increasing the acceleration and reducing the jerk. For dual extrusion a rough switch over time estimate is taken into account.
PP-377
> PP-377 Improve the time estimates for the Method machines

- conandata.yml
- conanfile.py
- plugins/CuraEngineBackend/Cura.proto
- plugins/CuraEngineBackend/CuraEngineBackend.py
- plugins/CuraEngineBackend/StartSliceJob.py
- resources/qml/Preferences/GeneralPage.qml
Allow logged in DF user to **opt-in** for Sentry crash reporting. This should help with triaging GH crashes, to quickly identify your own crash, or to help out customers in the future. 
I have gone over a couple of GitHub issues to test the build, any issue which resulted in a crash and Sentry event I have labeled and linked See: https://github.com/Ultimaker/Cura/issues?q=is%3Aissue+is%3Aopen+label%3A%22Sentry+%3Aeuropean_castle%3A%22 Issues were it sliced without trouble have been closed.
> [!NOTE]
> I also send the project base_name over as an optional (opt-in) this will allow us to write a nightly cron-job, downloading the slicing error :boom: issues and testing them nightly. If the crash is resolved in the latest build we can close the issue, if not we can get the GH issue number in …
> Cura 11482 sentry

- resources/extruders/ultimaker_methodx_extruder_left.def.json
- resources/extruders/ultimaker_methodx_extruder_right.def.json
- resources/extruders/ultimaker_methodxl_extruder_left.def.json
- resources/extruders/ultimaker_methodxl_extruder_right.def.json
Fan speeds are in 0..1 range and not in 0..255 range for the Method machines. 
This needs to be corrected in the switch over routine formula's.
Also the final iso the initial print temperature was used in the extruder start part of the code.
PP-417
> PP-417 Use correct fan speed in switch over formula's

- plugins/SimulationView/SimulationView.py
- resources/definitions/fdmprinter.def.json
- resources/setting_visibility/expert.cfg
Add a new setting to enable a monotonic line ordering of the raft top surface, in order to improve model quality.
I decided to link the value of this setting to `skin_monotonic`, because if this one is active, this means the user really wants a clean top/bottom surface, which is also the purpose of this impovement. We could even discuss of removing the new setting and use the existing one for both cases.
Comes along with https://github.com/Ultimaker/CuraEngine/pull/2018
> Cura 11438 raft monotonic top surface

- resources/definitions/voron2_base.def.json
This fixes the default gcode flavor set in the Voron printer profiles and improves the default start gcode to reflect the current recommended "print_start" macro for Voron/Klipper
> Update Voron base definitions to reflect Voron / Klipper docs

- conanfile.py
It will now use the Python Virtual env
> [!IMPORTANT]
> Yes that weird `{inner}` and `{outer}` construct is needed due to Windows Powershell behavior
> Fix Python Installs about dialog

- cura/CuraApplication.py
- resources/qml/Preferences/MachinesPage.qml
CURA-11558
A crash was happening in Cura while opening the printer setting through preferences.
The function called in qml was bit tricky because it was calling a function of a "qtslot qobjcet" with a singleton class function as parameter. The resolve of the function was not aligned in sense of time. So I moved the calculation out to Cura_application.
> creating pyqtslot for desired functionality

- conanfile.py
- cura/CuraApplication.py
- cura/PlatformPhysics.py
- cura/Scene/CuraSceneNode.py
- plugins/3MFReader/ThreeMFReader.py
- plugins/3MFReader/WorkspaceDialog.py
- plugins/3MFReader/WorkspaceDialog.qml
- plugins/3MFWriter/ThreeMFWriter.py
- resources/qml/Actions.qml
- resources/qml/Menus/ContextMenu.qml
- resources/qml/Menus/EditMenu.qml
- resources/qml/Preferences/GeneralPage.qml
the “drop to build plate” is a per model property. When loading a 3mf drop to build plate is restored from the model data.
Unfortunately for older project files (and non project files such as stl's) this property will not be present. When the property is not present. When we are in this situation we use the “drop to build plate” setting from the configuration as a default value for the per model drop to build plate property.
To summarize, this should be behavior for the following scenarios.
Along, with this a user can see while opening a project file the preference selected for drop to buildplate and can change it while opening the model. After opening the model with drop_to_buildplate preference enabled, the property of individual model of the project is preserved,
> Cura 10542 drop to buildplate permodel

- resources/qml/PrintMonitor.qml
- resources/qml/PrinterOutput/ExtruderBox.qml
- resources/qml/PrinterOutput/HeatedBedBox.qml
There is apparently a bug in Qt 6.6.0 that causes a segmentation fault when deleting a Python object that has been instanciated in QML, if a custom QML property has been set on this object. This bug has been [reported to Riverbank](https://www.riverbankcomputing.com/pipermail/pyqt/2024-March/045751.html).
In the meantime, I could still fix the crash because the properties set in QML are apparently useless now. They concern a resolve function on the "material_bed_temperature" which is a global setting. I am pretty sure this code has been copy-pasted from an other similar case, but in this case this is not needed. Please confirm this :)
However, the PyQt bug is not fixed yet and we may encounter other crashes. I just think/hope this is the only QML screen we ever destroy so this bug …
> CURA-11657 Fix crashes with USB printing

- conandata.yml
Bumping gradual flow plugin version to 0.1.0-beta.3, not 0.2.0 because we don't have a proper settings upgrade workflow for engine plugins yet.
> Use proper gradual flow plugin version

- resources/definitions/ultimaker2_plus_connect.def.json
Generic petcf was dropped during clean up. After confirmation with Frederic added it back to the exclude list
> Added the generic_petcf

- cura/OAuth2/AuthorizationService.py
I previously made a change on AuthorizationService to allow using it for other services (Onshape in my case) : https://github.com/Ultimaker/Cura/commit/b794989468653d04c3e0e24044cb8ea61ce29dff
Now I'm using the `loadAuthDataFromPreferences` method which also has a direct call to `getUserProfile`. This allows using stored auth preference without loading the user profile.
> Do not get user profile by loading auth data

- plugins/3MFReader/ThreeMFWorkspaceReader.py
Not clearing the current machine in case of UCP
because we don't want to write again the same thing. 
(This was the cause of not writing the machine after clearing it)
CURA-11701
> not clearing the current machinein case of UCP

- cura/PrinterOutput/Models/MaterialOutputModel.py
CURA-11729
The GUID of the ASA material for mapping was taken from generic which should have been the ultimaker material to start with.
I want to recommend other materials to be deleted from the material map if they are generic. I see the only 6 materials are used in case of Makerbot, and they are all ultimaker GUID in the list. others are generic.
> GUID of material ASA was from generic ASA, now given Ultimaker ASA GUID

- resources/qml/PrintSetupSelector/Recommended/RecommendedSupportSelector.qml
Changed the settings in RecommendedSupportSelector.qml so that now all extruders will not be updated by default. However, when a user changes the selected index, a temporary update to all extruders will be triggered. This allows for specific user-directed changes to propagate correctly across all extruders.
CURA-11776
> Update support extruder settings behavior

- plugins/3MFWriter/SettingExport.py
- plugins/3MFWriter/SettingsExportGroup.py
- plugins/3MFWriter/SettingsExportModel.py
- plugins/3MFWriter/SettingsSelectionGroup.qml
Introduced a new property 'show_in_menu' to control the visibility of individual settings in 3MFWriter plugin. Modified 'SettingExport' class constructor to store this visibility status. Also, updated the 'SettingsExportGroup' model to filter the settings based on visibility before presenting them in the GUI.
CURA-11723
> Add visibility control for settings in 3MFWriter plugin

- cura/CuraApplication.py
This should fix the reverting of project name to the previous one when the current project was not saved as a project (yet).
> [CURA-8897] Clear the last project name when the platform is empty.

- plugins/3MFReader/ThreeMFWorkspaceReader.py
Prevent crash if the variants field only has an 'empty' entry. Just get the one you'd get if no variant was asked (like in the other branch of the if) then.
> [CURA-11772] Crash on opening certain project files

- plugins/3MFReader/ThreeMFWorkspaceReader.py
Since we can't rely on the build-volume --because we can't know on which printer we open-- the safest bet (and the thing allowed by 3mf if I recall) is to just center the entire scene on the buildplate for Universal Cura Project files.
> [CURA-11703] Reset entire scene around center for UCP.

- plugins/3MFReader/SpecificSettingsModel.py
- plugins/3MFReader/WorkspaceDialog.qml
- plugins/3MFWriter/SettingExport.py
- plugins/3MFWriter/SettingSelection.qml
- plugins/3MFWriter/SettingsExportModel.py
CURA-11783
Changed setting value to enum value while saving ucp and loading UCP
Added a connection in WorkspaceDialog.qml to call function whenever the 'exportedSettingModel' changes. This ensures that any changes in the model will now be reflected in the UI table. (This wasn't updating for me)
> Cura 11783 enum instead of text value

- cura/API/Account.py
- resources/qml/Cura.qml
- resources/qml/WelcomePages/AddUltimakerPrinter.qml
CURA-11465
Updated account syncing functionality for logged-in and non-logged-in sessions in Ultimaker. More specifically, syncing is now engaged when the UI becomes visible and stopped when adding a machine action-> addmachinedialog is triggered. The modifications also include fallback to login if the user is not logged in.
> Implement syncing feature for Ultimaker account

- cura/Machines/MaterialNode.py
- cura/Machines/VariantNode.py
Although this is rare scenario.This allows for metadata retrieval from the container directly if one is provided, otherwise metadata is fetched using the container_id from the ContainerRegistry. Updated the MaterialNode creation in the VariantNode class(only one scenario) to pass the container.
CURA-11748
> Update MaterialNode initialization and metadata retrieval

- .github/workflows/printer-linter-pr-diagnose.yml
- .github/workflows/printer-linter-pr-post.yml
- .printer-linter
- printer-linter/pyproject.toml
- printer-linter/src/printerlinter/diagnostic.py
- printer-linter/src/printerlinter/factory.py
- printer-linter/src/printerlinter/linters/defintion.py
- printer-linter/src/printerlinter/linters/directory.py
- printer-linter/src/terminal.py
This update adds a new check for deleted files in the printer linter. This will alert the user when a file has been deleted that could potentially disrupt upgrade scripts. An argument "--deleted" is also added to terminal.py to facilitate this new check. Additionally, the printer-linter version has been incremented to 0.1.2.
CURA-10903
> Add detection for deleted files in printer linter

- resources/qml/PrintMonitor.qml
- resources/qml/PrinterOutput/ExtruderBox.qml
Currently, the preheat values on the Monitor stage are for "bed temperature" and "print temperature".
This PR changes them to "Print Temperature Initial Layer" and "Bed Temperature Initial Layer".
The changes involve a single line in each file.
- [ X] Bug fix (non-breaking change which fixes an issue)
* Cura Version:   5.7.0
* Operating System:  Win 10 Pro
- [ X] My code follows the style guidelines of this project as described in [UltiMaker Meta](https://github.com/Ultimaker/Meta) and [Cura QML best practices](https://github.com/Ultimaker/Cura/wiki/QML-Best-Practices)
- [ X] I have read the [Contribution guide](https://github.com/Ultimaker/Cura/blob/main/CONTRIBUTING.md) 
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have …
> Monitor Page Preheat values

- resources/qml/WelcomePages/AddLocalPrinterScrollView.qml
- resources/themes/cura-light/theme.json
Add Searchbar to the "Add An Offline Printer" list
> Cura 11003 add searchbar for offlineprinter

- resources/quality/ultimaker_factor4/um_f4_global_Fast_Quality.inst.cfg
Create the `fast`/`0.15mm` global quality for the Factor 4. This quality has never been made, as our own profiles do not make use of this layer height. This however, breaks 3rd party materials that _do_ make use of that layer height.
> [PP-484] Create Factor 4 "fast" global quality

- plugins/3MFWriter/ThreeMFWriter.py
Due to commit cdb2a5789d8ffe9ba4e5669d7bbb575b13d30fd6 all the meshes are re-centered when saving to 3MF so that they can be loaded centered, even when only models are imported. However, this should not be applied to objects that are a child of an other object, because it changes their relative position. This PR fixes the issues by only applying the mesh centering to top-level objects, so that we keep the best of both behaviors.
Contributes to CURA-11902
Fixes https://github.com/5axes/SpoonAntiWarping/issues/8
> CURA-11902 fix loaded support mesh position

- resources/definitions/fdmprinter.def.json
Also cherry-picked to 5.7 branch (https://github.com/Ultimaker/Cura/commit/86ccddbb1d00eb121506095e21c46148aa688c33)
CURA-11912
> Change `value` to `resolve`

- .github/workflows/printer-linter-pr-diagnose.yml
- .github/workflows/printer-linter-pr-post.yml
Previously they had no permission set, so by default all write access. We now specify only the required permissions for each of them.
> Reduce permissions on printer-linter GitHub actions

- .github/workflows/printer-linter-pr-post.yml
This is actually required to fix an issue where it was possible to inject malicious code into the environment variables when using a PR that changed the diagnose script. At the same time, it is also good practice to use the last version of the called clang-tidy-pr-comments action.
Note that I can't really test the script until is has been merged to `main`. However, 95% of it is just a copy-paste from the recommended script provided by `platisd/clang-tidy-pr-comments`. I just added the part that adds the `commentFileExists` variable, and this is my very first javascript code, so please review this part very carefully :smiley: 
CURA-11929
> CURA-11929 Update the printer-linter post actions to use the last version of inner sub-script

- resources/definitions/fdmprinter.def.json
This adds a new condition to the `prime_tower_mode` resolve function, so that it is now possible to define the mode on materials, and if all the selected materials have the same "interleaved" option, then interleaved mode is selected.
Although this is not perfect because the mode should be set depending on specific material combinations, we have decided that it will be good enough for now.
CURA-11931
> CURA-11931 set interleaved prime tower from material

- cura/API/Account.py
Since the permissions can only change with a token, we only need to check what the permissions at that moment (instead of every 60 seconds) Fixes CURA-11870
> Only request permissions when token changed

- .printer-linter
- printer-linter/src/printerlinter/factory.py
- printer-linter/src/printerlinter/linters/defintion.py
- printer-linter/src/printerlinter/linters/formulas.py
- printer-linter/src/printerlinter/linters/profile.py
This adds a simple printer-linter check against any use of experimental settings in printer/extruder definitions.
It also fixes a few printer-linter crashes I encountered (see dedicated commits for details)
CURA-10899
> CURA-10899 Warn if experimental settings are used

- .printer-linter
There was an entire ticket for this specific warning previously (CURA-10904) so I'm disabling it rather than removing it outright.
> [CURA-11999] Disable 'temp should be defined in material' warning for now.

- plugins/MakerbotWriter/MakerbotWriter.py
With the commits https://github.com/Ultimaker/Cura/commit/fdfc5dcc67f8efac60404421e86b357b5ef3a5af and https://github.com/Ultimaker/Cura/commit/2f8fc2cabef19b23f2d024105b21ad7ccd5b09a4 the instance list was changed from containing all model instances to a single instance called "instance0". Digital factory expects the same instances to be present in the gaggles object.
> Add "instance0" entry to gaggles

- plugins/3MFWriter/ThreeMFWriter.py
The transformation from UM to savitar in the 3MFWriter does not invert the transformation in the 3MFReader. This usually doesn't cause any problems as the center mesh extension is zero and the resulting matrix the identity. However if the extent is not zero the final transformation is incorrect.
I fixed the transformation as shown below
$$
T_{\text{UM}} = T_{\text{Printer}} \cdot T_{\text{Centre}} \cdot T_{\text{Savitor}}
$$
**Fixed implementation**
$$
T_{\text{Savitor}} = T_{\text{Centre}}^{-1} \cdot T_{\text{Printer}}^{-1} \cdot T_{\text{UM}}
$$
**Current implementation**
$$
T_{\text{Savitor}} = T_{\text{Printer}}^{-1} \cdot T_{\text{Centre}} \cdot T_{\text{UM}}
$$
Opened, saved and reopened multiple projects and the objects reload in the same position as expected
**Test …
> Fix UM to savitar transformation in 3MFWriter

- resources/themes/cura-light/theme.json
This might have some impact on the min window size you can use Cura with, but it was getting a bit silly.
> [CURA-12155] Was too small to fit in the start/end-gcode in new printers.

- resources/i18n/ja_JP/cura.po
- resources/i18n/ja_JP/fdmprinter.def.json.po
Tweaks common terms for Japanese translation.
- preference: プレファレンス -> 環境設定
- overlap (i.e. infill) : 重複 -> 重なり
* Operating System: Windows 11
> tweaks common terms for Japanese translation

- plugins/GCodeReader/FlavorParser.py
- plugins/GCodeReader/RepRapFlavorParser.py
This fixes https://github.com/Ultimaker/Cura/issues/19514, where the relative extrusion command was only recognized in RepRap flavoured GCode, but it is the same for Marlin flavoured GCode.
Moved the corresponding method to the superclass and removed it from the RepRap flavoured Reader
* Operating System: Windows 10
> PlugIn GCodeReader - Process M82 and M83 command for Marlin flavoured GCode

- resources/intent/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-pla-175_0.2mm_visual.inst.cfg
- resources/intent/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-tough-pla-175_0.2mm_visual.inst.cfg
* The settings used in the Visual intent profile improve the roof quality
* Settings include temp adjustments, line widths, small features, hole, roof accel & speed
* These apply to PLA & TPLA
* all of the visual intents are marked as experimental for Cura 5.10
PP-554
> PP-554 Kedge Visual Intents

- resources/definitions/ultimaker_sketch.def.json
- resources/definitions/ultimaker_sketch_sprint.def.json
- resources/quality/ultimaker_sketch/um_sketch_0.4mm_um-metallic-pla-175_0.2mm.inst.cfg
- resources/quality/ultimaker_sketch_large/um_sketch_large_0.4mm_um-metallic-pla-175_0.2mm.inst.cfg
- resources/quality/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-metallic-pla-175_0.2mm.inst.cfg
Previously we used the PLA quality files to print Metallic PLA. There were drastic differences in surface quality (matte vs shiny). The temperature increase to 230 addresses the surface differences. We reduced the print speed to stay within the max flow rate of 12 mm^3/s.  Additionally, the infill rotation was enabled for Metallic PLA (Similar to Sketch PLA infill).
Some other speed adjustments were made (walls, roof, support interface, support bottom).  These were paths that got slowed down too much when adjusting the global print speed. These adjustments were made to make up some of the lost speed without sacrificing print quality.
The previous support material flow value was set to 90%.  We increased it by 2% to limit under-extrusion, which is more pronounced at the higher nozzle …
> Add metallic PLA quality files for Sketch printers

- resources/definitions/fdmprinter.def.json
Add `material_pressure_advance_factor` setting. This is a machine setting and not exposed to the user.
[CURA-12389]: https://ultimaker.atlassian.net/browse/CURA-12389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PP-535]: https://ultimaker.atlassian.net/browse/PP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CURA-12389][PP-535] Add pressure advance setting

- plugins/USBPrinting/USBPrinterOutputDevice.py
This is the first step of smartly enabling the USB printing: we add an internal preference, that is `False` by default, and will be set to `True` whenever the user actually prints something over USB. This will remain as is for Cura 5.10, in order to "log" users that are actually using it. In a future version, we will use this preference to enable USB printing or not. This way, all the users that have been actively using it on Cura 5.10 should have it still enabled without any action. Others will be prompted with a specific UI when adding a printer. This is not perfect, but should allow us to catch a large majority of users of USB printing.
CURA-12150
> CURA-12150 Add local preference to monitor use of USB writing

- resources/quality/zyyx_pro/carbon06/flex/zyyx_pro_06_flex_fast.inst.cfg
- resources/quality/zyyx_pro/carbon06/flex/zyyx_pro_06_flex_fine.inst.cfg
- resources/quality/zyyx_pro/carbon06/flex/zyyx_pro_06_flex_normal.inst.cfg
- resources/quality/zyyx_pro/carbon12/flex/zyyx_pro_12_flex_normal.inst.cfg
- resources/quality/zyyx_pro/multi02/flex/zyyx_pro_02_flex_fast.inst.cfg
- resources/quality/zyyx_pro/multi02/flex/zyyx_pro_02_flex_fine.inst.cfg
- resources/quality/zyyx_pro/multi02/flex/zyyx_pro_02_flex_normal.inst.cfg
- resources/quality/zyyx_pro/multi04/flex/zyyx_pro_04_flex_fast.inst.cfg
- resources/quality/zyyx_pro/multi04/flex/zyyx_pro_04_flex_fine.inst.cfg
- resources/quality/zyyx_pro/multi04/flex/zyyx_pro_04_flex_normal.inst.cfg
- resources/quality/zyyx_pro/multi08/flex/zyyx_pro_08_flex_fast.inst.cfg
- resources/quality/zyyx_pro/multi08/flex/zyyx_pro_08_flex_fine.inst.cfg
- resources/quality/zyyx_pro/multi08/flex/zyyx_pro_08_flex_normal.inst.cfg
There was an issue with the ZYYX Pro's selection of profiles related to its many nozzles. It caused the wrong profile to be selected. 
Fixed by removing erroneous "global_quality=True" from material-specific quality profiles. 
I tested the new profiles and they seem to update correctly now. The version before this does not update.
> ZYYX Pro profile bugfix

- resources/intent/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-pla-175_0.27mm_draft.inst.cfg
- resources/intent/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-tough-pla-175_0.27mm_draft.inst.cfg
- resources/quality/ultimaker_sketch_sprint/um_sketch_sprint_0.4mm_um-metallic-pla-175_0.2mm.inst.cfg
The other commit that converted all the profiles missed a couple of files.
See 2db4d16a80bb0b449871399b8d236205e58c09b9
What's testing?
[CURA-11966]: https://ultimaker.atlassian.net/browse/CURA-11966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CURA-11966] Rename wall_overhang_speed_factor

- resources/definitions/ultimaker_method.def.json
- resources/definitions/ultimaker_sketch.def.json
- resources/definitions/ultimaker_sketch_sprint.def.json
- resources/intent/ultimaker_methodx/um_methodx_1c_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodx/um_methodx_1c_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodx/um_methodx_1xa_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodx/um_methodx_1xa_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodx/um_methodx_labs_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodx/um_methodx_labs_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_1c_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_1c_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_1xa_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_1xa_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_labs_um-pc-abs-175_0.2mm_solid.inst.cfg
- resources/intent/ultimaker_methodxl/um_methodxl_labs_um-pc-abs-fr-175_0.2mm_solid.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_1c_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_1c_um-pc-abs-fr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_1xa_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_1xa_um-pc-abs-fr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_labs_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodx/um_methodx_labs_um-pc-abs-fr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_1c_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_1c_um-pc-abs-fr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_1xa_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_1xa_um-pc-abs-fr-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_labs_um-pc-abs-175_0.2mm.inst.cfg
- resources/quality/ultimaker_methodxl/um_methodxl_labs_um-pc-abs-fr-175_0.2mm.inst.cfg
Add PC-ABS & PC-ABS-FR configurations for Method X
and Method XL.  These materials are allowed on 1C,
1XA and Labs extruders.  Included is a solid intent mode.
The first PR which I closed had good model performance,
however the self support was printing inconsistently.
Larger support regions had under-extruded portions. 
This PR includes changes that address the under-extrusion,
including fan, line width, print speed and flow adjustments.
I ran prints on Method X and Method XL with both materials
to confirm the changes are a net positive.
I added PC-ABS & PC-ABS-FR to the sketch, sketch sprint, and
method exclude materials lists.
> PP-550 PC-ABS & PC-ABS-FR 175

- resources/definitions/ultimaker_sketch_sprint.def.json
The Sprint tree supports inherited settings that
were tuned for Normal Support.  The support floor
connection to model roofs was weak, and causing
some trees to detach (depending on the model
geometry).  Sometimes the nozzle to collided
with the broken support, and resulted in XY shifts, and
the fan cover disconnecting while printing.
Additionally, I adjusted the support Z distance
values for layers heights > 0.2.
The new settings allow for better tree support
adhesion, improving the print success rate.
PP-573
Using the updated Sprint definition file, I completed test prints for the following configurations:
PLA Balanced Fast
PLA Balanced Extra Fast
PLA Draft
TPLA Balanced Fast
TPLA Balanced Extra Fast
TPLA Draft
MPLA Balanced
> PP-573 Sprint Tree Supports Update

- resources/quality/ultimaker_factor4/um_f4_ht0.6_cffpps_0.2mm.inst.cfg
PP-569 set top surface flow to material flow to reduce gaps in top surface. Overextrusion is preferred over gaps in the top surface.
> PP-569-improve-top-surface-PPS-CF-on-F4

- resources/qml/Settings/SettingItem.qml
- resources/qml/Settings/SettingTextField.qml
- resources/qml/Settings/SettingView.qml
When scrolling to settings, we might want to collapse the opened pop-ups (from extruder choses and the like) ... but that shouldn't come at the expense of losing focus on text-field settings occasionally (most notably of course if the scroll-bar changes length due to what you just changed).
> [CURA-12254] Don't lose text-field focus when scrolling.

- conandata.yml
- plugins/CuraEngineBackend/StartSliceJob.py
- tests/Machines/TestStartEndGCode.py
The regex was not specific enough and would catch the rest of the line, now we force stopping as soon as we see a `{` or `}`
CURA-12386
Fixes [20183](https://github.com/Ultimaker/Cura/issues/20183)
> CURA-12386 G-Code replacement fails with single line code

- resources/qml/Preferences/SettingVisibilityItem.qml
Reduce apparent visual clutter by making the supposed meaningful margin actually meaningful visually.
> [CURA-12441] Margin wasn't wide enough to see that it's a tree.

- resources/qml/Preferences/SettingVisibilityPage.qml
This does incur a cost on the first load of the list though.
> [CURA-12442] Same cache as other setting-lists to reduce slowness on scroll.

- cura/Arranging/ArrangeObjectsJob.py
- cura/Arranging/Arranger.py
- cura/Arranging/Nest2DArrange.py
- cura/MultiplyObjectsJob.py
1. Initial bug was caused by trying multiple placement strategies but not reconstructing the items between iterations, which caused inconsistencies in data given to libnest2d.
2. Changed the UI behavior to not display a partial re-arrange which is often worse than the current situation
3. Add more strategies to test to increase the likeliness of finding an arrangement
> CURA-12169 fix autoarrange for disallowed areas

- cura/Arranging/Nest2DArrange.py
* Use DONT_ALIGN alignment, otherwise all the transforms get re-centered, including the ones of the fixed objects
* Remove DONT_ALIGN strategy for starting point, which is a non-handled case in the inner library
CURA-12453
:warning: To be merged after https://github.com/Ultimaker/Cura/pull/20352
> CURA-12453 fix auto arrange overlapping models

- cura/UI/PrintInformation.py
CURA-12403
Apply the new project name only once, not for subsequent saves
Comes with https://github.com/Ultimaker/Uranium/pull/989
Fixes https://github.com/Ultimaker/Cura/issues/20175
> CURA-12403 Project names revert to previous name

- resources/definitions/fdmprinter.def.json
Only enable the bottom-most-surface settings when there is at least 1 layer of bottom surface. As a bonus, apply the same behavior for the top-most-surface.
CURA-12472
> CURA-12472 bottom surface settings visible when active

- resources/intent/ultimaker_s3/um_s3_cc0.4_nylon-cf-slide_0.2mm_engineering.inst.cfg
- resources/intent/ultimaker_s5/um_s5_cc0.4_nylon-cf-slide_0.2mm_engineering.inst.cfg
- resources/quality/ultimaker_s3/um_s3_cc0.4_nylon-cf-slide_0.2mm.inst.cfg
- resources/quality/ultimaker_s5/um_s5_cc0.4_nylon-cf-slide_0.2mm.inst.cfg
Nylon CF Slide still has some printing problems with the CC 0.4 print core on the S3/S5/S7. It prints a lot better with the CC 0.6 core. Let's mark the profiles as experimental on the CC 0.4 cores until we improve the quality to our standards.
> [PP-593] Mark Nylon CF Slide as experimental on CC 0.4 cores

- resources/definitions/ultimaker_s8.def.json
We see some occasional layer shifts with the S8 caused by the 400mm/s travel speed and potentially a bug in Cheetah. Reduce the travel speed to 300mm/s until this issue is resolved.
Ran test prints with 300mm/s and found no issues in the XCP logging
> PP-600: Reduce S8 travel speed

- resources/quality/ultimaker_s8/um_s8_cc_plus_0.4_nylon-cf-slide_0.2mm.inst.cfg
Based on customer feedback, we reduced extrusion issues in the S8 profiles for the CC+04 with Nylon CF Slide by reducing the retraction amount and the retraction prime speed.
> PP-599 slower unretracts to reduce extrusion issues

- resources/quality/ultimaker_s8/um_s8_aa_plus_0.4_cpe_0.2mm.inst.cfg
- resources/quality/ultimaker_s8/um_s8_cc_plus_0.4_pc_0.2mm.inst.cfg
PC: Prevent holes in outside wall of PC prints due to air capture during unretracts:
Reduce retract length, inner wall before outer wall, inner wall speed equal to outer wall. We also lowered the flow rate to 95% for PC because we noticed that it was over extruding.
CPE: CPE is VERY fragile to printer over itself or bumps. Lower all speeds to 40mm/s, goto 'lines' infill type to prevent crossing over lines, 3 walls to prevent issues with infill to reach the outer wall.
PP-607
> [PP-607] Improve CPE and PC surface quality

- resources/qml/Preferences/GeneralPage.qml
Also move the note at the bottom of the page, because now labels from different categories use it, and this is where people should look for it.
CURA-12486
> Indicates that changing option requires a restart

- packaging/NSIS/Ultimaker-Cura.nsi.jinja
Cleans up the Windows Start Menu entry by removing the uninstall shortcut (which is no longer created since at least Windows 10 anyways), and placing the Cura shortcut directly in the Start Menu without creating any folder, which is the recommenced practice for a clean appearance and saves the click needed for expanding a folder.
I have left the ability to create a website link in the Start Menu, although this not the right place and I consider it unclean. I would recommend removing that too.
Not tested, minor change. Will set up a build environment if requested
> Clean up Windows Start Menu

- resources/definitions/ultimaker_method_base.def.json
The Method gantry acceleration parameters do not allow a user to increase the print speed.  We have to expose and map another parameter (extruder acceleration) in order to increase the gantry acceleration values past the default value of 800.
This fixes... OR This improves... -->
Its confusing to the user if the exposed gantry acceleration parameters can be increased, yet do not produce a faster print.  Hiding these parameters for now resolves this confusion.
Eric and Alan looked at the UI to ensure it shows the expected parameters.  None of the changes produce different acceleration values, so no changes to the toolpath are expected.
> [PP-611]-Hide-Method-Accel

- resources/definitions/fdmprinter.def.json
Previously you could only set on/off starting on a certain layer.
Backend PR: https://github.com/Ultimaker/CuraEngine/pull/2226
> [CURA-12512] Add speed settings for auxilary ('build volume') fan.

- resources/definitions/ultimaker_s6.def.json
- resources/definitions/ultimaker_s7.def.json
- resources/definitions/ultimaker_s8.def.json
The machine_name setting is not user-facing. This is only used to paste into the gcode header. Opinicus expects a lower-case m (`Ultimaker`) for all the machines. With an upper-case, the job fails to start
I'll bring the cookies next week 🍪
> [SEM-608] Revert the capital M

- .github/workflows/printer-linter-pr-diagnose.yml
- .github/workflows/update-translation.yml
Adjustment to the workflow files:
- path -> paths: The correct keyword for filtering pull request triggers by file paths is paths (plural), not path (singular). 
- indentation fix: with keyword should be on the same indent level as uses.
- [X ] Bug fix (non-breaking change which fixes an issue)
> Workflow fixes

- resources/variants/ultimaker_s6_bb04.inst.cfg
Same as https://github.com/Ultimaker/Cura/pull/20463.
With the new S6 BB 0.4 variant, it was also missing. We've now switched to templates for the variants, so now they are all correct
> [PP-605] Add missing machine_nozzle_size to S6 BB 0.4

- packaging/AppImage-builder/AppImageBuilder.yml.jinja
Change compression level to gzip instead of xz, because xz is no more available in the AppImage toolkit.
* Pros:
* It works (and we don't really have an other option)
* It starts much faster
* Cons:
* Output file is now 316MB instead of 268MB
> CURA-12655 obsolete appimagetools

- resources/definitions/fdmprinter.def.json
This allows more retraction settings to be set per-object.  These retraction settings were already supported on a per-object basis on the backend by https://github.com/Ultimaker/CuraEngine/pull/1769, but were not enabled by the corresponding frontend PR at the time.
This helps get incrementally closer to exposing per-model settings https://github.com/Ultimaker/Cura/issues/3193
Tested the g-code output after changing per-object settings.  (e.g. add two objects, set retraction distance do something different on one of them, check that this modifies the output g-code by diffing the g code before and after the change.)
* Operating System: Debian
> Enable more retraction settings to be set per-model

- plugins/Marketplace/Marketplace.py
- plugins/Marketplace/resources/qml/Marketplace.qml
- resources/qml/Cura.qml
- resources/qml/Preferences/PreferencesDialog.qml
- resources/qml/qmldir
The Marketplace and the Preferences dialog are having display issues in Mac environment. In order to fix this, I have applied some sanity changes:
* Set the proper `transientParent` to dialogs created by Python code
* Set them as modal so that they sould always appear in front of the main window
* Instanciate them only when required, then delete them as soon as we don't need them, then create a new one if we need to re-display
As a bonus, I also removed some unused QML components and simplified the creation logic of the preferences dialog.
CURA-11810
Requires https://github.com/Ultimaker/Uranium/pull/1004
> CURA-11810 fix mac dialogs

- plugins/PaintTool/BrushColorButton.qml
- plugins/PaintTool/BrushShapeButton.qml
- plugins/PaintTool/PaintModeButton.qml
- plugins/PaintTool/PaintTool.py
- plugins/PaintTool/PaintTool.qml
- plugins/PaintTool/PaintUndoCommand.py
- plugins/PaintTool/PaintView.py
- plugins/PaintTool/__init__.py
Implements a full-stroke undo-redo instead of each stroke atomic operation, which is more user-expected.
This uses a QUndoStack instead of the previous custom-made mechanism, so that we can use common undo-redo mechanisms.
:warning:  Based on branch CURA-12660_painting-UI-improvements
CURA-12661
> CURA-12661 make more global paint undo

- packaging/NSIS/Ultimaker-Cura.nsi.jinja
Remove NSIS removal of uninstall Start Menu shortcut during uninstall, as it no longer exists. Accidentally left it behind. See #20446 / #20302
Windows specific.
> Remove NSIS uninstall shortcut removal

- plugins/GCodeReader/FlavorParser.py
Instead of just emitting the signal for the state change, actually set the state so that the UI and the model don't end up with inconsistent values
CURA-12055
:thought_balloon: There is also a similar signal emission on https://github.com/Ultimaker/Cura/blob/3c6400823d05b73ea689a631cf51eeed66c58302/plugins/CuraEngineBackend/CuraEngineBackend.py#L405
It should not be necessary and I actually tried to remove it and everything seems fine. In this case however, there should be no state inconsistency, and it does not seem to create a bug, so I let it as is.
> CURA-12055 fix load ufp then stl

- plugins/PaintTool/PaintTool.py
- plugins/PaintTool/PaintTool.qml
- plugins/PaintTool/PaintView.py
Fixes group handling, and disable painting for grouped objects. This is not really nice because it forces the user to ungroup objects to be able to paint them. However, the painting is currently designed to allow painting a single object at once, and selecting a group does select multiple objects. This should be improved later.
CURA-12761
Fixes https://github.com/Ultimaker/Cura/issues/21012
> CURA-12761 Handle group selection as multi-selection w.r.t painting
