resources/themes/cura/theme.json
The layer slider (in Layer viewmode) has poor visibility against the background if the slider overlaps the checkerboard in the 3d scene. This patch changes the color of the slider to the same color that is used for buttons, setting it apart from the checkerboard.
Fixes https://github.com/Ultimaker/Cura/issues/93
=> Improve visibility of layer slider 

resources/themes/cura/theme.json
The background of the MessageStack is the same as the (hardcoded) dark color of the buildplate grid. When the view is rotated so the MessageStack overlays the buildplate grid, the visibility of the messagestack is poor. 
This PR changes the backgroundcolor of the MessageStack to a darker shade, so it stands out against the grid. It uses the same color as the buttons, which may or may not be ideal. I'm a bit conflicted about changing the message text color to white for better contrast. But perhaps a different shade should be picked for the MessageStack background?
=> Fix poor visibility of MessageStack against grid

cura/BuildVolume.py
If a profile is not properly loaded, the width & height of the buildvolume may be set to None. This then causes an exception in buildvolume.rebuild().
Steps to reproduce the issue:
* remove %userprofile%/cura
* create a new profile, adding a machine, by running 15.06
* close 15.06 and open a master build of Cura
* witness crash in buildvolume.py:rebuild (trying to divide self._width by 2 when self._width == None)
Note: The actual mechanism of this crash is probably due to ongoing profile work by @awhiemstra. It could be worthwhile to fix the cause instead of fixing the symptom.
=> Fix crash when a profile cannot be loaded

resources/qml/WizardPages/SelectUpgradedParts.qml
From https://ultimaker.com/en/community/view/17296-cura-1510-open-beta?page=1&sort=#reply-117393:
first opening-select your printer --> Ultimaker Original: by default only the dual extrusion upgrade box is ticked. Should it be the opposite by default only the extruder driver upgrade?
This PR restores the default upgrade to what it was with legacy Cura.
=> Change the default UMO uprade options

cura/CuraApplication.py
For any reason this problem seems to be Ubuntu-specific and is also present since pyqt4.
* Updated the #131 pull request and added platform.linux_distribution to check for "Ubuntu"
* Added notice about the bug report above the if-clause
* Added comment why <platform.system() == "Linux"> is needed+
PS: If there is something missing to this PR, just let me know. I'll add it as soon as possible.
Regards
=> Fixes "could not create shader program" #385

resources/qml/ViewPage.qml
nog to not
Perhaps to fix the tooltip it has to be in the English translation since it uses the English string here as the lookup for other languages?  If so, feel free to close without merging, obviously.
=> Fix a few typos in comments and tooltip

cura.desktop
Related to the discussion at #407 just made the only needed modification to cura.desktop, that specifies which mime-types are supported by Cura.
This PR just adds the application/sla (as known as *.stl files) entry.
=> Adding supported stl mime-type

resources/machines/prusa_i3.json
When selecting the i3 printer, the heated bed option is not displayed.  This fixes that.
=> Enable heated bed for i3 printer.

plugins/USBPrinting/PrinterConnection.py
Some of the "threading.Thread.daemon"s have typo's.
=> Typo's in PrinterConnection.py

resources/qml/Cura.qml
Settings->Preferences does not open the General Preferences page consistently.
Steps to reproduce:
* (re)launch Cura
* Use the Settings->Preferences menu
=> General page opens
* Close preferences
* User the Profile->Manage profiles menu
* Close preferences
* Use the Settings->Preferences menu
Expected result:
General preferences page opens
Actual result:
Profile preferences page opens
=> Always show "General" page when opening preferences using Settings menu

cura/CuraApplication.py
The default view on the build volume shows the volume head-on to match how a user sees his/her printer. When an object is added to the center of the buildplate, this default view causes the y and z axes to align, making it harder to manipulate the object (translate, rotate, scale):
Attached patch makes a small change to the default view to be slightly from the side, so the two axes don't align (and also places the camera slightly closer to the build volume so everything is less tiny):
=> Adjust initial view to be slightly from the side

.gitignore, plugins/CuraProfileReader/CuraProfileReader.py, plugins/CuraProfileReader/__init__.py, plugins/CuraProfileWriter/CuraProfileWriter.py, plugins/CuraProfileWriter/__init__.py, plugins/GCodeProfileReader/GCodeProfileReader.py, plugins/GCodeProfileReader/__init__.py, plugins/GCodeReader/GCodeReader.py, plugins/GCodeReader/__init__.py, plugins/GCodeWriter/GCodeWriter.py
This feature will write the profile to g-code when saving the g-code, and allows importing settings from g-code with the Import Profile button in the profile manager.
It also creates two new types of plug-ins: Profile Reader and Profile Writer, to fulfil said function as a plug-in (which is handy for later).
A similar pull request is made for Uranium. They should be tested together.
=> Write and Read Profile in g-code

cura/CuraSplashScreen.py
It happens because the variable version has just one entry.
In case of a unversioned aka master codebase the only content is "master", so there is no second entry at all.
Now a len(version) checks whether there is a second entry or not.
I also wanted to fix the same in master, but it is already fixed there - https://github.com/Ultimaker/Cura/commit/e7fc881440a4b92598fb4bf64648c96b47e17bb5
=> Fixing error message, which appears when loading Cura.

plugins/CuraEngineBackend/CuraEngineBackend.py
Currently if the user starts using a Tool (eg the Move tool by moving an object, or the LayFlat tool) while a slice operation is ongoing, the slice operation continues during the operation. This unnecessarily loads the CPU, and makes the UI less responsive than it could be, because after the operation has finished we can be certain that a reslice is necessary.
This PR terminates the engine process when a ToolOperation starts, thus freeing up CPU cycles to perform the ToolOperation. It also makes "continuous slicing" slightly less obnoxious because it tries to get out of the way more.
=> Terminate engine when a ToolOperation starts

CMakeLists.txt
Instead of having a list of languages hardcoded, we scan the i18n directory for available languages.
It was a TODO, which was left after fixing po-file installation. After finding the macro I decided to fix it here.
The reference to the added macro is there as an URL.
=> Scanning i18n directory for languages

cura/CuraApplication.py
Fixes CURA-679
AxisAlignedBox() initializes as a 0 width, 0 height box around the origin.
=> Don't include origin in boundingbox

cura.desktop
Don't know how long we support opening images, but this commit adds them to the *.desktop file for Linux based desktops.
So "open with"-actions will now show Cura for these media-types.
=> Adding new supported image formats

cura/CuraApplication.py, resources/qml/Actions.qml, resources/qml/Toolbar.qml
This patch disables tools while a tooloperation is running. Some tool-operations, such as the Lay Flat operation, take a while to complete. It should not be possible to relaunch the lay flat operation while the same operation is already loading. Also manipulating an object with a different tool while an operation is running may affect the outcome of either tools.
Fixes CURA-623
Also see https://github.com/Ultimaker/Uranium/pull/96
=> Fix cura 623

resources/i18n/de/cura.po, resources/i18n/fr/cura.po
* Because these keywords got translated the code can't replace them with values.
* Basicly the idea having these keywords in translation files is just to change the order of them (according to the culture and the region, where another order would be expected).
-> So reverted the translated keywords for german and french.
Fixes #621
=> i18n: Revert translations on keywords

cura/CuraApplication.py
This patch delays the cameraanimation which happens when the selection is changed until after the operation that changed the animation is completed. This way, when a non-selected object is dragged, the cameraanimation only happens after the drag operation completes.
Fixes CURA-514
=> Feature delay cameraanimation

resources/i18n/de/cura.po
I just reviewed the translations and some some parts, which I (as native speaker) would translate another way.
The commits in this PR should be good documented.
Would love to see feedback ( maybe from @TMHogenhout ) to understand why you exactly translated things your way.
For example "X-Ray" is untranslated, but I don't see a reason, why you don't use "Röntgen". I don't think it sounds so bad.
=> i18n: de: Set of (better) translations for german

cura/CuraApplication.py
As I upgraded my computer to a developer version of Ubuntu, I noticed that the OpenGL module, which is needed for our workaround, is currently broken.
So I browsed the web and found the reason why it is needed at all and found a alternative.
The reason for the problem is that Qt5 is dynamicly loading libGL.so instead of libGL.so.1, as the OpenGL module loads libGL.so.1.
So if you install the closed-source nvidia drivers it only creates a link from libGL.so.1 to it's binaries and the result is that PyQt5/Qt5 tries to load Mesa binaries together with NVidia binaries.
By importing the OpenGL module you preload the libGL.so.1, but this can also be done directly by using ctypes.
* Replaced the OpenGL fix with the ctypes fix
* Added a TODO
=> Alternative fix for NVidia graphic cards

resources/machines/ultimaker.json, resources/machines/ultimaker2.json, resources/machines/ultimaker2_extended.json, resources/machines/ultimaker2_extended_olsson.json, resources/machines/ultimaker2_extended_olsson_025.json, resources/machines/ultimaker2_extended_olsson_040.json, resources/machines/ultimaker2_extended_olsson_060.json, resources/machines/ultimaker2_extended_olsson_080.json, resources/machines/ultimaker2_olsson.json, resources/machines/ultimaker2_olsson_025.json, resources/machines/ultimaker2_olsson_040.json, resources/machines/ultimaker2_olsson_060.json, resources/machines/ultimaker2_olsson_080.json, resources/machines/ultimaker_original.json, resources/profiles/ultimaker2_olsson/0.25_high.curaprofile, resources/profiles/ultimaker2_olsson/0.4_fast.curaprofile, resources/profiles/ultimaker2_olsson/0.4_high.curaprofile, resources/profiles/ultimaker2_olsson/0.4_normal.curaprofile, resources/profiles/ultimaker2_olsson/0.6_normal.curaprofile, resources/profiles/ultimaker2_olsson/0.8_fast.curaprofile, resources/qml/WizardPages/AddMachine.qml, resources/qml/WizardPages/SelectUpgradedPartsUM2.qml
Adds a "Select Upgraded Parts" wizard page when adding an UM2 or UM2 Extended, allowing the user to select the Olsson block upgrade. If the Olsson block is selected, the machine gets the same Nozzle options as the UM2+, but without the material options. For UM2 machines we still have the philosophy that material is chosen on the printer.
This PR also adds a set of ultimaker2_olsson profiles, which are based on the ultimaker2+ profiles but have the material-specific properties removed.
Also see https://github.com/Ultimaker/Uranium/pull/110
Fixes CURA-91
=> Support UM2 with Olsson block

resources/i18n/de/cura.po
Just found another translation error.
This commit corrects "Bereit zum Über USB drucken" into "Bereit zum Drucken über USB".
It is almost related to another set of corrections I sent before, but didn't found this one as I didn't had my printer connected.
=> [2.1] i18n: de: Correcting tooltip

plugins/USBPrinting/USBPrinterManager.py
* Requires https://github.com/Ultimaker/cura-binary-data/pull/2
=> USBPrinting: Adding entry for BQ Hephestos 2 firmware

cura/CuraApplication.py, resources/qml/GeneralPage.qml
When objects have been modeled with meters as units, they become so tiny that the cannot be selected in Cura to be scaled up.
See https://github.com/Ultimaker/Cura/issues/697#issuecomment-209518061
Also see https://github.com/Ultimaker/Uranium/pull/132
=> Add a preference for scaling up tiny objects

resources/machines/bq_hephestos_2.json
"support_enable" is already set as "enabled": false in fdmprinter.json.
So this line is unneeded here.
=> BQ Hephestos2: Removing override of support_enable

resources/machines/bq_hephestos_2.json
This is already default at https://github.com/Ultimaker/Cura/blob/master/resources/machines/fdmprinter.json#L115
=> BQ Hephestos2: Removing machine_gcode_flavor

CMakeLists.txt
While discussing on #718 I noticed that the splash screen still shows "master" when built from [2.1].
This sets the version to 2.1.2.
=> [2.1] Set default version to 2.1.2

cura_app.py
'os' is already imported at the beginning of the file.
=> Removing unneeded import of 'os'

resources/definitions/grr_neo.def.json
NEO Firmware moves head 1cm to the right after Y endstop is pressed. This shrinks build volume to 14cm width. With this extra commands, the head moves back to the endstop. Now 15cm width builds are possible.
Additional Commands:
G91
G1 Y-10.0000 F9000
G92 Y0
G90
=> support prints up to 15cm width with GRR NEO Printer

resources/definitions/fdmprinter.def.json
Needs an icon in resources/themes/cura/icons
=> CURA-1284: Changing icon for experimental category

plugins/USBPrinting/ControlWindow.qml
I think this sounds better, because I understand "USB" as an technology. So you wouldn't say "Print with USB", but would fit if you say "Print with USB cable". So "Print via USB" should be more correct here.
=> Better call it "Print via USB"

resources/definitions/bq_hephestos_2.def.json
When starting a print with the "custom" GCode by BQ, the printer resets
the nozzle temperature to 210°C when printing via SD card (no matter
what you set on Cura) and only preheats the nozzle to 180°C when
printing via USB.
So currently the printer begins to print via USB at 180°C and reaches
the correct temperature eg. while printing the brim.
=> BQ Hephestos2 - Preheating temperature fix

resources/definitions/bq_hephestos_2.def.json
Saves time and preheats the nozzle to the correct temperature (set by Cura).
Btw. the BQ support explained me the reason why they are assuming 210°C needs to set here. The reason is that the printer is just meant to be used with PLA, so they are only expecting to use exactly 210°C. Just explained them why this is incorrect when think about the possibility that Cura can set the temperature on it's own.
=> BQ Hephestos2: Heat up nozzle while leveling

plugins/GCodeProfileReader/GCodeProfileReader.py, plugins/GCodeWriter/GCodeWriter.py
The exported data is now the same as you can find in .curaprofile files, but when deserializing the data back into a ContainerInstance and returning the new container like done in ```CuraProfileReader``` the imported profile still does not appear in the "settings window -> profiles".
I even get this error when "reimporting" the same container again:
```[35m2016-06-23 19:38:18,136[0m - [33mWARNING[0m - [37m.../UM/Settings/ContainerRegistry.py (addContainer [238]): Container of type <class 'UM.Settings.InstanceContainer.InstanceContainer'> and id BH2_SimpleCube_10mm already added[0m```
Would be great if someone could give me hints on that.
Thanks!
=> [CURA-1615] GCodeProfileReader/-Export: Rework

plugins/CuraEngineBackend/CuraEngineBackend.py
Don't know how much lines we will need exactly, but I think 200 are
enough for the moment.
Contributes to CURA-1775
=> [CURA-1775] CuraEngineBackend: Keep the last 200 lines of logged messages

plugins/SolidView/SolidView.py, resources/shaders/striped.shader
This PR adds a two-color stripe-pattern to objects that are not entirely inside the buildvolume. This way they can not be confused with objects that are rendered with a (future) grey materialcolor.
There is no CURA-issue for this, hence the PR.
=> Stripe objects that are outside the build volume

cura/CuraApplication.py, resources/qml/SaveButton.qml
Contributes to CURA-271, but can hopefully be used to extend other areas of the gui in the future (eg plugin preferences on the general page, ...)
=> Add mechanism for plugins to add controls to designated areas in the GUI

plugins/3MFReader/ThreeMFReader.py
This commit adds a selftest before the "result" gets returned.
It should break on this/these functions and popup a message about using
the online repair tool.
I compared the content of both files for a long time, googled about the
format, but wasn't able to find a proper fix.
More routines will likely need to be added here, but with those I have
it is working so far very well.
Sadly it is not possible to override the default message, so two
messages will appear. Additionally, the URL of the link is not
clickable/executable from the UX. Just acting like normal text.
Contributes to CURA-1223
=> [CURA-1223] 3MFReader: Doing selftest and fail on broken files

plugins/LayerView/LayerView.py
The current implementation of layerview only shows a grey "ghost" of the currently selected object. If the user enters layerview without an object selected, she is presented with an empty buildplate until slicing is completed and layers are processed.
This PR shows a ghost for all objects instead of only for the selected object(s), this giving the user a decent view of where objects are located and where to click to select an object.
CURA-1601 is slated for a later sprint, but it seems such a shame to delay this now that we have made such great improvements to Layer View.
=> Show "ghosts" for all objects on the buildplate in layerview

cura/CuraApplication.py, cura_app.py
Also needed for https://github.com/Ultimaker/cura-build/pull/68, as Python3 built in cura-build thinks it is on "debian".
=> Updating NVidia workaround

resources/definitions/fdmprinter.def.json
The settings are general enough to be used in other situations where Cura/CuraEngine may want to do autospeed computation.
These are the settings definitions that expose the settings introduced in Ultimaker/CuraEngine#376
=> New settings to allow control over automatic speed changes for merged infill lines

plugins/CuraEngineBackend/CuraEngineBackend.py
So far I ran 2 or 3 times into the problem that my engine was not up to
date. The bad thing here is that there is always an updated version from
my PPA on the PC. So first this commit gives the possibility to look for
CuraEngine in the $PATH directories. Before I had to copy it always
manually, eg. via "cp $(which CuraEngine) bin/CuraEngine" in my
workbench.
Second, people can get into the situation that CuraEngine is missing at
all. So before making Cura loop and try to use an executable that does
not exist, better raise an Exception here.
An additional info message tells about the location being used.
Does not contribute to any JIRA issue (I think), but makes my life
easier.
=> Scanning for CuraEngine and stop if it was not found

resources/qml/JobSpecs.qml
I think it makes sense to add this character here, because the amount needed is only a approximated value, and without the end-user might expect a more accurate value.
=> Adding "approximately equal" to the amount of material needed

plugins/USBPrinting/USBPrinterOutputDevice.py, plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Looking at the old code shows that the download process was never
completely finished. The according function was only return'ed, but no
signal was emitted to the window to give the user the possibility to
close it again.
Optionally, it would be useful here to pass messages to the window
dialog to inform the user about problems.
However, this code is untested because:
1. I don't know where put my printers *.hex-file, when coding here with
my editor,
2. Have no idea how to reproduce the IO errors reported at JIRA, so
fingers crossed here.
Contributes to CURA-2079
=> CURA-2079: Finish firmware upload process on errors

plugins/USBPrinting/FirmwareUpdateWindow.qml, plugins/USBPrinting/USBPrinterOutputDevice.py, plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Just read https://github.com/Ultimaker/Cura/commit/0435706736b165cbb83b9a58c09dbc5ce2b21f06
and take a look at the code.
Short: Added different error messages, which appear whenever a exception was catched.
=> [CURA-2079] Adding detailed error messages to firmware updater dialog

resources/machines/innovo-inventor.json
Made some changes to the Inventor JSON file:
- made machine center is zero true
- added turn heated bed off to end g code
- changed top/bottom thickness from 0.30mm to 1.2mm (don’t know why I
put it to 0.3 in the first place!!)
- changed material bed temp to 0 by default
As for the STL file, it’s been updated to a much smaller file, 810kb
(down from 13mb).  I thought I updated this before but apparently not.
I hope this update can be merged soon, because I plan on launching a
makerspace with these printers and everyone will be using Cura so they
need these settings
=> Update Innovo Inventor JSON and STL files

cura/Settings/ContainerSettingsModel.py, cura/Settings/ExtrudersModel.py, cura/Settings/QualitySettingsModel.py
setItems sets the items to a (presorted) list of items instead of adding items one by one and then sorting the list. This way if an update to the model causes a signal storm at least it happens only once for an update.
Specifically this reduces switching to a dual extrusion printer by half.
Requires https://github.com/Ultimaker/Uranium/pull/163
Contributes to CURA-2193
=> Use ListModel.setItems() instead of appending one item at a time

resources/qml/MonitorButton.qml
Tested while starting two prints and aborting them. The buttons for
"Yes" and "No" are translated by Qt5.
=> CURA-2157: Adding an confirmation dialog

plugins/SliceInfoPlugin/SliceInfo.py
The problem seems to be related to our HTTP(S) server.
It is expected that the problem will be solved after the weekend.
Contributes to CURA-1445
=> [CURA-1445] SliceInfo: Using HTTPS again

plugins/CuraEngineBackend/StartSliceJob.py, plugins/X3DReader/X3DReader.py, plugins/X3DReader/__init__.py
Initial support for the X3D scene file format (see http://www.web3d.org/).
For now, just mesh import. Supports all mesh geometry nodes in Rendering, Geometry3D, Geometry2D,  and CAD geometry modules, specifically:
- Box 
- Cone 
- Cylinder 
- Sphere
- ElevationGrid 
- Extrusion 
- IndexedFaceSet
- IndexedTriangleFanSet
- IndexedTriangleSet
- IndexedTriangleStripSet
- TriangleFanSet
- TriangleSet
- TriangleStripSet
- IndexedQuadSet 
- QuadSet
- Disk2D
- Rectangle2D
- TriangleSet2D
No support for materials, color, or textures. Normals in the file (if any) are ignored. Light sources, viewpoints, sensors, world, shaders, scripts also ignored.
There are some more geometries in the standard: Text, GeoElevationGrid, and 4 NURBS based surfaces. No way I'm hand-tesselating those.
=> Support for the X3D format

cura/Settings/ExtruderManager.py, cura/Settings/ExtrudersModel.py
ExtruderManager.addMachineExtruders is supposed to create a cache, but this cache was always rebuilt because of an indentation error.
This PR does a little refactoring on behavior that had grown because of the error; ExtrudersModel should not respond to the cache being rebuilt, but instead it should respond to when the global containerstack changes to a definition with different extruders.
I came across this when trying to figure out why the ExtrudersModel did not reset when selecting a single extrusion printer after selecting a multiextrusion printer. That is because for single extrusion printers the code was correctly using the cache, which resulted in not updating the ExtrudersModel.
This is in a PR because there is a non-negligible regression hazard, and there is no issue for it.
=> Speed up switching between multiextrusion machines

plugins/SliceInfoPlugin/SliceInfo.py
After an discussion with the developers at YM, we decided to send all data in one keyword.
So now all data is bundled into a JSON dictionary, where "" is the global_container_stack and it's containers go into the same JSON, too, by using their IDs as keywords.
More on JIRA...
Contributes to CURA-1445
Includes/Fixes #1013
=> [CURA-1445] Sending bundle of serialized data

cura/QualityManager.py, cura/Settings/ContainerManager.py, cura/Settings/CuraContainerRegistry.py, cura/Settings/QualitySettingsModel.py
This is a reimplementation of some problems I tried to fix by introducing a "global_profile" metadata entry on quality_changes profiles. In this PR I revert to the way @sedwards2009 implemented profiles (because I did not fully understand it before but it makes more sense to me now)
CURA-2518 and CURA-2478
=> Revert "global_profile" reference changes while refixing import

cura/QualityManager.py, cura/Settings/MachineManager.py, cura/Settings/QualitySettingsModel.py, resources/qml/Actions.qml, resources/qml/Preferences/ProfilesPage.qml, resources/qml/SidebarHeader.qml
Show the warning color for unsupported materials/qualities by using the new 'supported' metadata flag which is read from the quality profile.
CURA-2271
=> Show the warning color for unsupported materials/qualities

cura/Settings/MachineManager.py
When clicking on the little revert arrow for a setting in the UI, it reverts the setting for all extruders not just the one which is currently selected. This PR fixes this and just changes the current extruder.
CURA-2640 Restore to default not per extruder
=> Only reset the setting for the currently selected extruder.

cura/Settings/MachineManager.py
This PR fixes an error when starting Cura without an active machine.
This should be applied to both the 2.3 and master branch; the "critical" unhandled exception error also happens with the released 2.3.0, but it only shows in the logs. Apropos, shouldn't a "critical" error trigger the CrashHandler instead of failing silently?
=> Fix error when starting with no active machine

resources/definitions/ultimaker2.def.json
This PR adds homing the X/Y axes, which is currently missing. As a result the UM2/UM2+ will not have the correct origin and may start printing outside the build volume if the gcode flavor is set to RepRap (eg for USB printing or for OctoPrint).
It would be nice if this fix could be included in 2.3.1
=> Fix homing UM2/UM2+ when printing with RepRap flavor

cura/BuildVolume.py
This PR adds a small indication at the machine origin. This is especially important for those machines that don't have a machine mesh that shows which end of the buildplate is the front.
The PR renders three thin cubes, similar to how toolhandles draw thick lines. This way the origin axes draw with a bit of body, over the blue-ish buildvolume wireframe cube.
=> Render an indication of the origin of the machine

cura/QualityManager.py
This PR fixes "critical" errors caused (I think) by "empty_material" not having a definition. The error also happens in the 2.3 branch, so it should probably be cherry-picked.
=> Fix errors when switching from UM3 to UM2.

resources/definitions/printrbot_simple.def.json
Mesh is drawn too high. See https://ultimaker.com/en/community/23473-23-for-printrbot-cura-is-placing-the-model-too-low-and-i-cant-move-it
=> Fix printrbot simple mesh alignment to buildplate grid

cura/CuraApplication.py, resources/qml/Actions.qml, resources/qml/Cura.qml, resources/qml/MultiplyObjectOptions.qml
This PR adds a dialog to allow the user to set the number of copies when duplicating models.
The copies are still naively set in the center of the buildplate, after which it is up to the buildplate physics to push them apart.
=> Add dialog to set number of copies when duplicating models

cura/PrinterOutputDevice.py
This PR fixes the PrinterOutputDevice._startCamera and PrinterOutputDevice._stopCamera stubs, which have a unused and not supplied required argument. This results in a critical error being logged when a printeroutputdevice subclass does not override _startCamera and/or _stopCamera (eg USBPrinterOutputDevice, or OctoPrintOutputDevice)
CURA-2411
=> Remove unused required argument on _startCamera and _stopCamera

resources/qml/Cura.qml
UM.MainWindow does not derive from QML Item, so it does not have a forceActiveFocus() method.
CURA-2835
=> Fix blurSettings

plugins/X3DReader/X3DReader.py
This change allows reading X3D IndexedTriangleSet nodes in which the list of coordinates contains commas as separators. Commas  are permitted by the specification of the XML encoding of the X3D standard: see ISO/IEC 19776-1:2015	(X3D Encoding:XML V3.3) Section 5.1.2;
http://www.web3d.org/documents/specifications/19776-1/V3.3/Part01/EncodingOfFields.html#5.1.2
=> Modify reading of Coordinate/@point attribute to allow comma separators

README.md
The readme contains a number of links to plugins, but the OctoPrint plugin is missing.
=> Add link to OctoPrintPlugin

plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
When sending data to a UM3, gcode postprocessing is not performed because of a missing writeStarted emit.
From OutputDevice.py:
"output device subclasses are completely free to implement writing however they want, though you should emit writeStarted and related signals whenever certain events happen related to the write process."
=> Allow postprocessing before sending data to the printer

cura/BuildVolume.py, plugins/MachineSettingsAction/MachineSettingsAction.qml, resources/definitions/fdmprinter.def.json
This PR provides an option to change the build plate shape to elliptic for polar printers.
An elliptic build volume is drawn, and disallowed area polygons are added so that only an elliptic area remains.
=> Initial support for elliptic build plate shape

resources/qml/Sidebar.qml, resources/qml/SidebarHeader.qml, resources/qml/SidebarSimple.qml, resources/qml/SidebarTooltip.qml, resources/themes/cura/theme.json
This PR is a proposal for some fixes to the theme. It builds on @jackha's extruder tab branch.
* Make extruder-tabs more clear on badly calibrated displays
I have seen a lot of screens (mainly running Win10) that are so badly calibrated that our viewport background color looks exactly the same as the sidebar color. I have added a highlight line to selected tab to make it more clear which tab is selected. The highlight design matches the website UM3 style in shape/style (eg new forum post indicator, selected site section).
* Move printer selection to the top bar
This makes more effective use of the sidebar screen realestate. It was also suggested by Oak & Morrow in their review of pre-2.1.
* Make infill selection same width as other "Recommended" controls
The improved "Recommended" sidebar …
=> Tweak 2.4 sidebar changes

cura/CuraApplication.py
On certain Linux platforms, urllib in py3 no longer accepts a top-level module import. Restricting the imported modules to just "parse" fixes this issue.
This has been tested and is verified working on the following configuration:
Linux Mint 18 x86 Cinnamon
=> Changed urllib import to be more restrictive

resources/definitions/kossel_pro.def.json, resources/meshes/kossel_pro_build_platform.stl
Kossel Pro is a larger version of the Kossel Mini, which is already represented here.
Source for generating these files can be found here:
https://github.com/dotscad/openbeam/blob/master/kossel_pro_build_platform/
=> Add definition and bed mesh for Kossel Pro

cura/BuildVolume.py
This PR fixes a silly y/z mixup which caused the elliptic buildplate to be wrong if the machine height did not match the machine width
=> Fix elliptic buildplate mesh when machine_height != machine_width

plugins/VersionUpgrade/VersionUpgrade22to24/VersionUpgrade.py
This PR fixes an issue introduced by the version upgrade from 2.3 to 2.4.
Since definition_changes containers are stored in the same folder as their machine_instances, the version upgrade system tried to upgrade them as containerstacks. This PR ignores definition_changes containers when looking at container stacks.
=> Make sure definition_changes containers are not upgraded to stacks

plugins/VersionUpgrade/VersionUpgrade22to24/VersionUpgrade.py
This PR fixes three related issues with the 2.3 to 2.4 version upgrade when there are Machine Settings.
Steps to reproduce the issues:
* Launch Cura 2.3.1 with an empty config
* Add a UM2
* Open machinesettings
* Close Cura 2.3.1 and launch Cura 2.4
Result: the UM2 cannot be loaded, because the versionupgrade screws up.
=> Fix version upgrade with user variants

resources/qml/Sidebar.qml
This PR tweaks the theming of the machine selection button to match the other controls in the header bar. It irks me that the machine selection widget behaves differently from the other two buttons. It is a purely cosmetic change.
=> Tweak the hovered state of the machine selection

resources/definitions/fdmprinter.def.json
This pull req creates a setting to change the skin pattern for just the first layer. I like concentric skin for bed adhesion but not for anything else so this allows to set just the layer that does the bed adhesion to concentric.
I've used this for a while but now I decided to make a PR for it, it was tested on the Ultimaker 2 printer.
=> Add a setting to select skin pattern for first layer

resources/definitions/printrbot_simple.def.json
Print head size settings for printrbot simple had y min and y max mixed up,
making "print one at a time" always print in the wrong order.
=> Correct y axis print head size for printrbot simple

plugins/USBPrinting/avr_isp/stk500v2.py
stk500v2 failed to release the serial port on timeout. Fixes Cura unable to connect to not arduino based printers on Windows. Bug did not occur on Linux due to different serial port behavior.
=> Fix connections to devices not based on arduino

resources/qml/Sidebar.qml, resources/qml/SidebarHeader.qml
This PR ensures the selection of profiles (variant/material/quality) is not shown when hiding the settings (eg when showing a gcode file). Showing the dropdown boxes for profile selection enables the user to change settings, and this should not be possible.
=> Hide profiles selection when hiding settings

cura/BuildVolume.py, resources/definitions/fdmprinter.def.json
This PR fixes how Cura determines the disallowed areas when machine_center_is_zero is true. It fixes https://github.com/Ultimaker/Cura/issues/1232
The PR contains a minor hack to ignore the extruder prime position when it is not set in the printer definition. Without this hack, Cura plonks a fairly large disallowed area in the center of the buildplate, because the extruder_prime_position is not settable inside Cura and it defaults to (0,0).
=> Fix prime disallowed areas when center is zero 

resources/definitions/fdmprinter.def.json
This allows the user to specify in mm^2 the minimum area of infill regions.
Areas smaller than this will be merged into the surrounding skin rather
than being filled with infill.
=> Added min_infill_area setting.

cura/CuraApplication.py, cura/PrintInformation.py, resources/qml/JobSpecs.qml, resources/qml/Preferences/GeneralPage.qml, resources/qml/Preferences/MaterialView.qml, resources/qml/Preferences/MaterialsPage.qml
This PR implements the forgotten material cost feature.
In this PR, filament weight per spool and cost per spool are stored per material guid in the preferences (instead of in the material profile). It can be argues that the price (and to a lesser extend the spool size) is not a material property but something that is set eg by the reseller. Furthermore this enables editing these values for readonly materials without affecting the xml profile.
Filament length on the spool as well as cost per meter are calculated on the material view tab.
TODO:
* ~~use cost per meter to calculate print cost on the print stats area~~
* ~~make currency a settable preference~~ fixed
=> Implement material cost

plugins/SolidView/SolidView.py
This PR fixes an error rendering unsliceable (striped) meshes, and adds theming for the color of overhang. It is a follow-up to https://github.com/Ultimaker/Cura/pull/1370; sorry I missed these two issues.
=> Fix unslicable model rendering and add overhang color theming

plugins/USBPrinting/USBPrinterOutputDeviceManager.py
This pr adds support for the wch driver. This driver is e.g. necessary to connect an anet a8 to a mac.
=> FEATURE: Support wsh usb driver (for mac)

resources/qml/PrintMonitor.qml
One of the labels in the newly redesigned printmonitor is lacking a color, thus making the hotend temperature unstylable. This PR fixes that.
TL;DR: "Oops, you missed a spot"
=> Add missing label color

cura/CuraApplication.py, plugins/3MFReader/ThreeMFWorkspaceReader.py, plugins/CuraEngineBackend/CuraEngineBackend.py, plugins/LayerView/LayerView.qml, plugins/LayerView/LayerViewProxy.py, resources/qml/JobSpecs.qml, resources/qml/MonitorButton.qml, resources/qml/SaveButton.qml
…between slots & properties
Case in point: LayerViewProxy.getLayerViewType was decorated as a property but was used/intended as a slot. This PR refactors property names to not start with the verb "get".
=> Refactor properties that start with 'get' to avoid confusion

README.md
[WirelessPrinting Plugin](https://github.com/probonopd/WirelessPrinting): Print wirelessly from Cura to your 3D printer connected to an ESP8266 module.
=> Add WirelessPrinting Plugin

resources/qml/DiscardOrKeepProfileChangesDialog.qml
Enable/disable "keep" and "discard" buttons on the Profile Override dialog according to the choice.
=> CURA-3397 Enable/disable "keep" and "discard" buttons according to the choice

plugins/LayerView/LayerView.py, plugins/LayerView/LayerView.qml, resources/themes/cura/theme.json
This PR combines the two sliders in the LayerView with a single rangeslider. The rangeslider has three draggable handles: lower, upper and range. By dragging the range it is possible to always display eg 5 layers.
See #1444
TODO:
* ~fix keyboard control~
* ~use PointingRectangle for the layernumber box~
* ~cleanup~
This is a followup to https://github.com/Ultimaker/Cura/pull/1472, which was against master
=> Use a single draggable range slider in Layerview 

cura/MachineActionManager.py
Fix this crash:
```
Version: 2.4.99-master.20170307132702
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1
Exception:
TypeError: unable to convert a Python 'set' object to a C++ 'QVariantList' instance
```
=> CURA-3470 Return list instead of set for QVariantList

resources/qml/DiscardOrKeepProfileChangesDialog.qml
Fix the problem that the option shown in the override profile dialog is not in sync when the option in the Preferences settings has been changed.
=> CURA-3397 Set override profile preference option upon visibility change

resources/definitions/fdmprinter.def.json, resources/definitions/renkforce_rf100.def.json
This boolean setting controls whether travel moves to the first point in an
outer wall will always involve a retraction. IMHO, forcing a retraction has
two benefits:
1 - avoids taking the ooze that would occur during the travel to the outer
surface.
2 - the slight pause when un-retracting could help reduce any ripples
introduced by the rapid movement hot-end movement.
=> Added combing_retract_before_outer_wall setting.

cura/PrintInformation.py
Fixes this issue:
```
Version: 2.4.99-master.20170309034509
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1
Exception:
File "D:/master/build/inst/lib/python3.5/site-packages/cura\Settings\ContainerManager.py", line 232, in setContainerMetaDataEntry
File "C:\Users\qa_tester\Desktop\Cura 2.4 master\Cura 2.4\plugins\XmlMaterialProfile\XmlMaterialProfile.py", line 43, in setMetaDataEntry
super().setMetaDataEntry(key, value)
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\InstanceContainer.py", line 196, in setMetaDataEntry
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 201, in emit
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 305, in __performEmit
TypeError: …
```
=> CURA-3482 _onMaterialMetaDataChanged() should take an argument

resources/variants/cartesio_0.25.inst.cfg, resources/variants/cartesio_0.4.inst.cfg, resources/variants/cartesio_0.8.inst.cfg
Fixes this issue:
```
Version: 2.4.99-master.20170308115948
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1
Exception:
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Qt\Bindings\ActiveToolProxy.py", line 67, in setProperty
File "C:\Program Files\Cura 2.4.99 2017-03-08 v2\plugins\PerObjectSettingsTool\PerObjectSettingsTool.py", line 70, in setSelectedActiveExtruder
selected_object.addDecorator(SettingOverrideDecorator())
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Scene\SceneNode.py", line 183, in addDecorator
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 201, in emit
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Signal.py", line 305, in __performEmit
File …
```
=> CURA-3480 Fix boolean values for Cartesio config files

cura/Settings/MachineManager.py
Fixes this issue:
```
DEBUG - cura.Settings.MachineManager.setActiveMaterial [708]: Attempting to change the active material to generic_pla_ultimaker3_AA_0.4
DEBUG - cura.Settings.MachineManager.setActiveMaterial [725]: Active material changed
CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
CRITICAL - cura.CrashHandler.show [39]:   File "/Users/ultimaker/build/2.5/build/inst/lib/python3.5/site-packages/cura/Settings/MachineManager.py", line 734, in setActiveMaterial
CRITICAL - cura.CrashHandler.show [39]: AttributeError: 'NoneType' object has no attribute 'getId'
```
=> CURA-3507 Make quality lookup more robust

resources/qml/Preferences/GeneralPage.qml
Adds a way to invert the zoom direction for Cura. A few engineers requested this, as it matches the default solid works behavior better. Also see https://github.com/Ultimaker/Uranium/pull/232
=> Added invert zoom preference option

cura/CuraApplication.py, resources/qml/AskOpenAsProjectOrModelsDialog.qml, resources/qml/Cura.qml, resources/qml/Menus/RecentFilesMenu.qml, resources/qml/Preferences/GeneralPage.qml
Add a dialog asking the user when he/she is opening a Cura project file. He/she can choose to:
1. open as a Cura project, or
2. import models from this project file.
It is possible to set a default option for this. This is configurable in the settings dialog.
Some screenshots:
=> CURA-3495 Open project/models menu

resources/qml/Preferences/MaterialView.qml
This is necessary for currencies such as Japanese Yen or South Korean Won, where prices can easily exceed 1000. This PR sets the limit to 100,000,000. If the price of a spool exceeds this amount, perhaps the user should consider moving to a more stable country.
Fixes https://github.com/Ultimaker/Cura/issues/1567
=> Up the limit of the maximum cost of a spool of filament

cura/PrintInformation.py
While editing the diameter value in the materials pane, it can happen that the radius evaluates to 0. This led to a division by zero.
Fixes https://github.com/Ultimaker/Cura/issues/1582
This needs to be cherrypicked to the 2.5 branch
=> Fix crash when editing material diameter

plugins/GCodeReader/GCodeReader.py, plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
- Change backend state to disabled after reading a gcode so the "save/print" button works
- Fix index issue with `materialLengths`
- Set `Scene.gcode_list` in `GCodeReader`
- Compress GCode line by line in batch so it's waaaaaaaaaaay faster
=> CURA-3604 Fix printing by loading a gcode

plugins/3MFReader/__init__.py, plugins/3MFWriter/__init__.py
By catching the ImportError, this prevents the logs being clogged with exceptions in start and when the plugins preference page is touched.
This PR is useful to keep the barrier of entry for contributing to the Cura project low. I have still not managed to compile lib savitar, and the logs do quickly become clogged up with the exceptions caused by not having a working libsavitar.
Note: this must be tested, because I can only test the case where there is no libSavitar, not the case when there is a libSavitar.
=> Fail gracefully when libSavitar is not found

cura/Settings/MachineManager.py
This pulls the checkStackHaveErrors code out of the critical path when
editing settings, instead moving it to be handled later. This greatly
reduces the delay that happens when editing settings, most noticeably the layer height.
Fixes CURA-3653
Contributes to #1631
=> Fix delays when settings change from error to valid

resources/definitions/fdmprinter.def.json
New PR created as the original was corrupted somehow (based on wrong parent, perhaps?)
=> The magic_spiralize setting is no longer settable per mesh (or extruder).

resources/definitions/fdmprinter.def.json
Reverts Ultimaker/Cura#1660
This shouldn't have been merged to 2.5, but to master.
It's too late to merge anything to 2.5; we're too far into the release process.
=> Revert "The magic_spiralize setting is no longer settable per mesh (or extruder)."

resources/definitions/peopoly_moai.def.json, resources/quality/peopoly_moai/peopoly_moai_high.inst.cfg, resources/quality/peopoly_moai/peopoly_moai_max.inst.cfg, resources/quality/peopoly_moai/peopoly_moai_normal.inst.cfg
This PR adds a definition and a set of quality profiles for the upcoming Peopoly Moai:
https://www.kickstarter.com/projects/1554809440/moai-affordable-high-resolution-laser-sla-3d-print
Note that this printer is an SLA printer. Because of this the definition disables/hides a number of features (materials, temperatures (nozzle, buildplate), fan cooling, retraction, supports). Supports are intended to be added using a different tool before slicing.  
In cooperation with Shu (Mark) Peng from Peopoly
=> Add support for Peopoly Moai (SLA)

plugins/USBPrinting/USBPrinterOutputDevice.py
Moved translated M105s (blank, M0, or M1) above and outside of exception block.
Clarified the error message and added the line to it.
Related to https://github.com/Ultimaker/Cura/pull/1615 conversation.
=> First refactor for Z parse section to increase verbosity

cura/Settings/ExtruderManager.py, cura/Settings/MachineManager.py, plugins/XmlMaterialProfile/XmlMaterialProfile.py, resources/qml/Menus/MaterialMenu.qml, resources/qml/Preferences/MaterialsPage.qml
In Cura, material diameters set in (xml) material profiles override the material diameter set in the machine or variant definition. This causes 1.75mm printers to switch to 2.85mm when selecting eg "Generic PLA". Additionally, 2.85mm machines may show a lot of materials that don't apply to these printers since the merge of a set of materials into the fdm_materials repository.
This PR applies filters to the listed materials so they only show those materials that have relevant diameters. To be robust to 1.75/1.74 and 2.85/3.0 mm materials, the PR takes an approximated material_diameter defined in the printer definition and compares that to the same approximation of the material_diameter defined in the material definition. 
See https://github.com/Ultimaker/Cura/issues/1441#issuecomment-281120 …
=> Filter materials by diameter

resources/qml/Preferences/MaterialView.qml
This PR fixes the print settings showing up as NaN:
See https://ultimaker.com/en/community/41810-retraction-is-nan for discussion
=> Fix NaN values on material print settings tab

plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
This fix no longer sends a temperature update to the printer when Cura receives a bed temperature update from the printer.
We had race conditions where the bed was not shut off at the end of a printer, and Cura is the only possible source of this problem.
CURA-3702
=> Only update the target bed temperature, without submitting it to the printer. To prevent race conditions.

resources/qml/Preferences/GeneralPage.qml
This PR disables flicking the general settings page in the horizontal direction, to match other scrollviews. 
Fixes #1723
=> Make the general settings page options draggable only vertically

resources/qml/Sidebar.qml, resources/qml/SidebarSimple.qml, resources/themes/cura/styles.qml, resources/themes/cura/theme.json
This PR adds hover effects to the new mode switch toggle and enabled support checkbox in simple mode. It also adds themeable colors to the mode switch toggle to make it fit more with the other controls.
It is an alternative to https://github.com/Ultimaker/Cura/pull/1741
=> Fix hover effects

resources/qml/JobSpecs.qml
Fixes this error:
```
file:///.../Cura/resources/qml/JobSpecs.qml:215: TypeError: Cannot call method 'toFixed' of undefined
```
=> Fix TypeError in JobSpec.qml due to material cost being undefined

resources/definitions/ultimaker3.def.json
Due to certain [python floating point limitations](https://docs.python.org/3.5/tutorial/floatingpoint.html), we have a float value representation issue for the original value of "Line Width" for UM3 (see screenshot). This is a small fix for it.
**How to reproduce:**
- Show all custom settings
- Change Line Width value
- Switch profile and get the settings override dialog
- Screenshot above
=> Fix default Line Width float value representation for UM3

plugins/UltimakerMachineActions/UM2UpgradeSelection.py, plugins/UltimakerMachineActions/UM2UpgradeSelectionMachineAction.qml, plugins/UltimakerMachineActions/__init__.py, resources/definitions/ultimaker2.def.json, resources/definitions/ultimaker2_plus.def.json, resources/variants/ultimaker2_0.25.inst.cfg, resources/variants/ultimaker2_0.4.inst.cfg, resources/variants/ultimaker2_0.6.inst.cfg, resources/variants/ultimaker2_0.8.inst.cfg
This PR adds a set of variants that just set the nozzle diameter and nozzle tip diameter. These variants are not used until the machine action sets the has_variants metadata entry.
See https://github.com/Ultimaker/Cura/issues/775#issuecomment-297284176 for discussion
=> Add Upgraded Parts action for UM2 to add support for Olsson block

resources/definitions/fdmprinter.def.json
Smoothing the contours minimises the visibility of the z-seam and for most models is
probably a good idea. Where it is less good is when the model has a fine surface details
which will get mangled by the smoothing. So we should let the user decide whether they
want to smooth or not. The default is true as most of the time it's a good thing.
Relates to https://github.com/Ultimaker/CuraEngine/issues/507.
=> Add smooth_spiralized_contours setting to control smoothing of contours when spiralizing.

cura/PrintInformation.py, plugins/CuraEngineBackend/Cura.proto, plugins/CuraEngineBackend/CuraEngineBackend.py, resources/qml/JobSpecs.qml
This PR lets cura give a time estimate for each of the print features, like support, infill, skin, etc. That lets you know where the printer spends most of its time, so you can adjust the speeds more effectively. For example you could see that the print takes 9h but 7h of that is skin, then changing the skin speed is better than changing the outer wall speed.
The normal time estimate looks the same but it only lists the details of each print feature in the tooltip of the normal time estimate. I can't make a screenshot because it's a tooltip.
Uranium: https://github.com/Ultimaker/Uranium/pull/247
CuraEngine: https://github.com/Ultimaker/CuraEngine/pull/512
=> Time estimate per print feature

plugins/PerObjectSettingsTool/PerObjectSettingVisibilityHandler.py
This PR fixes selecting settings for Per Model Settings when a single extrusion printer is active.
Steps to reproduce issue:
* Add an UM2+
* Load an object
* Go to Per Model Settings
* Select Settings
* Add "Infill Density"
Result:
```
2017-05-10 17:22:58,587 - CRITICAL - cura.CrashHandler.show [36]: An uncaught exception has occurred!
2017-05-10 17:22:58,602 - CRITICAL - cura.CrashHandler.show [39]: Traceback (most recent call last):
2017-05-10 17:22:58,603 - CRITICAL - cura.CrashHandler.show [39]:   File "C:\Users\Aldo\Documents\Code Projects\UM\Uranium\UM\Settings\Models\SettingDefinitionsModel.py", line 331, in setVisible
2017-05-10 17:22:58,607 - CRITICAL - cura.CrashHandler.show [39]:     self._visibility_handler.setVisible(self._visible)
2017-05-10 17:22:58,607 - CRITICAL - …
```
=> Fix selecting settings for Per Model Settings with single extrusion

resources/definitions/fdmprinter.def.json
=> Just like magic_spiralize, smooth_spiralized_contours should not be settable per model/extruder.

cura/CuraApplication.py
This PR extends the zoomrange of the cameratool to better support printers with a buildvolume that is much larger or much smaller than the originally intended (UMO) printer.
See eg https://ultimaker.com/en/community/49326-cura-needs-to-zoom-out-further
=> Extend the zoomrange to cater for smaller and larger buildvolumes

plugins/MachineSettingsAction/MachineSettingsAction.qml
This PR lets users enter negative values for extruder nozzle x/y offsets.
Fixes https://github.com/Ultimaker/Cura/issues/1832
=> Allow setting negative values on extruder offset x/y fields

cura/Settings/ContainerManager.py
This PR is a followup to #1757. It fixes the problem that if the user has a 1.75mm printer active, the Create button would clone the 2.85mm generic PLA which would then be invisible for the current machine.
The fix is to clone the generic PLA material for the current approximate material diameter instead.
=> Fix create material for printers that use 1.75mm materials

cura/Settings/CuraStackBuilder.py
This PR ensures the name (id) of new printer instances does not conflict with definition ids or container instance ids.
Steps to reproduce:
* add a printer named "ultimaker3" (this exact spelling)
* add a printer named "draft" (this exact spelling)
* close and restart Cura
Result:
The added printers are no longer listed.
Fixes https://github.com/Ultimaker/Cura/issues/1840
=> Fix creating conflicting machine names

plugins/3MFReader/__init__.py, plugins/3MFWriter/__init__.py
As MacOS has troubles understanding a dot in a file extension, this pull-request uses only .3mf as a project-extension on a Mac.
The biggest downside is that Mac-users can immediately identify a Cura-project file, but the upside is that we won't have weird file extensions (e.g. .curaproject.3mf.curaproject.3mf.curaproject.3mf)
CURA-3886
=> Use .3mf on MacOS as project extension

cura/LayerPolygon.py, resources/definitions/fdmprinter.def.json
This implements the basic ironing technique: Just horizontal ironing.
Ironing causes the nozzle to go over the top surface once again while extruding only very little material. This makes the top surface very smooth.
These settings are now in the Experimental category. As far as I'm concerned they can be put in the normal Shell category, since the technique is reliable.
See also the accompanying pull request in the engine: https://github.com/Ultimaker/CuraEngine/pull/534
Implements CURA-3903.
=> Horizontal Ironing

resources/qml/Preferences/GeneralPage.qml, resources/themes/cura/theme.json
This PR builds on https://github.com/Ultimaker/Uranium/pull/252 to show a list of available plugins instead of the current "list" that is hardcoded in GeneralPage.qml
=> Get a list of available themes instead of the hardcoded list

plugins/CuraEngineBackend/StartSliceJob.py
This PR fixes an issue which causes settings to be ignored if a Custom FDM Printer is used with the number of extruders set to 1. Fixes https://github.com/Ultimaker/Cura/issues/2007
When there is 1 extruder, the frontend stores all settings in the global stack. Sending an extruder stack confuses CuraEngine into using the values of the extruder stack, which results in defaults being used.
Basically, single extrusion Custom FDM Printers are broken at the moment, so if there were a point-release for Cura 2.6 it would be great if this fix could be included.
Steps to reproduce:
* Add a Custom FDM Printer
* Keep number of extruders to 1, keep diameter at 2.85
* Slice an object, and note down the estimated length of material.
* Change the diameter to 1.75 in the sidebar
* Note that after slicing …
=> [2.6] Don't send extruder stack to CuraEngine when there is only 1 extruder

plugins/LayerView/LayerView.qml, resources/qml/Cura.qml
This PR makes the layerview panel hug the bottom, when the window is to small to vertically fit the panel underneath the view mode button.
Fixes #2013
=> Fix layerview on small windows

.gitignore
`gitignore` contains the directory `debian/`, which is normally used for storing Debian packaging information.
This directory is not part of Cura and will probably never be. However, adding it to `gitignore` interferes with out-of-tree modifications, as it will mask changes to files in this directory. This is not a problem for Cura developers, but a major problem for anyone who works with packaging information.
I propose the removal of this directory from `gitignore`. It is the responsibility of all Cura developers to make sure there are not inadvertent commits to the project.
Thank you!
=> Remove debian/ from gitignore

plugins/LayerView/layers3d.shader
This change fixes a problem where a sequence of lines that have different widths are displayed
with the widths shifted by 1, i.e. line 1 had the width of line 2 and so on.
Fixes https://github.com/Ultimaker/Cura/issues/2026
=> In geometry41core, take the line width/depth from the second vertex rather than the first.

resources/qml/Settings/SettingCategory.qml, resources/qml/Settings/SettingCheckBox.qml, resources/qml/Settings/SettingComboBox.qml, resources/qml/Settings/SettingExtruder.qml, resources/qml/Settings/SettingItem.qml, resources/qml/Settings/SettingOptionalExtruder.qml, resources/qml/Settings/SettingTextField.qml, resources/qml/Settings/SettingView.qml, resources/themes/cura/styles.qml
This PR adds tab-navigation between fields in the (custom) sidebar; it allows the user to tab/shift-tab between fields in the sidebar, making it quicker to make changes. Checkbox items can be operated with the spacebar, as can category headers. Comboboxes can be operated by the spacebar and/or up/down cursor keys.
=> Add tab navigation to sidebar

cura/ConvexHullDecorator.py, resources/definitions/fdmprinter.def.json
This PR adds functionality to change the Horizontal Expansion for the first layer only. This can be used to compensate for "elephant's foot".
See Ultimaker/Cura#1573 for discussion
Also see CuraEngine PR https://github.com/Ultimaker/CuraEngine/pull/540
=> Add a setting for Horizontal Expansion for the first layer

plugins/LayerView/LayerView.qml, resources/qml/Toolbar.qml
This PR uses https://github.com/Ultimaker/Uranium/pull/261 to clean up the use of pointing rectangles with a border. For consistency it also adds a border to the layerview panel.
CURA-3994
=> Replace mock borders with true borders

resources/definitions/fdmprinter.def.json
Due to the incompatibility of legacy Marlin gcode with the gcode that is supported by RepRap firmwares (as used by the Duet family of controllers), this new gcode flavor has been created to support the latter.
I don't think it should be called "RepRap (Duet)" because that ties it to a particular product. Instead, I think it should be "RepRap (RepRap)" so that it can be applicable to all firmwares that are based on the RepRap source (that is until they diverge!)
=> Refactor gcode flavors to better match the target firmwares

plugins/PluginBrowser/PluginBrowser.py, plugins/PluginBrowser/PluginBrowser.qml
This PR improves the plugin browser UI in a couple of ways:
* Uses a proper system-styled progress bar instead of a Cura-styled progressbar, since the dialog uses the system style
* Adds a way to cancel long downloads and properly cancels download when closing the window during a download
* Shows why a download button is disabled when a plugin is already installed 
It would be nice to be able to open the plugin browser through the Plugins page of the preferences, but that is tricky because that is a Uranium page and Uranium does not know about the Plugin Browser.
=> Improve plugin browser ui

resources/qml/Settings/SettingView.qml
Scrolling the sidebar feels rather slow one line at a time (at least when using the scroll wheel; my Ubuntu laptop is able to use the "fling" mechanics with the touchpad).
This PR adjusts the scroll to be three lines/rows at once (the default scroll speed in Windows). If it seems a bit too fast, two lines (`50`) would be my fallback.
Comparison GIFs:
=> Speed up sidebar-settings scrolling

plugins/UltimakerMachineActions/UMOUpgradeSelection.py
This PR fixes setting the upgrade option (heated bed) for the UMO, which got broken here:
https://github.com/Ultimaker/Cura/commit/81e07b153071edb783d33f799785125cf58d6cf1#commitcomment-23006662
```global_container_stack.definitionChanges``` always returns a container, ```global_container_stack.findContainer({"type": "definition_changes"})``` does not (because an empty container does not have the type "definition_changes".
=> Fix creating a new definition_changes container

resources/qml/Toolbar.qml
This PR hides the extruder button in the toolbar if a Custom FDM Printer has its number of extruders set to 1 in Machine Settings. Before this PR, there would be a single extruder button to set the extruder of the currently selected object(s). For a single extrusion printer, this button serves no purpose.
=> Hide the extruder button for Custom FDM Printers with 1 extruder

plugins/MachineSettingsAction/MachineSettingsAction.py, plugins/MachineSettingsAction/MachineSettingsAction.qml
This PR adds tooltips to the Machine Settings dialog to clarify some of its settings. It also fixes setting the nominal diameter of the machine.
In 2.6.x, the material diameter set in the Machine Settings would always be overridden by the diameter set in the material container. In this PR, the material container is switched to an appropriate material when changing the material diameter field.
Most tooltips are directly from the property provider, though some tooltips are overridden for clarity in the context of the machine settings dialog.
The code has been restructured for less verbosity, using reusable components instead of repeating the same QML code over and over.
=> Add tooltips to Machine Settings and fix setting diameter

plugins/LayerView/LayerView.qml
Before it was using the system's default, which is not that nicely visible, if you are using a dark theme.
Now it looks like this:
Belongs to no JIRA issue.
=> LayerView: Set color for comp. mode text

plugins/3MFReader/WorkspaceDialog.qml, plugins/ChangeLogPlugin/ChangeLog.qml, plugins/MachineSettingsAction/MachineSettingsAction.qml, plugins/PerObjectSettingsTool/PerObjectCategory.qml, plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml, plugins/UM3NetworkPrinting/DiscoverUM3Action.qml, plugins/UltimakerMachineActions/UMOCheckupMachineAction.qml, resources/qml/AboutDialog.qml, resources/qml/DiscardOrKeepProfileChangesDialog.qml, resources/qml/OpenFilesIncludingProjectsDialog.qml, resources/qml/Preferences/MachinesPage.qml, resources/qml/Preferences/MaterialView.qml, resources/qml/Preferences/MaterialsPage.qml, resources/qml/Preferences/ProfileTab.qml, resources/qml/WorkspaceSummaryDialog.qml
This PR fixes text rendering in system-themed qml by rounding fractional widths and heights.
Depending on window/dialog sizes, Label elements could be rendered at fractional pixel offsets. The Text.NativeRendering renderType does not handle that nicely, leading to ugly font rendering on Windows and OSX. In an attempt to fix this, some Labels were switched to Text (which uses Text.QtRendering rendertype). Unfortunately this leads to font-rendering that is distinctively non-native on Windows. Furthermore, Text does not use the system-themed colors used by Label, leading to unreadable text in dark-themed systems (black on black).
By rounding all widths/heights to whole pixels, Text.NativeRendering can be used without rendering problems.
Depends on …
=> Fix system-themed text rendering

cura/Settings/MachineManager.py, plugins/USBPrinting/USBPrinterOutputDeviceManager.py
This PR replaces the homebrew platform-specific serial port enumeration with functionality provided by pySerial. This prevents us from having to chase all iterations of tty|cu.\*usb|rfcomm\*, and should make serial port detection work with more printers.
This PR is a backport of a fix in the Lulzbot edition of Cura (where it has been extensively tested): https://code.alephobjects.com/rCT14f9814802f4384ef255327afc26ac3156e9539d. It has also been tested here: https://github.com/Ultimaker/Cura/pull/1999#issuecomment-314276734. It is an alternative to https://github.com/Ultimaker/Cura/pull/1999
=> Use pyserial to list serial ports

cura/PrinterOutputDevice.py, plugins/UM3NetworkPrinting/MonitorItem.qml, resources/qml/Cura.qml
This PR makes sure the camera image adapts to the available size in the window. Cura 2.6 did the same thing, but this was missing since the refactor of the camera image in Cura 2.7.
Steps to reproduce the issue: 
switch to the monitor view and make the window as small as it will go.
Result:
the image will be cut off, and could even overlap the topbar (making it hard to return to the "prepare" tab. 
The issue is even more of a problem for users of the OctoPrint plugin, where the camera image can be much larger than the UM3 image (eg 1920x1080). A separate fix for the OctoPrint plugin is in preparation, but it relies on this PR.
It would be nice if this could be cherry picked for Cura 2.7.
=> Adapt camera image to available space

.gitignore, resources/qml/Preferences/GeneralPage.qml
This be addin' the Pirate language to Cura, in the spirit of Talk Like a Pirate Day.
The Pirate language be only selected on the 19th of September in Cura's UI. Yowl, after selecting it the language be not deactivated automatically or anything, once the 19th has passed. Ye can also counterfeit yer cura.cfg file if ye be a scallywag like that, by setting the language to `7s`, the language code fer the Seven Seas.
Commandeer requests to keep in yer spyglass too:
* https://github.com/Ultimaker/Uranium/pull/273
* https://github.com/Ultimaker/cura-binary-data/pull/7
=> Pirate Speak

cura/Settings/MachineManager.py, resources/qml/Menus/MaterialMenu.qml, resources/qml/Menus/NozzleMenu.qml
This PR fixes the application menus for materials and variants for multiextrusion printers. All extruder menus would always act on the currently active extruder only, instead of acting on the extruder suggested by the menu. 
**Reproduce steps:**
* Add a new UM3 printer to Cura, do not connect it
* Note that both extruders have PLA for material and that Extruder **1** is the selected extruder tab in the sidebar.
* From the Settings application menu, choose Extruder **2** -> Material -> ABS
**Expected result:**
The material of Extruder 2 (2nd tab) changes
**Actual result:**
The material of Extruder 1 (1st tab) changes instead
The PR fixes #1641, an issue that has been open since Cura 2.3. It may or may not have gotten a JIRA ticket nr.
=> Fix multiextruder menus

cura/Settings/CuraContainerStack.py
This PR fixes the issue that a 1.75mm printer more often than not gets a 2.85mm material assigned by default.
Fixes this: https://github.com/Ultimaker/Cura/issues/2270#issuecomment-323577901
Probably a good idea to cherry-pick this to 2.7, but I don't know if this fix is still in time.
=> Find a material with the correct diameter when adding a printer

README.md
This PR removes the link to definition generator and some incorrect instructions. The definition generator produces definitions that don't work with Cura 2.3 and newer. It also adds some instructions for multi-extrusion printers.
=> Fix readme section about making definitions

README.md
[WirelessPrinting](https://github.com/probonopd/WirelessPrinting) now uses a subset of the OctoPrint protocol because this is supported by Cura by default now
=> Remove WirelessPrinting Plugin

plugins/MachineSettingsAction/MachineSettingsAction.qml
This PR fixes setting the Gantry height setting in Machine Settings. Before this PR, the setting would be correctly added to the definition_changes container, but the buildvolume would not be updated. That means that Cura needs to be restarted, or the active stack needs to be switched before the buildvolume updates.
Fixes an issue uncovered here:
http://elb-v2-prod-615036279.eu-west-1.elb.amazonaws.com/en/community/50595-cura-27-beta?page=4&sort=#reply-187977
Would be nice if this could still make it in to 2.7, but I understand if it doesn't. There are workarounds for the bug.
=> Fix setting the Gantry height setting in Machine Settings

plugins/PluginBrowser/PluginBrowser.py, plugins/PluginBrowser/PluginBrowser.qml
CURA-4222
If a downloaded plugin contains a license file, a dialog which contains
the license information will pop up. The user has to accept the license
before he/she can install the plugin.
If a plugin doesn't have a license file, after it is downloaded, it will
be installed directly just like before.
=> Let user accept/decline a plugin license if present

plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py, resources/qml/PrintMonitor.qml
This PR shows the target hotend temperature(s) in the print monitor, similar to how the target temperature for the bed is shown.
Note: I don't have an UM3. I have tested this PR with the OctoPrintPlugin. The code change for the UM3 is fairly trivial, but untested.
=> Show target hotend temperatures

CMakeLists.txt
This commit is needed for https://github.com/probonopd/Cura/commit/b9970d57b48b31f217f08fb652e5e39f1e55f3bb
Never tested it, but believing the author of the commit that this change will work.
=> Install cura icon on Linux

resources/definitions/fdmprinter.def.json
Can now specify that the z-seam should be located in either the most concave region of the
outline, the most convex region or the most curved (concave or convex) region.
See https://github.com/Ultimaker/CuraEngine/pull/590.
=> Add further options to z_seam_type.

plugins/UM3NetworkPrinting/NetworkPrinterOutputDevice.py
This PR prevents a possible memory leak while showing a stuck camera stream by flushing the stream buffer and restarting the stream if the stream buffer gets unrealistically large.
Note: I don't have an UM3 to test this with. The 2000000 is an arbitrary number. I don't think any 800x600 jpg frame will realistically be larger than that.
Note 2: Interestingly I have not received any similar memory leak reports from OctoPrintPlugin users, though it uses the same code as UM3NetworkPrinting. It could be the specific version of mjpgstreamer in the UM3 that is acting up.
=> Prevent a possible memory leak while showing a stuck camera stream

plugins/USBPrinting/USBPrinterOutputDevice.py
This PR removes homing the bed from the abort sequence. On printers that home the bed to the bottom (ie: printhead moves towards the bed), homing the bed when aborting a print could cause the printhead to crash into the aborted print.
Fixes #2307 and #2344
=> Remove home bed from abort sequence

resources/themes/cura-light/styles.qml
This PR makes the Monitor button have the same behavior as the Prepare button, in regards to its hover state. Before this PR, the Monitor has no underline when hovered, while the Prepare button does.
=> Fix hover state of Monitor button in the topbar

cura/CuraApplication.py
When grouping nodes, add a ConvexHullDecorator to the group SceneNode.
When multiplying the group it was crashing because it didn't have the ConvexHullDecorator.
=> add ConvexHullDecorator when grouping

resources/definitions/fdmprinter.def.json
This can save some time if only the highest layer of your print needs to be smooth.
See also https://github.com/Ultimaker/CuraEngine/pull/603 for the implementation of this setting.
=> Add setting to only iron the highest layer of a mesh

resources/definitions/prusa_i3_mk2.def.json
The current Prusa i3 MK2 GCode in Cura first homes the extruder, then does mesh bed levelling, then heats the bed and extruder. This has a few issues:
1. When the bed and nozzle heats up, the nozzle increases in size slightly and the bed can change shape slightly. Also the PINDA probe used for bed levelling behaves differently when cold.This makes mesh bed levelling less accurate when cold, resulting in bad first layers, or worst case PEI-sheet damage.
2. The extruder is very close to the bed during nozzle and bed heating, because it just auto homed. When working with higher temperature materials, this can damage the relatively fragile PEI-sheet on the print bed.
So here's a pull request that changes the sequence: it first heats up the extruder and print bed, then waits for the …
=> Improve Prusa i3 MK2 start GCode

cura/CuraActions.py, resources/qml/Actions.qml, resources/qml/Menus/ViewMenu.qml
This PR adds a menu item to the view menu to reset the camera position and lookat, homing the camera. This can be used when the user "looses" the buildplate from the view.
Fixes #2411 and contributes to #2361
=> Add menu item to reset the camera

cura/CuraSplashScreen.py, plugins/3MFReader/WorkspaceDialog.qml, plugins/ImageReader/ConfigUI.qml, plugins/LayerView/LayerView.qml, plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml, plugins/PluginBrowser/PluginBrowser.qml, plugins/UM3NetworkPrinting/DiscoverUM3Action.qml, plugins/USBPrinting/FirmwareUpdateWindow.qml, resources/qml/AboutDialog.qml, resources/qml/AskOpenAsProjectOrModelsDialog.qml, resources/qml/DiscardOrKeepProfileChangesDialog.qml, resources/qml/ExtruderButton.qml, resources/qml/OpenFilesIncludingProjectsDialog.qml, resources/qml/Preferences/GeneralPage.qml, resources/qml/Preferences/MachinesPage.qml, resources/qml/Settings/SettingCheckBox.qml, resources/qml/Settings/SettingComboBox.qml, resources/qml/Settings/SettingExtruder.qml, resources/qml/Settings/SettingOptionalExtruder.qml, resources/qml/SidebarSimple.qml, resources/qml/Toolbar.qml, resources/qml/WorkspaceSummaryDialog.qml, resources/themes/cura-light/styles.qml
This PR attempts to solve the Hi DPI issues on both OSX and Windows. OSX apparently no longer needs the Screen.devicePixelRatio workaround when specifying pixel sizes, but Windows certainly does.
This PR is for testing an approach where instead of using Screen.devicePixelRatio, we use a Uranium-supplied screenScaleFactor. This context variable was introduced a couple of releases ago, but never used.
This PR requires https://github.com/Ultimaker/Uranium/pull/285
For additional discussion see https://github.com/Ultimaker/Cura/commit/7bc715a9bd5e61efcfef4b54f7d004b3f6248f5a#commitcomment-24539576
=> Use screenScaleFactor to consistently adapt sizes to display pixel ratio

cura/CuraApplication.py
This PR makes "Solid View" a required plugin. Without Solid View, Cura will start with a blank viewport and spew lots of critical errors because the "view" is None.
Note: There is no plugin with the id "MeshView".
Prevents https://ultimaker.com/en/community/51244-cura-27-3d-interface-is-gone
=> Make Solid View a required plugin

plugins/USBPrinting/USBPrinterOutputDevice.py
#2307 homing the head with "G28" does not work on my printer for some reason. "G28 X" and "G28 Y" however do.
this fix should not break behaviour on other printers as "G28" is just a shortcut.
=> refine abort sequence

resources/qml/SidebarSimple.qml
This PR fixes a UX issue where if only a single quality is available, it always shows a "Slower". If a single quality is available, the quality indicator (handle) is now moved to the center of the slider.
Fixes #2485
CURA-4383
=> Move the quality indicator to the center when there is only one quality

resources/qml/SidebarSimple.qml
This PR hides the gradual infill checbox from the simple mode tab, if the "gradual_infill_steps" setting is disabled by the current machine definition.
Followup to https://github.com/Ultimaker/Cura/pull/2335
=> Hide gradual infill if its setting is disabled

plugins/UM3NetworkPrinting/ClusterControlItem.qml, plugins/UM3NetworkPrinting/ClusterMonitorItem.qml, plugins/UM3NetworkPrinting/PrintWindow.qml, plugins/UM3NetworkPrinting/PrinterInfoBlock.qml, plugins/UM3NetworkPrinting/PrinterTile.qml, plugins/UM3NetworkPrinting/PrinterVideoStream.qml
This PR applies the screenScaleFactor fix to the recently added Cura Connect UI.
Any pixel size specified in QML should not either use UM.Theme.getSize(), or use screenScaleFactor to make sure the pixel size is as intended on OSX, Windows and Linux regardless of display DPI.
Contributes to CURA-4376
=> Apply screenScaleFactor to Cura Connect UI

plugins/UM3NetworkPrinting/NetworkClusterPrinterOutputDevice.py
https://jira.ultimaker.com:8443/browse/CL-271
When Cura is running, but not as the front-most application, at the time a printer gets blocked because my print is scheduled next and requires a configuration change, I want to receive a proper* desktop notification, so I'm reminded to change the configuration as soon as possible.
=> CL-271 Show a notification when a configuration change is needed for your print

cura/Settings/MachineManager.py, resources/qml/SidebarSimple.qml
Sometimes when loading a new project, the materials and print cores and nozzles appear as "empty". Even if the material, print cores or nozzles were properly selected, the UI doesn't update to the right value.
It also happens when creating a new "Custom FDM" or UM2+ or UM2E+:
**Reproduction Steps:** 
1. Add UM3.
2. Add UM2+
3. Check that material and nozzles, set to "empty"
This solves CURA-4377
=> Empty Materials and Print Cores or Nozzle

resources/themes/cura-light/theme.json
This will apply to all UMO+, UM2, UM2+ and UM3 with old firmware users, which look at the camera view. The background changed from blue > grey.
=> Update camera 'viewport_overlay' color > GREY

resources/qml/SaveButton.qml, resources/qml/Sidebar.qml, resources/qml/SidebarHeader.qml, resources/qml/SidebarSimple.qml, resources/qml/SidebarTooltip.qml, resources/themes/cura-light/theme.json
This should be merged together with an Uranium pull request:
https://github.com/Ultimaker/Uranium/pull/287
I replaced the qml Texts by Labels (yes @fieldOfView you were right) and in the Uranium PR the font sizes are then set to point size instead of pixel size. Pixel size seems to be messed up on high DPI screens.
=> Move text back to label and remove unused font

resources/definitions/raise3D_N2_dual.def.json, resources/definitions/raise3D_N2_plus_dual.def.json, resources/definitions/raise3D_N2_plus_single.def.json, resources/definitions/raise3D_N2_single.def.json, resources/extruders/raise3D_N2_dual_extruder_0.def.json, resources/extruders/raise3D_N2_dual_extruder_1.def.json, resources/extruders/raise3D_N2_plus_dual_extruder_0.def.json, resources/extruders/raise3D_N2_plus_dual_extruder_1.def.json
This PR adds definitions for the Raise3D N2 printers (standard/extended and single/dual).
See https://ultimaker.com/en/community/51242-please-add-these-raise3d-printer-definitions for source and details.
=> Add definitions for the Raise3D N2 series

resources/definitions/tevo_tarantula.def.json
Modified version of the Prusa i3's definition. While the i3 values work, the print time estimations were horribly imprecise (often the print takes 2x to 3x as long as Cura estimated). Therefore, I inspected the problem, and found a Reddit thread [1] about it. Instead of hacking my own installation, I just wrote a defition including the correct acceleration/jerk values that work with my firmware (custom build of Marlin based on https://github.com/JimBrown/MarlinTarantula/).
There's downsides however. I don't know how it performs with the stock firmware (although I doubt there'd be many differences). Furthermore, the `jerk_xy` is set to 4 in my definition, but that's only true for the `x`value,the Marlin firmware has a `y` jerk value of 7. That leads to minor differences in the printing …
=> Add definition for Tevo Tarantula printer

CMakeLists.txt
Rather than share/appstream. This is what is suggested by the specification.
Fixes #2563
=> Install AppStream metadata into share/metainfo

resources/qml/AboutDialog.qml
For me having "Cura" under the logo actually doesn't make sense, as it is quite obvious by the logo that we are talking about _Cura_ here. So in my opinion we can prefix the application version here with "version: " instead.
Untested but it should work (fingers crossed)
=> QML: Remove name of application

plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
See jira CL-508
Note: This PR recycles an existing string.
=> CL-508 Show the printer unreachable status in the Cura Connect tab when needed.

resources/shaders/grid.shader
The patch to do the grid rendering from a shader wasn't done a 100% right, as the "legacy" shader wasn't compiling. I also fixed a warning that the intel driver is reporting.
After this fix the grid renders again on my Intel HD 3000 master-of-disaster rendering device.
@fieldOfView still love you ;-)
=> Fix the OpenGL shader for older (legacy?) OpenGL.

plugins/UM3NetworkPrinting/NetworkPrinterOutputDevicePlugin.py, plugins/UM3NetworkPrinting/PrinterInfoBlock.qml
Details in CL-508. This PR simply ensures that the 'unreachable' printer message is shown instead of the 'action required' one in the case where a printer disappears while waiting for a configuration/material change.
=> CL-508 correct status msg when disconnected

plugins/UM3NetworkPrinting/blocked-icon.svg
This applies to the printer status icons shown in the monitor tab when connected via Cura Connect.
=> Update the icon used to show that a printer is blocked.

cura/Settings/ExtruderManager.py, cura/Settings/GlobalStack.py, cura/Settings/UserChangesModel.py
When BPA type is modified, and then the user changes Quality Profile, Cura will prompt user if they want to Keep or Discard Changes. However, the value for default is incorrect as displayed.
=> Cura-4358 Build Plate Adhesion default value takes the current value

resources/qml/PrintMonitor.qml, resources/qml/Settings/SettingTextField.qml, resources/qml/Sidebar.qml
This PR changes the renderType of TextInput elements to be the same as other text elements (Label and native elements such as comboboxes).
Unlike Label elements, which are defined to use Text.NativeRendering, TextInput uses Qt text rendering by default. This can lead to differences in font rendering between input fields and other texts.
Probably fixes https://ultimaker.com/en/community/51334-cura-fonts-garbled-on-macos-high-sierra?page=1#reply-190665
Edit: it also fixes one more occurrence of a fractional pixel offset affecting the placement of text: the Recommended/Custom switch.
=> Change renderType for TextInput elements

cura/CrashHandler.py, cura_app.py
As a new feature, a new crash report dialog was created in order to allow users to directly "Send to developers" the information collected in the crash, such as traceback, last logs, platform information, module (or plugin) that causes the crash, ... and even some user comments.
All this data is formatted as a JSON file and send via POST to the server, where the core developers can constantly check.
=> CURA-4195 New crash report dialog that sends data directly to developers

cura/CuraSplashScreen.py
This PR changes the size of secondary version "elements" (such as "BETA") to use a pixel size instead of a font size, so they scale correctly with the splash screen. This likely only shows on Windows.
=> Fix size of "beta" classifier on splash screen for HiDPI screens

cura.desktop.in
Add model/x3d+xml as a supported MIME type in the desktop file.
Fixes issue #2571.
=> List model/x3d+xml in the desktop file

cura/CameraAnimation.py
I've tweaked the camera animation a bit.
The difference is that it no longer eases into the animation, making it react more immediate. This makes it feel snappier. The duration is made a little shorter to make the ease-out feel approximately the same.
Let me know what you think.
=> Make camera animation feel snappier

plugins/UM3NetworkPrinting/UM3InfoComponents.qml, resources/qml/Menus/MaterialMenu.qml, resources/qml/Menus/NozzleMenu.qml
This PR fixes the following qml errors on startup:
```
.../Cura/resources/qml/Menus/NozzleMenu.qml:19: TypeError: Cannot read property 'clusterSize' of undefined
.../Cura/resources/qml/Menus/MaterialMenu.qml:19: TypeError: Cannot read property 'clusterSize' of undefined
.../Cura/resources/qml/Menus/MaterialMenu.qml:19: TypeError: Cannot read property 'clusterSize' of undefined
.../Cura/resources/qml/Menus/NozzleMenu.qml:19: TypeError: Cannot read property 'clusterSize' of undefined
```
Also fixes code style
=> Fix qml error when there is no connected printer

resources/qml/Settings/SettingTextField.qml
This PR stops SettingTextField from setting a new "literal" value when just tabbing in/out of focus by checking if the text has changed between receiving the focus and editingFinished.
Fixes #2694
=> Stop SettingTextField from setting values when getting/losing the focus

resources/definitions/fdmprinter.def.json
https://en.wikipedia.org/wiki/Trihexagonal_tiling
This is a very simple edit of Triangle infill: the same infill lines are just shifted a bit.
This pattern avoids the junctions where 3 lines meet. As such we can expect this pattern to fail less often.
Because it contains the same directions as triangle infill we can expect the structural properties to remain similar.
However, this hasn't been physically tested. At this moment we can't be 100% sure we can replace triangle infill with trihex infill.
Let's include it in Cura to test with it to see whether trihex infill is indeed as good as it theoretically seems to be.
=> trihex infill

cura/PrintInformation.py, resources/qml/JobSpecs.qml, resources/qml/MonitorButton.qml, resources/qml/SaveButton.qml, resources/qml/Sidebar.qml, resources/qml/SidebarTooltip.qml
This PR rearranges the time & cost specs in the save button area, and puts some more information in the tooltips for these elements
* Time specification has better formatting and now adds percentages
* Cost item has elide, shows only total cost and weight
* Cost item has a tooltip that shows further specification
This PR fixes https://github.com/Ultimaker/Cura/issues/2662 and https://github.com/Ultimaker/Cura/issues/2643 (CURA-4478)
Currently a WIP, because there are still a couple of QML binding loops that need fixing.
=> Cleanup save/monitor button area

resources/definitions/fdmprinter.def.json
A mesh fix setting that reduces the resolution of mesh polygons. This is already happening by default to a resolution of 10 micrometres, but now it's a setting that can be edited.
Implements issue CURA-4590.
See also https://github.com/Ultimaker/CuraEngine/pull/657 for the actual implementation.
=> Maximum mesh resolution

cura/CrashHandler.py
This PR fixes a Python error being thrown when CrashHandler is opened before opengl is initialised.
Contributes to #2837
=> Fix error when CrashHandler is opened before opengl is initialised

plugins/SimulationView/SimulationView.qml, plugins/SimulationView/layers3d.shader, plugins/SimulationView/resources/simulation_pause.svg, plugins/SimulationView/resources/simulation_resume.svg, resources/qml/Topbar.qml, resources/themes/cura-dark/theme.json, resources/themes/cura-light/styles.qml, resources/themes/cura-light/theme.json
Due to the travel speed is normally very high compared with the other speeds in the model, the gradient is now gradual instead of linear in order to show more changes in the low values and less changes in the high values. In the pictures below, you can see the difference after the changes. Red colors are also avoided since it could indicate that there is an error.
This PR also adapts the button styles and themes' colors. Play/Pause button is set to the left and reduce the size.
=> Adapt gradient in Simulation view for better visualization of feedrates

resources/definitions/fdmprinter.def.json
This allows printers to determine this for themselves. By default it's based on the g-code flavour in the same way as it is now implemented in the engine.
See also https://github.com/Ultimaker/CuraEngine/pull/656
Fixes #1097.
=> Add setting to determine whether to use firmware retraction

resources/definitions/fdmprinter.def.json
New experimental settings for adaptive layer heights in the engine. See https://github.com/Ultimaker/CuraEngine/pull/649 for details of this feature. Note that the default values might change depending on results from materials & processing.
=> Add experimental settings for adaptive layer heights - CURA-4524

plugins/CuraEngineBackend/StartSliceJob.py
This PR fixes a regression caused by https://github.com/Ultimaker/Cura/commit/1d6b7c71cbd3301915a0777404d0d6627373b979 which double encodes start/end gcode snippets, leading to non-valid start and end seuqences.
See https://github.com/Ultimaker/Cura/issues/2877#issuecomment-348113324 for discussion
Note: the issue does not manifest on UM2(+) or UM3 printers, because they don't use start/end gcode snippets. On all other printers, Cura outputs quite broken gcode at the moment.
=> [CRITICAL] Prevent start & end gcode snippets being double encoded

plugins/MachineSettingsAction/MachineSettingsAction.qml
This PR hides the material diameter field from Machine Settings when the current machine does not have materials (eg Ultimaker 2 when using UltiGcode)
Contributes to https://github.com/Ultimaker/Cura/issues/1273
=> Hide material diameter when the machine has no materials

resources/qml/Sidebar.qml
This PR tweaks the layout and alignment of print time and cost estimation tooltips, improving readability.
* table takes the full width and values are right-aligned
* time estimates are shortened
* values are right aligned
* feature/time/percentage are on a single line again
* handle long feature & material names gracefully
* totals are only shown when there are multiple extruders
Discussion:
In the current design it is fairly hard to associate the data with the label. Because there is a line of text between each datum, it is also harder to get an overview at a glance. Finally, this design is "punishing" wellbehaved (compact) languages for the chance that there may be a more verbose language.
It would be better if the layout adapted itself (as a HTML table can). Here is the counter offer …
=> Tweak layout and alignment of print time and cost estimation

resources/qml/SidebarHeader.qml
Just read the code and noticed that.
=> SidebarHeader: Adding missing comment about "extruder row"

cura_app.py
As of 12/3/2017 Cura as provided with Fedora 27 does not work when the nvidia driver is installed.
The test in the top level script to decide to apply the Linux nvidia work around lists some Linux distributions:
"debian", "Ubuntu", "LinuxMint"
this patch adds "Fedora" to that test.
Tested on Fedora 27 with nvidia driver. Also submitted to Fedora bugzilla
https://bugzilla.redhat.com/show_bug.cgi?id=1520138
they additionally requested that this patch be proposed upstream.
=> Add Fedora to test for nvidia driver work around.

plugins/SimulationView/SimulationPass.py, plugins/SimulationView/layers3d.shader
This enables backface culling for layer view.
[Backface culling](https://en.wikipedia.org/wiki/Back-face_culling) effectively says that you only render one side of a triangle. If it's facing the other way, you don't render it. This is often used in games when they have watertight models, since you can't see the inside of the model anyway; they simply make all triangles face outwards. Backface culling then cuts the number of triangles to render in half because all the triangles at the back side of the model will be facing the other way and so won't be rendered.
In layer view I first had to fix the winding order but could then simply enable the backface culling that was already implemented. All the sides of the 3D tubes facing away from the camera won't be rendered, but you wouldn't see …
=> Layer view backface culling

cura/CrashHandler.py
This PR prevents crashhandler from crashing (and hiding the actual exception) when it is invoked before the QApplication has been initialized (eg when there is an syntax error in a py file).
```
QWidget: Must construct a QApplication before a QWidget
Fatal Python error: Aborted
Current thread 0x000012c8 (most recent call first):
File "...\UM\Cura\cura\CrashHandler.py", line 56 in __init__
File "cura_app.py", line 47 in exceptHook
```
=> Prevent CrashHandler creating a QWidget before QApplication is created

plugins/CuraEngineBackend/StartSliceJob.py
This PR allows specifying the extruder stack to use for each replacement pattern. The replacement pattern is (optionally) extended with an extruder_nr: {setting_key,extruder_nr}. The extruder_nr can either be a number (-1 for the global stack, 0 or higher for an extruder), or a setting keyword such as support_extruder_nr etc. If an extruder_nr is not specified, the value is taken from the same stack as the current implementation.
* ```{material_standby_temperature}``` in start gcode gets the (resolved) setting value from the default stack (the first used extruder), as before
* ```{material_standby_temperature, 1}``` gets the value from the 2nd extruder (extruder nrs start by 0)
* ```{material_standby_temperature, support_extruder_nr}``` gets the value from whatever extruder is set as …
=> Multiextruder gcode snippet replacement patterns

resources/definitions/tevo_tarantula.def.json
At the moment, the base plate is moved to the end stops, which moves the head to the front of the base plate (at least for stock printers, but most likely for modified ones, too), making the object inaccessible. This has been fixed by moving the base plate to the back after this step. That eliminates the need for the X/Y homing, hence it got removed from the after print code.
Also, before these changes, the "steppers off" command was pretty pointless, as the final move was performed after this step. This is not necessarily a problem, but can be annoying when trying to move the base plate or extruder after the print by hand.
All in all some useful changes.
Owners of the printer should replace the "after print" code of their existing printers in their settings with this:
```
M104 S0 …
```
=> Reduce amount of movements after print for Tevo Tarantula

resources/definitions/fdmprinter.def.json
Enabling this can greatly reduce the travel time during the printing of infill but it can
be expensive to compute so now the user can decide whether to use it or not.
=> Added infill_enable_travel_optimization setting.

resources/qml/Settings/SettingTextField.qml
This PR changes the textfield to select its contents when gaining focus. This is especially usefull when tabbing through fields.
See https://github.com/Ultimaker/Cura/issues/1969#issuecomment-352632035
=> Select text when gaining focus

cura_app.py
The problem with running cura when using the proprietary nvidia driver is relevant for all Linux distributions. Therefore, I suggest that you remove the condition for checking the distribution. I maintainer cura for ALT Linux distribution.
=> Activation workaround Linux+NVidia proprietary drivers for all distributions

plugins/MonitorStage/MonitorStage.py
This PR makes sure events such as onAcceptsCommandsChanges get connected if an outputdevice has been added before the monitorstage is initialized. Without these connections, an outputdevice that uses eg setAcceptCommands to change its state will not show an updated icon in the topbar. 
This PR applies to #2974
=> Fix updating icon in the top bar

plugins/PerObjectSettingsTool/PerObjectSettingsPanel.qml, plugins/SolidView/SolidView.py, resources/definitions/fdmprinter.def.json, resources/shaders/striped.shader
This PR provides the following enhancements to support meshes:
* Allow adding (only) support-specific settings for support meshes in Per Model Settings
* Render support meshes with a vertical stripe to tell them apart from normal meshes
* Hide the Support Mesh/Anti overhang mesh/... option if the machine definition disables the settings
This PR is a continuation of #2758
=> Support Mesh enhancements

resources/definitions/fdmprinter.def.json
Still not enabled by default yet but perhaps in the future after it has been tested more it will be.
As discussed in #2972.
=> Move optimize_wall_printing_order from experimental section to shell.

resources/definitions/fdmprinter.def.json
The initial layer has a different layer height and so the actual rounding of a line conforms to the naive square model CuraEngine uses in a different way.
In order to compensate for that you would want a different flow rate on the initial layer.
=> initial layer flow

plugins/SupportEraser/SupportEraser.py, plugins/SupportEraser/__init__.py, plugins/SupportEraser/plugin.json, plugins/SupportEraser/tool_icon.svg
This is the first draft of the Support Eraser tool. The plugin creates a cube mesh which has the `anti_overhang_mesh` decorator causing it to block the creation of support material for overhangs within its volume. This distinction is necessary to avoid confusing this behavior from actually erasing a _portion_ of a support structure.
Some (non-necessary) improvements could be made such as:
- Better graphical style
- Discussion of whether the cube should be able to pass through the build plate or not
- Possible improvements to the tool's icon
- Placing the cube at a cursor click location
=> Added Support Eraser Plugin

resources/qml/Settings/SettingComboBox.qml, resources/qml/Settings/SettingExtruder.qml, resources/qml/Settings/SettingOptionalExtruder.qml, resources/qml/Sidebar.qml
This PR fixes two theming issues that are mainly visible in the dark theme:
In addition, extruder dropdowns now have swatches in the dropdown "menu", which they did no have before (possible thanks to QtQuick Controls 2)
=> Fix sidebar theming (for Ultimaker Dark theme)

plugins/UFPWriter/__init__.py
This PR gracefully handles missing libCharon when importing the UFPWriter plugin, in the same way 3MFWriter handles a missing libSavitar. 
Please?
=> Gracefully handle missing libCharon

plugins/CuraEngineBackend/StartSliceJob.py
This PR fixes the detection of multiextruder replacement patterns. Since #3068, replacement patterns can take the form of {setting_nr, extruder_nr}. This form was not being recognised when determining if CuraEngine should prepend its own preheat sequence.
=> Fix the detection of multiextruder replacement patterns

resources/qml/Settings/SettingCategory.qml, resources/qml/Settings/SettingComboBox.qml, resources/qml/Settings/SettingExtruder.qml, resources/qml/Settings/SettingItem.qml, resources/qml/Settings/SettingOptionalExtruder.qml, resources/qml/Settings/SettingTextField.qml, resources/qml/Sidebar.qml
This PR fixes font rendering of setting labels in the sidebar on affected OS X installations. Apparently, the qtquickcontrols 2 Label no longer defaults to using renderType: Text.NativeRendering
This causes text to render with QtRendering which looks subtly different on Windows and succinctly broken on some OSX installations.
With this PR the sidebar is now rendered with a single renderer again, making for a more consistent look on all systems and avoiding the broken QtRendering on OS X alltogether.
=> Set renderType to Text.NativeRendering for qtquick controls 2 Labels

resources/i18n/cura.pot, resources/i18n/de_DE/cura.po, resources/qml/AboutDialog.qml
Add AppImageKit to credits. AppImageKit has been used to distribute Cura to Linux users running various Linux distributions for a while now.
=> Add AppImageKit to credits

cura/CrashHandler.py
This PR adds a button on the early crash dialog to open the configuration folder, and clarifies where configuration backups are stored.
=> Add a button to open the configuration folder.

cura/CuraApplication.py
If this commit gets merged into Uranium, then _reloadMeshFinished is not needed anymore.
https://github.com/Ultimaker/Uranium/commit/31bff5b9b9797fb5654ea8ed74a51fff42600e1d
The function has been moved, so reloading a mesh after a file has been modified is possible.
=> CuraApplication/UM.MeshBuilder: Removing _reloadMeshFinished

resources/definitions/ultimaker3.def.json, resources/quality/ultimaker3/um3_aa0.4_TPU_Draft_Print.inst.cfg, resources/quality/ultimaker3/um3_aa0.4_TPU_Fast_Print.inst.cfg, resources/quality/ultimaker3/um3_aa0.4_TPU_Normal_Quality.inst.cfg, resources/quality/ultimaker3/um3_aa0.8_TPU_Draft_Print.inst.cfg, resources/quality/ultimaker3/um3_aa0.8_TPU_Superdraft_Print.inst.cfg, resources/quality/ultimaker3/um3_aa0.8_TPU_Verydraft_Print.inst.cfg
Reverted combing settings (noskin lead to a lot of extra ooze), fixed the minimum travel for TPU and Connected our infill lines.
=> M&p setting optimization

plugins/PostProcessingPlugin/PostProcessingPlugin.py
This PR fixes the location of post processing scripts on Linux.
On Windows and OSX, resources and preferences are stored in the same folder. On Linux, preferences are in ~/.config, resources are in ~/.local/shared. Postprocessing scripts belong in the latter, along with all the other resources (definitions, plugins, themes).
Fixes #3356
=> Fix location of post processing scripts on Linux

resources/definitions/printrbot_simple_makers_kit.def.json
The Printrbot Simple Maker's Kit, model 1405, was a low-cost FDM printer
without a heated bed and a 10x10cm print area.
The print area can be extended to 185x100mm with the "Printrbot Simple XL
Upgrade with Spool Rack for Maker's Kit 1405".
=> Add definition for Printrbot Simple Maker's Kit 1405

resources/definitions/fdmprinter.def.json, resources/definitions/m180.def.json
This adds a few extra machine settings in order to be able to store more information about machines. These settings are primarily used by X3GWriter in order to output correct X3G. However I took care to select only settings that could feasibly be used for slicing in general. For instance, the steps per MM can be used to align g-code output to the step grid, which would improve quality and speed while reducing g-code size.
The settings are correctly configured for Malyan M180 as well. If we're going to use them for actual slicing we should set them correct for the Ultimaker printers too.
=> Extra machine settings

resources/qml/Settings/SettingTextField.qml
This PR is a re-issue of #3196, against master.
This PR tweaks the behavior introduced in #3017, which intended to select all text when tabbing through text input fields. In #3017 text is also selected when the control is clicked. Some users have reported that the latter is unwanted.
This PR makes sure the text selection is not triggered when the input field gains the focus by pressing on the input field. I have made the PR against the 3.2 branch, since it fixes behavior introduced in 3.2; some would call the current behavior in 3.2 a regression.
See https://github.com/Ultimaker/Cura/issues/1969#issuecomment-352632035 for the original comment, and https://github.com/Ultimaker/Cura/pull/3017#issuecomment-358357664 and https://community.ultimaker.com/topic/21149-introducing-ultimaker-cura-32 …
=> Only select all text when tabbing to fields, not when clicking a field

resources/definitions/seemecnc_artemis.def.json, resources/definitions/seemecnc_v32.def.json
All SeeMeCNC printers will only print with 1.75 diameter filament. Added this to the definitions of both printers.
=> Added default material diameter to SeeMeCNC printer definitions

cura/PlatformPhysics.py, plugins/SupportEraser/SupportEraser.py
This PR is a small followup to #3492, which parents the added meshes to the clicked node instead of putting both the added meshes and the parent into a group. This prevents an extra convex hull from being drawn, and a wireframe cage from appearing. It does require a small change in PlatformPhysics, or otherwise the added mesh would still drop down to the buildplate.
=> Further improvements of the Support Eraser

resources/variants/ultimaker3_aa0.8.inst.cfg, resources/variants/ultimaker3_bb0.8.inst.cfg, resources/variants/ultimaker3_extended_aa0.8.inst.cfg, resources/variants/ultimaker3_extended_bb0.8.inst.cfg
Changed  it to 2 or 3 times line width, similar as with the 0.4mm profiles.  Was 5mm standard for all profiles with the 0.8mm printcore, except TPU.
=> Retraction minimum travel update

cura/CuraApplication.py, cura/MultiplyObjectsJob.py, cura/Scene/BuildPlateDecorator.py, plugins/3MFReader/ThreeMFReader.py, plugins/SupportEraser/SupportEraser.py
This PR fixes issues with grouping and meshes created with the support eraser tool.
See https://github.com/Ultimaker/Cura/pull/3505#issuecomment-374141862:
> @Vandrasc has discovered a few issues:
>
>  1.  When grouping and then ungrouping a mesh with blockers, the blockers will fall to the build plate. This is expected but possibly confusing to users who don't know what the feature is doing under the hood.
>  2.  When importing and then ungrouping a project with blockers, the non-blocker meshes will just... vanish. This is of course not the expected behavior, even given what's under the hood.
With this PR, support eraser meshes are no longer ungrouped. The PR also fixes multiplying meshes that have support eraser meshes parented to them.
=> Fix support eraser grouping

plugins/PostProcessingPlugin/scripts/Stretch.py
Extract line width from current extruder nozzle size
Change default values of stretch parameters from 0.08 to 0.1
Using the Cura version 3.2.1, the old global "line_width" parameter is not valid anymore (it reports 0.35 instead of 0.53 in my case). To fix this issue, I use the nozzle size of the current extruder.
By the way, I pushed small refinements...
=> Post stretch algorithm fixes

cura/CrashHandler.py, cura/Machines/ContainerNode.py, cura/Machines/MaterialManager.py, cura/Machines/Models/QualityManagementModel.py, cura/Machines/Models/QualitySettingsModel.py, cura/Machines/QualityChangesGroup.py, cura/Machines/QualityManager.py, cura/Machines/VariantManager.py, cura/Settings/ContainerManager.py, cura/Settings/CuraStackBuilder.py, cura/Settings/ExtruderManager.py, cura/Settings/MachineManager.py, plugins/3MFReader/ThreeMFWorkspaceReader.py, plugins/XmlMaterialProfile/XmlMaterialProfile.py
Whenever a problem is detected with the user's configuration that we can't fix, this change shows a message to the user that gives the user some pointers of which files are broken and recovers from this break as best as it can by leaving those broken containers out.
To test, try for instance to edit a stack file to list a different container ID that doesn't exist, or give two variants of the same printer the same name.
The message also allows the user to reset their configuration to factory defaults as a reliable (but destructive) way to recover from the error.
This PR depends on https://github.com/Ultimaker/Cura/pull/3579
Implements CURA-5045.
=> Show configuration errors

plugins/PostProcessingPlugin/PostProcessingPlugin.py
There was a bug in the persistent post-processing scripts. Actually, this is a bug in all of our cfg files but it comes to fruition here.
Python's ConfigParser by default always outputs lowercase keys. Some of our post-processing scripts have setting keys with uppercase characters though. So when we saved these settings in a cfg document it would transform them to lowercase and when loading them back in we couldn't recognise any more which setting that value belonged to. The setting value was then lost (and a warning was put in our log about that).
Setting ConfigParser's transform function to `str()` when saving and loading prevents casting to lowercase.
=> Fix postprocessing persistence of setting names with uppercase characters

resources/definitions/fdmprinter.def.json
Engine implementation is here: https://github.com/Ultimaker/CuraEngine/pull/739. This setting is intended for debugging problems with interrupted walls. It should probably not be published in a final release, but we're planning to merge it now to allow people to test.
Implements CURA-5189.
=> Add setting to try multiple line thicknesses

resources/definitions/fdmprinter.def.json
Some users report that omitting the retractions causes print failures.
It might be machine/material dependant, so we need a user setting for this.
Omitting retractions was implemented somewhere in 2.5 or something, but it was never a setting.
We've since gotten some critique on this.
=> setting to disable omitting retractions in support

cura/PrinterOutput/GenericOutputController.py, plugins/USBPrinting/USBPrinterOutputDevice.py
This PR fixes sending commands in rapid succession over USB. When sending multiple commands using sendCommand(), it can happen that a command is sent before a previous command is fully received.
Probably contributes to #3050
=> Fix sending commands in rapid succession over USB

plugins/GCodeReader/FlavorParser.py
I tried saving a gcode file that was read by the gcode reader and it all came out in one very long line so this PR adds back a \n at the end of each gcode line.
With this PR, the saved file is identical to the original (on Linux, don't know about other systems)  except that it has the SETTINGS_3 block added to the end. The original settings block is still there so perhaps it would be good if the settings are not written when the gcode has been read (as opposed to having been created by slicing when you do want to write the settings block). Anyway, I won't be making that change so I just mention it in case someone else wants to do it.
=> Append a \n to each saved line of gcode otherwise the whole file ends up as one line!

cura/PrinterOutput/GenericOutputController.py, plugins/USBPrinting/USBPrinterOutputDevice.py
This PR prevents preheat timers (bed, extruder) resetting the temperature to 0 after a print has started. Starting a print should stop all preheat timers, without setting the temperatures back to 0.
Steps to reproduce the issue:
* Use printer connected with USB
* Preheat bed
* Start print
After a couple of minutes of printing, the bed temperature will be set back to 0, and the print will detach from the buildplate.
=> [3.3] Prevent preheat timeout from occurring during a print

plugins/GCodeReader/FlavorParser.py
The gcode reader assumed that each layer starts with a move to the initial position but
for spiralized code that isn't true because the previous layer always ends up in the right
location. So we now start each layer with a fake move to the end position of the previous layer.
This won't actually cause a real move to occur but it ensures that the first line segment
in the new layer has the correct initial point.
Without this PR:
With this PR:
I admit that this PR hasn't received extensive testing.
=> Fix gcode reader bug that can create a gap at the start of a spiralized layer

cura/Machines/VariantManager.py
This PR prevents a crash (and logs a warning instead) when a variant has no hardware_type. A hardware_type of "nozzle" is assumed (as all pre-3.3 variants are nozzle variants).
=> Fix a crash when a variant has no hardware_type

cura_app.py, plugins/SimulationView/layers.shader, plugins/SimulationView/layers_shadow.shader, plugins/SimulationView/simulationview_composite.shader, plugins/XRayView/xray_composite.shader, resources/shaders/grid.shader, resources/shaders/striped.shader
Based on the discussion in #2991, this patchset allows me to run Cura successfully on ARM/Mali platforms using HW-accelerated GLES.
Note that there are two more aspects to reaching this goal: Qt needs a small patch to succeed initialisation (https://forum.odroid.com/viewtopic.php?f=93&t=15362#p100029), and you may have to uninstall the system-default libGL.so.1. I haven't tracked down the latter problem, unfortunately.
=> Fixes for cura on ARM/Mali-based systems

resources/definitions/fdmprinter.def.json
This PR adds a couple of missing units to the machine category settings. These settings are normally not visible, but plugins may expose them to the user.
=> Add some missing units to machine settings

cura/CuraPackageManager.py, plugins/MachineSettingsAction/plugin.json, plugins/Toolbox/resources/qml/ToolboxActionButtonStyle.qml, plugins/Toolbox/resources/qml/ToolboxInstalledTile.qml, plugins/Toolbox/src/PackagesModel.py, plugins/Toolbox/src/Toolbox.py, plugins/UM3NetworkPrinting/plugin.json, plugins/UltimakerMachineActions/plugin.json, plugins/UserAgreement/plugin.json, resources/packages.json
This PR makes bundled packages (that is to say: the packages which Cura ships with), visible to the package manager as such. Now, you will see bundled materials in the Installed tab and will not be able to install them a second time unless a higher version is present on the server.
=> Cura-5296 Make bundled resources visible to CuraPackageManager

resources/qml/Settings/SettingView.qml
This makes the settings filtering field way more bearable on slower machines. It now only triggers when you hit enter, leave the field or after you stop typing for 500ms.
=> Only trigger settings filter on enter or after 500ms timeout

cura/CuraApplication.py, resources/qml/Preferences/GeneralPage.qml
This PR selects models after loading them into Cura. This makes Cura behave like other applications, including legacy Cura.
Fixes #356
=> Select models after loading

cura/Arranging/Arrange.py, cura/Arranging/ArrangeObjectsAllBuildPlatesJob.py, cura/Arranging/ArrangeObjectsJob.py, cura/Arranging/ShapeArray.py, cura/BuildVolume.py, cura/CuraActions.py, cura/CuraApplication.py, cura/MultiplyObjectsJob.py, tests/TestArrange.py
Fixed CURA-5370 bug: arranger didn't find a location while it fits fine. This was caused by brims taken into account double. The arranger used an offset convex hull, but the disallowed areas already had a "brim"* in.
- arranger uses disallowed areas without brim* 
- faster, 
- better results when "Arrange all"
- cleanup, 
- more unit tests, 
- take actual build plate size in Arranger instances
- make x and y consistent (numpy arrays start with y first in general), they were used mixed but it wasn't seen because previously the build size was always a square
- use *brim to determine minimum offset between objects
*brim = brim / skirt / other
=> CURA-5370 Small refactor for Arranger: 

plugins/USBPrinting/USBPrinterOutputDevice.py
This PR fixes the USB Printing plugin incorrectly handling multiple extruder temperatures. Zipping the extruders with the matches puts the temperature of the first extruder in both extruders, because the temperatures for the first extruder are returned twice for the M105 request; once without the tool number, and once with.
Could fix https://github.com/Ultimaker/Cura/issues/3563
=> [3.3] Fix getting multiple extruder temperatures from USB printer

plugins/USBPrinting/USBPrinterOutputDeviceManager.py
Hi!
This fix prevents the USB print manager from needlessly tying up the serial port on printers that do not support gcode.
The current behavior with extended baud rate probing is harmless (at least on the ZYYX Agile) but annoying. I don't know your policy on which bugs are severe enough to go into the release, feel free to put this on master if that is more appropriate.
=> Only open USB ports if the printer understands gcode.

plugins/Toolbox/resources/qml/ToolboxCompatibilityChart.qml
This PR fixes a cosmetic issue in the Toolbox:
Notice how the items in the table shine through the header, which is not a great look.
=> Make headers non-transparent

resources/qml/Menus/ConfigurationMenu/ConfigurationItem.qml, resources/qml/Menus/ConfigurationMenu/PrintCoreConfiguration.qml, resources/qml/Menus/ConfigurationMenu/SyncButton.qml
This PR fixes some minor issues with the ConfigurationMenu ("sync button"):
* Fix text rendering on some OSX systems
* Fix untranslatable text
=> Fix configurationmenu text

resources/definitions/fdmprinter.def.json
Wall lines whose flow is < wall_min_flow are converted into travel moves.
=> Added wall_min_flow and wall_min_flow_retract settings.

cura/CuraPackageManager.py, plugins/Toolbox/resources/qml/ToolboxDetailTileActions.qml, plugins/Toolbox/src/Toolbox.py, resources/bundled_packages.json
Check if plugins are installed through the 'old' plugin browser and are not yet known in the package manager. If so, show them as installed and updatable.
Once a user updates them through the new Toolbox they are correctly known in the package manager.
=> Feature update old plugins

plugins/SimulationView/SimulationView.qml, resources/qml/Settings/SettingView.qml, resources/qml/SidebarHeader.qml
This PR removes vestigial references to "monitoringPrint" that were missed in #3593. 
sidebar.monitoringPrints is no longer declared since #3593, but checking if the property is set does not lead to a warning thanks to ecmascript (undefined ~= false).
=> Remove vestigial references to "monitoringPrint"

resources/definitions/creality_cr10s.def.json
The CR-10S is functionally equivalent to the CR-10, but since the definitions support inheritance I figured I'd add it for completeness sake.
It's not entirely the same - The CR-10S has a different board and has dual Z-rods, but that shouldn't matter for this definition.
=> Add Creality CR-10S machine definition

resources/qml/Preferences/MaterialsPage.qml, resources/qml/Preferences/ProfilesPage.qml
This PR fixes two issues in the Profiles and Materials pages:
The profiles page now opens with the currently active profile selected. Not only is this consistent with the other preference pages (printers, materials), but it is also important for the usability of pressing the "star" icon next to the profile name in the sidebar. This should show the changed settings, otherwise the functionality of that button is moot.
Additionally the coloring of the currently selected items was not working correctly in the Materials and Profiles pages. In fixing this, I also slightly simplified the structure of the Profiles page QML.
=> Fixes for preference pages

plugins/Toolbox/resources/qml/ToolboxDetailList.qml, plugins/Toolbox/resources/qml/ToolboxDownloadsPage.qml, plugins/Toolbox/resources/qml/ToolboxInstalledPage.qml
This PR fixes the scrolling panes in the Toolbox window so they can only be "flicked" vertically, like other scrollviews in Cura. "Flicking" is where, instead of dragging the scrollbar or using mousewheel/multitouch scrolling, you just click and drag around the contents of the scrolling pane. Before this PR, the toolbox scrolling panes could be dragged horizontally as well as vertically, which looks weird.
=> Limit flicking the Toolbox scrollviews to vertical only

resources/qml/Preferences/GeneralPage.qml
This PR changes the wording of the Profile Override options on the General preferences page. It also makes the "Always ask me this" wording consistent.
=> Clarify Profile Override preference options

resources/qml/Cura.qml
This PR fixes a bright line/gap between the viewport and the sidebar that can appear due to rounding issues or when resizing the window when using a dark theme.
=> Fix a bright line/gap between the viewport and sidebar due to rounding

resources/extruders/raise3D_N2_plus_single_extruder_0.def.json
These IDs are not used and should never be added again.
=> Remove ID from Raise3D definition

cura/BuildVolume.py
We already have this variable. Let's not use a private variable from another class.
=> Use _engine_ready to detect if there is a QML engine

resources/definitions/fdmprinter.def.json
These let you override the fan speed when printing the skin regions immediately above support.
Engine PR is https://github.com/Ultimaker/CuraEngine/pull/748
=> Added support_fan_enable and support_supported_skin_fan_speed settings.

cura/Machines/MaterialManager.py
Fixes CURA-5548.
Requesting you, @diegopradogesto, since you know why you set it to only sync with `read_only` groups
=> Do not sync only with read_only material groups

cura/Machines/MaterialManager.py, cura/Machines/Models/BaseMaterialsModel.py, cura/Machines/Models/BrandMaterialsModel.py, cura/Machines/Models/GenericMaterialsModel.py, resources/definitions/ultimaker.def.json, resources/definitions/ultimaker2.def.json, resources/definitions/ultimaker_original.def.json, resources/definitions/ultimaker_original_dual.def.json, resources/qml/Menus/MaterialMenu.qml, resources/qml/SidebarHeader.qml
DO NOT MERGE THIS YET! This requires changes in the Ultimaker 3 and Ultimaker S5 firmware.
The Exclude Materials metadata property had the same functionality as the "hardware compatible" property in materials. We remove the data here in favour of the property in the material profiles.
Implements CURA-5460.
=> Move "Exclude Materials" metadata to materials

resources/qml/SidebarHeader.qml
When a material is not compatible with the buildplate, Cura shows a message that now needs to change.
FYI @Kristel88.
=> Modify the compatibility message to only use glue

resources/qml/Settings/SettingComboBox.qml, resources/qml/Settings/SettingExtruder.qml, resources/qml/Settings/SettingOptionalExtruder.qml
Align the dropdown panel in the combobox with the parent and get rid of binding loop messages. Fixes #4074.
I did the same fix for the Extruder selector and the Optional Extruder selector. Those were working but for sake of consistency. 
The height of the popups was adjusted so there is no more shakes when hovering the items.
=> Fix blank dropdown panel in the comboboxes

resources/qml/SaveButton.qml
This PR enforces focus on the save button to ensure edits to jobname happen before saving.
Fixes #4007
=> Fix setting jobname before saving

cura/CuraApplication.py, plugins/3MFReader/ThreeMFReader.py
Contributes to CURA-5465
Fixed bug by preventing read jobs for 3mf files from being auto-arranged.
Boyscout changes:
- Fixed typo in `ThreeMFReader.py` (`splitted` → `split`)
- Fixed code style in `CuraApplication.py` (`filename` → `file_name`)
=> Retain 3MF mesh positions

plugins/USBPrinting/AutoDetectBaudJob.py, plugins/USBPrinting/USBPrinterOutputDevice.py
Hello, just installed Ultimate Cura 3.3.1 and wasn't able to connect my Malyan M200 via USB. Debugging the problem I found that the answer from the printer during the `AutoDetectBaudJob` was:
`b'ok N0 P15 B15 T:28.8 /0.0 B:24.8 /0.0 T0:28.8 /0.0 @:0 B@:0\n'`
So it didn't pass the check. Changing the check to `if b"ok " in line and b"T:" in line` fixed it.
I don't have any other printers to test if the fix breaks the check for them, but I think they will be fine
Jorge.
=> Fix for detecting USB connection to Malyan M200 and Monoprice Mini

cura/Settings/MachineManager.py, resources/definitions/dagoma_discoeasy200.def.json, resources/definitions/dagoma_neva.def.json, resources/definitions/dagoma_neva_magis.def.json, resources/extruders/dagoma_discoeasy200_extruder_0.def.json, resources/extruders/dagoma_neva_extruder_0.def.json, resources/extruders/dagoma_neva_magis_extruder_0.def.json, resources/quality/dagoma/dagoma_discoeasy200_pla_fast.inst.cfg, resources/quality/dagoma/dagoma_discoeasy200_pla_fine.inst.cfg, resources/quality/dagoma/dagoma_discoeasy200_pla_standard.inst.cfg, resources/quality/dagoma/dagoma_global_fast.inst.cfg, resources/quality/dagoma/dagoma_global_fine.inst.cfg, resources/quality/dagoma/dagoma_global_standard.inst.cfg, resources/quality/dagoma/dagoma_neva_magis_pla_fast.inst.cfg, resources/quality/dagoma/dagoma_neva_magis_pla_fine.inst.cfg, resources/quality/dagoma/dagoma_neva_magis_pla_standard.inst.cfg, resources/quality/dagoma/dagoma_neva_pla_fast.inst.cfg, resources/quality/dagoma/dagoma_neva_pla_fine.inst.cfg, resources/quality/dagoma/dagoma_neva_pla_standard.inst.cfg
- Removed nozzle size in magis def because it's in the extruder def on other machines
- Removed material diam from disco extruder def because its in the disco machine
- Removed material diam from neva extruder def because its in the neva machine
- Added extruder def for magis machine
- Fixed unused id field in disco machine
- Fixed duplicate name between Neva and Neva magis
Contributes to CURA-5499
=> Fix-up Dagoma3d dagoma profiles

plugins/SimulationView/LayerSlider.qml, plugins/SimulationView/SimulationSliderLabel.qml
Previously it was set to the text field. That makes it easier to release the focus by clicking in the main view and use the arrow keys to rotate the view.
=> CURA-5613 Set the focus in the upper handle in the layer view

plugins/CuraEngineBackend/CuraEngineBackend.py
This way if you move the model, and don't hit prepare again, you can end up exporting the old gcode again thinking its new gcode.
=> Clear out old gcode

plugins/SimulationView/LayerSlider.qml, plugins/SimulationView/PathSlider.qml
This PR tries to fix this problem:
- When using the arrow keys to move up/down the layers or left/right the paths, the slider went out of range, as you can see in this picture:
It's more notifiable when there are just a few layers (or paths) and you use the SHIFT combination to move 10 by 10.
=> Fix the sliders that went out of range when using the arrow keys

plugins/USBPrinting/USBPrinterOutputDevice.py
This PR fixes firmware uploading on Windows by correctly creating a local path from a url-encoded path. 
On Windows, local file URLs start with file:/// (three forwards slashes). Instead of hardcoding a fix for Windows only, this PR uses QUrl to handle this properly.
Fixes #3731 and #3987
=> Fix firmware upload on Windows

plugins/SupportEraser/SupportEraser.py
This PR fixes rendering support eraser/blocker cubes by creating meshes that have per-vertex normals.
MeshBuilder.addCube creates cubes that don't have per-vertex normals. Geometry like that does not render properly in most shaders used in Cura. This becomes obvious when a user changes the "Mesh Type" using Per Model Settings.
Contributes to https://github.com/Ultimaker/Cura/issues/3959 by making the effect of changing a support blocker mesh to another type more visible and predictable.
=> Fix rendering support eraser cubes

resources/definitions/fdmprinter.def.json
See https://github.com/Ultimaker/CuraEngine/pull/781
=> Added the "Within Infill" combing option that functions identically to the original "Not in Skin" option.

plugins/PostProcessingPlugin/scripts/PauseAtHeightRepRapFirmwareDuet.py
This PR adds a post-processing script to add a Pause-At-Height step for RepRapFirmware, which inserts a M226 at the specified height (layer).
This works for RRF, commonly used with DuetWifi, Duet Ethernet, and Duet Maestro boards (also some RADDS-based ones).
=> add PauseAtHeight post-processing script for RRF

plugins/SimulationView/LayerSlider.qml, plugins/SimulationView/PathSlider.qml, plugins/SimulationView/SimulationView.qml
Add a property that indicates when the layer or the path slider has changed manually.
With this we can differentiate when the layer changed automatically (during simulation) or manually (by user interaction). In case it was changed manually, the simulation will stop.
=> Stop simulation when dragging handles

plugins/USBPrinting/AutoDetectBaudJob.py
This PR fixes opening the serial port after baud rate detection.
After detecting the baudrate, closing the serial port used for detection is left to garbage collection. This has worked for Cura for a long time, but while fixing #4369 I noticed Cura could no longer connect to the serial port, giving an Access Denied error. It looks like there's a race condition between the garbage collector doing its thing destroying the serial port object and the USBPrinterOutputDevice trying to open the same serial port again. By actively closing the serial port in the AutoDetectBaudRateJob, this race condition goes away.
I have created this PR against the 3.5 branch, because for me the 3.5 branch consistently fails to open the USB serial port, while the 3.4 branch has no such problem. I have not tested …
=> [3.5][regression]Fix opening port after baudrate detection

resources/i18n/pl_PL/cura.po, resources/i18n/pl_PL/fdmprinter.def.json.po
Translation was incomplete, phrases related to functions implemented after version 3.3 were missing. I have translated all missing phrases in Polish translation of files cura.po, uranium.po and fdmprinter.def.json.po. For now, translation is complete. I tried running it on 3.5 beta and I can't encounter any issues.
I closed and re-opened pull request, because previous one had attached only one of the files, and I had no idea how to change it.
=> Complete Polish translation for version 3.5

cura/API/Account.py, cura/API/Backups.py, cura/API/Interface/Settings.py, cura/API/Interface/__init__.py, cura/API/__init__.py, cura/Backups/Backup.py, cura/Backups/BackupsManager.py, cura/CuraApplication.py, cura/OAuth2/AuthorizationService.py, tests/TestOAuth2.py
@nallath https://github.com/Ultimaker/Cura/pull/4423 Looks good. I made some changes to resolve circular imports here.
- Resolve circular imports between oauth, CuraAPI, and CuraApplication which implies circular dependencies.
- It should always be safe to call `import` at the beginning of the code.
- `__init__()` should always be safe to call instead of keeping, for example, `self._cura_api` `None` until all its dependencies have been initialized and then create `CuraAPI`.
=> Resolve circular imports for CuraAPI

cura/CuraApplication.py
If you're adding a model file as command line argument to Cura, it should auto-load this file upon start-up. However when adding this command line argument upon first launch of Cura, there is no printer yet so Cura would crash because it tries to load a model before there is a build volume. This prevents that crash and instead doesn't load the model at all.
=> Fix initial start-up when providing model parameter

plugins/SliceInfoPlugin/SliceInfo.py, plugins/VersionUpgrade/VersionUpgrade34to35/VersionUpgrade34to35.py, plugins/VersionUpgrade/VersionUpgrade34to35/tests/TestVersionUpgrade34to35.py
Because the data Cura collects has been changed.
=> [3.5] CURA-5095 Reset send slice info and show privacy dialog

plugins/USBPrinting/USBPrinterOutputDevice.py
This PR fixes updates to the print monitor temperatures while preheating.
While preheating the bed/extruder with M190 or M109, the firmware keeps outputting temperature lines, but these do not contain "ok" because no new command was acknowledged.
This PR is against master, but since it fixes a bug and the risk of regressions is low, it might be considered for cherry-picking to 3.5
Fixes #3741
=> Fix updating temperature while preheating bed or extruder

plugins/UFPWriter/UFPWriter.py
The snapshot-creation of the UFP-writer should only be called when writing to UFP-files.
=> [CURA-5775] Fix crash on save to 3MF

plugins/CuraEngineBackend/StartSliceJob.py
CURA-5793
Fix GcodeStartEndFormatter to take the correct default_extruder_nr instead of always using -1.
=> [3.5] CURA-5793 fix setting value templates

plugins/3MFWriter/__init__.py, plugins/ChangeLogPlugin/__init__.py, plugins/FirmwareUpdateChecker/__init__.py, plugins/MachineSettingsAction/__init__.py, plugins/ModelChecker/__init__.py, plugins/MonitorStage/__init__.py, plugins/PostProcessingPlugin/__init__.py, plugins/RemovableDriveOutputDevice/__init__.py, plugins/SliceInfoPlugin/__init__.py, plugins/UM3NetworkPrinting/__init__.py, plugins/VersionUpgrade/VersionUpgrade21to22/__init__.py, plugins/VersionUpgrade/VersionUpgrade22to24/__init__.py, plugins/VersionUpgrade/VersionUpgrade25to26/__init__.py, plugins/VersionUpgrade/VersionUpgrade26to27/__init__.py, plugins/VersionUpgrade/VersionUpgrade33to34/__init__.py, plugins/VersionUpgrade/VersionUpgrade34to35/__init__.py, plugins/XmlMaterialProfile/__init__.py
This PR removes unused imports and declaration of i18n in plugins. There's also a PR for Uranium that does the same thing there.
=> Remove unnecessary import and declaration of i18n in plugins

resources/definitions/creality_ender3.def.json
hi @stelgenhof, because the default layer height of Ender 3 is 0.15mm which is the same as "Draft" quality, you can see double qualities in the dropdown list:
So, we propose to change the default layer height to 0.1mm. For Ender 3, you already have `"preferred_quality_type": "draft"`, so it will be draft by default which is 0.15mm
=> [3.5] Use 0.1 layer height as normal for Ender 3

resources/definitions/fdmprinter.def.json
I had some issues with my print, so I decided to fix the issues with a sweat and cool little pull request.
1) control the interaction between brim and support
2) generate a brim under support with the support extruder
new settings:
Enable Support Brim
Support Brim Width
Support Brim Line Count
and
Brim Replaces Support
This PR are the frontend settings for: https://github.com/Ultimaker/CuraEngine/pull/849
=> Feat: support brim

cura/API/Account.py
Cloud team has updated the OAuth2 scopes format to be more uniform, while keeping compatibility with the old scopes) It is still advised though that all clients switch their requested scopes to the new format. This is currently deployed on staging as a test and will be deployed to production early next week, so this PR should be merged after that. Part of STAR-273.
=> Update OAuth2 scopes

plugins/UM3NetworkPrinting/resources/qml/PrintWindow.qml
Small fix in QML to make sure the printer selection pops up for clusters when sending print jobs.
=> [3.6] CL-1117 Hotfix: Show printer selection

plugins/UM3NetworkPrinting/resources/qml/PrinterCard.qml
Contributes to CL-1119
Fixes this issue:
=> CL-1119 Use shorter machine name for skeleton and longer for text (Fix for 3.6)

resources/bundled_packages/cura.json
Otherwise they won't show as installed in the toolbox when in fact they are.
**Before:**
**After:**
=> [3.6] Add Ultimaker materials as bundled

plugins/UM3NetworkPrinting/resources/qml/PrintJobContextMenu.qml
The context menu for queued jobs has "move to top" and "delete"
The context menu for running jobs has "pause" and "abort"
The context menu for paused jobs has "resume" and "abort"
All other print job states do not show the context menu
=> CL-1118 Don't show the context menu for printed jobs

plugins/Toolbox/src/Toolbox.py
Reset the list of generic materials to emtpy when creating the models.
Contributes to CURA-5873.
=> Fix duplicated generic materials

resources/definitions/fdmprinter.def.json
Feature: "Support Interface Offset"
This feature allows to apply offset for support interface polygons.
New Settings:
"Support Interface Offset" ("Support Roof Offset", "Support Floor Offset")
Default values for these settings are 0mm. 
Minimum allowable value is 0mm.
This PR is frontend settings for backend implementation: https://github.com/Ultimaker/CuraEngine/pull/879
=> Feature: "Support Interface Offset"

plugins/3MFReader/ThreeMFWorkspaceReader.py
CURA-5899
Fixes https://github.com/Ultimaker/Cura/issues/4708
Should always use custom quality profile names to look up.
=> [3.6] [CURA-5899] Fix quality changes lookup in project loading

cura/PrinterOutput/NetworkedPrinterOutputDevice.py, plugins/UM3NetworkPrinting/src/LegacyUM3OutputDevice.py
This PR fixes a type error in NetworkedPrinterOutputDevice.post: NetworkedPrinterOutputDevice.post takes data as a Python string, and passes that to QNetworkManager.post(), which does not handle strings.
Strictly speaking the QNetworkManager.post() method takes a QByteArray instead of Python bytes, but according to the PyQt documentation, PyQt handles that conversion transparently:
http://pyqt.sourceforge.net/Docs/PyQt5/gotchas.html#python-strings-qt-strings-and-unicode
The type mismatch only came up recently when I added typing to OctoPrintPlugin:
https://github.com/fieldOfView/OctoPrintPlugin/issues/88#issuecomment-433621940
Only that plugin and the LegacyUM3OutputDevice use the NetworkedPrinterOutputDevice.post method. It would cause a crash when using the manual printer controls. I …
=> Fix type error in NetworkedPrinterOutputDevice.post

cura/Machines/MaterialManager.py
This PR changes how the "Create" button on the Materials pane of the Preferences creates a new material. Since Cura 2.3, a new material is created by duplicating the Generic PLA material. This is done because *most of the time* creating a duplicate of PLA creates a material that is sure to be available for the current printer. However, for some printers, (generic) PLA may not be available or applicable (eg a printer that is specifically not compatible with the generic materials and only shows the materials that are offered/tested by a specific vendor).
Generic PLA is still used for printers that do not specify a preferred material.
=> Use preferred material instead of generic PLA when creating a new material

cura/Machines/QualityManager.py, cura/Settings/ContainerManager.py, cura/Settings/CuraContainerRegistry.py, plugins/LegacyProfileReader/DictionaryOfDoom.json, plugins/LegacyProfileReader/LegacyProfileReader.py, plugins/LegacyProfileReader/tests/TestLegacyProfileReader.py, plugins/LegacyProfileReader/tests/normal_case.ini
It was very buggy in multiple ways:
* It was checking if the importer generated a file with the current version, but still performed the version upgrade (which should not upgrade if it has the current version).
* It was translating using the dictionary of doom to version 3.0, but the version in the file was explicitly overwritten to version 1.0.
* It was using an actual `Profile` instance to save the settings during translating, and serialised that (which serialises in version 4.5 at the moment) and then overwrites the version to 1.0. So the version upgrade system thought it was upgrading from version 1.0 to 4.5, but in actuality it was upgrading from version 4.5 to 4.5, which could corrupt the files.
Now it no longer uses the `Profile` class so that it stays stable even if Uranium/Cura …
=> Fix legacy profile importer

cura/API/Account.py
The new client has access to more permissions and is labeled as "Ultimaker Cura" instead of "Cura Backups Plugin".
Also removes `self._cloud_api_root` as that's not used anymore now that `self._oauth_root` is used for the redirect URLs.
=> Switch Ultimaker Account OAuth2 client

resources/definitions/wanhao_d4s.def.json, resources/definitions/wanhao_d6.def.json, resources/definitions/wanhao_d6_plus.def.json, resources/definitions/wanhao_duplicator5S.def.json, resources/definitions/wanhao_duplicator5Smini.def.json, resources/definitions/wanhao_i3.def.json, resources/definitions/wanhao_i3mini.def.json, resources/definitions/wanhao_i3plus.def.json
The Wanhao profiles are broken as they still use the old `travel_speed` macro. This just updates them to use `speed_travel`.
=> Fix Wanhao profiles to use speed_travel macro

cura/CuraApplication.py, resources/qml/ActionPanel/OutputProcessWidget.qml, resources/qml/Cura.qml
I also decided to hide some elements that are not necessary when looking at a gcode file, such as the Toolbar or the  print time estimations.
=> Fix an issue when loading Gcode to the New UI

resources/qml/AddMachineDialog.qml
Remove transitions when collapsing/expanding the printer category in the add printer dialog. Due to these transitions, there is a weird behavior that Cura seems laggy when in fact is only the transition that make this feeling.
=> Remove laggy transitions

plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterPill.qml
> _Ian, why are you putting this kind of hack into our code base?_
Well I'll tell you: Because Cura Connect uses the printer name/type all over the place so until we have a new design for CC to match Cura 4.0, this was _actually_ a case where the quick solution was also the cleaner one. We can maybe think about adding a "tag" to Cura Connect but then it has to be treated differently than all other printers which use the `NetworkedPrinterOutputModel`.
Contributes to CL-1173.
=> CL-1173 Use short printer family tags

resources/qml/ActionPanel/OutputDevicesActionButton.qml
Now the behavior is the following:
- The active output device is the one that shows up in the button (same as before)
- The list of the output devices don't show the active device
- When clicking in one item of the list, it becomes the active output and automatically it performs the action.
Contributes to CURA-6026.
=> Change the behaviour of the output device selector

resources/definitions/ultimaker_original_plus.def.json
The reason of this issue because it used a heated firmware from his
parent(UMO) printer. To avoid this case we need to define externally
the firmware_hbk_file property in umo+ defintion file
=> [4.0] CURA-5994 Cura used wrong firmware version for UMO+. The firmware was from UMO.

plugins/USBPrinting/MonitorItem.qml, resources/qml/PrintMonitor.qml
This PR fixes two instances of an unthemed rectangle, which causes the print monitor (USB/OctoPrint) to look bad in dark themes.
=> Fix (USB) print monitor in dark theme

cura/Machines/MaterialManager.py, plugins/UM3NetworkPrinting/src/SendMaterialJob.py, plugins/UM3NetworkPrinting/tests/TestSendMaterialJob.py
Updated or new materials wheren't always sent to the (UM) printer, causing the name to be 'unkown'.
=> third party send-materials fix

cura/PrinterOutput/ConfigurationModel.py, resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml, resources/qml/Menus/NetworkPrinterMenu.qml, resources/qml/PrinterSelector/MachineSelector.qml
This PR fixes how connected networkprinters that are not part of Cura Connect are handled in the interface. Network printers that are using eg OctoPrint (but also others, such as Repetier) don't have "connect_group_name"  metadata and may not have the concept of configurations. The PR also fixes a repeating QML warning for every non-networked printer that is added to Cura (including UM2+).
=> Fixes for networkprinters that are not part of Cura Connect

resources/qml/Menus/ProfileMenu.qml, resources/qml/PrintSetupSelector/PrintSetupSelectorHeader.qml
When an experimental quality profile is active, the stage panel does not show that it is experimental.
It is however shown on the quality drop-down menu in Custom mode.
This commit also fixes the untranslated (hardcoded) 'Experimental' string in the dropdown in Custom.
Fixes the issue reported in CURA-6118.
=> Add 'Experimental' tag for quality profiles in the header.

resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
This PR adds the variant name (print-core / nozzle size) to the headerItem of the configuration menu:
This makes the header a better "summary" of the extruder configuration. Without this, the print core/nozzle size is only shown when expanding the configuration menu for the extruders.
=> Add variant to the configuration menu headerItem

resources/qml/PrintSetupSelector/PrintSetupSelectorContents.qml, resources/themes/cura-light/icons/grip_lines.svg, resources/themes/cura-light/icons/resize.svg, resources/themes/cura-light/theme.json
Make it wider and more visible to the user.
Change icon.
Keep margins according to the other panels.
This is how it would look like with this change:
=> Change the style of the resize bar

resources/definitions/monoprice_ultimate.def.json
The default values on my Monoprice Ultimate are way different to what Cura has the Wanhao Duplicator 6 as. I'm guessing that Monoprice have changed these (if not, then maybe the Duplicator 6 file is wrong?). Without this profile, I had a 4hr print estimate for a piece that's only 55% through after 4hours. With this profile, it estimates 7:22 (which seems very accurate).
I got the default values from the printer when I connected Octoprint to it:
```
21:20:56: Attempting to connect to printer
21:20:56: Connection opened
< 21:20:57: start
> 21:20:57: N1 M110 *2
< 21:20:57: echo:Marlin 1.0.0
> 21:20:57: N2 M110 *1
< 21:20:57: echo: Last Updated: Jun 26 2016 12:14:19 | Author: Version DEV 3.01
> 21:20:57: N3 M115 *5
< 21:20:57: Compiled: Jun 26 2016
< 21:20:57: echo: Free Memory: 1961 …
```
=> Add Monoprice Ultimate based on Wanhao D6

plugins/XRayView/XRayView.py
This PR fixes z-fighting in the X-Ray view, by not rendering convex hulls. It sort-of makes sense not to render a shadow in X-Ray view.
Example with a fairly flat model where the z-fighting is particularly distracting:
**Before**
**After**
=> Fix z-fighting on bottom layer of x-ray view

resources/qml/Preferences/Materials/MaterialsPage.qml
Do not allow the user to activate a material if the printer is not defined to have materials. In 3.0.4 it was like this, but it was changed in some refactor.
Contributes to #4550.
=> Not activate materials if the printer has no materials.

plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
NOTE: The original issue of the print job requiring action showing up alongside a printer status has been fixed already, so this ticket now just fixes the issue of "unreachable" printers being labeled "unavailable." They're now labeled correctly.
=> CL-1188 hide print job on unavailable printer

cura/GlobalStacksModel.py, cura/Settings/GlobalStack.py, cura/Settings/MachineManager.py, plugins/UM3NetworkPrinting/src/DiscoverUM3Action.py, plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
After a lot of discussion and finding out what the hell was going on, we figured out we made a pretty big derp by only setting a single connection_type in the metadata of the machine. What it's actually doing is describing what connection types have been configured (and not just randomly displaying whatever output device set the value last).
So this PR refactors that by adding a convenience function to the global stack, which still uses the same metadata.
=> Fix configured connection types

cura/Settings/MachineManager.py, plugins/MonitorStage/MonitorMain.qml, plugins/UM3NetworkPrinting/resources/qml/ExpandableCard.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorQueue.qml, resources/themes/cura-dark/theme.json, resources/themes/cura-light/theme.json
- When you have a UM network-enabled printer, configured for network printing, connected, you should see the monitor tab, and if there are no jobs, see a link to Cura Connect.
- When you have a UM network-enabled printer, configured for network printing, not connected, you should see a warning to check that the printer is on and has connection.
- When you have a UM network-enabled printer, not configured for network printing, you should see a message telling you to select a network-enabled printer to monitor, and a link to the UM website with printer manuals.
- When you have any non-network enabled printer, you should see only the message telling you to select a network-enabled printer to monitor.
=> CL-1154 Monitor empty states

cura/GlobalStacksModel.py, cura/Machines/Models/MachineManagementModel.py, cura/Settings/MachineManager.py, plugins/3MFReader/ThreeMFWorkspaceReader.py, plugins/UM3NetworkPrinting/src/DiscoverUM3Action.py, plugins/VersionUpgrade/VersionUpgrade35to40/VersionUpgrade35to40.py, resources/qml/Menus/NetworkPrinterMenu.qml, resources/qml/Preferences/MachinesPage.qml, resources/qml/PrinterSelector/MachineSelectorList.qml
Per @nallath 's request: Added a rename and a version-upgrade ('connect_group_name' is now 'group_name') to this, as this was a good opportunity to do just that. (The actual fix is in the first commit.)
=> CURA-6153 wrong name on disconnect

plugins/PrepareStage/PrepareMain.qml, plugins/PrepareStage/PrepareStage.py, plugins/PreviewStage/PreviewMain.qml, resources/qml/ActionPanel/ActionPanelWidget.qml, resources/qml/ActionPanel/OutputProcessWidget.qml, resources/qml/Cura.qml
The positioning and configuration of the action panel greatly differs per stage. In this pull request we make the stage create its own action panel widget. This way it can choose for itself whether or not it even wants an action panel, where the action panel is located and whether or not the preview button is visible on that panel.
Contributes to issue CURA-6086.
@fieldOfView You might want to check if this has any influence on your sidebar plug-in. It should behave the same, but you never know.
=> Let each stage create its own action panel

cura/API/Account.py, cura/OAuth2/AuthorizationHelpers.py, cura/OAuth2/AuthorizationRequestHandler.py, cura/OAuth2/AuthorizationService.py, cura/OAuth2/Models.py, plugins/UM3NetworkPrinting/src/Cloud/CloudApiClient.py, tests/TestOAuth2.py
This PR adds proper refreshing of access tokens before they are used in an API call that. By storing the creation date (and using the already stored expiry time) we calculate the expected expiry date. If the access token is requested from the account object after this time, we do a token refresh before returning the (new) access token. This prevents API calls to result in a 401.
=> Fix token refresh

cura/PrinterOutput/PrinterOutputModel.py, plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterPrinterStatus.py, plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
This makes sure cloud printers set their build plate so Cura doesn't try to handle an empty build plate.
This includes a fix where the `buildplate` (e.g. "glass") was misidentified as `buildplate_name` (e.g. "Glass").
=> CL-1250 set cloud build plate

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py, plugins/UM3NetworkPrinting/tests/Cloud/TestCloudOutputDevice.py
This fixes UFP not being selected as default file type when printing over cloud.
=> CL-1255 Manually create printer properties for cloud output device

plugins/CuraDrive/src/DriveApiService.py
When the API returns a 200 but the content does not contain a data field, Cura would crash. Although this should not happen in the API, it's better to handle this case properly in Cura anyways.
=> Add extra validation to backup list response

cura/OAuth2/AuthorizationService.py, plugins/CuraDrive/src/DriveApiService.py
As the token was expired on the very last second, sometimes an API call could be made between the 'local expiry' and the actual expiry on the server. Having some overlap (1 minute) will prevent these time syncing issues.
=> Fix token expiry

plugins/CuraEngineBackend/StartSliceJob.py, resources/definitions/wanhao_d9.def.json
This PR adds {travel_speed} as an alias to {speed_travel} for replacement patterns in start- and end-gcode snippets for all those people who still copy paste legacy start&end gcode snippets into Cura. It also fixes one current definition which uses the deprecated {travel_speed} pattern, to set a better example.
=> Add {travel_speed} as an alias to {speed_travel}

cura/Settings/CuraContainerRegistry.py, resources/definitions/fdmextruder.def.json, resources/definitions/fdmprinter.def.json, tests/Settings/TestCuraContainerRegistry.py, tests/Settings/conftest.py
When a container had an incorrect setting version, the metadata was still being loaded (but the complete container was not). This PR corrects that.
This PR depends on https://github.com/Ultimaker/Uranium/pull/471.
Implements CURA-6270.
=> Don't load containers with a wrong setting version

plugins/USBPrinting/USBPrinterOutputDevice.py
The g-code writer processes the post-processing scripts properly, so get the g-code from that plug-in.
Fixes #5410.
=> Fix post-processing scripts when printing via USB

plugins/GCodeReader/GCodeReader.py, plugins/UFPReader/UFPReader.py, plugins/UFPReader/__init__.py, plugins/UFPReader/plugin.json, plugins/UFPWriter/UFPWriter.py, resources/bundled_packages/cura.json
This PR adds the possibility to open and visualise the Ultimaker Format Package files. It was an internal request. 
The UFP file is used in the Ultimaker S5 as a 3mf format files that stores the gcode and other files that are needed for the right operation in that printer. The file includes a screenshot and information about the material that is used (among other files)
With this plugin, the user will be able to open the GCode that is included in that file.
=> New bundled plugin: UFPReader

plugins/ImageReader/ConfigUI.qml, plugins/ImageReader/ImageReader.py, plugins/ImageReader/ImageReaderUI.py
The defaults for image import were rather arbitrary.
I think more people use this option for lithophanes than for height fields.
I've also updated the tooltip to explain *when* to use which option, rather than only being descriptive.
=> Lithophane defaults

resources/qml/PrintSetupSelector/PrintSetupSelector.qml
Noticed that "g-code" is written at some places with and without a hyphen.
Since it think it should be written with, I'm correcting it at this point.
=> PrintSetupSelector: "G code" -> "G-code"

cura_app.py
The expanduser function will expand to a combination of HOMEDRIVE and HOMEPATH which might not be the same as APPDATA if your configuration is very weird (e.g. you've changed your APPDATA location).
Contributes to CURA-6418.
Hopefully fixes #5471.
=> Fix for weird home directories on Windows

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
The goal here is to prevent a cloud cluster which is connected but not tied to the active machine setting metadata on the active machine.
=> CL-1267 Don't hide Cloud flow message for wrong printer

cura/CuraApplication.py, cura/Settings/MachineManager.py, plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py, resources/qml/Dialogs/AddMachineDialog.qml, tests/TestMachineManager.py
This changes the position where we store the list of networked printers, so that we can use it outside of the UM networking plug-in.
Contributes to issue CURA-6179.
=> Networked printer architecture

resources/qml/Menus/ConfigurationMenu/ConfigurationMenu.qml
Actually it only made sense for Ultimaker materials. Now that we can include instruction link in every materials, a specific link for every material can be used instead. This is done in https://github.com/Ultimaker/fdm_materials/pull/78
Contributes to CURA-6423.
=> Remove the link to the compatibility chart

resources/definitions/anycubic_4max.def.json, resources/definitions/anycubic_i3_mega.def.json
There are some comments on new lines in the anycubic printer definitions, which do not start with ";". The printer will respond with an error for this reason.
I decided to remove the new line, as many other printer definitions include the same comment without new line.
=> Fix comments in anycubic printer definitions

cura/Machines/Models/DiscoveredPrintersModel.py, resources/qml/PrinterSelector/MachineSelectorButton.qml, resources/qml/WelcomePages/AddNetworkPrinterScrollView.qml
- Group printers into hosts and non-hosts and of unknown type.
- Show available/connectable printers first in the list.
- Show sections for connectable and non-connectable printers.
=> CURA-6449 Disable printers that are not host of a group

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py, plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterResponse.py, plugins/UM3NetworkPrinting/tests/Cloud/TestCloudOutputDevice.py
This is a very MVP version of cloud cluster discovery. It shows the cloud printers in the 'add printer' discovery list when signed in and creates a stack with the correct printer type when clicking 'add'. There is no further UX changes yet (like telling the user in the UI that cloud printers will appear in the list when signed in). The code and UX are not optimal, but since we're going to re-work the plugin anyways we might as well have a temp solution?
ping @ianpaschal @sedwards2009 @nallath
=> Add minimal support for discovering cloud printers outside of LAN

plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml, plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py
Formerly the pills were rendered based on the print job's `compatible_machine_families` property.
This property is always the intersection of printers in the group and printers the job can use.* In the case of an S5 print job in a group with no S5 machines, the print job has no compatible machine families to show a pill for, and hence there's no pill and this bug exists. Although logical, this is not ideal because knowing what the print job was sliced for is exactly the case where it's very important to see the pill next to the blocked print job.
For this reason I have switched to using the `configuration.machine_variant` instead of `compatible_machine_families`.
*This is sort of a lie. In the Cura Connect code, the print job's side of the matching never uses more than a single printer …
=> CL-1055 Show "sliced for" pills on print jobs

plugins/UFPReader/__init__.py
This PR fixes an ugly error when libCharon is not available on the system. The same fix is also in place in UFPWriter, and similar fixes for a missing libSavitar are in 3MFReader and 3MFWriter. Functionally the PR has no impact, but it cleans up logs.
=> Fix error when libCharon is not available

resources/definitions/fdmprinter.def.json
This option prefers hiding, but if no good hiding spot is available it'll expose the seam on the sharpest outer corner.
Contributes to issue CURA-6489.
=> Add option to prefer hiding seams in a smarter way

plugins/USBPrinting/USBPrinterOutputDeviceManager.py
…by filtering ports with regular expressions passed in as environment variables.
Cura scans all USB serial ports for printers. To do this it reads (steals) data from the ports, writes data and changes settings of those ports. 
Due to this you cannot use USB serial ports for other things while using Cura.
Cura could check for lock files and leave associated ports alone. Not all other software uses those lock files, so this would not be a universal solution.
On linux you can prevent unwanted access to the devices by authorization. E.g. make the device file owned by a group and make only the services or users that should access the device a member of that group. This does not help here, since the Cura user and the user of the other devices can easily be the same. Also it would need an …
=> Prevent Cura from messing with serial ports of other devices

resources/definitions/creality_ender3.def.json
#5701 Adjusted retraction distance and retraction speed for Ender 3. 
These settings work well for me. I can't say for certain if these settings really improve the print over the previous settings. 
Chuck talks about these numbers specifically in his video: https://www.youtube.com/watch?time_continue=6&v=GXSqZ68UdsE
=> Adjust retraction distance and retraction speed on Ender 3

resources/definitions/creality_ender3.def.json
I suggest a change to the value of max  Z-axis Jerk to be the same as on Marlin 1.1.9 firmware used by Ender 3. Its a small change, reducing 0,4 to 0,3. Having these settings match the firmware's configuration makes a print's estimated time more accurate.
=> Adjust max Z-axis jerk on Ender 3

cura/API/Machines.py, cura/API/__init__.py, plugins/UM3NetworkPrinting/resources/qml/DiscoverUM3Action.qml, plugins/UM3NetworkPrinting/src/DiscoverUM3Action.py, plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
> Heavily WIP! Mainly a conversation starter for now.
This PR is intended to make the network printing plugin less knowledgable about the internal structure of Cura in the hope that it will make it easier to maintain.
Specifically this means:
1. No more touching of container stacks. That's Cura's internal way to represent things and should not be our concern. We only want to handle "printers" and their respective connection types.
2. Output devices, container stacks, and metadata are all often different pieces of data related to a single physical machine (or cluster) which we want to operate on. Since Cura doesn't have a machine class (yet), we bundle that data into a more usable object via the API.
3. Reduced use of signals because they are icky and you never know who is triggering them …
=> CL-1331 Extending the Cura API for the Network Printing Plugin

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py, plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Cloud/Models/CloudClusterResponse.py
This PR fixes some small bugs in the cloud discovery flow and make it more robust:
* Allow printer_type field from cloud cluster list endpoint (will make a cloud PR that adds this field to the /clusters endpoint so we know the printer type without having to do a 2nd call to /status). This is more robust than the current solution that tries to map the machine variant to printer type.
* Use a default value for printer type (discovered printer list does not always fully refresh once actual data comes in).
* Using `device.key` instead of `cluster.cluster_id` to be more consistent between the add, update and remove function calls for discovered devices.
* Added some missing documentation.
=> Amazing fixes for cloud discovery

resources/definitions/fdmprinter.def.json
Feature: "Nozzle Switch Extra Prime Distance"
This feature allows to set the extra material to prime after nozzle switching.
New Setting:
"Nozzle Switch Extra Prime Distance"
This PR is frontend settings for backend implementation: https://github.com/Ultimaker/CuraEngine/pull/882
=> Feature: "Nozzle Switch Extra Prime Distance"

cura/Settings/MachineManager.py
This fixes a bug where settings are being reset to "0" (or whatever the default extruder number is) when discarding current changes to settings. This happens to all settings that are:
* In the quality-changes profile.
* Not currently visible.
Why would it need to reset all invisible settings? It shouldn't matter whether a setting is visible or not.
This is causing bugs because the settings that are being reset are not necessarily extruder-type settings (as that is checked below). They are being reset to the value self._default_extruder, which is not always a valid setting value.
Reproduce steps:
1. Ultimaker 3, 0.4mm nozzle, PLA, 0.1mm layer height to start with.
2. Enable support.
3. Set Support Placement to the non-default (=Touching Buildplate).
4. Disable support.
5. Save the current …
=> Fix auto-resetting settings when discarding user changes

cura/CuraView.py
This PR fixes the QUrl to the local file holding the placeholder from view menu components.
Before the PR:
````QUrl('c:%5CUsers%5CAldo%5CDocuments%5CCode Projects%5CUM%5CCura%5Ccura%5C..%5Cresources%5Cqml%5CEmptyViewMenuComponent.qml')```` (which is not a valid URL)
After the PR:
```QUrl('file:///C:/Users/Aldo/Documents/Code Projects/UM/Cura/cura/../resources/qml/EmptyViewMenuComponent.qml')```
=> Fix creating QUrl to EmptyViewMenuComponent.qml

plugins/MonitorStage/MonitorMain.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorContextMenu.qml
Due to an issue with Qt list models the order of the queued print jobs is not the actual order of them in the print queue. This can be solved by adding a custom sort to the list model, but we currently have no data to base this sorting on as the cluster API does not return the order of a print job in the queue (and fields like UUID or creation date are not appropriate for sorting either). For now we have decided to just hide the 'move to top' option that is somewhat useless at the moment (you will still be able to use it via the cloud or connect web interfaces).
=> Hide 'move to top' option from actions

cura/CuraApplication.py, cura/Machines/Models/IntentCategoryModel.py, cura/Machines/Models/IntentModel.py, cura/Settings/IntentManager.py, resources/intent/smooth.inst.cfg, resources/intent/strong.inst.cfg, resources/qml/Menus/IntentMenu.qml, tests/TestIntentManager.py
This gives the intent model a property for which intent category it should list the intents. And then it lists those intents.
Implements CURA-6597.
=> Create an intent model per intent category

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py, plugins/UM3NetworkPrinting/src/ClusterUM3OutputDevice.py, plugins/UM3NetworkPrinting/src/ClusterUM3PrinterOutputController.py
In the cloud and new local endpoints we're using 'resume' as the action, but Cura was still using the older endpoints which was using 'print' as state. For now this is just a quick fix to make it work with the existing endpoints, in the future we can switch to the newer endpoints on the CC API once enough people have updated their printer.
=> Send the correct action name when using local network

plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobCard.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterCard.qml
The preferred solution was to change the copywriting, but since we are after string freeze we cannot do this. This is the next best solution to prevent user confusion.
=> Hide incorrect tooltip

resources/qml/ActionPanel/PrintInformationWidget.qml
Remains compatible with Qt 5.10.
Tested using Qt 5.13 on Linux and Qt 5.10 on Windows.
=> Fix dimensions of print job information popup when using Qt 5.13.

plugins/UM3NetworkPrinting/resources/qml/DiscoverUM3Action.qml, plugins/UM3NetworkPrinting/resources/qml/MonitorPrinterPill.qml, plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py
There were some hard-coded references to machine types and BOM numbers. These are already in the definition files so don't need to be in the actual code. This PR fixes that.
=> Get rid of any hard-coded references to machines

resources/qml/ExpandablePopup.qml
Without this, the view selector dropdown has no background.
Tested with Qt 5.13 on Linux and Qt 5.10 on Windows.
=> Qt 5.13 compatibility - fix size of ExpandablePopup background.

resources/definitions/creality_base.def.json
Follow up to https://github.com/Ultimaker/Cura/commit/1d7f2e645e3489eedac41fb20f98b9f66c100b28
Setting Z speed too high may lead to skipped steps and losing Z accuracy, which is super important with Z hop enabled.
=> Creality machines - lower Z-hop speed to 5

plugins/UM3NetworkPrinting/src/Cloud/CloudApiClient.py, plugins/UM3NetworkPrinting/src/Messages/LegacyDeviceNoLongerSupportedMessage.py, plugins/UM3NetworkPrinting/src/Messages/NotClusterHostMessage.py, plugins/UM3NetworkPrinting/src/Network/ClusterApiClient.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py
Some issues were found when testing:
* Adding by manual IP address would not always work. This PR fixes that by ensuring the validation API call to `/api/v1/system` is not cleaned up by Python's garbage collection before a reply was received.
* A neat message is shown when a user is attempting to connect to a legacy (firmware < 4.0.0) device.
* A neat message is shown when a user is attempting to connect to a printer that is not a Connect group host.
* Code improvements with regards to manual device check callbacks (no need to store them globally when we can pass them with a lambda).
* Proper abstraction methods for getting/setting stored manual IP addresses in preferences.
* Fixed some return types.
=> CS-234: Network plugin improvements

resources/definitions/fdmprinter.def.json
Add a dropdown with position presets to quickly set Z-Seam X/Y when using `z_seam_type='back'`, eg. **User Specified** alignement.
=> feat: "Z-Seam Position" presets to ease XY setting

cura/LayerPolygon.py
I guess the compatibility mode doesn't get much testing these days. This slipped through the net.
=> Add entry for prime tower type to _isInfillOrSkinTypeMap.

resources/definitions/fdmprinter.def.json
Research into the physical properties of print paths by Peter Sap has indicated that starting the infill pattern at the same location on each layer reduces the stiffness of the print.
This is the case for line-based infill patterns which contain crossings, e.g. grid and triangle.
Those crossings cause problems; when a print path crosses an already printed path the second path gets interrupted and the connection between the two print paths is not strong. When the same ordering of the infill paths is present on each layer, you get one strong wall and all other walls of the infill pattern are weaker.
In tensile tests you can easily see this is the case because you will end up with the infill pattern broken apart and hanging on to those initial lines.
By randomizing the start position where …
=> JSON: new setting infill_randomize_start_location

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDevice.py
Before it was creating an API client (with network access manager) on every device object instance. Now it's only creating it once that device is connected and starts doing API calls.
=> Only create API client when actually used

plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterMaterialStationSlot.py, plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterStatus.py
Materials in slots that are (nearly) empty should be ignored in the available configurations list as they are in fact not available for printing. As this field was added to the Connect API later it is supposed to be optional.
=> Cs 278 ignore material empty

plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
See issue #5924 
PauseAtHeight.py was resuming 1mm higher than it paused at (line 312). If the original script doesn't happen to move to the correct Z height before resuming the layer, the entire layer will be printed 1mm too high.
I modified code to resume at the same level it paused at _after_ the X-Y jog completes (to avoid hitting any prints). Also added additional comments to generated code.
=> Fixed PauseAtHeight.py to resume at starting height

cura/PrinterOutput/NetworkedPrinterOutputDevice.py, plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDevice.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Network/SendMaterialJob.py
This PR is an investigation into the print job uploading issues we have experienced recently. Several small changes combined hopefully reduce the chance that a print job upload fails.
* Reduce logging for material syncing (which was found to be annoying).
* Disable material syncing when uploading print job to reduce network activity to the printer. This changes the current behavior but I think it is fine as the material profiles are still synced after installing a new material profile (which forces a Cura restart and thus device reconnect).
* Remove the re-creation of the network manager (I have found that job uploading got stuck while the network manager was re-created every 30 seconds). I'm aware this could cause new issues on MacOS (as described in the removed lines), but I think this …
=> Print job uploading

plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterStatus.py
When a printer is just added to a group, it might happen that its configurations aren't known yet. In this case we should not access properties on it (and wait for the next status update). Also setting the amount of expected extruders to 2 (all UM networked printers have 2 extruders) because the first status call the number of configurations in the API might not be 2 (and it cannot be changed in the model later on).
=> Check if printerConfiguration is actually set before trying to access it

plugins/PostProcessingPlugin/scripts/RetractContinue.py
This post-processing script makes the printer keep on retracting during a travel move.
Implements issue CURA-6755.
=> Add retract-continue script

plugins/UM3NetworkPrinting/resources/qml/MonitorPrintJobProgressBar.qml, resources/themes/cura-light/theme.json
> **Note:** Cherry picked some commits to a new branch from 4.3
This is two things in one to hopefully avoid having this bug from ever returning from the grave for a 3rd time:
1. Reduce text size from 'medium' to 'default'. It looks a little small, but there simply isn't more room in the design as it was created and wrapping to the next line looks silly.
2. Reduce the progress bar length a bit so that the percent label's left side as at the "column edge" (aligned with the 2nd extruder info).
=> CS-158 Fix monitor tab print status (4.3 cherry pick)

plugins/UM3NetworkPrinting/src/Messages/CloudFlowMessage.py, plugins/UM3NetworkPrinting/src/Messages/CloudPrinterDetectedMessage.py
Users might not want to see the message that new cloud printers were found every time. This PR adds a checkbox to allow them to disable the message in the future.
Also fixed loading another popup's image on Windows.
=> Store in preferences if the user wants to hide the message

cura/Machines/Models/IntentModel.py, cura/Settings/cura_empty_instance_containers.py
When adding some printers you would get a crash when you add them. This happened if the material or quality profile layer ended up empty. No longer.
Fixes CURA-6775.
=> Fix crash when adding printers with empty profile layers

plugins/MonitorStage/__init__.py, plugins/PrepareStage/__init__.py, plugins/PreviewStage/__init__.py
In theory, it should be possible to add stages, but there is no possibility to add to any other stage in between. Therefore, I moved the weights by 10+n×10. So we can add 10 before prepare and 9 stages between those 3 known stages.
It is probably possible to set the same weight to multiple stages, but I'm not sure how Cura decides, which stage to take first then. By the moment the plugin's init is called? Or by alphabet?
Therefore, putting some space in between the weights should give some clarity.
Related to: https://github.com/tetonsim/is-cura-ui/issues/1
=> plugins: Reweighting stages

plugins/PostProcessingPlugin/scripts/PauseAtHeight.py, plugins/PostProcessingPlugin/scripts/PauseAtHeightforRepetier.py
Curretly the Feedrate is set to 9000 at the end of the Pause at height script. @ChrisTerBeke, please let me know if there was a valid reason for that.
After a Pause at a certain height, the previous feed rate should be restored. This PR implements it for the general Pause At height script and the Repetier script.
The Duet and BQ, scripts should be unaffected by this issue and thus not need a change
=> Cura 6799 pause at height resume speed

resources/definitions/bibo2_dual.def.json
BIBO and members from the BIBO group on Facebook say this printer should be run at 40-45mm/s and not the FDMprinter default of 60mm/s. BIBO provided test gcode files also show that they are setting 40mm/s in the slicer to create their test files.
This change sets the print speed override so the printer profile does not start at the FDMPrinter print speed default of 60mm/s but at the reccommended value of 40mm/s
=> Set BIBO print speed to 40mm/s

cura.desktop.in
This has been infuriating me for the past few weeks. The result of this change is that when you use Cura as built from source or via [thopiekar's PPA](https://github.com/thopiekar/Cura-packaging) the Gnome shortcut will act only as a launcher for potentially infinite instances of Cura. That is, if you keep clicking it, it will open up more and more instances of Cura. This is because the class cura.real is not present or specified in the desktop file. See this askubuntu thread on the topic;
https://askubuntu.com/questions/367396/what-does-the-startupwmclass-field-of-a-desktop-file-represent/367851#367851
Simply adding "StartupWMClass=cura.real" allows Cura to behave like a normal application in all desktop environments that implement .desktop. Cura can now spawn children and in gnome in …
=> Add StartupWMClass=cura.real to fix window grouping in most DEs.

plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py
* The cloud flow message is now only shown when the user is signed in and the active machine is not cloud connected yet.
* When using the legacy 'connect over network' button, we now create a new machine to enforce proper configuration is applied (instead of trying to transform the current machine into something else, which can cause a lot of issues). This fixes CS-328.
=> Network plugin improvements

plugins/UM3NetworkPrinting/resources/qml/DiscoverUM3Action.qml, plugins/UM3NetworkPrinting/src/UltimakerNetworkedPrinterOutputDevice.py
This fixes an issue where the printer's type ID would be shown in the networking window instead of the display name (CS-298).
=> Use printer type name instead of id

resources/definitions/fdmprinter.def.json
This could cause a large overhang.
Contributes to issue CURA-6106.
=> Warn when difference between X/Y distance and minimum X/Y distance is too big

cura/Settings/MachineManager.py
- Approximate diameter needed to be a string.
- GUID-tag is mostly in capitals.
- Workaround for an overload of 'get' not being called (default parameter didn't work somehow?).
part of CURA-6817
=> Fix synchronise configurations (intent branch).

plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDevice.py, plugins/UM3NetworkPrinting/src/Cloud/CloudOutputDeviceManager.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDeviceManager.py
Due to a race between setting some required metadata entries and actually switching to the stack containing them, sometimes the right data would not be there on time, and the auto-pairing to cloud discovered devices would not work.
Additionally there was an error in logic for auto pairing cloud devices for manually added local devices.
=> Fix cloud connection auto fallback

cura/OneAtATimeIterator.py, cura/Scene/ConvexHullDecorator.py
In juli 2018, the OneAtATimeIterator - which determines the order in which objects are printed - was rewritten. Based on bug reports, the old implementation performed better than the new one. It was decided that the old implementation was a better starting point for this fix.
I verified that some obvious improvements of 06-2018 are kept in place. The Shapely library is still used for higher precision in intersection calculation.
As another improvement and hopefully fix to the problem we see now, the nozzle offset is taken into account. 
Given that...
A: An earlier ticket, https://jira.ultimaker.com/browse/CURA-5538
( source: https://github.com/Ultimaker/Cura/issues/4011 ) explicitly states that the issue only occurs with extruder 2 and
B: The nozzle offset relative to the printhead for …
=> Cura 6785 one at a time ordering

cura/Machines/VariantNode.py
Fixes a crash for materials which don't have that metadata-entry,
such as an empty material (UM2)
CURA-6873
=> None-check for material diameter.

plugins/AMFReader/AMFReader.py
When an AMF file is imported, the Y axis is reversed, creating a mirrored object. 
Here are an AMF and a STL files exported from the same FreeCAD project and print screens showing the object being imported correctly as STL but having the Y axis reversed when the AMF is imported, and the AMF being imported correctly to Slic3r.
- [AMF mirror test.zip](https://github.com/Ultimaker/Cura/files/3705114/AMF.mirror.test.zip)
This change reverses the Y coordinates so the object is imported correctly. It's just a quick workaround to mask something that is likely not right in the AMFReader code.
=> Reverse Y coordinates when importing AMF files so it isn't mirrored

resources/definitions/bibo2_dual.def.json
The default value here would not be used. Override must be `value` not `default_value` solves #6491 for BIBO but other printers may also be affected by #6491.
=> Overwrite prime_tower_position_* use value not default_value

resources/qml/Preferences/GeneralPage.qml
This PR adds a preference around restoring the previous window position/size to the last used position/size on start up. This would be a workaround for those setups where starting Cura on a secondary screen will prevent it from working. 
Contributes to https://github.com/Ultimaker/Cura/issues/5651#issuecomment-488048392 and the rest of these issues: https://github.com/ultimaker/cura/issues?utf8=%E2%9C%93&q=is%3Aissue+window_left+is%3Aopen+
Requires https://github.com/Ultimaker/Uranium/pull/523
See https://github.com/Ultimaker/Uranium/pull/523
=> Add preference to (not) restore the window geometry on startup

plugins/CuraEngineBackend/StartSliceJob.py
Checking the whole stack can be time consuming and we don't need to do it again if there are no per-object settings that could possibly cause errors.
=> Return early from _checkStackForErrors() if top container is empty.

cura/PrinterOutput/Models/PrinterOutputModel.py, plugins/UM3NetworkPrinting/resources/qml/PrintWindow.qml, plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterStatus.py, plugins/UM3NetworkPrinting/src/Network/LocalClusterOutputDevice.py
We removed this feature in 4.3, but market feedback let us know that this feature was actually used quite a bit. This PR brings it back! It also polishes the previous code for this feature a bit (no more 4 yields).
(see https://github.com/Ultimaker/Cura/issues/6433 and https://community.ultimaker.com/topic/29672-cant-select-specific-printer-43/)
=> Bring back the printer selection dialog for networked printers

plugins/SimulationView/LayerSlider.qml
Upper handle position would not be updated on resize
CURA-6854
=> Fix window resize bug in LayerSlider concerning handle position

cura/Settings/ContainerManager.py, resources/qml/Preferences/Materials/MaterialsView.qml
I'm not very knowledgeable about this area of the code.
I'd say fixing the casing of the dict index is okay,
but not sure why it worked originally (was the default for ignore_case changed?)
The getLinkedMaterials call returns 20+ materials after aforementioned fix.
Not sure what amount to expect there. Depending on the answer it might
be a good idea to only show the first result.
I re-made this PR because the base should be 4.4 branch
=> Cura 6917 unlink duplicated material

plugins/MachineSettingsAction/MachineSettingsPrinterTab.qml, resources/definitions/fdmprinter.def.json
This PR adds the machine_extruders_share_heater setting and an associated checkbox in the printer settings dialog. Defaults to false.
See #5770.
=> Add support for printers that have multiple extruders that share a single heater

plugins/PostProcessingPlugin/scripts/PauseAtHeight.py
Previously, the line after the layer change would also contain the z height.
If not found, the could would break the per-line reading, and skip to the next layer.
However, if the code doesn't contain the Z on the first gcode line of the layer, this would cause it to skip past all layers, until there was a layer with the Z in the first line (so this also explains the 'late' pauses).
I just ignored the optimization and made it a continue.
I checked, and I don't think there's any way this causes the postproc.-gcode to be inserted twice, since it returns the complete data after insering it once.
CURA-6965
Tagging @DonExo ; Was looking at this as well.
=> Fix skip (or late) pause at height.

resources/definitions/fdmprinter.def.json
A skin that is over sparse infill is considered to be unsupported for bridging purposes.
As discussed in https://community.ultimaker.com/topic/22195-introducing-the-experimental-bridging-settings/?do=findComment&comment=237649
=> Added bridge_sparse_infill_max_density to specify max density of sparse infill.

cura/PrinterOutput/NetworkedPrinterOutputDevice.py
This PR fixes a typo that creates incomplete multipart form data parts when uploading prints to a networked printer.
=> Fix typo in content disposition header

plugins/VersionUpgrade/VersionUpgrade41to42/VersionUpgrade41to42.py, plugins/VersionUpgrade/VersionUpgrade42to43/VersionUpgrade42to43.py, plugins/VersionUpgrade/VersionUpgrade43to44/VersionUpgrade43to44.py
Prevent deleting comments from Start/End G-codes by changing the `comment_prefixes` in ConfigParser" -m "CURA/6994".
Note: We should add this in every future VersionUpgrade.
Fixes #6689
=> CURA-6994/Prevent deleting comments from Start/End G-codes

resources/definitions/creality_ender3.def.json
Added the popular prime line for the Ender 3 as the default starting g-code and added a modification that works around the Cura 4.3.0 update that moves the print head to Z0 before starting the print, which moves the printhead down into the filament.
=> Added Ender 3 Prime Line to Start G-code

plugins/ImageReader/ImageReader.py
That way the picture is not always square. We can use the alpha channel to encode the actual shape
=> make lithophane alpha channel control total final width multiplier.

cura/Settings/MachineManager.py
The machine manager was leading to a crash when trying to enable
the second extruder in single-extrusion printers, because the check
for the second extruder was not correctly implemented. This commit
fixes that issue by checking if the global stack has the specified
extruder. If it does not, then the function returns while logging the
issue.
CURA-7048
=> Fix PPA crashing on single-extruder printers

plugins/XmlMaterialProfile/XmlMaterialProfile.py, resources/definitions/fdmprinter.def.json
These settings are currently unused by cura, but passed into the PPA
output. Some considerations:
- material_ prepended to all. Even though they are not all
material specific. The consistency is more developer-friendly imho
- defaults taken from generic_pla
- type is float for all, consistent with what I found in this file
CURA-7041
=> CURA-7041_add_misp_material_settings

plugins/PerObjectSettingsTool/PerObjectCategory.qml, resources/qml/Menus/SettingVisibilityPresetsMenu.qml, resources/qml/Settings/SettingCategory.qml, resources/qml/Settings/SettingView.qml
Adds a menu item in the Custom Print Settings list to collapse all categories
Does not work when a search is active. See Accompanying Uranium PR.
=> CURA-6959_collapse_categories

cura/CrashHandler.py, cura_app.py
Only whenever the sentry_sdk module is there functions of this module will be used.
The only changes, which were needed to be made, are done on cura_app.py and cura.CrashHandler.
Whenever the module is not available, it's functions will be omitted.
The if-clauses could happen earlier, but this at least the bare minimum, and, to be honest, on Ultimaker's distribution it won't speed up anything.
I expect the if-clause to take the same amount of runtime sooner or later. The check is the same and it should be on Ultimaker's distribution always be "True".
Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)
=> SentrySDK: Turn on deep integration on demand

plugins/Toolbox/resources/qml/dialogs/ToolboxLicenseDialog.qml, plugins/Toolbox/src/Toolbox.py
Implemented the logic for syncing packages from Cura MP to Cloud MP when a user installs a package.
Re-based version of #6924 with latest HttpRequestManager.
=> CURA-6577/Implementation of logic for syncing packages from Cura MP to Cloud MP

cura/CuraPackageManager.py, cura/OneAtATimeIterator.py, cura/Operations/PlatformPhysicsOperation.py, cura/Operations/SetParentOperation.py, plugins/PostProcessingPlugin/scripts/Stretch.py, plugins/SimulationView/SimulationViewProxy.py, plugins/UM3NetworkPrinting/src/Models/Http/ClusterPrinterMaterialStationSlot.py
This PR adds a number of typing fixes in __init__ statements, because MYPY is complaining about them.
=> Fix typing in __init__ methods to appease MYPY

resources/definitions/renkforce_rf100.def.json, resources/definitions/renkforce_rf100_v2.def.json, resources/definitions/renkforce_rf100_xl.def.json, resources/extruders/renkforce_rf100_xl_extruder_0.def.json
Back-ported well-tested, in-production use RF100 V1, V2, and XL resources files from [dok-net RF100](https://github.com/dok-net/RF100) to Renkforce COTS stock firmware (temperature, flow rate; build volume on V1). These are running on RF100s both with and without the original enclosure, printing both PLA and PET-G.
=> Updated Renkforce RF100 (and V2, XL) resources

cura/Backups/Backup.py
Prevent unpacking of possibly spoofed backups (as a last line of defence if other security has failed).
Zips with partially known content are a lot harder to spoof.
Thanks WhiteHats :-)
=> Check if main config file is in backup zip.

resources/definitions/renkforce_rf100.def.json, resources/definitions/renkforce_rf100_v2.def.json, resources/definitions/renkforce_rf100_xl.def.json
Retraction hop enable has default value, the height value is fine by default, too.
This cleans up confusion after merging 7e1162093c7d6814db114877bc68677d49bd1cdb (which is a dead branch?)
=> Renkforce printers: Use defaults for retraction hop

cura/CuraApplication.py, cura/Settings/CuraFormulaFunctions.py
This PR adds CuraFormulaFunctions to get a value for a key from a stack starting at a specified container index. This enables a writer of profiles to eg refer to inherited values for a key from a formula for the same setting, eg:
A quality profile can use this formula to specify a temperature 5 degrees higher than the temperature specified in the material container:
`material_print_temperature = = valueFromContainer("material_print_temperature", 4) + 5`
A setting referencing itself without this function will create an infinite loop.
=> Add valueFromContainer() functions for profiles
